force-app/main/default/objects/ContractTerm__c/ContractTerm__c.object-meta.xml
<CustomObject>
    <label>Contract Term</label>
    <nameField>
        <label>Terms of Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ContractTerm__c/fields/TermsHTML__c.field-meta.xml
<CustomField>
    <fullName>TermsHTML__c</fullName>
    <label>Terms</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/NAM__c/NAM__c.object-meta.xml
<CustomObject>
    <label>NAM</label>
    <nameField>
        <label>NAM Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NAMs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrder/fields/ContractTerm__c.field-meta.xml
<CustomField>
    <fullName>ContractTerm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract term</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>ContractTerm__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>ContractTerm__c.RelatedObjectName__c</field>
            <operation>equals</operation>
            <value>WorkOrder</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ContractTerm__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>WorkOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/NAM__c.field-meta.xml
<CustomField>
    <fullName>NAM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NAM</label>
    <referenceTo>NAM__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>WorkOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/BRL__c.field-meta.xml
<CustomField>
    <fullName>BRL__c</fullName>
    <inlineHelpText>R$</inlineHelpText>
    <label>Price BRL</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/MS__c.field-meta.xml
<CustomField>
    <fullName>MS__c</fullName>
    <label>M/S</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Material</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>F</fullName>
                <isActive>false</isActive>
                <label>F</label>
            </value>
            <value>
                <fullName>I</fullName>
                <isActive>false</isActive>
                <label>I</label>
            </value>
            <value>
                <fullName>M/S</fullName>
                <isActive>false</isActive>
                <label>M/S</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/NAM__c.field-meta.xml
<CustomField>
    <fullName>NAM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NAM</label>
    <referenceTo>NAM__c</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>WorkOrderLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <inlineHelpText>USD</inlineHelpText>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/ResponsibleCountry__c.field-meta.xml
<CustomField>
    <fullName>ResponsibleCountry__c</fullName>
    <label>Responsible</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Outside of Brazil</fullName>
            </value>
            <value>
                <fullName>MODEC, Inc</fullName>
                <isActive>false</isActive>
                <label>MODEC, Inc</label>
            </value>
            <value>
                <fullName>MdB</fullName>
                <isActive>false</isActive>
                <label>MdB</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WorkOrderPdfController.cls
public with sharing class WorkOrderPdfController {
	
	private final WorkOrder objWorkOrder;
    
    public WorkOrderPdfController(ApexPages.StandardController stdController) {
        this.objWorkOrder = (WorkOrder)stdController.getRecord();
    }

    public List<WorkOrderLineItem> getItems() {
		//List<WorkOrderLineItem> lst = WorkOrderLineItemDAO.getWorkOrderLineItemByNAM(objWorkOrder.NAM__c);
		List<WorkOrderLineItem> lst = WorkOrderLineItemDAO.getByWorkOrderId(objWorkOrder.Id);

		for(WorkOrderLineItem obj : lst) {
			obj.Status = (String.isNotBlank(obj.Status) ? obj.Status.left(1) : null);
			obj.MS__c = (String.isNotBlank(obj.MS__c) ? obj.MS__c.left(1) : null);
		}
        return lst;
	}
	
	public Decimal getAllPortionAmount() {
		Decimal portionAmount = 0;

		//for(WorkOrderLineItem obj : WorkOrderLineItemDAO.getWorkOrderLineItemByNAM(objWorkOrder.NAM__c)) {
		for(WorkOrderLineItem obj : WorkOrderLineItemDAO.getByWorkOrderId(objWorkOrder.Id)) {	
			portionAmount += obj.Price__c != null ? obj.Price__c : 0;
		}
        return portionAmount;
	}

	public Decimal getAllTotalBRL() {
		Decimal totalBRL = 0;

		//for(WorkOrderLineItem obj : WorkOrderLineItemDAO.getWorkOrderLineItemByNAM(objWorkOrder.NAM__c)) {
		for(WorkOrderLineItem obj : WorkOrderLineItemDAO.getByWorkOrderId(objWorkOrder.Id)) {
			totalBRL += obj.BRL__c != null ? obj.BRL__c : 0;
		}
        return totalBRL;
	}

	public Decimal getAllBrazilPortionAmount() {
		Decimal portionAmount = 0;

		//for(WorkOrderLineItem obj : WorkOrderLineItemDAO.getWorkOrderLineItemByNAM(objWorkOrder.NAM__c)) {
		for(WorkOrderLineItem obj : WorkOrderLineItemDAO.getByWorkOrderId(objWorkOrder.Id)) {	
			if(obj.ResponsibleCountry__c == 'Brazil' || obj.ResponsibleCountry__c == 'MdB')
				portionAmount += obj.Price__c != null ? obj.Price__c : 0;
		}
        return portionAmount;
	}

	public String getContractTerms(){
		WorkOrder wOrder = [SELECT Id, ContractTerm__c FROM WorkOrder WHERE Id =: objWorkOrder.Id];

		if(wOrder.ContractTerm__c == null) return '';
		else{
			ContractTerm__c c = [SELECT TermsHTML__c FROM ContractTerm__c WHERE Id =: wOrder.ContractTerm__c];
			return c.TermsHTML__c;
		}
	}
}