force-app/main/default/objects/ContractTerm__c/ContractTerm__c.object-meta.xml
<CustomObject>
    <label>Contract Term</label>
    <nameField>
        <label>Terms of Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NAM__c/NAM__c.object-meta.xml
<CustomObject>
    <label>NAM</label>
    <nameField>
        <label>NAM Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NAMs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NAM__c/fields/NAMRevision__c.field-meta.xml
<CustomField>
    <fullName>NAMRevision__c</fullName>
    <formula>IF(TEXT(ClosedOutStatus__c) &lt;&gt; &apos;&apos;, TEXT(Revision__c) + &apos;-&apos; +  Text(RevisionCO__c), text(Revision__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>NAM Revision</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/ClosedOutRevision__c.field-meta.xml
<CustomField>
    <fullName>ClosedOutRevision__c</fullName>
    <formula>TEXT(NAM__r.RevisionCO__c)</formula>
    <label>Closed Out Revision</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/ContractTerm__c.field-meta.xml
<CustomField>
    <fullName>ContractTerm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract term</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>ContractTerm__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>ContractTerm__c.RelatedObjectName__c</field>
            <operation>equals</operation>
            <value>WorkOrder</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ContractTerm__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>WorkOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/NAM__c.field-meta.xml
<CustomField>
    <fullName>NAM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NAM</label>
    <referenceTo>NAM__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>WorkOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/NAMRevision__c.field-meta.xml
<CustomField>
    <fullName>NAMRevision__c</fullName>
    <formula>TEXT(NAM__r.Revision__c)</formula>
    <label>NAM Revision</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Responsible__c.field-meta.xml
<CustomField>
    <fullName>Responsible__c</fullName>
    <formula>Contractor__r.ShortName__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Responsible</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>WorkOrder__c</fullName>
    <externalId>true</externalId>
    <label>Work Order</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WorkOrderDAO.cls
public class WorkOrderDAO {
    public static WorkOrder getById(Id woId){
        List<WorkOrder> lst = WorkOrderDAO.getByWOItem(new Set<Id>{woId});
        
        if(lst.size() > 0) return lst[0];
        else return null;
    }
    public static List<WorkOrder> getByWOItem(Set<Id> setIds){
        return [SELECT 
                    ID,
                    WorkOrder__c,
                    NAM__c,
                    Responsible__c,
                    ContractTerm__c,
                    ( SELECT 
                        WorkOrderId,
                        Product__c,
                        Status,
                        MS__c,
                        Price__c,
                        Responsible__c,
                        ResponsibleCountry__c,
                        Vendor__c,
                        BRL__c
                    FROM WorkOrderLineItems)
                 FROM WorkOrder 
                 WHERE Id IN : setIds];
    }

    public static List<WorkOrder> getByNAMId(Set<Id> setIds){
        return  [SELECT 
                    Id,
                    WorkOrder__c,
                    NAM__c,
                    NAMRevision__c,
                    ClosedOutRevision__c 
                 FROM WorkOrder 
                 WHERE NAM__c IN : setIds];
    }
}