force-app/main/default/objects/OccurrenceGroup__c/OccurrenceGroup__c.object-meta.xml
<CustomObject>
    <label>Occurrence Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Occurrence Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OccurrenceGroup__c/fields/LastOccurrence__c.field-meta.xml
<CustomField>
    <fullName>LastOccurrence__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Last Occurrence</label>
    <referenceTo>Occurrences__c</referenceTo>
    <relationshipLabel>Occurrence Groups</relationshipLabel>
    <relationshipName>OccurrenceGroups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Occurrences__c/Occurrences__c.object-meta.xml
<CustomObject>
    <label>Occurrences</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>Occurrence Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Occurrences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Occurrences__c/fields/OccurrenceGroup__c.field-meta.xml
<CustomField>
    <fullName>OccurrenceGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Occurrence Group</label>
    <referenceTo>OccurrenceGroup__c</referenceTo>
    <relationshipLabel>Occurrences</relationshipLabel>
    <relationshipName>Occurrences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OccurrenceBO.cls
public with sharing class OccurrenceBO {

    private static final OccurrenceBO instance = new OccurrenceBO();


    public static OccurrenceBO getInstance() {
		return instance;
    }
   
    public void fillLastOccurrence(List<Occurrences__c> lstOccurrence){

        List<OccurrenceGroup__c> lstUpdate = new List<OccurrenceGroup__c>();
        List<OccurrenceGroup__c> lstOccurrenceGroup = new List<OccurrenceGroup__c>();
        set<Id> idOccurrenceGroup = new set<Id>();

        for(Occurrences__c occ : lstOccurrence){

            if(!lstOccurrence.isEmpty()){
                idOccurrenceGroup.add(occ.OccurrenceGroup__c);
            }
        }

        lstOccurrenceGroup = OccurrenceGroupDAO.getOccurrenceGroupById(idOccurrenceGroup);

        for(Occurrences__c lst : lstOccurrence){

            for(OccurrenceGroup__c lstOG : lstOccurrenceGroup){

                if(!lstOccurrence.isEmpty()){
                    lstOG.LastOccurrence__c = lst.Id;
                    lstUpdate.add(lstOG);
                }
            }
        }

        update lstUpdate;

    }

}