force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vessel__c/Vessel__c.object-meta.xml
<CustomObject>
    <label>Vessel</label>
    <nameField>
        <label>Vessel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vessels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vessel__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vessels (Client)</relationshipLabel>
    <relationshipName>Vessels1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vessel__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Decommissioned</fullName>
            </value>
            <value>
                <fullName>EPCI</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>In Operation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vessel__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New build</fullName>
            </value>
            <value>
                <fullName>Conversion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VesselContract__c/VesselContract__c.object-meta.xml
<CustomObject>
    <label>Vessel Contract</label>
    <nameField>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vessel Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VesselContract__c/fields/ActualDailyRateBRL__c.field-meta.xml
<CustomField>
    <fullName>ActualDailyRateBRL__c</fullName>
    <label>Actual Daily Rate (BRL)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VesselContract__c/fields/ActualDailyRateUSD__c.field-meta.xml
<CustomField>
    <fullName>ActualDailyRateUSD__c</fullName>
    <label>Actual Daily Rate (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VesselContract__c/fields/BOMEndDate__c.field-meta.xml
<CustomField>
    <fullName>BOMEndDate__c</fullName>
    <formula>ADDMONTHS(BOMStartDate__c ,1) - 1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BOM End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VesselContract__c/fields/BOMStartDate__c.field-meta.xml
<CustomField>
    <fullName>BOMStartDate__c</fullName>
    <label>BOM Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VesselContract__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Management</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Vessel Contracts</relationshipLabel>
    <relationshipName>VesselContracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VesselContract__c/fields/ContractAnniversary__c.field-meta.xml
<CustomField>
    <fullName>ContractAnniversary__c</fullName>
    <label>Contract Anniversary</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VesselContract__c/fields/Contracted__c.field-meta.xml
<CustomField>
    <fullName>Contracted__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contractor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vessel Contracts (Contracted)</relationshipLabel>
    <relationshipName>VesselContracts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VesselContract__c/fields/Contractor__c.field-meta.xml
<CustomField>
    <fullName>Contractor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vessel Contracts</relationshipLabel>
    <relationshipName>VesselContracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VesselContract__c/fields/ContractTotalAmountBRL__c.field-meta.xml
<CustomField>
    <fullName>ContractTotalAmountBRL__c</fullName>
    <label>Contract Total Amount (BRL)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VesselContract__c/fields/ContractTotalAmountUSD__c.field-meta.xml
<CustomField>
    <fullName>ContractTotalAmountUSD__c</fullName>
    <label>Contract Total Amount (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VesselContract__c/fields/MealAllowance__c.field-meta.xml
<CustomField>
    <fullName>MealAllowance__c</fullName>
    <label>Meal Allowance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VesselContract__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/VesselContract__c/fields/Pilot__c.field-meta.xml
<CustomField>
    <fullName>Pilot__c</fullName>
    <label>Pilot Gas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VesselContract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Close</fullName>
                <isActive>false</isActive>
                <label>Close</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Current</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VesselContract__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Charter</fullName>
            </value>
            <value>
                <fullName>Cost Plus</fullName>
            </value>
            <value>
                <fullName>O&amp;M Support</fullName>
            </value>
            <value>
                <fullName>Pre-Ops</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VesselContract__c/fields/Vessel__c.field-meta.xml
<CustomField>
    <fullName>Vessel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vessel</label>
    <referenceTo>Vessel__c</referenceTo>
    <relationshipLabel>Vessel Contracts</relationshipLabel>
    <relationshipName>VesselContracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/VesselContractDAO.cls
public with sharing class VesselContractDAO {

    public static List<VesselContract__c> getVesselContractById(Id vesselContractId) {
		return [SELECT
                    Id,
                    ActualDailyRateBRL__c,
                    ActualDailyRateUSD__c,
                    BOMStartDate__c,
                    BOMEndDate__c,
                    Client__c,
                    ContractAnniversary__c,
                    ContractTotalAmountBRL__c,
                    ContractTotalAmountUSD__c,
                    Contracted__c,
                    Contractor__c,
                    EndDate__c,
                    Object__c,
                    StartDate__c,
                    Status__c,
                    Type__c,
                    Vessel__c,
                    VesselShortName__c
				FROM
                    VesselContract__c
				WHERE
                    Id =: vesselContractId];
     }

     public static List<VesselContract__c> getContractByVesselID(String vesselID, String type1){
          return [SELECT 
                    id,
                    Name, 
                    VesselShortName__c 
                    FROM 
                    VesselContract__c 
                    WHERE 
                    Vessel__c =: vesselID
                    AND
                    Type__c =: type1];
     }
     
     public static List<VesselContract__c> getVesselContractByContractNumber(String nrContract, String shortName, String type1){
          return [SELECT 
                    id,
                    Name, 
                    VesselShortName__c 
                    FROM 
                    VesselContract__c 
                    WHERE 
                    Name =: nrContract 
                    AND 
                    VesselShortName__c =: shortName
                    AND
                    Type__c =: type1];
     }

     public static List<VesselContract__c> getVesselContractByIdAndType(String vesselContractId, String type) {
		return [SELECT
                    Id,
                    ActualDailyRateBRL__c,
                    ActualDailyRateUSD__c,
                    BOMStartDate__c,
                    BOMEndDate__c,
                    Client__c,
                    ContractAnniversary__c,
                    ContractTotalAmountBRL__c,
                    ContractTotalAmountUSD__c,
                    Contracted__c,
                    Contractor__c,
                    EndDate__c,
                    Object__c,
                    StartDate__c,
                    Status__c,
                    Type__c,
                    Vessel__c,
                    VesselShortName__c,
                    MealAllowance__c
				FROM
                    VesselContract__c
				WHERE
                    Id =: vesselContractId
                    AND
                    Type__c =: type];
     }

     public static List<VesselContract__c> getMealAllowanceByNumber(String contractNumber){
          return [SELECT
                    Id,
                    ActualDailyRateBRL__c,
                    ActualDailyRateUSD__c,
                    BOMStartDate__c,
                    BOMEndDate__c,
                    Client__c,
                    ContractAnniversary__c,
                    ContractTotalAmountBRL__c,
                    ContractTotalAmountUSD__c,
                    Contracted__c,
                    Contractor__c,
                    EndDate__c,
                    Object__c,
                    StartDate__c,
                    Status__c,
                    Type__c,
                    Vessel__c,
                    VesselShortName__c,
                    MealAllowance__c,
                    Pilot__c
                    FROM
                    VesselContract__c
                    WHERE
                    Name =: contractNumber];
     }
}