force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vessel__c/Vessel__c.object-meta.xml
<CustomObject>
    <label>Vessel</label>
    <nameField>
        <label>Vessel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vessels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vessel__c/fields/ChaterPeriod__c.field-meta.xml
<CustomField>
    <fullName>ChaterPeriod__c</fullName>
    <label>Chater Period</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vessel__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vessels (Client)</relationshipLabel>
    <relationshipName>Vessels1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vessel__c/fields/ContractResponsible__c.field-meta.xml
<CustomField>
    <fullName>ContractResponsible__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract Administrator</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Vessels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vessel__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vessel__c/fields/CreatedByMe__c.field-meta.xml
<CustomField>
    <fullName>CreatedByMe__c</fullName>
    <formula>$User.Id = CreatedBy.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Created by me</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vessel__c/fields/FieldLocation__c.field-meta.xml
<CustomField>
    <fullName>FieldLocation__c</fullName>
    <label>Field Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vessel__c/fields/FirstOil__c.field-meta.xml
<CustomField>
    <fullName>FirstOil__c</fullName>
    <label>First Oil</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vessel__c/fields/GasProduction__c.field-meta.xml
<CustomField>
    <fullName>GasProduction__c</fullName>
    <inlineHelpText>mmscfd</inlineHelpText>
    <label>Gas Production</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vessel__c/fields/Management__c.field-meta.xml
<CustomField>
    <fullName>Management__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Management</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Vessels</relationshipLabel>
    <relationshipName>Vessels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vessel__c/fields/ManagementName__c.field-meta.xml
<CustomField>
    <fullName>ManagementName__c</fullName>
    <formula>Management__r.Name</formula>
    <label>Management Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vessel__c/fields/MooringType__c.field-meta.xml
<CustomField>
    <fullName>MooringType__c</fullName>
    <label>Mooring Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vessel__c/fields/NumberLastSentLetter__c.field-meta.xml
<CustomField>
    <fullName>NumberLastSentLetter__c</fullName>
    <label>Number of last sent Letter</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vessel__c/fields/OilProduction__c.field-meta.xml
<CustomField>
    <fullName>OilProduction__c</fullName>
    <inlineHelpText>bopd</inlineHelpText>
    <label>Oil Production</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vessel__c/fields/OperationManager__c.field-meta.xml
<CustomField>
    <fullName>OperationManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Operations Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Vessels (Operation Manager)</relationshipLabel>
    <relationshipName>Vessels1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vessel__c/fields/ResponsibleManagement__c.field-meta.xml
<CustomField>
    <fullName>ResponsibleManagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager (Client)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Vessels (Manager (Client))</relationshipLabel>
    <relationshipName>Vessels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vessel__c/fields/ScopeOfWork__c.field-meta.xml
<CustomField>
    <fullName>ScopeOfWork__c</fullName>
    <label>Scope of Work</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Engineering</fullName>
            </value>
            <value>
                <fullName>Procurement</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Mobilization</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>OperationMaintenance</fullName>
                <label>Operation &amp; Maintenance</label>
            </value>
            <value>
                <fullName>Operation</fullName>
                <isActive>false</isActive>
                <label>Operation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vessel__c/fields/ShortName__c.field-meta.xml
<CustomField>
    <fullName>ShortName__c</fullName>
    <label>Short Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vessel__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Decommissioned</fullName>
            </value>
            <value>
                <fullName>EPCI</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>In Operation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vessel__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New build</fullName>
            </value>
            <value>
                <fullName>Conversion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vessel__c/fields/VesselCode__c.field-meta.xml
<CustomField>
    <fullName>VesselCode__c</fullName>
    <inlineHelpText>Example: MHXXX-MBS</inlineHelpText>
    <label>Vessel Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vessel__c/fields/WaterDepth__c.field-meta.xml
<CustomField>
    <fullName>WaterDepth__c</fullName>
    <inlineHelpText>meters</inlineHelpText>
    <label>Water  Depth</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VesselDAO.cls
public with sharing class VesselDAO {
    private static final VesselDAO instance = new VesselDAO();

    private VesselDAO() { }

    public static VesselDAO getInstance(){
        return instance;
    }

    public List<Vessel__c> getVesselbyShortName(String shortName){
        return [SELECT id, ShortName__c, Name FROM Vessel__c WHERE ShortName__c =: shortName LIMIT 1];
    }

    public List<Vessel__c> getVesselById(String idVessel){
        return [SELECT 
                  id,   
                  ChaterPeriod__c,
                  Client__c,
                  ContractResponsible__c,
                  Country__c,
                  CreatedByMe__c,
                  FieldLocation__c,
                  FirstOil__c,
                  GasProduction__c,
                  Management__c,
                  ManagementName__c,
                  MooringType__c,
                  NumberLastSentLetter__c,
                  OilProduction__c,
                  OperationManager__c,
                  ResponsibleManagement__c,
                  ScopeOfWork__c,
                  ShortName__c,
                  Status__c,
                  Type__c,
                  VesselCode__c,
                  Name,
                  WaterDepth__c
                  FROM
                  Vessel__c
                  WHERE
                  id =: idVessel];
    }
}