force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vessel__c/Vessel__c.object-meta.xml
<CustomObject>
    <label>Vessel</label>
    <nameField>
        <label>Vessel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vessels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vessel__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vessels (Client)</relationshipLabel>
    <relationshipName>Vessels1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vessel__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vessel__c/fields/Management__c.field-meta.xml
<CustomField>
    <fullName>Management__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Management</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Vessels</relationshipLabel>
    <relationshipName>Vessels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vessel__c/fields/ManagementName__c.field-meta.xml
<CustomField>
    <fullName>ManagementName__c</fullName>
    <formula>Management__r.Name</formula>
    <label>Management Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vessel__c/fields/ShortName__c.field-meta.xml
<CustomField>
    <fullName>ShortName__c</fullName>
    <label>Short Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vessel__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Decommissioned</fullName>
            </value>
            <value>
                <fullName>EPCI</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>In Operation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VesselBOTest.cls
@isTest
public with sharing class VesselBOTest {

    @isTest
    public static void populateVesselClientHistoryTest()
    {
        List<Vessel__c> lstVessel = new List<Vessel__c>();
        Map<Id, Vessel__c> mapIdVessel = new Map<Id, Vessel__c>();

        Test.startTest();
        Client__c management = new Client__c();
        management.Name = 'Management-Test';
        insert management;

        Client__c newManagement = new Client__c();
        newManagement.Name = 'Management-Test-New';
        insert newManagement;

        Vessel__c vessel = new Vessel__c();
        vessel.Name = 'Vessel-Test';
        vessel.ShortName__c = 'Test';
        vessel.Management__c = management.Id;
        vessel.Status__c = 'In Operation'; 
        vessel.Country__c = 'Brazil';
        insert vessel;

        Vessel__c oldVessel = [SELECT Id, Name, ShortName__c, Management__c, Status__c, Country__c, ManagementName__c from Vessel__c where Vessel__c.Id = :vessel.Id];
        oldVessel.Management__c = newManagement.Id;
        update vessel;

        lstVessel.add(vessel);
        mapIdVessel.put(oldVessel.Id, oldVessel);

        VesselBO.getInstance().populateVesselClientHistory(lstVessel, mapIdVessel);
        Test.stopTest();
    }
}