force-app/main/default/objects/TW1_Facility__c/TW1_Facility__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Facility__c/fields/TW1_Facility__c.field-meta.xml
<CustomField>
    <fullName>TW1_Facility__c</fullName>
    <label>Facility</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Facility__c/fields/TW1_Type__c.field-meta.xml
<CustomField>
    <fullName>TW1_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>Vessel</fullName>
            </value>
            <value>
                <fullName>Warehouse</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Interaction__c/TW1_Interaction__c.object-meta.xml
<CustomObject>
    <label>Interaction</label>
    <nameField>
        <displayFormat>I-{000000}</displayFormat>
        <label>Interaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Interaction__c/fields/TW1_Description__c.field-meta.xml
<CustomField>
    <fullName>TW1_Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TW1_Interaction__c/fields/TW1_Facility__c.field-meta.xml
<CustomField>
    <fullName>TW1_Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>TW1_Facility__c</referenceTo>
    <relationshipLabel>Interactions</relationshipLabel>
    <relationshipName>Interactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Interaction__c/fields/TW1_Invoice__c.field-meta.xml
<CustomField>
    <fullName>TW1_Invoice__c</fullName>
    <label>Invoice</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Interaction__c/fields/TW1_Location_Base__c.field-meta.xml
<CustomField>
    <fullName>TW1_Location_Base__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Base Macaé</fullName>
            </value>
            <value>
                <fullName>Base São Cristovão</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Interaction__c/fields/TW1_Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>TW1_Purchase_Order__c</fullName>
    <label>Purchase Order</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Interaction__c/fields/TW1_Supplier__c.field-meta.xml
<CustomField>
    <fullName>TW1_Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Interactions</relationshipLabel>
    <relationshipName>Interactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Interaction__c/fields/TW5_Delivery_Date_to_Inspection__c.field-meta.xml
<CustomField>
    <fullName>TW5_Delivery_Date_to_Inspection__c</fullName>
    <label>Delivery Date to Inspection</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TW1_Interaction__c/fields/TW5_Inbound_Base_Date__c.field-meta.xml
<CustomField>
    <fullName>TW5_Inbound_Base_Date__c</fullName>
    <label>Inbound Base Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TW1_Interaction__c/fields/TW5_Inspection_Type__c.field-meta.xml
<CustomField>
    <fullName>TW5_Inspection_Type__c</fullName>
    <label>Inspection Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Emergency</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Interaction__c/fields/TW5_International_Company__c.field-meta.xml
<CustomField>
    <fullName>TW5_International_Company__c</fullName>
    <label>International Company?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Interaction__c/fields/TW5_Invoice_Value__c.field-meta.xml
<CustomField>
    <fullName>TW5_Invoice_Value__c</fullName>
    <label>Invoice Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TW1_Interaction__c/fields/TW5_Quality_Receipt_Status__c.field-meta.xml
<CustomField>
    <fullName>TW5_Quality_Receipt_Status__c</fullName>
    <label>Quality Receipt Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Approved Under Restriction</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Interaction__c/recordTypes/TW1_Receipt_Inspection.recordType-meta.xml
<RecordType>
    <fullName>TW1_Receipt_Inspection</fullName>
    <active>true</active>
    <label>Quality Receipt Inspection</label>
</RecordType>

force-app/main/default/objects/TW1_Quality_Inspection_Receipt_Item__c/TW1_Quality_Inspection_Receipt_Item__c.object-meta.xml
<CustomObject>
    <label>Quality Receipt Inspection Item</label>
    <nameField>
        <displayFormat>Item-{000000}</displayFormat>
        <label>Quality Receipt Inspection Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Receipt Inspection Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Quality_Inspection_Receipt_Item__c/fields/TW1_Item_Value__c.field-meta.xml
<CustomField>
    <fullName>TW1_Item_Value__c</fullName>
    <label>Item Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TW1_Quality_Inspection_Receipt_Item__c/fields/TW1_Quality_Inspection_Receipt__c.field-meta.xml
<CustomField>
    <fullName>TW1_Quality_Inspection_Receipt__c</fullName>
    <label>Quality Receipt Inspection</label>
    <referenceTo>TW1_Interaction__c</referenceTo>
    <relationshipName>Quality_Inspection_Receipt_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TW1_Quality_Inspection_Receipt_Item__c/fields/TW5_Family_of_Materials__c.field-meta.xml
<CustomField>
    <fullName>TW5_Family_of_Materials__c</fullName>
    <label>Family of Materials</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pipe Fittings</fullName>
            </value>
            <value>
                <fullName>Consumables</fullName>
            </value>
            <value>
                <fullName>Security Devices</fullName>
            </value>
            <value>
                <fullName>Fastening Elements</fullName>
            </value>
            <value>
                <fullName>Electric</fullName>
            </value>
            <value>
                <fullName>Electronics</fullName>
            </value>
            <value>
                <fullName>PPE</fullName>
            </value>
            <value>
                <fullName>Static Equipment</fullName>
            </value>
            <value>
                <fullName>Structural</fullName>
            </value>
            <value>
                <fullName>Tools</fullName>
            </value>
            <value>
                <fullName>Instrumentation</fullName>
            </value>
            <value>
                <fullName>Liftings</fullName>
            </value>
            <value>
                <fullName>Hydraulic Hoses</fullName>
            </value>
            <value>
                <fullName>Marine</fullName>
            </value>
            <value>
                <fullName>Piping</fullName>
            </value>
            <value>
                <fullName>Rotating Equipment</fullName>
            </value>
            <value>
                <fullName>Valves</fullName>
            </value>
            <value>
                <fullName>Seal</fullName>
            </value>
            <value>
                <fullName>Fire Equipment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Quality_Inspection_Receipt_Item__c/fields/TW5_Item_PO__c.field-meta.xml
<CustomField>
    <fullName>TW5_Item_PO__c</fullName>
    <label>Item PO</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TW1_Quality_Inspection_Receipt_Item__c/fields/TW5_Quantity__c.field-meta.xml
<CustomField>
    <fullName>TW5_Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/T_ImpressaoPDFInspectionController_TST.cls
@isTest
public class T_ImpressaoPDFInspectionController_TST {

    Private static Id QualityReceiptInspection = Schema.SObjectType.TW1_Interaction__c.getRecordTypeInfosByDeveloperName().get('TW1_Receipt_Inspection').getRecordTypeId();

    @TestSetup
    Public static void TestSetup(){
        Account conta = new Account();
        conta.name = 'TestClass';
        insert conta;
        
		TW1_Facility__c unit = new TW1_Facility__c();
        unit.TW1_Type__c = 'Vessel';
        unit.Name = 'Macaé';        
        insert unit;    
            
        TW1_Interaction__c interaction = new TW1_Interaction__c();
        interaction.RecordTypeId = QualityReceiptInspection;
        interaction.TW1_Supplier__c = conta.id;
        interaction.TW5_International_Company__c = 'No';
        interaction.TW5_Inspection_Type__c = 'Normal';
        interaction.TW5_Invoice_Value__c = 1;
        interaction.TW1_Invoice__c	= 'Test';
        interaction.TW1_Purchase_Order__c = 'TestTest';
        interaction.TW1_Facility__c = unit.id;
        interaction.TW1_Location_Base__c = 'Base Macaé';
        interaction.TW5_Inbound_Base_Date__c = Date.today();
        interaction.TW5_Delivery_Date_to_Inspection__c = Date.today() + 10;
		interaction.TW5_Quality_Receipt_Status__c = 'Not Submitted';        
        insert interaction;
            
        //interaction.TW5_Quality_Receipt_Status__c = 'Submitted';
        //update interaction;
        
        TW1_Quality_Inspection_Receipt_Item__c itemUm = new TW1_Quality_Inspection_Receipt_Item__c();
        itemUm.TW1_Quality_Inspection_Receipt__c = interaction.id;
        itemUm.TW5_Quantity__c = 2;
        itemUm.TW5_Item_PO__c = 3;
        itemUm.TW5_Family_of_Materials__c = 'Consumables';
        itemUm.TW1_Item_Value__c = 123;
        itemUm.TW1_Description__c = 'sdfafdajgahfçgafgajlfganvaovjaocsjmgbçvjg';        
        insert itemUm;
        
        TW1_Quality_Inspection_Receipt_Item__c itemDois = new TW1_Quality_Inspection_Receipt_Item__c();
        itemDois.TW1_Quality_Inspection_Receipt__c = interaction.id;
        itemDois.TW5_Quantity__c = 4;
        itemDois.TW5_Item_PO__c = 32;
        itemDois.TW5_Family_of_Materials__c = 'Pipe Fittings';
        itemDois.TW1_Item_Value__c = 754;
        itemDois.TW1_Description__c = 'nçanvçnaringjaopabvt';        
        insert itemDois;  
    }
    
    @isTest
    public static void testMethod_getInspectionItems(){
        TW1_Interaction__c interaction = [SELECT id FROM TW1_Interaction__c WHERE TW1_Invoice__c = 'Test' LIMIT 1];
        
        List<TW1_Quality_Inspection_Receipt_Item__c> itens = [SELECT id FROM TW1_Quality_Inspection_Receipt_Item__c WHERE TW1_Quality_Inspection_Receipt__c = :interaction.id];
        List<String> listIdsItens = new List<String>();
        for(TW1_Quality_Inspection_Receipt_Item__c item : itens){
            listIdsItens.add(item.id);
        }
        
        PlatformCacheUtils.Parametro param = new PlatformCacheUtils.Parametro();
        param.operation = 'set';
        param.particao = 'Interaction';
        param.particaoItem = 'ListaInspectionItemsIds';
        param.value = listIdsItens;
        PlatformCacheUtils.manageValuesOnPartition(new List<PlatformCacheUtils.Parametro>{param});
        
        ApexPages.StandardController sc = new ApexPages.StandardController ( interaction );    
        T_ImpressaoPDFInspectionItensController ic = new T_ImpressaoPDFInspectionItensController(sc);
    }
}