force-app/main/default/objects/TW1_Facility__c/TW1_Facility__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Facility__c/fields/TW1_Facility__c.field-meta.xml
<CustomField>
    <fullName>TW1_Facility__c</fullName>
    <label>Facility</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Interaction__c/TW1_Interaction__c.object-meta.xml
<CustomObject>
    <label>Interaction</label>
    <nameField>
        <displayFormat>I-{000000}</displayFormat>
        <label>Interaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Interaction__c/fields/InspectionResultsDateFormula__c.field-meta.xml
<CustomField>
    <fullName>InspectionResultsDateFormula__c</fullName>
    <formula>CASE(Month(DATEVALUE(TW5_Inspection_Result_Date__c)),
1, &quot;January&quot;, 
2, &quot;February&quot;, 
3, &quot;March&quot;, 
4, &quot;April&quot;, 
5, &quot;May&quot;, 
6, &quot;June&quot;, 
7, &quot;July&quot;, 
8, &quot;August&quot;, 
9, &quot;September&quot;, 
10, &quot;October&quot;, 
11, &quot;November&quot;, 
12, &quot;December&quot;, &quot;Nenhum&quot;) + &apos;/&apos; + Text(Day(DateValue(TW5_Inspection_Result_Date__c))) + &apos;/&apos; + Text(Year(DateValue(TW5_Inspection_Result_Date__c)))</formula>
    <label>InspectionResultsDateFormula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Interaction__c/fields/TW1_Description__c.field-meta.xml
<CustomField>
    <fullName>TW1_Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TW1_Interaction__c/fields/TW1_Facility__c.field-meta.xml
<CustomField>
    <fullName>TW1_Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>TW1_Facility__c</referenceTo>
    <relationshipLabel>Interactions</relationshipLabel>
    <relationshipName>Interactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Interaction__c/fields/TW1_Inspector_Name__c.field-meta.xml
<CustomField>
    <fullName>TW1_Inspector_Name__c</fullName>
    <label>Inspector Name</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Interaction__c/fields/TW1_Invoice__c.field-meta.xml
<CustomField>
    <fullName>TW1_Invoice__c</fullName>
    <label>Invoice</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Interaction__c/fields/TW1_Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>TW1_Purchase_Order__c</fullName>
    <label>Purchase Order</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Quality_Inspection_Receipt_Item__c/TW1_Quality_Inspection_Receipt_Item__c.object-meta.xml
<CustomObject>
    <label>Quality Receipt Inspection Item</label>
    <nameField>
        <displayFormat>Item-{000000}</displayFormat>
        <label>Quality Receipt Inspection Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Receipt Inspection Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Quality_Inspection_Receipt_Item__c/fields/StatusEtiquetaFormula__c.field-meta.xml
<CustomField>
    <fullName>StatusEtiquetaFormula__c</fullName>
    <formula>IF(ISPICKVAL(TW5_Supply_Chain_Status__c,&apos;&apos;), TEXT(TW1_Status__c),TEXT(TW5_Supply_Chain_Status__c))</formula>
    <label>StatusEtiquetaFormula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Quality_Inspection_Receipt_Item__c/fields/TW1_Quality_Inspection_Receipt__c.field-meta.xml
<CustomField>
    <fullName>TW1_Quality_Inspection_Receipt__c</fullName>
    <label>Quality Receipt Inspection</label>
    <referenceTo>TW1_Interaction__c</referenceTo>
    <relationshipName>Quality_Inspection_Receipt_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TW1_Quality_Inspection_Receipt_Item__c/fields/TW5_Item_PO__c.field-meta.xml
<CustomField>
    <fullName>TW5_Item_PO__c</fullName>
    <label>Item PO</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TW1_Quality_Inspection_Receipt_Item__c/fields/TW5_Quantity__c.field-meta.xml
<CustomField>
    <fullName>TW5_Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/T_ImpressaoPDFInspectionItensController.cls
public class T_ImpressaoPDFInspectionItensController {

    public TW1_Interaction__c interaction {get; set;}
    public ApexPages.StandardController standardInspectionController;
    public List<TW1_Quality_Inspection_Receipt_Item__c> items {get; set;}    
    
    public T_ImpressaoPDFInspectionItensController(ApexPages.StandardController cntrl) {
        standardInspectionController = cntrl;        
        interaction = (TW1_Interaction__c) cntrl.getRecord();        
        getInspectionItems();
    }
    
    public void getInspectionItems(){
        PlatformCacheUtils.Parametro param = new PlatformCacheUtils.Parametro();
        param.particao = 'Interaction';
        param.particaoItem = 'ListaInspectionItemsIds';
        param.operation = 'get';
        
        List<PlatformCacheUtils.Parametro> params = new List<PlatformCacheUtils.Parametro>();
        params.add(param);
        
        List<List<String>> retorno = PlatformCacheUtils.manageValuesOnPartition(params);
        
        IF(retorno != null){
            //Query tem que ser colocada em uma reposity
            this.items = [select id,TW1_Quality_Inspection_Receipt__r.TW1_Purchase_Order__c,TW5_Quantity__c,TW5_Item_PO__c,TW1_Description__c,TW1_Quality_Inspection_Receipt__r.Name,
                          TW1_Quality_Inspection_Receipt__r.TW1_Facility__r.Name, TW1_Quality_Inspection_Receipt__r.TW1_Inspector_Name__c,
                          TW1_Quality_Inspection_Receipt__r.InspectionResultsDateFormula__c,StatusEtiquetaFormula__c, TW1_Quality_Inspection_Receipt__r.TW1_Invoice__c
                          from TW1_Quality_Inspection_Receipt_Item__c
                          where id in: retorno.get(0) 
                          limit 1000];            
        }
    }
}