force-app/main/default/objects/TW1_Facility__c/TW1_Facility__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Facility__c/fields/TW1_Facility__c.field-meta.xml
<CustomField>
    <fullName>TW1_Facility__c</fullName>
    <label>Facility</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Inspection_Item__c/TW1_Inspection_Item__c.object-meta.xml
<CustomObject>
    <label>Inspection Item</label>
    <nameField>
        <displayFormat>Item-{000000}</displayFormat>
        <label>Inspection Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspection Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Inspection_Item__c/fields/TW1_Quantity__c.field-meta.xml
<CustomField>
    <fullName>TW1_Quantity__c</fullName>
    <label>Quantity</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TW1_Inspection_Item__c/fields/TW1_Request__c.field-meta.xml
<CustomField>
    <fullName>TW1_Request__c</fullName>
    <label>Request</label>
    <referenceTo>TW1_Request__c</referenceTo>
    <relationshipLabel>Inspection Items</relationshipLabel>
    <relationshipName>Inspection_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/TW1_Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>REQ{000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Request__c/fields/Inspection_Type__c.field-meta.xml
<CustomField>
    <fullName>Inspection_Type__c</fullName>
    <label>Inspection Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Emergency</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/Technical_Inspection_Recommendation__c.field-meta.xml
<CustomField>
    <fullName>Technical_Inspection_Recommendation__c</fullName>
    <inlineHelpText>(RTI). Fill as the Ex.: SPIE-RIT-2020-0001</inlineHelpText>
    <label>Technical Inspection Recommendation</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Change_and_Repair_Project__c.field-meta.xml
<CustomField>
    <fullName>TW1_Change_and_Repair_Project__c</fullName>
    <inlineHelpText>(PAR). Fill as the Ex.: PAR-2020-0001</inlineHelpText>
    <label>Change and Repair Project</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Facility__c.field-meta.xml
<CustomField>
    <fullName>TW1_Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>TW1_Facility__c</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Inspection_Address__c.field-meta.xml
<CustomField>
    <fullName>TW1_Inspection_Address__c</fullName>
    <label>Inspection Address</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Barra Mansa</fullName>
            </value>
            <value>
                <fullName>Macaé</fullName>
            </value>
            <value>
                <fullName>Niterói</fullName>
            </value>
            <value>
                <fullName>Rio das Ostras</fullName>
            </value>
            <value>
                <fullName>São Paulo</fullName>
            </value>
            <value>
                <fullName>Rio de Janeiro</fullName>
            </value>
            <value>
                <fullName>Angra dos Reis</fullName>
            </value>
            <value>
                <fullName>N/D</fullName>
            </value>
            <value>
                <fullName>Av Teste</fullName>
                <isActive>false</isActive>
                <label>Av Teste</label>
            </value>
            <value>
                <fullName>Rua Teste</fullName>
                <isActive>false</isActive>
                <label>Rua Teste</label>
            </value>
            <value>
                <fullName>rua xxxx</fullName>
                <isActive>false</isActive>
                <label>rua xxxx</label>
            </value>
            <value>
                <fullName>testeEEEEE2</fullName>
                <isActive>false</isActive>
                <label>testeEEEEE2</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Inspection_Contact_Number__c.field-meta.xml
<CustomField>
    <fullName>TW1_Inspection_Contact_Number__c</fullName>
    <label>Inspection Contact Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Inspection_Perfomed__c.field-meta.xml
<CustomField>
    <fullName>TW1_Inspection_Perfomed__c</fullName>
    <label>Inspection Performed</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Material Release</fullName>
            </value>
            <value>
                <fullName>Pressure Test</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Dimensional</fullName>
            </value>
            <value>
                <fullName>Painting</fullName>
            </value>
            <value>
                <fullName>Welding</fullName>
            </value>
            <value>
                <fullName>Documentation Analysis</fullName>
            </value>
            <value>
                <fullName>PMI follow up</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Acompanhamento de PMI</fullName>
                <isActive>false</isActive>
                <label>Acompanhamento de PMI</label>
            </value>
            <value>
                <fullName>Acompanhamento de Qualificação</fullName>
                <isActive>false</isActive>
                <label>Acompanhamento de Qualificação</label>
            </value>
            <value>
                <fullName>Análise de Documentação</fullName>
                <isActive>false</isActive>
                <label>Análise de Documentação</label>
            </value>
            <value>
                <fullName>Final Delivery</fullName>
                <isActive>false</isActive>
                <label>Final Delivery</label>
            </value>
            <value>
                <fullName>Inspeção Dimensional</fullName>
                <isActive>false</isActive>
                <label>Inspeção Dimensional</label>
            </value>
            <value>
                <fullName>Inspeção de Pintura</fullName>
                <isActive>false</isActive>
                <label>Inspeção de Pintura</label>
            </value>
            <value>
                <fullName>Inspeção de Solda</fullName>
                <isActive>false</isActive>
                <label>Inspeção de Solda</label>
            </value>
            <value>
                <fullName>Liberação de Materiais</fullName>
                <isActive>false</isActive>
                <label>Liberação de Materiais</label>
            </value>
            <value>
                <fullName>Reapresentação de Certificados</fullName>
                <isActive>false</isActive>
                <label>Reapresentação de Certificados</label>
            </value>
            <value>
                <fullName>Teste Hidrostático</fullName>
                <isActive>false</isActive>
                <label>Teste Hidrostático</label>
            </value>
            <value>
                <fullName>Teste de Carga</fullName>
                <isActive>false</isActive>
                <label>Teste de Carga</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Inspection_Status__c.field-meta.xml
<CustomField>
    <fullName>TW1_Inspection_Status__c</fullName>
    <label>Inspection Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TW1_Inspection_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Management_Of_Change__c.field-meta.xml
<CustomField>
    <fullName>TW1_Management_Of_Change__c</fullName>
    <inlineHelpText>(MOC) Fill as the Ex.: MOC-MV20-20-00001</inlineHelpText>
    <label>Management Of Change</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Planned_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>TW1_Planned_Delivery_Date__c</fullName>
    <label>Planned Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Project_Number__c.field-meta.xml
<CustomField>
    <fullName>TW1_Project_Number__c</fullName>
    <inlineHelpText>Supplier number control</inlineHelpText>
    <label>Project Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>TW1_Purchase_Order__c</fullName>
    <inlineHelpText>Fill as the Ex.: PO-45000XXXXX / AM-MV20-20-00001</inlineHelpText>
    <label>Purchase Order</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Related_Request__c.field-meta.xml
<CustomField>
    <fullName>TW1_Related_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cloned From</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>5 AND (1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>TW1_Request__c.TW1_Inspection_Perfomed__c</field>
            <operation>equals</operation>
            <value>Material Release</value>
        </filterItems>
        <filterItems>
            <field>$Source.TW1_Inspection_Perfomed__c</field>
            <operation>equals</operation>
            <value>Pressure Test, Delivery, Dimensional, Welding</value>
        </filterItems>
        <filterItems>
            <field>TW1_Request__c.TW1_Inspection_Perfomed__c</field>
            <operation>equals</operation>
            <value>Material Release, Pressure Test, Delivery, Dimensional, Painting, Welding, Documentation Analysis, PMI follow up, Others</value>
        </filterItems>
        <filterItems>
            <field>$Source.TW1_Inspection_Perfomed__c</field>
            <operation>equals</operation>
            <value>Material Release, Painting, Documentation Analysis, PMI follow up, Others</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Inspection</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>TW1_Request__c</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Supplier_Email__c.field-meta.xml
<CustomField>
    <fullName>TW1_Supplier_Email__c</fullName>
    <label>Supplier Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Vendor__c.field-meta.xml
<CustomField>
    <fullName>TW1_Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4) OR (6 AND (5 OR 7))</booleanFilter>
        <errorMessage>Make sure the selected vendor is already homologated or not.</errorMessage>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>BM, Contract - New Contract, Contract - Amendment, Material Packing List (Third-party), Inspection</value>
        </filterItems>
        <filterItems>
            <field>Account.TW1_Vendor_Vetting__c</field>
            <operation>equals</operation>
            <value>Active, No Registered, Ongoing, Blocked, Vetting Not Requested, Vetting Rejected, Vetting Approved with Red Flag, Vetting Approved, Vetting Expired</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vendor Vetting, Vendor Vetting - Senegal</value>
        </filterItems>
        <filterItems>
            <field>Account.TW1_Vendor_Vetting__c</field>
            <operation>equals</operation>
            <value>Active, No Registered, Ongoing, Blocked, Vetting Not Requested, Vetting Rejected, Vetting Approved with Red Flag, Vetting Approved, Vetting Expired</value>
        </filterItems>
        <filterItems>
            <field>Account.TW1_Step_Owner__c</field>
            <operation>equals</operation>
            <valueField>$User.Id</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>PO Review Form</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator, VV Team</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_WO_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>TW1_WO_Due_Date__c</fullName>
    <label>WO Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Work_Order__c.field-meta.xml
<CustomField>
    <fullName>TW1_Work_Order__c</fullName>
    <inlineHelpText>(WO). Fill as the Ex.: WOCS-20-00001</inlineHelpText>
    <label>Work Order</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/recordTypes/Inspection.recordType-meta.xml
<RecordType>
    <fullName>Inspection</fullName>
    <active>true</active>
    <label>Inspection</label>
</RecordType>

force-app/main/default/globalValueSets/TW1_Inspection_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Inspection Rescheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Reproved</fullName>
    </customValue>
    <customValue>
        <fullName>Awaiting Date Confirmation</fullName>
    </customValue>
    <customValue>
        <fullName>Verifying Date Availability</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>Inspection Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Rescheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <customValue>
        <fullName>Emergency Inspection</fullName>
    </customValue>
    <customValue>
        <fullName>Not Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Approved with Restriction</fullName>
    </customValue>
    <masterLabel>Inspection Status</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/T_MODEC_CloneInspection_App.cls
/**
 * @File Name          : T_MODEC_CloneInspection_App.cls
 * @Description        : Apex application for the LP T_MODEC_CloneInspection
 * @Author             : Rafael Hadama
 * @Group              :
 * @Last Modified By   : Rafael Hadama
 * @Last Modified On   : 07-09-2020
 * @Modification Log   :
 * Ver       Date            Author              Modification
 * 1.0    29/06/2020   Rafael Hadama     Initial Version
 **/
public class T_MODEC_CloneInspection_App {
    
    public T_MODEC_CloneInspection_Ctrl.CloneResponseDto CloneInspection(string RequestId) {
        
        T_MODEC_CloneInspection_Ctrl.CloneResponseDto ResponseDto = new T_MODEC_CloneInspection_Ctrl.CloneResponseDto();
        
        try {
            T_MODEC_Request_Rep RequestREP = new T_MODEC_Request_Rep();
            TW1_Request__c Inspection = RequestREP.getInspectionAndInspectionLinesCLONE(RequestId);       
            
            TW1_Request__c CloneInspection = new TW1_Request__c();
            CloneInspection.RecordTypeId                           = Inspection.RecordtypeId;
            CloneInspection.TW1_Purchase_Order__c                  = Inspection.TW1_Purchase_Order__c;
            CloneInspection.TW1_Work_Order__c                      = Inspection.TW1_Work_Order__c;
            CloneInspection.TW1_Change_and_Repair_Project__c       = Inspection.TW1_Change_and_Repair_Project__c;
            CloneInspection.TW1_Project_Number__c                  = Inspection.TW1_Project_Number__c;
            CloneInspection.TW1_Management_Of_Change__c            = Inspection.TW1_Management_Of_Change__c;
            CloneInspection.TW1_WO_Due_Date__c                     = Inspection.TW1_WO_Due_Date__c;
            CloneInspection.TW1_Planned_Delivery_Date__c           = Inspection.TW1_Planned_Delivery_Date__c;
            CloneInspection.Technical_Inspection_Recommendation__c = Inspection.Technical_Inspection_Recommendation__c;
            CloneInspection.TW1_Facility__c                        = Inspection.TW1_Facility__c;
            CloneInspection.TW1_Inspection_Perfomed__c             = Inspection.TW1_Inspection_Perfomed__c;
            CloneInspection.TW1_Inspection_Contact_Number__c       = Inspection.TW1_Inspection_Contact_Number__c;
            CloneInspection.TW1_Inspection_Address__c              = Inspection.TW1_Inspection_Address__c;
            CloneInspection.TW1_Vendor__c                          = Inspection.TW1_Vendor__c;
            CloneInspection.Inspection_Type__c                     = Inspection.Inspection_Type__c;
            CloneInspection.TW1_Related_Request__c                 = Inspection.Id;
            CloneInspection.TW1_Supplier_Email__c                  = Inspection.TW1_Supplier_Email__c;
            CloneInspection.TW1_Inspection_Status__c               = 'Not Submitted';
            
            TriggerFactory.stopRequestTrigger = false;
            Database.SaveResult SaveResult = Database.insert(CloneInspection, true);
            
            if (SaveResult.isSuccess()) {
                User uObj = [Select id, Profile.UserLicense.Name from User where Id =: UserInfo.getUserId()];
                
                ResponseDto.Status = 'Sucesso';
                if (uObj.Profile.UserLicense.Name == 'External Apps') {
                    ResponseDto.CloneUrl = System.URL.getSalesforceBaseUrl().toExternalForm() + '/modecsupplierportal/s/detail/' + SaveResult.getId();
                } else {
                    ResponseDto.CloneUrl = System.URL.getSalesforceBaseUrl().toExternalForm() + '/' + SaveResult.getId();
                }
                
                if (Inspection.Inspection_Items__r.size() > 0) {
                    
                    List<TW1_Inspection_Item__c> listInspecItens = new list<TW1_Inspection_Item__c>();
                    
                    for (TW1_Inspection_Item__c InspecItem: Inspection.Inspection_Items__r) {
                        TW1_Inspection_Item__c inspectionItem = new TW1_Inspection_Item__c();
                        
                        inspectionItem.TW1_Quantity__c = InspecItem.TW1_Quantity__c;
                        inspectionItem.TW1_Tag_or_Certificate_Number__c = InspecItem.TW1_Tag_or_Certificate_Number__c;
                        inspectionItem.TW1_Heat_Number__c = InspecItem.TW1_Heat_Number__c;
                        inspectionItem.TW1_Item_Description__c = InspecItem.TW1_Item_Description__c;
                        inspectionItem.TW1_Request__c = SaveResult.getId();
                        inspectionItem.TW1_Previous_Status__c = InspecItem.TW1_Status__c;
                        inspectionItem.TW5_Isometric_Drawing__c = InspecItem.TW5_Isometric_Drawing__c;
                        inspectionItem.TW5_PO_Item_Number__c = InspecItem.TW5_PO_Item_Number__c;
                        
                        listInspecItens.add(inspectionItem);
                    }
                    insert listInspecItens;
                }
            } else {
                for (Database.Error err : SaveResult.getErrors()) {
                    ResponseDto.Status = 'Erro';
                    ResponseDto.MessageList.add(err.getMessage());
                    System.debug('Database.Error T_MODEC_CloneInspection_App.class - Method: CloneInspection() ==> ' + err.getMessage());
                }
            }
        } catch(Exception e){
            ResponseDto.Status = 'Erro';
            ResponseDto.MessageList.add(e.getMessage());
            System.debug('Exception.Error T_MODEC_CloneInspection_App.class - Method: CloneInspection() ==> ' + e.getMessage());
        }
        return ResponseDto;
    }
}