force-app/main/default/objects/ExchangeRate__c/ExchangeRate__c.object-meta.xml
<CustomObject>
    <label>Exchange Rate</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Exchange Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exchanges Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ExchangeRate__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NAM__c/NAM__c.object-meta.xml
<CustomObject>
    <label>NAM</label>
    <nameField>
        <label>NAM Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NAMs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NAM__c/fields/BRLRate__c.field-meta.xml
<CustomField>
    <fullName>BRLRate__c</fullName>
    <label>BRL Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/BRLRate__c.field-meta.xml
<CustomField>
    <fullName>BRLRate__c</fullName>
    <label>BRL Rate</label>
    <summarizedField>WorkOrderLineItem.BRLRate__c</summarizedField>
    <summaryForeignKey>WorkOrderLineItem.WorkOrderId</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/NAM__c.field-meta.xml
<CustomField>
    <fullName>NAM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NAM</label>
    <referenceTo>NAM__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>WorkOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/BRL__c.field-meta.xml
<CustomField>
    <fullName>BRL__c</fullName>
    <inlineHelpText>R$</inlineHelpText>
    <label>Price BRL</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/BRLRate__c.field-meta.xml
<CustomField>
    <fullName>BRLRate__c</fullName>
    <label>BRL Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/BRLUpdate__c.field-meta.xml
<CustomField>
    <fullName>BRLUpdate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BRL Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/NAM__c.field-meta.xml
<CustomField>
    <fullName>NAM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NAM</label>
    <referenceTo>NAM__c</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>WorkOrderLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <inlineHelpText>USD</inlineHelpText>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/ResponsibleCountry__c.field-meta.xml
<CustomField>
    <fullName>ResponsibleCountry__c</fullName>
    <label>Responsible</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Outside of Brazil</fullName>
            </value>
            <value>
                <fullName>MODEC, Inc</fullName>
                <isActive>false</isActive>
                <label>MODEC, Inc</label>
            </value>
            <value>
                <fullName>MdB</fullName>
                <isActive>false</isActive>
                <label>MdB</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/ResponsibleWO__c.field-meta.xml
<CustomField>
    <fullName>ResponsibleWO__c</fullName>
    <formula>WorkOrder.Contractor__r.ShortName__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Responsible WO</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WorkOrderLineItemBO.cls
public class WorkOrderLineItemBO {
    private static final WorkOrderLineItemBO instance = new WorkOrderLineItemBO();

	public static WorkOrderLineItemBO getInstance() {
		return instance;
	}
    public void updateFields(List<WorkOrderLineItem> lstWoItem, Map<Id, WorkOrderLineItem> mapWOLineItem){
        ExchangeRATE__c exchangeValue = [SELECT value__c FROM ExchangeRATE__c WHERE Active__c =: true LIMIT 1];       
        Set<Id> setWO = new Set<Id>(); 
        for(WorkOrderLineItem woLine : lstWoItem){
            setWO.add(woLine.WorkOrderId);
        }
        Map<String, WorkOrder> mapWO = new Map<String, WorkOrder> (WorkOrderDAO.getByWOItem(setWO));
        Map<String, Decimal> mapNamRate = new Map<String, Decimal>();

        for(WorkOrderLineItem woLine : lstWoItem){
            woLine.NAM__c = mapWO.get(woLine.WorkORderId).NAM__c;
            //if((woLine.ResponsibleWO__c == 'MdB' && !woLine.BRLUpdate__c) && (mapWOLineItem == null || woLine.Price__c != mapWOLineItem.get(woLine.Id).Price__c) ) {
            if(woLine.ResponsibleCountry__c == 'Brazil' || woLine.ResponsibleCountry__c == 'MdB' ){
                woLine.BRL__c = (woLine.Price__c == null? 0: exchangeValue.Value__c * woLine.Price__c);
                woLine.BRLRate__c = exchangeValue.Value__c;
                mapNamRate.put(mapWO.get(woLine.WorkORderId).NAM__c, exchangeValue.Value__c );
            }//else if(woLine.ResponsibleWO__c != 'MdB'){
            else{
                woLine.BRL__c = null;
                woLine.BRLRate__c = null;
            }
        }
    }
}