force-app/main/default/objects/ExchangeRate__c/ExchangeRate__c.object-meta.xml
<CustomObject>
    <label>Exchange Rate</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Exchange Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exchanges Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ExchangeRate__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NAM__c/NAM__c.object-meta.xml
<CustomObject>
    <label>NAM</label>
    <nameField>
        <label>NAM Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NAMs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NAM__c/fields/CounterMeasure__c.field-meta.xml
<CustomField>
    <fullName>CounterMeasure__c</fullName>
    <label>Counter Measure</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/CriticalityCategory__c.field-meta.xml
<CustomField>
    <fullName>CriticalityCategory__c</fullName>
    <label>Criticality Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Safety</fullName>
            </value>
            <value>
                <fullName>Shutdown</fullName>
            </value>
            <value>
                <fullName>Regulation</fullName>
            </value>
            <value>
                <fullName>Other Special</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NAM__c/fields/CriticalityUrgency__c.field-meta.xml
<CustomField>
    <fullName>CriticalityUrgency__c</fullName>
    <label>Criticality Urgency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Within 24 Hours</fullName>
            </value>
            <value>
                <fullName>Within 1 Week</fullName>
            </value>
            <value>
                <fullName>Within 1 Month</fullName>
            </value>
            <value>
                <fullName>Within 1 Year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NAM__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/EscalationRisk__c.field-meta.xml
<CustomField>
    <fullName>EscalationRisk__c</fullName>
    <label>Escalation Risk</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/IssueDate__c.field-meta.xml
<CustomField>
    <fullName>IssueDate__c</fullName>
    <label>Issue Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/Revision__c.field-meta.xml
<CustomField>
    <fullName>Revision__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Revision</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AMC</fullName>
                <default>true</default>
                <label>AMC</label>
            </value>
            <value>
                <fullName>OM</fullName>
            </value>
            <value>
                <fullName>PEM</fullName>
            </value>
            <value>
                <fullName>Tech Team</fullName>
            </value>
            <value>
                <fullName>SPC Partners</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>SPC Modec</fullName>
                <isActive>false</isActive>
                <label>SPC Modec</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NAM__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/SubSystemNumber__c.field-meta.xml
<CustomField>
    <fullName>SubSystemNumber__c</fullName>
    <label>SubSystem Number</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SystemNumber__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Mooring Chan / Wire / Rope &amp; Fairlead</fullName>
                <label>Mooring Chain / Wire / Rope &amp; Fairlead</label>
            </value>
            <value>
                <fullName>Chain Handling / Chain Jack / Chain Stoppers - FWD</fullName>
            </value>
            <value>
                <fullName>Chain Handling / Chain Jack / Chain Stoppers - AFT</fullName>
            </value>
            <value>
                <fullName>Riser Pull-in Winch</fullName>
            </value>
            <value>
                <fullName>Riser Pull-in Equipment</fullName>
            </value>
            <value>
                <fullName>Inlet Oil Production</fullName>
            </value>
            <value>
                <fullName>Crude Oil Treating / Stabilization</fullName>
            </value>
            <value>
                <fullName>Flowline Circulation System</fullName>
            </value>
            <value>
                <fullName>Produced Water Treatment System</fullName>
            </value>
            <value>
                <fullName>Seawater Treatment &amp; Distribution</fullName>
            </value>
            <value>
                <fullName>Seawater Injection Pumps</fullName>
            </value>
            <value>
                <fullName>Inlet Gas Production / Lift / Export / Import / Injection</fullName>
            </value>
            <value>
                <fullName>Vapor Recovery Unit</fullName>
            </value>
            <value>
                <fullName>Main Gas Compression - A</fullName>
            </value>
            <value>
                <fullName>Gas Dehydration &amp; Regeneration</fullName>
            </value>
            <value>
                <fullName>Gas Compression (GI)</fullName>
            </value>
            <value>
                <fullName>Main Gas Compression - B</fullName>
            </value>
            <value>
                <fullName>HP Flare System</fullName>
            </value>
            <value>
                <fullName>Carcass Vent</fullName>
            </value>
            <value>
                <fullName>Fuel Gas System</fullName>
            </value>
            <value>
                <fullName>Gas Lift Compression</fullName>
            </value>
            <value>
                <fullName>Chemical Injection Tank - A</fullName>
            </value>
            <value>
                <fullName>Chemical Injection Tank - B</fullName>
            </value>
            <value>
                <fullName>Closed Drain System</fullName>
            </value>
            <value>
                <fullName>Open Drain System</fullName>
            </value>
            <value>
                <fullName>Heating Medium System</fullName>
            </value>
            <value>
                <fullName>PIP Heating System</fullName>
            </value>
            <value>
                <fullName>Cooling Medium System</fullName>
            </value>
            <value>
                <fullName>Process Inert Gas (N2)</fullName>
            </value>
            <value>
                <fullName>Diesel Generator - 1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NAM__c/fields/SystemNumber__c.field-meta.xml
<CustomField>
    <fullName>SystemNumber__c</fullName>
    <label>System Number</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>06 - Mooring System Mechanical Component</fullName>
            </value>
            <value>
                <fullName>07 - Mooring System Component</fullName>
            </value>
            <value>
                <fullName>08 - Installation Aids</fullName>
            </value>
            <value>
                <fullName>10 - Inlet Oil Production</fullName>
            </value>
            <value>
                <fullName>11 - Crude Oil Treating/Stabilization</fullName>
            </value>
            <value>
                <fullName>12 - Flowline Circulation</fullName>
            </value>
            <value>
                <fullName>14 - Produced Water Treatment</fullName>
            </value>
            <value>
                <fullName>15 - Seawater Treatment &amp; Injection</fullName>
            </value>
            <value>
                <fullName>21 - Vapor Recovery Unit</fullName>
            </value>
            <value>
                <fullName>20 - Inlet Gas Production/Gas Lift/Gas Export/Gas Import/Gas Injection</fullName>
            </value>
            <value>
                <fullName>22 - Main Gas Compression</fullName>
            </value>
            <value>
                <fullName>23 - Gas Dehydration &amp; Regeneration</fullName>
            </value>
            <value>
                <fullName>24 - Gas Compression (GI)</fullName>
            </value>
            <value>
                <fullName>30 - Flare &amp; Vent</fullName>
            </value>
            <value>
                <fullName>31 - Fuel Gas System - General</fullName>
            </value>
            <value>
                <fullName>33 - Chemical Injection</fullName>
            </value>
            <value>
                <fullName>34 - Closed/Open Drain System</fullName>
            </value>
            <value>
                <fullName>35 - Heat Medium</fullName>
            </value>
            <value>
                <fullName>36 - Cooling Medium</fullName>
            </value>
            <value>
                <fullName>37 - Process Inert Gas (N2)</fullName>
            </value>
            <value>
                <fullName>40 - Power Generation</fullName>
            </value>
            <value>
                <fullName>41 - Fuel System - Marine</fullName>
            </value>
            <value>
                <fullName>42 - Seawater System</fullName>
            </value>
            <value>
                <fullName>43 - Steam &amp; Condensate System</fullName>
            </value>
            <value>
                <fullName>44 - Potable &amp; Fresh Water System</fullName>
            </value>
            <value>
                <fullName>45-Compressed(Utility &amp; Instrument)Air</fullName>
            </value>
            <value>
                <fullName>46 - Lube Oil System</fullName>
            </value>
            <value>
                <fullName>47 - Bilge System</fullName>
            </value>
            <value>
                <fullName>50 - Life Saving &amp; Emergency Rescue</fullName>
            </value>
            <value>
                <fullName>51 - E/R</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NAM__c/fields/TypeEvent__c.field-meta.xml
<CustomField>
    <fullName>TypeEvent__c</fullName>
    <label>Type of Event</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accident</fullName>
            </value>
            <value>
                <fullName>Mechanical Failure</fullName>
            </value>
            <value>
                <fullName>Wear &amp; Tear</fullName>
            </value>
            <value>
                <fullName>Design Error</fullName>
            </value>
            <value>
                <fullName>Preventive</fullName>
            </value>
            <value>
                <fullName>Upgrade/Modification</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NAM__c/fields/Vessel__c.field-meta.xml
<CustomField>
    <fullName>Vessel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vessel</label>
    <referenceTo>Vessel__c</referenceTo>
    <relationshipLabel>NAMs</relationshipLabel>
    <relationshipName>NAMs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vessel__c/Vessel__c.object-meta.xml
<CustomObject>
    <label>Vessel</label>
    <nameField>
        <label>Vessel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vessels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vessel__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Decommissioned</fullName>
            </value>
            <value>
                <fullName>EPCI</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>In Operation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NAMFactory.cls
public  class NAMFactory {
   
    public static NAM__c createNAM(Vessel__c vessel, string namName) {
        NAM__c nam = new NAM__c(
            Name = namName,
            Revision__c = 0,
            Status__c = 'AMC',
            Vessel__c = vessel.Id,
            IssueDate__c = Date.today(),
            Subject__c = 'Error 1',
            SystemNumber__c = '06 - Mooring System Mechanical Component',
            SubSystemNumber__c = 'Mooring Chain / Wire / Rope & Fairlead',
            TypeEvent__c = 'Accident',
            CriticalityCategory__c = 'Safety',
            CriticalityUrgency__c = 'Within 24 Hours',
            // ResponsibilityCategory__c = 'Warranty',
            Description__c = 'Descv',
            EscalationRisk__c = 'Escalation',
            CounterMeasure__c = 'Counter'
        );
        insert nam;
        return nam;
    }
    public static ExchangeRATE__c createExchange() {
        ExchangeRATE__c exchange = new ExchangeRATE__c(Active__c = true, value__c = 4);
            
        insert exchange;
        return exchange;
    }
}