force-app/main/default/objects/Letter__c/Letter__c.object-meta.xml
<CustomObject>
    <label>Letter</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Letter Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Letters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Letter__c/fields/LetterGroup__c.field-meta.xml
<CustomField>
    <fullName>LetterGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Letter Group</label>
    <referenceTo>LetterGroup__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Vessel__c.field-meta.xml
<CustomField>
    <fullName>Vessel__c</fullName>
    <label>Vessel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Letter__c/recordTypes/Received.recordType-meta.xml
<RecordType>
    <fullName>Received</fullName>
    <active>true</active>
    <label>Received</label>
</RecordType>

force-app/main/default/objects/LetterGroup__c/LetterGroup__c.object-meta.xml
<CustomObject>
    <label>Letter Group</label>
    <nameField>
        <displayFormat>LG-{00000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Letter Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LetterGroup__c/fields/Vessel__c.field-meta.xml
<CustomField>
    <fullName>Vessel__c</fullName>
    <label>Vessel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LetterGroupVesselAssociation__c/LetterGroupVesselAssociation__c.object-meta.xml
<CustomObject>
    <label>Letter Group Vessel Association</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Letter Group Vessel Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LetterGroupVesselAssociation__c/fields/LetterGroup__c.field-meta.xml
<CustomField>
    <fullName>LetterGroup__c</fullName>
    <label>Letter Group</label>
    <referenceTo>LetterGroup__c</referenceTo>
    <relationshipLabel>Letter Group Vessel Associations</relationshipLabel>
    <relationshipName>LetterGroupVesselAssociationsLetterGroup</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LetterGroupVesselAssociation__c/fields/Vessel__c.field-meta.xml
<CustomField>
    <fullName>Vessel__c</fullName>
    <label>Vessel</label>
    <referenceTo>Vessel__c</referenceTo>
    <relationshipLabel>Letter Group Vessel Associations</relationshipLabel>
    <relationshipName>LetterGroupVesselAssociationsVessel</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LetterVesselAssociation__c/LetterVesselAssociation__c.object-meta.xml
<CustomObject>
    <label>Letter Vessel Association</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Letter Vessel Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LetterVesselAssociation__c/fields/Letter__c.field-meta.xml
<CustomField>
    <fullName>Letter__c</fullName>
    <label>Letter</label>
    <referenceTo>Letter__c</referenceTo>
    <relationshipLabel>Letter Vessel Associations</relationshipLabel>
    <relationshipName>LetterVesselAssociationsLetter</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LetterVesselAssociation__c/fields/Vessel__c.field-meta.xml
<CustomField>
    <fullName>Vessel__c</fullName>
    <label>Vessel</label>
    <referenceTo>Vessel__c</referenceTo>
    <relationshipLabel>Letter Vessel Associations</relationshipLabel>
    <relationshipName>LetterVesselAssociationsVessel</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Vessel__c/Vessel__c.object-meta.xml
<CustomObject>
    <label>Vessel</label>
    <nameField>
        <label>Vessel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vessels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/LetterBO.cls
public with sharing class LetterBO {

    private static final LetterBO instance = new LetterBO();

	public static LetterBO getInstance() {
		return instance;
    }

    public void createVesselAssociations (List<Letter__c> lstLetter)
    {
        List<LetterGroup__c> lstGroup = new List<LetterGroup__c>();
        List<LetterGroupVesselAssociation__c> lstGroupVessels = new List<LetterGroupVesselAssociation__c>();
        List<LetterVesselAssociation__c> lstLetterVessels = new List<LetterVesselAssociation__c>();
        String groupId;
        String letterId;

        for(Letter__c letter : lstLetter)
        {
            if(letter.LetterGroup__c != null)
            {   
                groupId = letter.LetterGroup__c;
                letterId = letter.Id;
            }
        }

        if(groupId != null)
            lstGroupVessels = LetterGroupVesselAssociationDAO.getLetterGroupVesselById(groupId);

        if(lstGroupVessels != null)
        {
            for(LetterGroupVesselAssociation__c groupVessel : lstGroupVessels)
            {
                LetterVesselAssociation__c  letterVessel = new LetterVesselAssociation__c();
                letterVessel.Letter__c = letterId;
                letterVessel.Vessel__c = groupVessel.Vessel__c;

                lstLetterVessels.add(letterVessel);
            }
            insert lstLetterVessels;
        }
    }
    
    public void updateDeadlineLetterGroup(List<Letter__c> lstLetter)
    {
        List<LetterGroup__c> lstGroup = new List<LetterGroup__c>();
        LetterGroup__c letterGroup = new LetterGroup__c();
        Letter__c letterInstance = new Letter__c();
        String idGroup;

        RecordType received = [SELECT Id FROM RecordType WHERE Name = 'Received'];
        
        for(Letter__c letter : lstLetter)
        {
            if(letter.RecordTypeId != received.Id)
            {
                return;
            }
            else 
            {
                if(letter.LetterGroup__c == null)
                {
                    return;
                }

                if(letter.Deadline__c == null)
                {
                    return;
                }
                else
                {
                    idGroup = letter.LetterGroup__c;
                }
            }
        }

        lstGroup = LetterGroupDAO.getLetterGroupById(idGroup);
        letterInstance = lstLetter[0];

        if(!lstGroup.isEmpty())
        {
            letterGroup = lstGroup[0];
            letterGroup.Deadline__c = letterInstance.Deadline__c;

            update letterGroup;
        }
    }
}