force-app/main/default/objects/Letter__c/Letter__c.object-meta.xml
<CustomObject>
    <label>Letter</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Letter Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Letters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Letter__c/fields/ContractAdministrator__c.field-meta.xml
<CustomField>
    <fullName>ContractAdministrator__c</fullName>
    <label>Contract Administrator</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/LetterCode__c.field-meta.xml
<CustomField>
    <fullName>LetterCode__c</fullName>
    <label>Letter Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/LetterGroup__c.field-meta.xml
<CustomField>
    <fullName>LetterGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Letter Group</label>
    <referenceTo>LetterGroup__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Vessel__c.field-meta.xml
<CustomField>
    <fullName>Vessel__c</fullName>
    <label>Vessel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Letter__c/recordTypes/Sent.recordType-meta.xml
<RecordType>
    <fullName>Sent</fullName>
    <active>true</active>
    <label>Sent</label>
</RecordType>

force-app/main/default/objects/LetterGroup__c/LetterGroup__c.object-meta.xml
<CustomObject>
    <label>Letter Group</label>
    <nameField>
        <displayFormat>LG-{00000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Letter Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LetterGroup__c/fields/Vessel__c.field-meta.xml
<CustomField>
    <fullName>Vessel__c</fullName>
    <label>Vessel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LetterGroup__c/recordTypes/Vessel.recordType-meta.xml
<RecordType>
    <fullName>Vessel</fullName>
    <active>true</active>
    <label>Vessel</label>
</RecordType>

force-app/main/default/objects/LetterVesselAssociation__c/LetterVesselAssociation__c.object-meta.xml
<CustomObject>
    <label>Letter Vessel Association</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Letter Vessel Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LetterVesselAssociation__c/fields/Letter__c.field-meta.xml
<CustomField>
    <fullName>Letter__c</fullName>
    <label>Letter</label>
    <referenceTo>Letter__c</referenceTo>
    <relationshipLabel>Letter Vessel Associations</relationshipLabel>
    <relationshipName>LetterVesselAssociationsLetter</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LetterVesselAssociation__c/fields/Vessel__c.field-meta.xml
<CustomField>
    <fullName>Vessel__c</fullName>
    <label>Vessel</label>
    <referenceTo>Vessel__c</referenceTo>
    <relationshipLabel>Letter Vessel Associations</relationshipLabel>
    <relationshipName>LetterVesselAssociationsVessel</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Vessel__c/Vessel__c.object-meta.xml
<CustomObject>
    <label>Vessel</label>
    <nameField>
        <label>Vessel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vessels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vessel__c/fields/ContractResponsible__c.field-meta.xml
<CustomField>
    <fullName>ContractResponsible__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract Administrator</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Vessels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vessel__c/fields/NumberLastSentLetter__c.field-meta.xml
<CustomField>
    <fullName>NumberLastSentLetter__c</fullName>
    <label>Number of last sent Letter</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vessel__c/fields/VesselCode__c.field-meta.xml
<CustomField>
    <fullName>VesselCode__c</fullName>
    <inlineHelpText>Example: MHXXX-MBS</inlineHelpText>
    <label>Vessel Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LVAssociationBO.cls
public with sharing class LVAssociationBO {
    
    private static final LVAssociationBO instance = new LVAssociationBO();

	public static LVAssociationBO getInstance() {
		return instance;
    }

    public void generateLetterCode(List<LetterVesselAssociation__c> lstLVAssociation)
    {
        LetterVesselAssociation__c LVAssociationInstance = new LetterVesselAssociation__c();
        LetterGroup__c letterGroupInstance = new LetterGroup__c();
        Letter__c letterInstance = new Letter__c();
        Vessel__c vesselInstance = new Vessel__c();
        List<LetterGroup__c> lstLetterGroup = new List<LetterGroup__c>();
        List<Letter__c> lstLetter = new List<Letter__c>();
        List<Vessel__c> lstVessel = new List<Vessel__c>();
        String letterCode;
        String numberLastLetter;

        if(!lstLVAssociation.isEmpty())
        {
            LVAssociationInstance = lstLVAssociation[0];
        }
        else 
        {
            return;
        }

        lstLetter = LetterDAO.getLetterById(LVAssociationInstance.Letter__c);

        if(!lstLetter.isEmpty())
        {
            letterInstance = lstLetter[0];
        }

        if(letterInstance.RecordType.DeveloperName != 'Sent')
        {
            return;
        }
        else 
        {
            if(letterInstance.LetterGroup__c != null)
            {
                lstLetterGroup = LetterGroupDAO.getLetterGroupById(letterInstance.LetterGroup__c);
            }
        }

        if(!lstLetterGroup.isEmpty())
        {
            letterGroupInstance = lstLetterGroup[0];
        }

        if(letterGroupInstance.RecordType.DeveloperName != 'Vessel')
        {
            return;
        }
        else 
        {
            lstVessel = VesselDAO.getInstance().getVesselById(LVAssociationInstance.Vessel__c);
        }

        if(!lstVessel.isEmpty())
        {
            vesselInstance = lstVessel[0];
        }

        if(vesselInstance.NumberLastSentLetter__c == null || vesselInstance.NumberLastSentLetter__c < 1)
        {
            vesselInstance.NumberLastSentLetter__c = 1;
            numberLastLetter = '000' + String.valueOf(vesselInstance.NumberLastSentLetter__c);

            if(vesselInstance.VesselCode__c != null)
            {
                letterCode = vesselInstance.VesselCode__c + '-LET-' + numberLastLetter + '-' + System.Today().year(); 

                letterInstance.LetterCode__c = letterCode;
                
                update letterInstance;
                update vesselInstance;
            }
        }
        else 
        {
            System.debug('entrei no else');
            vesselInstance.NumberLastSentLetter__c ++;
            System.debug('vesselInstance.NumberLastSentLetter__c -- ' + vesselInstance.NumberLastSentLetter__c);
            numberLastLetter = '000' + String.valueOf(vesselInstance.NumberLastSentLetter__c);

            if(vesselInstance.VesselCode__c != null)
            {
                letterCode = vesselInstance.VesselCode__c + '-LET-' + numberLastLetter.right(4) + '-' + System.Today().year(); 

                letterInstance.LetterCode__c = letterCode;
                
                update letterInstance;
                update vesselInstance;
            }

        }
    }

    public void fillVesselName(List<LetterVesselAssociation__c> lstLVAssociation, Map<Id, LetterVesselAssociation__c> oldMap){

        List<Letter__c> lstLetter = new List<Letter__c>();
        List<LetterVesselAssociation__c> lstLetterVessels = new List<LetterVesselAssociation__c>();
        List<Letter__c> lstUpdate = new List<Letter__c>();
        Vessel__c vesselRecord = new Vessel__c();
        String idLetter;
        String vesselId = '';
        String vessel = '';
        Integer contador = 0;

        System.debug('user id -> ' + UserInfo.getUserId());
    
        if(oldMap == null){

            for(LetterVesselAssociation__c lst : lstLVAssociation){

                if(!lstLVAssociation.isEmpty()){
                    idLetter = lst.Letter__c;
                }
            }

            lstLetter = LetterDAO.getLetterById(idLetter);
            lstLetterVessels = LetterVesselAssociationDAO.getLetterVesselById(idLetter);

            for(LetterVesselAssociation__c lstLV : lstLetterVessels){

                for(Letter__c letter : lstLetter){
            
                    if(contador == 0){
                        letter.Vessel__c = '';
                    }
                    letter.Vessel__c = letter.Vessel__c + ' ' + lstLV.VesselShortName__c;
                    vessel = letter.Vessel__c;
                    vesselId = lstLV.Vessel__c;
                    contador ++;
                    
                }
            }

            vesselRecord = VesselDAO.getInstance().getVesselById(vesselId)[0];

            Letter__c letter = new Letter__c();
            letter = lstLetter[0];
            letter.Vessel__c = vessel;

            if(vesselRecord.ContractResponsible__c != null){
                letter.ContractAdministrator__c = String.ValueOf(vesselRecord.ContractResponsible__c).subString(0,15);
            }

            update letter;

        } else 
        {
            String letterId = oldMap.values().Letter__c;
            idLetter = letterId;

            lstLetter = LetterDAO.getLetterById(idLetter);
            lstLetterVessels = LetterVesselAssociationDAO.getLetterVesselById(idLetter);

            for(LetterVesselAssociation__c lstLV : lstLetterVessels){

                for(Letter__c letter : lstLetter){
                
                    if(contador == 0){
                        letter.Vessel__c = '';
                    }
                        letter.Vessel__c = letter.Vessel__c + ' ' + lstLV.VesselShortName__c;
                        vessel = letter.Vessel__c;
                        contador ++;
                }
            }

            Letter__c letterDelete = new Letter__c();
            letterDelete = lstLetter[0];
            letterDelete.Vessel__c = vessel;
            update letterDelete;
        } 
    }  
}