force-app/main/default/objects/Letter__c/Letter__c.object-meta.xml
<CustomObject>
    <label>Letter</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Letter Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Letters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Letter__c/fields/LetterGroup__c.field-meta.xml
<CustomField>
    <fullName>LetterGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Letter Group</label>
    <referenceTo>LetterGroup__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LetterGroup__c/LetterGroup__c.object-meta.xml
<CustomObject>
    <label>Letter Group</label>
    <nameField>
        <displayFormat>LG-{00000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Letter Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VORVO__c/VORVO__c.object-meta.xml
<CustomObject>
    <label>VOR/VO</label>
    <nameField>
        <displayFormat>V-{00000}</displayFormat>
        <label>VOR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VOR/VOs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VORVO__c/fields/Letter__c.field-meta.xml
<CustomField>
    <fullName>Letter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Letter</label>
    <referenceTo>Letter__c</referenceTo>
    <relationshipName>VORs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VORVO__c/fields/LetterGroup__c.field-meta.xml
<CustomField>
    <fullName>LetterGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Letter Group</label>
    <referenceTo>LetterGroup__c</referenceTo>
    <relationshipLabel>VOR/VOs</relationshipLabel>
    <relationshipName>VORVOs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/VORVOBO.cls
public with sharing class VORVOBO {
    
    private static final VORVOBO instance = new VORVOBO();

	public static VORVOBO getInstance() {
		return instance;
    }

    public void fillLetterGroup(List<VORVO__c> lstVORVO)
    {
        List<Letter__c> lstLetter = new List<Letter__c>();
        String idLetter;
        String idLetterGroup;

        for(VORVO__c vor : lstVORVO)
        {
            if(vor.Letter__c != null && vor.LetterGroup__c == null)
            {
                idLetter = vor.Letter__c;
            }
            else 
            {
                return;    
            }
        }

        lstLetter = LetterDAO.getLetterById(idLetter);

        if(!lstLetter.isEmpty())
        {
            for(Letter__c letter : lstLetter)
            {
                if(letter.LetterGroup__c != null)
                {
                    idLetterGroup = letter.LetterGroup__c;

                    for(VORVO__c vor : lstVORVO)
                    {
                        vor.LetterGroup__c = idLetterGroup;
                    }
                }
            }
        }
    }
}