force-app/main/default/objects/Letter__c/Letter__c.object-meta.xml
<CustomObject>
    <label>Letter</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Letter Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Letters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Letter__c/fields/AnswerNeeded__c.field-meta.xml
<CustomField>
    <fullName>AnswerNeeded__c</fullName>
    <label>Answer Needed?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Letter__c/fields/LetterGroup__c.field-meta.xml
<CustomField>
    <fullName>LetterGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Letter Group</label>
    <referenceTo>LetterGroup__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Penalty__c.field-meta.xml
<CustomField>
    <fullName>Penalty__c</fullName>
    <label>Penalty</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Letter__c/fields/ReceivedDate__c.field-meta.xml
<CustomField>
    <fullName>ReceivedDate__c</fullName>
    <label>Received Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/SendDate__c.field-meta.xml
<CustomField>
    <fullName>SendDate__c</fullName>
    <label>Send Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Closed in Delay</fullName>
            </value>
            <value>
                <fullName>Closed on Time</fullName>
            </value>
            <value>
                <fullName>Delay</fullName>
            </value>
            <value>
                <fullName>No Actions</fullName>
            </value>
            <value>
                <fullName>Ongoing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Letter__c/fields/Vessel__c.field-meta.xml
<CustomField>
    <fullName>Vessel__c</fullName>
    <label>Vessel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LetterGroup__c/LetterGroup__c.object-meta.xml
<CustomObject>
    <label>Letter Group</label>
    <nameField>
        <displayFormat>LG-{00000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Letter Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LetterGroup__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LetterGroup__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LetterGroup__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LetterGroup__c/fields/Vessel__c.field-meta.xml
<CustomField>
    <fullName>Vessel__c</fullName>
    <label>Vessel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Penalty__c/Penalty__c.object-meta.xml
<CustomObject>
    <label>Penalty</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Penalty Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Penalties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Penalty__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Penalty__c/fields/Letter__c.field-meta.xml
<CustomField>
    <fullName>Letter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Letter</label>
    <referenceTo>Letter__c</referenceTo>
    <relationshipLabel>Penalties</relationshipLabel>
    <relationshipName>Penalties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Penalty__c/fields/LetterGroup__c.field-meta.xml
<CustomField>
    <fullName>LetterGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Letter Group</label>
    <referenceTo>LetterGroup__c</referenceTo>
    <relationshipLabel>Penalties</relationshipLabel>
    <relationshipName>Penalties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Penalty__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Deducted</fullName>
            </value>
            <value>
                <fullName>Exposure</fullName>
            </value>
            <value>
                <fullName>In dispute</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
            <value>
                <fullName>Open</fullName>
                <isActive>false</isActive>
                <label>Open</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Penalty__c/fields/Vessel__c.field-meta.xml
<CustomField>
    <fullName>Vessel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vessel</label>
    <referenceTo>Vessel__c</referenceTo>
    <relationshipLabel>Penalties</relationshipLabel>
    <relationshipName>Penalties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vessel__c/Vessel__c.object-meta.xml
<CustomObject>
    <label>Vessel</label>
    <nameField>
        <label>Vessel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vessels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vessel__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Decommissioned</fullName>
            </value>
            <value>
                <fullName>EPCI</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>In Operation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LetterDAO.cls
public with sharing class LetterDAO {
    
    public static List<Letter__c> getLetterById(String idLetter){
        return [SELECT 
                  id,   
                  AnswerNeeded__c,
                  Comments__c,
                  Deadline__c,
                  LetterGroup__c,
                  Penalty__c,
                  ReceivedDate__c,
                  RecordType.DeveloperName,
                  RecordType.Name,
                  SendDate__c,
                  Status__c,
                  Subject__c,
                  Vessel__c
                  FROM
                  Letter__c
                  WHERE
                  id =: idLetter];
    }
}