force-app/main/default/objects/Controle_de_Triggers__c/Controle_de_Triggers__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Controle de triggers para facilitar controle de acesso e configuração.</description>
    <label>Controle de Triggers</label>
</CustomObject>

force-app/main/default/objects/Controle_de_Triggers__c/fields/Request_Vendor_Vetting_RecId__c.field-meta.xml
<CustomField>
    <fullName>Request_Vendor_Vetting_RecId__c</fullName>
    <label>Request Vendor Vetting RecId</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Controle_de_Triggers__c/fields/Trigger_Account__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Trigger Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Controle_de_Triggers__c/fields/Trigger_BMItem__c.field-meta.xml
<CustomField>
    <fullName>Trigger_BMItem__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Trigger_BMItem</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Controle_de_Triggers__c/fields/Trigger_Inspection_Item__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Inspection_Item__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Trigger Inspection Item</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Controle_de_Triggers__c/fields/Trigger_Request__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Request__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Trigger_Request</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ID_Account__c/ID_Account__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ID - Account</label>
</CustomObject>

force-app/main/default/objects/ID_Account__c/fields/Id_IntegrationUser__c.field-meta.xml
<CustomField>
    <fullName>Id_IntegrationUser__c</fullName>
    <label>Id_IntegrationUser</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ID_Queues__c/ID_Queues__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ID Queues</label>
</CustomObject>

force-app/main/default/objects/ID_Queues__c/fields/ID_Procurement_Manager_Queue__c.field-meta.xml
<CustomField>
    <fullName>ID_Procurement_Manager_Queue__c</fullName>
    <label>ID Procurement Manager Queue</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IDStep__c/IDStep__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ID - Step</label>
</CustomObject>

force-app/main/default/objects/IDStep__c/fields/Id_RecordType_Procurement_Manager__c.field-meta.xml
<CustomField>
    <fullName>Id_RecordType_Procurement_Manager__c</fullName>
    <label>Id RecordType Procurement Manager</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IDStep__c/fields/Id_RecordType_VVW_Attachment__c.field-meta.xml
<CustomField>
    <fullName>Id_RecordType_VVW_Attachment__c</fullName>
    <label>Id RecordType VVW Attachment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/T_Debug_Setting__mdt/T_Debug_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Configurações de Debug</description>
    <label>Triscal debug setting</label>
    <pluralLabel>Triscal debug setting</pluralLabel>
</CustomObject>

force-app/main/default/objects/T_Debug_Setting__mdt/fields/T_Armazenar_Cause__c.field-meta.xml
<CustomField>
    <fullName>T_Armazenar_Cause__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Se true armazena a causa da exception caso exista</description>
    <label>Armazenar Cause?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/T_Debug_Setting__mdt/fields/T_Armazenar_linha_debug__c.field-meta.xml
<CustomField>
    <fullName>T_Armazenar_linha_debug__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Se true armazena linha de debug</description>
    <label>Armazenar linha debug?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/T_Debug_Setting__mdt/fields/T_Armazenar_StackTrace__c.field-meta.xml
<CustomField>
    <fullName>T_Armazenar_StackTrace__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Se true então armazena o StackTrace da exceção</description>
    <inlineHelpText>Se true então armazena o StackTrace da exceção</inlineHelpText>
    <label>Armazenar StackTrace?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/T_Debug_Setting__mdt/fields/T_Armazenar_texto_Exception__c.field-meta.xml
<CustomField>
    <fullName>T_Armazenar_texto_Exception__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Se true então armazena o texto da exceção</description>
    <inlineHelpText>Se true então armazena o texto da exceção</inlineHelpText>
    <label>Armazenar texto Exception?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TW1_Facility__c/TW1_Facility__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Facility__c/fields/TW1_Facility__c.field-meta.xml
<CustomField>
    <fullName>TW1_Facility__c</fullName>
    <label>Facility</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Facility__c/fields/TW1_Type__c.field-meta.xml
<CustomField>
    <fullName>TW1_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>Vessel</fullName>
            </value>
            <value>
                <fullName>Warehouse</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Inspection_Item__c/TW1_Inspection_Item__c.object-meta.xml
<CustomObject>
    <label>Inspection Item</label>
    <nameField>
        <displayFormat>Item-{000000}</displayFormat>
        <label>Inspection Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspection Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Inspection_Item__c/fields/TW1_All_Appraisal__c.field-meta.xml
<CustomField>
    <fullName>TW1_All_Appraisal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>All Appraisal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TW1_Inspection_Item__c/fields/TW1_Request__c.field-meta.xml
<CustomField>
    <fullName>TW1_Request__c</fullName>
    <label>Request</label>
    <referenceTo>TW1_Request__c</referenceTo>
    <relationshipLabel>Inspection Items</relationshipLabel>
    <relationshipName>Inspection_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TW1_Inspection_Item__c/fields/TW1_Status__c.field-meta.xml
<CustomField>
    <fullName>TW1_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Previously Inspected</fullName>
            </value>
            <value>
                <fullName>Approved with Restriction</fullName>
            </value>
            <value>
                <fullName>Approved by OM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Request__c/TW1_Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>REQ{000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Request__c/fields/TW1_All_Appraisal__c.field-meta.xml
<CustomField>
    <fullName>TW1_All_Appraisal__c</fullName>
    <label>All Appraisal</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_All_Inspection_Items_Status__c.field-meta.xml
<CustomField>
    <fullName>TW1_All_Inspection_Items_Status__c</fullName>
    <label>All Inspection Items Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved with Restriction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_All_Inspection_Items_Status_Filled__c.field-meta.xml
<CustomField>
    <fullName>TW1_All_Inspection_Items_Status_Filled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>All Inspection Items Status Filled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Change_and_Repair_Project__c.field-meta.xml
<CustomField>
    <fullName>TW1_Change_and_Repair_Project__c</fullName>
    <inlineHelpText>(PAR). Fill as the Ex.: PAR-2020-0001</inlineHelpText>
    <label>Change and Repair Project</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Facility__c.field-meta.xml
<CustomField>
    <fullName>TW1_Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>TW1_Facility__c</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Inspection_Status__c.field-meta.xml
<CustomField>
    <fullName>TW1_Inspection_Status__c</fullName>
    <label>Inspection Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TW1_Inspection_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Management_Of_Change__c.field-meta.xml
<CustomField>
    <fullName>TW1_Management_Of_Change__c</fullName>
    <inlineHelpText>(MOC) Fill as the Ex.: MOC-MV20-20-00001</inlineHelpText>
    <label>Management Of Change</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Project_Number__c.field-meta.xml
<CustomField>
    <fullName>TW1_Project_Number__c</fullName>
    <inlineHelpText>Supplier number control</inlineHelpText>
    <label>Project Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>TW1_Purchase_Order__c</fullName>
    <inlineHelpText>Fill as the Ex.: PO-45000XXXXX / AM-MV20-20-00001</inlineHelpText>
    <label>Purchase Order</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Status__c.field-meta.xml
<CustomField>
    <fullName>TW1_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Work_Order__c.field-meta.xml
<CustomField>
    <fullName>TW1_Work_Order__c</fullName>
    <inlineHelpText>(WO). Fill as the Ex.: WOCS-20-00001</inlineHelpText>
    <label>Work Order</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/recordTypes/Inspection.recordType-meta.xml
<RecordType>
    <fullName>Inspection</fullName>
    <active>true</active>
    <label>Inspection</label>
</RecordType>

force-app/main/default/objects/TW1_Request__c/recordTypes/TW1_Vendor_Vetting.recordType-meta.xml
<RecordType>
    <fullName>TW1_Vendor_Vetting</fullName>
    <active>true</active>
    <label>Vendor Vetting</label>
</RecordType>

force-app/main/default/objects/TW1_Step__c/TW1_Step__c.object-meta.xml
<CustomObject>
    <label>Step</label>
    <nameField>
        <displayFormat>S{000000}</displayFormat>
        <label>Steps Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Step__c/fields/TW1_Request__c.field-meta.xml
<CustomField>
    <fullName>TW1_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request</label>
    <referenceTo>TW1_Request__c</referenceTo>
    <relationshipLabel>Steps</relationshipLabel>
    <relationshipName>Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Step__c/fields/TW1_Status__c.field-meta.xml
<CustomField>
    <fullName>TW1_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opened</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Step__c/recordTypes/TW1_Approval_Step_Procurement_Manager.recordType-meta.xml
<RecordType>
    <fullName>TW1_Approval_Step_Procurement_Manager</fullName>
    <active>true</active>
    <label>Approval Step - Procurement Manager</label>
</RecordType>

force-app/main/default/objects/TW1_Step__c/recordTypes/TW1_Approval_Step_VVW_Attachment.recordType-meta.xml
<RecordType>
    <fullName>TW1_Approval_Step_VVW_Attachment</fullName>
    <active>true</active>
    <label>Approval Step - VVW Attachment</label>
</RecordType>

force-app/main/default/globalValueSets/TW1_Inspection_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Inspection Rescheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Reproved</fullName>
    </customValue>
    <customValue>
        <fullName>Awaiting Date Confirmation</fullName>
    </customValue>
    <customValue>
        <fullName>Verifying Date Availability</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>Inspection Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Rescheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <customValue>
        <fullName>Emergency Inspection</fullName>
    </customValue>
    <customValue>
        <fullName>Not Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Approved with Restriction</fullName>
    </customValue>
    <masterLabel>Inspection Status</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/T_MODEC_InspectionItem_TST.cls
/**
 * @File Name          : T_MODEC_InspectionItem_TST.cls
 * @Description        :
 * @Author             : Rafael Hadama
 * @Group              :
 * @Last Modified By   : Rafael Hadama
 * @Last Modified On   : 07-22-2020
 * @Modification Log   :
 * Ver       Date            Author              Modification
 * 1.0    29/06/2020   Rafael Hadama     Initial Version
 **/
@isTest
public class T_MODEC_InspectionItem_TST {
    @TestSetup
    public static void criarCustomSettings() //Obs.: Apenas Triggers que contêm este método serão liberadas
    {
        Controle_de_Triggers__c ctrlTriggers = new Controle_de_Triggers__c();
        ctrlTriggers.Trigger_Request__c              = true; // ***** LEMBRAR ***** (Lembrar de mudar "Trigger_Request__c" ao reutilizar código)
        ctrlTriggers.Trigger_Account__c              = true;
        ctrlTriggers.Trigger_BMItem__c               = true;
        ctrlTriggers.Trigger_Inspection_Item__c      = true;
        ctrlTriggers.Request_Vendor_Vetting_RecId__c = Schema.SObjectType.TW1_Request__c.getRecordTypeInfosByDeveloperName().get('TW1_Vendor_Vetting').getRecordTypeId();
        insert ctrlTriggers;
        //Creating Custom Settings
        ID_Account__c customSettingIdAccount = new ID_Account__c();
        customSettingIdAccount.Id_IntegrationUser__c = UserInfo.getUserId();
        insert customSettingIdAccount;
        //Buscando recordtype para preencher na custom settings
        RecordType recStep           = [SELECT Id, Name, DeveloperName, SobjectType FROM RecordType where DeveloperName = 'TW1_Approval_Step_Procurement_Manager'];
        RecordType recStep2          = [SELECT Id, Name, DeveloperName, SobjectType FROM RecordType where DeveloperName = 'TW1_Approval_Step_VVW_Attachment'];
        IDStep__c  customSettingSTEP = new IDStep__c();
        customSettingSTEP.Id_RecordType_Procurement_Manager__c = recStep.id;
        customSettingSTEP.Id_RecordType_VVW_Attachment__c      = recStep2.Id;
        insert customSettingSTEP;
        //Buscando fila para preencher custom settings
        Group filaPmanager = new Group();
        filaPmanager.Type = 'Queue';
        filaPmanager.Name = 'Procurement_Manager';
        insert       filaPmanager;
        QueueSobject mappingObjectStep    = new QueueSobject(QueueId = filaPmanager.Id, SobjectType = 'TW1_Step__c');
        QueueSobject mappingObjectRequest = new QueueSobject(QueueId = filaPmanager.Id, SobjectType = 'TW1_Request__c');
        System.runAs(new User(Id = UserInfo.getUserId()))
        {
            insert mappingObjectStep;
            insert mappingObjectRequest;
        }
        ID_Queues__c customIdQueues = new ID_Queues__c();
        customIdQueues.ID_Procurement_Manager_Queue__c = filaPmanager.Id;
        insert customIdQueues;
        /*******************************************/
        T_Debug_Setting__mdt testsetting;
        testsetting                                = new T_Debug_Setting__mdt();
        testsetting.Label                          = 'Teste';
        testsetting.DeveloperName                  = 'Teste';
        testsetting.T_Armazenar_Cause__c           = true;
        testsetting.T_Armazenar_linha_debug__c     = true;
        testsetting.T_Armazenar_StackTrace__c      = true;
        testsetting.T_Armazenar_texto_Exception__c = true;
        T_SDK_DebugLog_Test.testsetting            = testsetting;
    }
    /**
     * @description method that validates InspectionItem trigger - testing negative scenario
     * @author Rafael Hadama | 29/06/2020
     * @return void
     **/
    @isTest
    public static void CheckAllInspectionItensTST()
    {
        T_MODEC_Request_Rep RequestREP = new T_MODEC_Request_Rep();
        Test.startTest();
        TW1_Request__c Inspection = CreateInspectionRequest();

        system.debug('Inspection >' + Inspection);
        list<TW1_Inspection_Item__c> ListInspecItem = CreateInspectionItem(Inspection.Id, 3);
        system.debug('ListInspecItem >' + ListInspecItem);
        Inspection.TW1_Inspection_Status__c = 'Inspection Scheduled';
        update Inspection;
        //Atualizar campos do inspection item e depois validar os campos da request.
        Test.stopTest();
        ListInspecItem.get(0).TW1_Status__c = 'Rejected';
        ListInspecItem.get(1).TW1_Status__c = 'Approved';
        ListInspecItem.get(2).TW1_Status__c = null;
        update ListInspecItem;
        TW1_Request__c InspectionAfterUpdate = RequestREP.getRequestById(ListInspecItem.get(0).TW1_Request__c);
        system.debug('InspectionAfterUpdate.TW1_All_Inspection_Items_Status_Filled__c' + InspectionAfterUpdate.TW1_All_Inspection_Items_Status_Filled__c);
        system.debug('InspectionAfterUpdate.TW1_All_Appraisal__c.contains' + InspectionAfterUpdate.TW1_All_Appraisal__c);
        system.debug('InspectionAfterUpdate.TW1_All_Inspection_Items_Status__c' + InspectionAfterUpdate.TW1_All_Inspection_Items_Status__c);
        system.assertEquals(false, InspectionAfterUpdate.TW1_All_Inspection_Items_Status_Filled__c);
        //GUFSTODO Descomentar - system.assertEquals(true, InspectionAfterUpdate.TW1_All_Appraisal__c.contains('Rejection Reason'));
        //GUFSTODO Descomentar - system.assertEquals('Rejected', InspectionAfterUpdate.TW1_All_Inspection_Items_Status__c);

        //Realizar atualizações para que rode a trigger de Inspection Item
    }
    /**
     * @description method that validates InspectionItem trigger - testing positive scenario
     * @author Rafael Hadama | 29/06/2020
     * @return void
     **/
    @isTest
    public static void CheckAllInspectionItensTST2()
    {
        T_MODEC_Request_Rep RequestREP = new T_MODEC_Request_Rep();
        Test.startTest();
        TW1_Request__c Inspection = CreateInspectionRequest();

        system.debug('Inspection >' + Inspection);
        list<TW1_Inspection_Item__c> ListInspecItem = CreateInspectionItem(Inspection.Id, 3);
        system.debug('ListInspecItem >' + ListInspecItem);
        Inspection.TW1_Inspection_Status__c = 'Inspection Scheduled';
        update Inspection;
        //Atualizar campos do inspection item e depois validar os campos da request.
        Test.stopTest();
        ListInspecItem.get(0).TW1_Status__c = 'Approved';
        ListInspecItem.get(1).TW1_Status__c = 'Approved';
        ListInspecItem.get(2).TW1_Status__c = 'Approved';
        update ListInspecItem;
        TW1_Request__c InspectionAfterUpdate = RequestREP.getRequestById(ListInspecItem.get(0).TW1_Request__c);
        system.debug('InspectionAfterUpdate.TW1_All_Inspection_Items_Status_Filled__c' + InspectionAfterUpdate.TW1_All_Inspection_Items_Status_Filled__c);
        system.debug('InspectionAfterUpdate.TW1_All_Appraisal__c.contains' + InspectionAfterUpdate.TW1_All_Appraisal__c);
        system.debug('InspectionAfterUpdate.TW1_All_Inspection_Items_Status__c' + InspectionAfterUpdate.TW1_All_Inspection_Items_Status__c);
        //GUFSTODO Descomentar - system.assertEquals(true, InspectionAfterUpdate.TW1_All_Inspection_Items_Status_Filled__c);
        //GUFSTODO Descomentar - system.assertEquals(false, InspectionAfterUpdate.TW1_All_Appraisal__c.contains('Rejection Reason'));
        //GUFSTODO Descomentar - system.assertEquals('Approved', InspectionAfterUpdate.TW1_All_Inspection_Items_Status__c);

        //Realizar atualizações para que rode a trigger de Inspection Item
    }
    @isTest
    public static void CheckAllInspectionItensTST3()
    {
        T_MODEC_Request_Rep RequestREP = new T_MODEC_Request_Rep();
        Test.startTest();
        TW1_Request__c Inspection = CreateInspectionRequest();

        system.debug('Inspection >' + Inspection);
        list<TW1_Inspection_Item__c> ListInspecItem = CreateInspectionItem(Inspection.Id, 3);
        system.debug('ListInspecItem >' + ListInspecItem);
        Inspection.TW1_Inspection_Status__c = 'Inspection Scheduled';
        update Inspection;
        //Atualizar campos do inspection item e depois validar os campos da request.
        Test.stopTest();
        ListInspecItem.get(0).TW1_Status__c = 'Approved';
        ListInspecItem.get(1).TW1_Status__c = 'Approved';
        ListInspecItem.get(2).TW1_Status__c = 'Approved with Restriction';
        update ListInspecItem;
        TW1_Request__c InspectionAfterUpdate = RequestREP.getRequestById(ListInspecItem.get(0).TW1_Request__c);
        system.debug('InspectionAfterUpdate.TW1_All_Inspection_Items_Status_Filled__c' + InspectionAfterUpdate.TW1_All_Inspection_Items_Status_Filled__c);
        system.debug('InspectionAfterUpdate.TW1_All_Appraisal__c.contains' + InspectionAfterUpdate.TW1_All_Appraisal__c);
        system.debug('InspectionAfterUpdate.TW1_All_Inspection_Items_Status__c' + InspectionAfterUpdate.TW1_All_Inspection_Items_Status__c);
        //GUFSTODO Descomentar - system.assertEquals(true, InspectionAfterUpdate.TW1_All_Inspection_Items_Status_Filled__c);
        //GUFSTODO Descomentar - system.assertEquals(false, InspectionAfterUpdate.TW1_All_Appraisal__c.contains('Rejection Reason'));
        //GUFSTODO Descomentar - system.assertEquals('Approved with Restriction', InspectionAfterUpdate.TW1_All_Inspection_Items_Status__c);

        //Realizar atualizações para que rode a trigger de Inspection Item
    }
    public static TW1_Request__c CreateInspectionRequest()
    {
        TW1_Facility__c Unit = new TW1_Facility__c();
        Unit.TW1_Type__c = 'Office';
        Unit.Name        = 'Unit Mock';
        insert Unit;
        TW1_Request__c Inspection = new TW1_Request__c();
        Inspection.RecordTypeId                           = Schema.SObjectType.TW1_Request__c.getRecordTypeInfosByDeveloperName().get('Inspection').getRecordTypeId();
        Inspection.TW1_Purchase_Order__c                  = 'Purchase Order';
        Inspection.TW1_Work_Order__c                      = 'Work Order Mock';
        Inspection.TW1_Change_and_Repair_Project__c       = 'Change & Repair Project Mock';
        Inspection.TW1_Project_Number__c                  = '123456';
        Inspection.TW1_Management_Of_Change__c            = 'Management of change mock';
        Inspection.TW1_WO_Due_Date__c                     = date.today().addDays(10);
        Inspection.TW1_Planned_Delivery_Date__c           = date.today().addDays(15);
        Inspection.Technical_Inspection_Recommendation__c = 'Technical Inspection Rec Mock';
        Inspection.TW1_Facility__c                        = Unit.Id;
        Inspection.TW1_Inspection_Perfomed__c             = 'Pressure Test';
        Inspection.TW1_Inspection_Contact_Number__c       = '(21) 99999-9999';
        Inspection.TW1_Inspection_Address__c              = 'Macaé';
        Inspection.Inspection_Type__c                     = 'Normal';
        Inspection.TW1_Inspection_Status__c               = 'Not Submitted';
        insert Inspection;
        return Inspection;
    }
    public static list<TW1_Inspection_Item__c> CreateInspectionItem(string RequestId, integer qtd)
    {
        list<TW1_Inspection_Item__c> listInspecItens = new list<TW1_Inspection_Item__c>();
        for (integer i = 0; i < qtd; i++)
        {
            TW1_Inspection_Item__c InspecItem = new TW1_Inspection_Item__c();
            InspecItem.TW1_Item_Description__c          = 'Item Description Mock';
            InspecItem.TW1_Quantity__c                  = 5;
            InspecItem.TW1_Tag_or_Certificate_Number__c = 'Certificate Number Mock';
            InspecItem.TW1_Heat_Number__c               = 'Heat Number Mock';
            InspecItem.TW1_Request__c = RequestId;
            listInspecItens.add(InspecItem);
        }
        insert listInspecItens;
        return listInspecItens;
    }
}