force-app/main/default/objects/Controle_de_Triggers__c/Controle_de_Triggers__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Controle de triggers para facilitar controle de acesso e configuração.</description>
    <label>Controle de Triggers</label>
</CustomObject>

force-app/main/default/objects/Controle_de_Triggers__c/fields/Request_Vendor_Vetting_RecId__c.field-meta.xml
<CustomField>
    <fullName>Request_Vendor_Vetting_RecId__c</fullName>
    <label>Request Vendor Vetting RecId</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Controle_de_Triggers__c/fields/Trigger_Account__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Trigger Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Controle_de_Triggers__c/fields/Trigger_BMItem__c.field-meta.xml
<CustomField>
    <fullName>Trigger_BMItem__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Trigger_BMItem</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Controle_de_Triggers__c/fields/Trigger_Inspection_Item__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Inspection_Item__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Trigger Inspection Item</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Controle_de_Triggers__c/fields/Trigger_Request__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Request__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Trigger_Request</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Controle_de_Triggers__c/fields/Trigger_Step__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Step__c</fullName>
    <defaultValue>false</defaultValue>
    <description>boolean field  to determine if the trigger should fire or not.</description>
    <label>Trigger Step</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Controle_de_Triggers__c/fields/TW2_Inspection_Advance_Hours_Schedule__c.field-meta.xml
<CustomField>
    <fullName>TW2_Inspection_Advance_Hours_Schedule__c</fullName>
    <description>Number field in hours, to control the date available for next inspection</description>
    <label>Inspection Advance Hours Schedule</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Controle_de_Triggers__c/fields/TW2_Inspection_Daily_Hour_Break__c.field-meta.xml
<CustomField>
    <fullName>TW2_Inspection_Daily_Hour_Break__c</fullName>
    <description>Number field to determine a 24 hour clock. Used to determine if today should count as an available date,</description>
    <label>Inspection Daily Hour Break</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ID_Account__c/ID_Account__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ID - Account</label>
</CustomObject>

force-app/main/default/objects/ID_Account__c/fields/Id_IntegrationUser__c.field-meta.xml
<CustomField>
    <fullName>Id_IntegrationUser__c</fullName>
    <label>Id_IntegrationUser</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ID_Queues__c/ID_Queues__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ID Queues</label>
</CustomObject>

force-app/main/default/objects/ID_Queues__c/fields/ID_Procurement_Manager_Queue__c.field-meta.xml
<CustomField>
    <fullName>ID_Procurement_Manager_Queue__c</fullName>
    <label>ID Procurement Manager Queue</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IDStep__c/IDStep__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ID - Step</label>
</CustomObject>

force-app/main/default/objects/IDStep__c/fields/Id_RecordType_Procurement_Manager__c.field-meta.xml
<CustomField>
    <fullName>Id_RecordType_Procurement_Manager__c</fullName>
    <label>Id RecordType Procurement Manager</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IDStep__c/fields/Id_RecordType_VVW_Attachment__c.field-meta.xml
<CustomField>
    <fullName>Id_RecordType_VVW_Attachment__c</fullName>
    <label>Id RecordType VVW Attachment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/T_Debug_Setting__mdt/T_Debug_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Configurações de Debug</description>
    <label>Triscal debug setting</label>
    <pluralLabel>Triscal debug setting</pluralLabel>
</CustomObject>

force-app/main/default/objects/T_Debug_Setting__mdt/fields/T_Armazenar_Cause__c.field-meta.xml
<CustomField>
    <fullName>T_Armazenar_Cause__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Se true armazena a causa da exception caso exista</description>
    <label>Armazenar Cause?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/T_Debug_Setting__mdt/fields/T_Armazenar_linha_debug__c.field-meta.xml
<CustomField>
    <fullName>T_Armazenar_linha_debug__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Se true armazena linha de debug</description>
    <label>Armazenar linha debug?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/T_Debug_Setting__mdt/fields/T_Armazenar_StackTrace__c.field-meta.xml
<CustomField>
    <fullName>T_Armazenar_StackTrace__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Se true então armazena o StackTrace da exceção</description>
    <inlineHelpText>Se true então armazena o StackTrace da exceção</inlineHelpText>
    <label>Armazenar StackTrace?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/T_Debug_Setting__mdt/fields/T_Armazenar_texto_Exception__c.field-meta.xml
<CustomField>
    <fullName>T_Armazenar_texto_Exception__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Se true então armazena o texto da exceção</description>
    <inlineHelpText>Se true então armazena o texto da exceção</inlineHelpText>
    <label>Armazenar texto Exception?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/TW1_Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>REQ{000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Conclusion_Date__c.field-meta.xml
<CustomField>
    <fullName>TW1_Conclusion_Date__c</fullName>
    <label>Conclusion Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Inspection_Status__c.field-meta.xml
<CustomField>
    <fullName>TW1_Inspection_Status__c</fullName>
    <label>Inspection Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TW1_Inspection_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Status__c.field-meta.xml
<CustomField>
    <fullName>TW1_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Request__c/recordTypes/Inspection.recordType-meta.xml
<RecordType>
    <fullName>Inspection</fullName>
    <active>true</active>
    <label>Inspection</label>
</RecordType>

force-app/main/default/objects/TW1_Request__c/recordTypes/TW1_Vendor_Vetting.recordType-meta.xml
<RecordType>
    <fullName>TW1_Vendor_Vetting</fullName>
    <active>true</active>
    <label>Vendor Vetting</label>
</RecordType>

force-app/main/default/objects/TW1_Step__c/TW1_Step__c.object-meta.xml
<CustomObject>
    <label>Step</label>
    <nameField>
        <displayFormat>S{000000}</displayFormat>
        <label>Steps Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Step__c/fields/TW1_Inspection_Date_Confirmation__c.field-meta.xml
<CustomField>
    <fullName>TW1_Inspection_Date_Confirmation__c</fullName>
    <label>Inspection Date Confirmation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Confirm</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Reschedule</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Step__c/fields/TW1_Inspection_Scheduled_Date__c.field-meta.xml
<CustomField>
    <fullName>TW1_Inspection_Scheduled_Date__c</fullName>
    <label>Inspection Scheduled Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TW1_Step__c/fields/TW1_Request__c.field-meta.xml
<CustomField>
    <fullName>TW1_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request</label>
    <referenceTo>TW1_Request__c</referenceTo>
    <relationshipLabel>Steps</relationshipLabel>
    <relationshipName>Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Step__c/fields/TW1_Status__c.field-meta.xml
<CustomField>
    <fullName>TW1_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opened</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Step__c/recordTypes/Approval_Step_Date_Confirmation.recordType-meta.xml
<RecordType>
    <fullName>Approval_Step_Date_Confirmation</fullName>
    <active>true</active>
    <label>Approval Step - Date Confirmation</label>
</RecordType>

force-app/main/default/objects/TW1_Step__c/recordTypes/TW1_Approval_Step_Procurement_Manager.recordType-meta.xml
<RecordType>
    <fullName>TW1_Approval_Step_Procurement_Manager</fullName>
    <active>true</active>
    <label>Approval Step - Procurement Manager</label>
</RecordType>

force-app/main/default/objects/TW1_Step__c/recordTypes/TW1_Approval_Step_VVW_Attachment.recordType-meta.xml
<RecordType>
    <fullName>TW1_Approval_Step_VVW_Attachment</fullName>
    <active>true</active>
    <label>Approval Step - VVW Attachment</label>
</RecordType>

force-app/main/default/globalValueSets/TW1_Inspection_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Inspection Rescheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Reproved</fullName>
    </customValue>
    <customValue>
        <fullName>Awaiting Date Confirmation</fullName>
    </customValue>
    <customValue>
        <fullName>Verifying Date Availability</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>Inspection Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Rescheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <customValue>
        <fullName>Emergency Inspection</fullName>
    </customValue>
    <customValue>
        <fullName>Not Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Approved with Restriction</fullName>
    </customValue>
    <masterLabel>Inspection Status</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/T_MODEC_StepTrigger_TST.cls
/**
 * @description       : T_MODEC_StepTrigger_TST.cls
 * @author            : Rafael Hadama
 * @group             :
 * @last modified on  : 07-22-2020
 * @last modified by  : Rafael Hadama
 * Modifications Log
 * Ver   Date         Author          Modification
 * 1.0   07-06-2020   Rafael Hadama   Initial Version
 **/
@Istest
public class T_MODEC_StepTrigger_TST {
    @TestSetup
    public static void criarCustomSettings() //Obs.: Apenas Triggers que contêm este método serão liberadas
    {
        Controle_de_Triggers__c ctrlTriggers = new Controle_de_Triggers__c();

        ctrlTriggers.Trigger_Request__c         = true;      // ***** LEMBRAR ***** (Lembrar de mudar "Trigger_Request__c" ao reutilizar código)
        ctrlTriggers.Trigger_Account__c         = true;
        ctrlTriggers.Trigger_BMItem__c          = true;
        ctrlTriggers.Trigger_Inspection_Item__c = true;
        ctrlTriggers.Trigger_Step__c            = true;
        ctrlTriggers.TW2_Inspection_Advance_Hours_Schedule__c = 48;
        ctrlTriggers.TW2_Inspection_Daily_Hour_Break__c       = 15;
        ctrlTriggers.Request_Vendor_Vetting_RecId__c          = Schema.SObjectType.TW1_Request__c.getRecordTypeInfosByDeveloperName().get('TW1_Vendor_Vetting').getRecordTypeId();
        insert ctrlTriggers;

        //Creating Custom Settings
        ID_Account__c customSettingIdAccount = new ID_Account__c();
        customSettingIdAccount.Id_IntegrationUser__c = UserInfo.getUserId();
        insert customSettingIdAccount;

        //Buscando recordtype para preencher na custom settings
        RecordType recStep           = [SELECT Id, Name, DeveloperName, SobjectType FROM RecordType where DeveloperName = 'TW1_Approval_Step_Procurement_Manager'];
        RecordType recStep2          = [SELECT Id, Name, DeveloperName, SobjectType FROM RecordType where DeveloperName = 'TW1_Approval_Step_VVW_Attachment'];
        IDStep__c  customSettingSTEP = new IDStep__c();
        customSettingSTEP.Id_RecordType_Procurement_Manager__c = recStep.id;
        customSettingSTEP.Id_RecordType_VVW_Attachment__c      = recStep2.Id;
        insert customSettingSTEP;

        //Buscando fila para preencher custom settings

        Group filaPmanager = new Group();
        filaPmanager.Type = 'Queue';
        filaPmanager.Name = 'Procurement_Manager';
        insert       filaPmanager;
        QueueSobject mappingObjectStep    = new QueueSobject(QueueId = filaPmanager.Id, SobjectType = 'TW1_Step__c');
        QueueSobject mappingObjectRequest = new QueueSobject(QueueId = filaPmanager.Id, SobjectType = 'TW1_Request__c');
        System.runAs(new User(Id = UserInfo.getUserId()))
        {
            insert mappingObjectStep;
            insert mappingObjectRequest;
        }
        ID_Queues__c customIdQueues = new ID_Queues__c();
        customIdQueues.ID_Procurement_Manager_Queue__c = filaPmanager.Id;
        insert customIdQueues;

        /*******************************************/

        T_Debug_Setting__mdt testsetting;

        testsetting                                = new T_Debug_Setting__mdt();
        testsetting.Label                          = 'Teste';
        testsetting.DeveloperName                  = 'Teste';
        testsetting.T_Armazenar_Cause__c           = true;
        testsetting.T_Armazenar_linha_debug__c     = true;
        testsetting.T_Armazenar_StackTrace__c      = true;
        testsetting.T_Armazenar_texto_Exception__c = true;
        T_SDK_DebugLog_Test.testsetting            = testsetting;
    }

    @isTest
    public static void CloseStepConfirmationDateCanceled()
    {
        T_MODEC_Request_Rep RequestREP = new T_MODEC_Request_Rep();
        String              RecTypeStepDateConfirmation = Schema.SObjectType.TW1_Step__c.getRecordTypeInfosByDeveloperName().get('Approval_Step_Date_Confirmation').getRecordTypeId();
        //Creating inspection
        TW1_Request__c InspectionRequest = T_MODEC_ScheduleInspection_TST.CreateInspectionRequest();

        //Creating Inspection item
        T_MODEC_InspectionItem_TST.CreateInspectionItem(InspectionRequest.Id, 1);

        InspectionRequest.TW1_Inspection_Status__c         = 'Awaiting Date Confirmation';
        InspectionRequest.TW1_Inspection_Scheduled_Date__c = Datetime.now().addDays(5);
        update InspectionRequest;

        //Criada pelo process builder.
        TW1_Step__c StepDateConfirmation = new TW1_Step__c();
        StepDateConfirmation.TW1_Request__c = InspectionRequest.Id;
        StepDateConfirmation.TW1_Inspection_Scheduled_Date__c = InspectionRequest.TW1_Inspection_Scheduled_Date__c;
        StepDateConfirmation.TW1_Status__c = 'Opened';
        StepDateConfirmation.RecordTypeId  = RecTypeStepDateConfirmation;
        insert StepDateConfirmation;
        //[Select id, TW1_Request__c from TW1_Step__c where TW1_Request__c =:InspectionRequest.Id AND RecordtypeId =:RecTypeStepDateConfirmation];
        system.debug('StepDateConfirmation >>' + StepDateConfirmation);

        Test.startTest();
        StepDateConfirmation.TW1_Status__c = 'Closed';
        //StepDateConfirmation.TW1_Conclusion_Date__c = Datetime.Now();
        StepDateConfirmation.TW1_Inspection_Date_Confirmation__c = 'Cancel';
        update StepDateConfirmation;
        system.debug('StepDateConfirmation apos update >>' + StepDateConfirmation);
        Test.stopTest();
        TW1_Request__c inspection = RequestREP.getInspectionAndInspectionLines(InspectionRequest.Id);

        system.assertEquals('Canceled', inspection.TW1_Inspection_Status__c);
    }

    @isTest
    public static void CloseStepConfirmationDateReproved()
    {
        T_MODEC_Request_Rep RequestREP = new T_MODEC_Request_Rep();
        String              RecTypeStepDateConfirmation = Schema.SObjectType.TW1_Step__c.getRecordTypeInfosByDeveloperName().get('Approval_Step_Date_Confirmation').getRecordTypeId();
        //Creating inspection
        TW1_Request__c InspectionRequest = T_MODEC_ScheduleInspection_TST.CreateInspectionRequest();

        //Creating Inspection item
        T_MODEC_InspectionItem_TST.CreateInspectionItem(InspectionRequest.Id, 1);

        InspectionRequest.TW1_Inspection_Status__c         = 'Awaiting Date Confirmation';
        InspectionRequest.TW1_Inspection_Scheduled_Date__c = Datetime.now().addHours(3);
        update InspectionRequest;

        //Criada pelo process builder.
        TW1_Step__c StepDateConfirmation = new TW1_Step__c();
        StepDateConfirmation.TW1_Request__c = InspectionRequest.Id;
        StepDateConfirmation.TW1_Inspection_Scheduled_Date__c = InspectionRequest.TW1_Inspection_Scheduled_Date__c;
        StepDateConfirmation.TW1_Status__c = 'Opened';
        StepDateConfirmation.RecordTypeId  = RecTypeStepDateConfirmation;
        insert StepDateConfirmation;
        //[Select id, TW1_Request__c from TW1_Step__c where TW1_Request__c =:InspectionRequest.Id AND RecordtypeId =:RecTypeStepDateConfirmation];
        system.debug('StepDateConfirmation >>' + StepDateConfirmation);
        Test.startTest();
        StepDateConfirmation.TW1_Status__c = 'Closed';
        //StepDateConfirmation.TW1_Conclusion_Date__c = Datetime.Now();
        StepDateConfirmation.TW1_Inspection_Date_Confirmation__c = 'Cancel';
        update StepDateConfirmation;
        system.debug('StepDateConfirmation apos update >>' + StepDateConfirmation);

        Test.stopTest();
        TW1_Request__c inspection = RequestREP.getInspectionAndInspectionLines(InspectionRequest.Id);

        system.assertEquals('Reproved', inspection.TW1_Inspection_Status__c);
    }

    @isTest
    public static void CloseStepConfirmationDateRescheduled()
    {
        T_MODEC_Request_Rep RequestREP = new T_MODEC_Request_Rep();
        String              RecTypeStepDateConfirmation = Schema.SObjectType.TW1_Step__c.getRecordTypeInfosByDeveloperName().get('Approval_Step_Date_Confirmation').getRecordTypeId();
        //Creating inspection
        TW1_Request__c InspectionRequest = T_MODEC_ScheduleInspection_TST.CreateInspectionRequest();

        //Creating Inspection item
        T_MODEC_InspectionItem_TST.CreateInspectionItem(InspectionRequest.Id, 1);

        InspectionRequest.TW1_Inspection_Status__c         = 'Awaiting Date Confirmation';
        InspectionRequest.TW1_Inspection_Scheduled_Date__c = Datetime.now().addDays(3);
        update InspectionRequest;

        //Criada pelo process builder.
        TW1_Step__c StepDateConfirmation = new TW1_Step__c();
        StepDateConfirmation.TW1_Request__c = InspectionRequest.Id;
        StepDateConfirmation.TW1_Inspection_Scheduled_Date__c = InspectionRequest.TW1_Inspection_Scheduled_Date__c;
        StepDateConfirmation.TW1_Status__c = 'Opened';
        StepDateConfirmation.RecordTypeId  = RecTypeStepDateConfirmation;
        insert StepDateConfirmation;
        //[Select id, TW1_Request__c from TW1_Step__c where TW1_Request__c =:InspectionRequest.Id AND RecordtypeId =:RecTypeStepDateConfirmation];
        system.debug('StepDateConfirmation >>' + StepDateConfirmation);
        Test.startTest();
        StepDateConfirmation.TW1_Status__c = 'Closed';
        //StepDateConfirmation.TW1_Conclusion_Date__c = Datetime.Now();
        StepDateConfirmation.TW1_Inspection_Date_Confirmation__c = 'Reschedule';
        update StepDateConfirmation;
        system.debug('StepDateConfirmation apos update >>' + StepDateConfirmation);


        Test.stopTest();
        TW1_Request__c inspection = RequestREP.getInspectionAndInspectionLines(InspectionRequest.Id);

        system.assertEquals('Rescheduled', inspection.TW1_Inspection_Status__c);
    }

    @isTest
    public static void CloseStepConfirmationDateCalculateMinutes()
    {
        T_MODEC_Request_Rep RequestREP = new T_MODEC_Request_Rep();
        String              RecTypeStepDateConfirmation = Schema.SObjectType.TW1_Step__c.getRecordTypeInfosByDeveloperName().get('Approval_Step_Date_Confirmation').getRecordTypeId();
        //Creating inspection
        TW1_Request__c InspectionRequest = T_MODEC_ScheduleInspection_TST.CreateInspectionRequest();

        //Creating Inspection item
        T_MODEC_InspectionItem_TST.CreateInspectionItem(InspectionRequest.Id, 1);

        InspectionRequest.TW1_Inspection_Status__c         = 'Awaiting Date Confirmation';
        InspectionRequest.TW1_Inspection_Scheduled_Date__c = Datetime.now().addDays(1).addMinutes(-60);
        update InspectionRequest;

        //Criada pelo process builder.
        TW1_Step__c StepDateConfirmation = new TW1_Step__c();
        StepDateConfirmation.TW1_Request__c = InspectionRequest.Id;
        StepDateConfirmation.TW1_Inspection_Scheduled_Date__c = InspectionRequest.TW1_Inspection_Scheduled_Date__c;
        StepDateConfirmation.TW1_Status__c = 'Opened';
        StepDateConfirmation.RecordTypeId  = RecTypeStepDateConfirmation;
        insert StepDateConfirmation;
        //[Select id, TW1_Request__c from TW1_Step__c where TW1_Request__c =:InspectionRequest.Id AND RecordtypeId =:RecTypeStepDateConfirmation];
        system.debug('StepDateConfirmation >>' + StepDateConfirmation);
        Test.startTest();
        StepDateConfirmation.TW1_Status__c = 'Closed';
        //StepDateConfirmation.TW1_Conclusion_Date__c = Datetime.Now();
        StepDateConfirmation.TW1_Inspection_Date_Confirmation__c = 'Cancel';
        update StepDateConfirmation;
        system.debug('StepDateConfirmation apos update >>' + StepDateConfirmation);

        Test.stopTest();
        TW1_Request__c inspection = RequestREP.getInspectionAndInspectionLines(InspectionRequest.Id);

        system.assertEquals('Reproved', inspection.TW1_Inspection_Status__c);
    }

    @isTest
    public static void CloseStepConfirmationDateSUCESS()
    {
        T_MODEC_Request_Rep RequestREP = new T_MODEC_Request_Rep();
        String              RecTypeStepDateConfirmation = Schema.SObjectType.TW1_Step__c.getRecordTypeInfosByDeveloperName().get('Approval_Step_Date_Confirmation').getRecordTypeId();
        //Creating inspection
        TW1_Request__c InspectionRequest = T_MODEC_ScheduleInspection_TST.CreateInspectionRequest();

        //Creating Inspection item
        T_MODEC_InspectionItem_TST.CreateInspectionItem(InspectionRequest.Id, 1);

        InspectionRequest.TW1_Inspection_Status__c         = 'Awaiting Date Confirmation';
        InspectionRequest.TW1_Inspection_Scheduled_Date__c = Datetime.now().addDays(2);
        update InspectionRequest;

        //Criada pelo process builder.
        TW1_Step__c StepDateConfirmation = new TW1_Step__c();
        StepDateConfirmation.TW1_Request__c = InspectionRequest.Id;
        StepDateConfirmation.TW1_Inspection_Scheduled_Date__c = InspectionRequest.TW1_Inspection_Scheduled_Date__c;
        StepDateConfirmation.TW1_Status__c = 'Opened';
        StepDateConfirmation.RecordTypeId  = RecTypeStepDateConfirmation;
        insert StepDateConfirmation;
        //[Select id, TW1_Request__c from TW1_Step__c where TW1_Request__c =:InspectionRequest.Id AND RecordtypeId =:RecTypeStepDateConfirmation];
        system.debug('StepDateConfirmation >>' + StepDateConfirmation);
        Test.startTest();
        StepDateConfirmation.TW1_Status__c = 'Closed';
        //StepDateConfirmation.TW1_Conclusion_Date__c = Datetime.Now();
        StepDateConfirmation.TW1_Inspection_Date_Confirmation__c = 'Confirm';
        update StepDateConfirmation;
        system.debug('StepDateConfirmation apos update >>' + StepDateConfirmation);

        Test.stopTest();
        TW1_Request__c inspection = RequestREP.getInspectionAndInspectionLines(InspectionRequest.Id);

        system.assertEquals('Inspection Scheduled', inspection.TW1_Inspection_Status__c);
    }

    @isTest
    public static void ModifyStepAlreadyClosed()
    {
        T_MODEC_Request_Rep RequestREP = new T_MODEC_Request_Rep();
        String              RecTypeStepDateConfirmation = Schema.SObjectType.TW1_Step__c.getRecordTypeInfosByDeveloperName().get('Approval_Step_Date_Confirmation').getRecordTypeId();
        //Creating inspection
        TW1_Request__c InspectionRequest = T_MODEC_ScheduleInspection_TST.CreateInspectionRequest();

        //Creating Inspection item
        T_MODEC_InspectionItem_TST.CreateInspectionItem(InspectionRequest.Id, 1);

        InspectionRequest.TW1_Inspection_Status__c         = 'Awaiting Date Confirmation';
        InspectionRequest.TW1_Inspection_Scheduled_Date__c = Datetime.now().addDays(2);
        update InspectionRequest;

        //Criada pelo process builder.
        TW1_Step__c StepDateConfirmation = new TW1_Step__c();
        StepDateConfirmation.TW1_Request__c = InspectionRequest.Id;
        StepDateConfirmation.TW1_Inspection_Scheduled_Date__c = InspectionRequest.TW1_Inspection_Scheduled_Date__c;
        StepDateConfirmation.TW1_Status__c = 'Opened';
        StepDateConfirmation.RecordTypeId  = RecTypeStepDateConfirmation;
        insert StepDateConfirmation;
        //[Select id, TW1_Request__c from TW1_Step__c where TW1_Request__c =:InspectionRequest.Id AND RecordtypeId =:RecTypeStepDateConfirmation];
        system.debug('StepDateConfirmation >>' + StepDateConfirmation);
        Test.startTest();
        StepDateConfirmation.TW1_Status__c = 'Closed';
        //StepDateConfirmation.TW1_Conclusion_Date__c = Datetime.Now();
        StepDateConfirmation.TW1_Inspection_Date_Confirmation__c = 'Confirm';
        update StepDateConfirmation;
        system.debug('StepDateConfirmation apos update >>' + StepDateConfirmation);

        Test.stopTest();

        try{
            StepDateConfirmation.TW1_Status__c = 'Opened';
            update StepDateConfirmation;
        }
        catch (Exception e) {
            system.debug('Exception occurs :' + e.getMessage());
            String currentuserId   = UserInfo.getUserId();
            User   currentUserInfo = [select LanguageLocaleKey from User where Id = :UserInfo.getUserId()];
            if (currentUserInfo.LanguageLocaleKey == 'pt_BR')
            {
                system.assertEquals(true, e.getMessage().contains('Step está fechada mudanças não são permitidas'));
            }
            else
            {
                system.assertEquals(true, e.getMessage().contains('Step is closed changes are not allowed'));
            }
        }
    }
}