force-app/main/default/objects/Controle_de_Triggers__c/Controle_de_Triggers__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Controle de triggers para facilitar controle de acesso e configuração.</description>
    <label>Controle de Triggers</label>
</CustomObject>

force-app/main/default/objects/Controle_de_Triggers__c/fields/Triscal_User_Id__c.field-meta.xml
<CustomField>
    <fullName>Triscal_User_Id__c</fullName>
    <description>User Id, for Triscal support.</description>
    <label>Triscal User Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TOBJ_AvaliacaoHSE__c/TOBJ_AvaliacaoHSE__c.object-meta.xml
<CustomObject>
    <label>HSEQ Evaluation</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{0000}</displayFormat>
        <label>HSE Evaluation Cod</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HSEQ Evaluation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Documentation__c/TW1_Documentation__c.object-meta.xml
<CustomObject>
    <label>Documentation</label>
    <nameField>
        <displayFormat>DOC{000000}</displayFormat>
        <label>Documentation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documentations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Documentation__c/fields/MODEC_Contract__c.field-meta.xml
<CustomField>
    <fullName>MODEC_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MODEC Contract</label>
    <referenceTo>TW1_MODEC_Contract__c</referenceTo>
    <relationshipLabel>Documentations</relationshipLabel>
    <relationshipName>Documentations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Documentation__c/fields/Step__c.field-meta.xml
<CustomField>
    <fullName>Step__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Step</label>
    <referenceTo>TW1_Step__c</referenceTo>
    <relationshipLabel>Documentations</relationshipLabel>
    <relationshipName>Documentations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Documentation__c/fields/TCF_HSEEvaluation__c.field-meta.xml
<CustomField>
    <fullName>TCF_HSEEvaluation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Click here to return to the evaluation.</inlineHelpText>
    <label>HSEQ Evaluation</label>
    <referenceTo>TOBJ_AvaliacaoHSE__c</referenceTo>
    <relationshipLabel>Documentations</relationshipLabel>
    <relationshipName>DocumentationsHSEEvaluation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Documentation__c/fields/TW1_Comments__c.field-meta.xml
<CustomField>
    <fullName>TW1_Comments__c</fullName>
    <label>Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TW1_Documentation__c/fields/TW1_DocumentationAux__c.field-meta.xml
<CustomField>
    <fullName>TW1_DocumentationAux__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Booleano para controle dos documentation que foram efetivamente criados. 
para facilitar schedule de delete posterior.</description>
    <label>DocumentationAux</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TW1_Documentation__c/fields/TW1_Interaction__c.field-meta.xml
<CustomField>
    <fullName>TW1_Interaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interaction</label>
    <referenceTo>TW1_Interaction__c</referenceTo>
    <relationshipLabel>Documentations</relationshipLabel>
    <relationshipName>Documentations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Documentation__c/fields/TW1_Request__c.field-meta.xml
<CustomField>
    <fullName>TW1_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request</label>
    <referenceTo>TW1_Request__c</referenceTo>
    <relationshipLabel>Documentations</relationshipLabel>
    <relationshipName>Documentations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Interaction__c/TW1_Interaction__c.object-meta.xml
<CustomObject>
    <label>Interaction</label>
    <nameField>
        <displayFormat>I-{000000}</displayFormat>
        <label>Interaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Interaction__c/fields/Step__c.field-meta.xml
<CustomField>
    <fullName>Step__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Step</label>
    <referenceTo>TW1_Step__c</referenceTo>
    <relationshipLabel>Interactions</relationshipLabel>
    <relationshipName>Interactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Interaction__c/fields/TW1_Comments__c.field-meta.xml
<CustomField>
    <fullName>TW1_Comments__c</fullName>
    <label>Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/TW1_Interaction__c/fields/TW3_From_Portal__c.field-meta.xml
<CustomField>
    <fullName>TW3_From_Portal__c</fullName>
    <label>From Portal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Senegal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/TW1_MODEC_Contract__c.object-meta.xml
<CustomObject>
    <label>MODEC Contract</label>
    <nameField>
        <label>MODEC Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MODEC Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Request__c.field-meta.xml
<CustomField>
    <fullName>TW1_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request</label>
    <referenceTo>TW1_Request__c</referenceTo>
    <relationshipLabel>MODEC Contracts</relationshipLabel>
    <relationshipName>MODEC_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/TW1_Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>REQ{000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Step__c/TW1_Step__c.object-meta.xml
<CustomObject>
    <label>Step</label>
    <nameField>
        <displayFormat>S{000000}</displayFormat>
        <label>Steps Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Step__c/fields/TCF_HSEEvaluation__c.field-meta.xml
<CustomField>
    <fullName>TCF_HSEEvaluation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HSE Evaluation</label>
    <referenceTo>TOBJ_AvaliacaoHSE__c</referenceTo>
    <relationshipLabel>Steps</relationshipLabel>
    <relationshipName>TRN_Steps_HSEEvaluation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Step__c/fields/TW1_Interaction__c.field-meta.xml
<CustomField>
    <fullName>TW1_Interaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interaction</label>
    <referenceTo>TW1_Interaction__c</referenceTo>
    <relationshipLabel>Steps</relationshipLabel>
    <relationshipName>Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Step__c/fields/TW1_Request__c.field-meta.xml
<CustomField>
    <fullName>TW1_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request</label>
    <referenceTo>TW1_Request__c</referenceTo>
    <relationshipLabel>Steps</relationshipLabel>
    <relationshipName>Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/T_MODEC_CreateDocumentation_App.cls
/**
 * @File Name          : T_MODEC_CreateDocumentation_App.cls
 * @Description        : Classe Application para criação de Documentation
 * @Author             : Rafael Hadama
 * @Group              :
 * @Last Modified By   : Rafael Hadama
 * @Last Modified On   : 10-22-2020
 * @Modification Log   :
 * Ver       Date            Author              Modification
 * 1.0    06/12/2019   Rafael Hadama     Initial Version
 **/
public class T_MODEC_CreateDocumentation_App {
    public string documentationInsertDMLAux(string recTypeId)
    {
        try{
            Controle_de_Triggers__c ctrlTriggers = Controle_de_Triggers__c.getInstance();
            TW1_Documentation__c    documentAux  = new TW1_Documentation__c();
            //documentAux.Step__c      = stepId;
            documentAux.RecordTypeId = recTypeId;
            //documentAux.OwnerId = ctrlTriggers.Triscal_User_Id__c;
            documentAux.OwnerId = UserInfo.getUserId();
            documentAux.TW1_DocumentationAux__c = true;
            insert documentAux;
            System.debug('GUFS: '+documentAux.id);
            T_SDK_DebugLog.EscreverLog('Doc criado; ID:> ' + documentAux.Id);
            return documentAux.Id;
        }
        catch (Exception e)
        {
            // Exception handling goes here....
            T_SDK_DebugLog.EscreverLog('Erro ao criar Documentation Auxiliar ' + e.getMessage());
            T_SDK_DebugLog.EscreverLog('Erro ao criar Documentation- stacktrace: ' + e.getStackTraceString());
            string emptyReturn = '';
            return emptyReturn;
        }
    }

    public string documentationUpdateDMLAux(string docId, string recordId, string comments, string objName)
    {
        try{
            //User usuarioTriscal = [Select id from User where Name = 'Suporte Triscal'];
            TW1_Documentation__c documentAux = new TW1_Documentation__c();
            documentAux.id = docId;

            documentAux.TW1_Comments__c = comments;
            //documentAux.RecordTypeId = recTypeId;
            documentAux.OwnerId = UserInfo.getUserId();
            documentAux.TW1_DocumentationAux__c = false;

            if (objName == 'TW1_Step__c')
            {
                documentAux.Step__c = recordId;
                TW1_Step__c step = [Select Id, TW1_Request__c, TW1_Interaction__c, TW3_From_Portal__c from TW1_Step__c where Id =:recordId];
                documentAux.TW1_Interaction__c = step.TW1_Interaction__c;
                documentAux.TW1_Request__c     = step.TW1_Request__c;
                documentAux.TW3_From_Portal__c = step.TW3_From_Portal__c;
                //system.debug('Id Step: ' + step);
            }
            if (objName == 'TW1_Interaction__c')
            {
                TW1_Interaction__c interaction = [Select Id, TW3_From_Portal__c from TW1_Interaction__c where Id =:recordId];
                documentAux.TW3_From_Portal__c = interaction.TW3_From_Portal__c;
                documentAux.TW1_Interaction__c = recordId;
            }
            if (objName == 'TW1_Request__c')
            {
                TW1_Request__c request = [Select Id, TW3_From_Portal__c from TW1_Request__c where Id =:recordId];
                documentAux.TW3_From_Portal__c = request.TW3_From_Portal__c;
                documentAux.TW1_Request__c     = recordId;
            }

            if (objName == 'TW1_MODEC_Contract__c')
            {
                documentAux.MODEC_Contract__c = recordId;
                TW1_MODEC_Contract__c contrato = [SELECT Id, TW1_Request__c FROM TW1_MODEC_Contract__c where id =:recordId];
                documentAux.TW1_Request__c = contrato.TW1_Request__c;
            }
            
            if (objName == 'TOBJ_AvaliacaoHSE__c')
            {
                documentAux.TCF_HSEEvaluation__c = recordId;
            }
            update documentAux;
            T_SDK_DebugLog.EscreverLog('Doc atualizado; ID:> ' + documentAux.Id);
            return documentAux.Id;
        }
        catch (Exception e)
        {
            // Exception handling goes here....
            T_SDK_DebugLog.EscreverLog('Erro ao atualizar Documentation Auxiliar ' + e.getMessage());
            T_SDK_DebugLog.EscreverLog('Erro ao atualizar Documentation- stacktrace: ' + e.getStackTraceString());
            string emptyReturn = '';
            return emptyReturn;
        }
    }
}