force-app/main/default/objects/Controle_de_Triggers__c/Controle_de_Triggers__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Controle de triggers para facilitar controle de acesso e configuração.</description>
    <label>Controle de Triggers</label>
</CustomObject>

force-app/main/default/objects/Controle_de_Triggers__c/fields/Request_Vendor_Vetting_RecId__c.field-meta.xml
<CustomField>
    <fullName>Request_Vendor_Vetting_RecId__c</fullName>
    <label>Request Vendor Vetting RecId</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Controle_de_Triggers__c/fields/Trigger_Account__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Trigger Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Controle_de_Triggers__c/fields/Trigger_BMItem__c.field-meta.xml
<CustomField>
    <fullName>Trigger_BMItem__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Trigger_BMItem</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Controle_de_Triggers__c/fields/Trigger_Inspection_Item__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Inspection_Item__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Trigger Inspection Item</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Controle_de_Triggers__c/fields/Trigger_Request__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Request__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Trigger_Request</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Controle_de_Triggers__c/fields/TW2_Inspection_Advance_Hours_Schedule__c.field-meta.xml
<CustomField>
    <fullName>TW2_Inspection_Advance_Hours_Schedule__c</fullName>
    <description>Number field in hours, to control the date available for next inspection</description>
    <label>Inspection Advance Hours Schedule</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Controle_de_Triggers__c/fields/TW2_Inspection_Daily_Hour_Break__c.field-meta.xml
<CustomField>
    <fullName>TW2_Inspection_Daily_Hour_Break__c</fullName>
    <description>Number field to determine a 24 hour clock. Used to determine if today should count as an available date,</description>
    <label>Inspection Daily Hour Break</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ID_Account__c/ID_Account__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ID - Account</label>
</CustomObject>

force-app/main/default/objects/ID_Account__c/fields/Id_IntegrationUser__c.field-meta.xml
<CustomField>
    <fullName>Id_IntegrationUser__c</fullName>
    <label>Id_IntegrationUser</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ID_Queues__c/ID_Queues__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ID Queues</label>
</CustomObject>

force-app/main/default/objects/ID_Queues__c/fields/ID_Procurement_Manager_Queue__c.field-meta.xml
<CustomField>
    <fullName>ID_Procurement_Manager_Queue__c</fullName>
    <label>ID Procurement Manager Queue</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IDStep__c/IDStep__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ID - Step</label>
</CustomObject>

force-app/main/default/objects/IDStep__c/fields/Id_RecordType_Procurement_Manager__c.field-meta.xml
<CustomField>
    <fullName>Id_RecordType_Procurement_Manager__c</fullName>
    <label>Id RecordType Procurement Manager</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IDStep__c/fields/Id_RecordType_VVW_Attachment__c.field-meta.xml
<CustomField>
    <fullName>Id_RecordType_VVW_Attachment__c</fullName>
    <label>Id RecordType VVW Attachment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/T_Debug_Setting__mdt/T_Debug_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Configurações de Debug</description>
    <label>Triscal debug setting</label>
    <pluralLabel>Triscal debug setting</pluralLabel>
</CustomObject>

force-app/main/default/objects/T_Debug_Setting__mdt/fields/T_Armazenar_Cause__c.field-meta.xml
<CustomField>
    <fullName>T_Armazenar_Cause__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Se true armazena a causa da exception caso exista</description>
    <label>Armazenar Cause?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/T_Debug_Setting__mdt/fields/T_Armazenar_linha_debug__c.field-meta.xml
<CustomField>
    <fullName>T_Armazenar_linha_debug__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Se true armazena linha de debug</description>
    <label>Armazenar linha debug?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/T_Debug_Setting__mdt/fields/T_Armazenar_StackTrace__c.field-meta.xml
<CustomField>
    <fullName>T_Armazenar_StackTrace__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Se true então armazena o StackTrace da exceção</description>
    <inlineHelpText>Se true então armazena o StackTrace da exceção</inlineHelpText>
    <label>Armazenar StackTrace?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/T_Debug_Setting__mdt/fields/T_Armazenar_texto_Exception__c.field-meta.xml
<CustomField>
    <fullName>T_Armazenar_texto_Exception__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Se true então armazena o texto da exceção</description>
    <inlineHelpText>Se true então armazena o texto da exceção</inlineHelpText>
    <label>Armazenar texto Exception?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TW1_Facility__c/TW1_Facility__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Facility__c/fields/TW1_Facility__c.field-meta.xml
<CustomField>
    <fullName>TW1_Facility__c</fullName>
    <label>Facility</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Facility__c/fields/TW1_Type__c.field-meta.xml
<CustomField>
    <fullName>TW1_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>Vessel</fullName>
            </value>
            <value>
                <fullName>Warehouse</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Request__c/TW1_Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>REQ{000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Request__c/fields/Technical_Inspection_Recommendation__c.field-meta.xml
<CustomField>
    <fullName>Technical_Inspection_Recommendation__c</fullName>
    <inlineHelpText>(RTI). Fill as the Ex.: SPIE-RIT-2020-0001</inlineHelpText>
    <label>Technical Inspection Recommendation</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Change_and_Repair_Project__c.field-meta.xml
<CustomField>
    <fullName>TW1_Change_and_Repair_Project__c</fullName>
    <inlineHelpText>(PAR). Fill as the Ex.: PAR-2020-0001</inlineHelpText>
    <label>Change and Repair Project</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Facility__c.field-meta.xml
<CustomField>
    <fullName>TW1_Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>TW1_Facility__c</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Management_Of_Change__c.field-meta.xml
<CustomField>
    <fullName>TW1_Management_Of_Change__c</fullName>
    <inlineHelpText>(MOC) Fill as the Ex.: MOC-MV20-20-00001</inlineHelpText>
    <label>Management Of Change</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Planned_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>TW1_Planned_Delivery_Date__c</fullName>
    <label>Planned Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Project_Number__c.field-meta.xml
<CustomField>
    <fullName>TW1_Project_Number__c</fullName>
    <inlineHelpText>Supplier number control</inlineHelpText>
    <label>Project Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>TW1_Purchase_Order__c</fullName>
    <inlineHelpText>Fill as the Ex.: PO-45000XXXXX / AM-MV20-20-00001</inlineHelpText>
    <label>Purchase Order</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_WO_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>TW1_WO_Due_Date__c</fullName>
    <label>WO Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Work_Order__c.field-meta.xml
<CustomField>
    <fullName>TW1_Work_Order__c</fullName>
    <inlineHelpText>(WO). Fill as the Ex.: WOCS-20-00001</inlineHelpText>
    <label>Work Order</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/recordTypes/Inspection.recordType-meta.xml
<RecordType>
    <fullName>Inspection</fullName>
    <active>true</active>
    <label>Inspection</label>
</RecordType>

force-app/main/default/objects/TW1_Request__c/recordTypes/TW1_Vendor_Vetting.recordType-meta.xml
<RecordType>
    <fullName>TW1_Vendor_Vetting</fullName>
    <active>true</active>
    <label>Vendor Vetting</label>
</RecordType>

force-app/main/default/objects/TW1_Step__c/TW1_Step__c.object-meta.xml
<CustomObject>
    <label>Step</label>
    <nameField>
        <displayFormat>S{000000}</displayFormat>
        <label>Steps Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Step__c/fields/TW1_Request__c.field-meta.xml
<CustomField>
    <fullName>TW1_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request</label>
    <referenceTo>TW1_Request__c</referenceTo>
    <relationshipLabel>Steps</relationshipLabel>
    <relationshipName>Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Step__c/recordTypes/TW1_Approval_Step_Procurement_Manager.recordType-meta.xml
<RecordType>
    <fullName>TW1_Approval_Step_Procurement_Manager</fullName>
    <active>true</active>
    <label>Approval Step - Procurement Manager</label>
</RecordType>

force-app/main/default/objects/TW1_Step__c/recordTypes/TW1_Approval_Step_VVW_Attachment.recordType-meta.xml
<RecordType>
    <fullName>TW1_Approval_Step_VVW_Attachment</fullName>
    <active>true</active>
    <label>Approval Step - VVW Attachment</label>
</RecordType>

force-app/main/default/classes/T_MODEC_ScheduleInspection_TST.cls
/**
 * @File Name          : T_MODEC_ScheduleInspection_TST.cls
 * @Description        :
 * @Author             : Rafael Hadama
 * @Group              :
 * @Last Modified By   : Rafael Hadama
 * @Last Modified On   : 07-22-2020
 * @Modification Log   :
 * Ver       Date            Author              Modification
 * 1.0    29/06/2020   Rafael Hadama     Initial Version
 **/
@istest
public class T_MODEC_ScheduleInspection_TST {
    @TestSetup
    public static void criarCustomSettings() //Obs.: Apenas Triggers que contêm este método serão liberadas
    {
        Controle_de_Triggers__c ctrlTriggers = new Controle_de_Triggers__c();

        ctrlTriggers.Trigger_Request__c         = true;      // ***** LEMBRAR ***** (Lembrar de mudar "Trigger_Request__c" ao reutilizar código)
        ctrlTriggers.Trigger_Account__c         = true;
        ctrlTriggers.Trigger_BMItem__c          = true;
        ctrlTriggers.Trigger_Inspection_Item__c = true;
        ctrlTriggers.TW2_Inspection_Advance_Hours_Schedule__c = 48;
        ctrlTriggers.TW2_Inspection_Daily_Hour_Break__c       = 15;
        ctrlTriggers.Request_Vendor_Vetting_RecId__c          = Schema.SObjectType.TW1_Request__c.getRecordTypeInfosByDeveloperName().get('TW1_Vendor_Vetting').getRecordTypeId();
        insert ctrlTriggers;

        //Creating Custom Settings
        ID_Account__c customSettingIdAccount = new ID_Account__c();
        customSettingIdAccount.Id_IntegrationUser__c = UserInfo.getUserId();
        insert customSettingIdAccount;

        //Buscando recordtype para preencher na custom settings
        RecordType recStep           = [SELECT Id, Name, DeveloperName, SobjectType FROM RecordType where DeveloperName = 'TW1_Approval_Step_Procurement_Manager'];
        RecordType recStep2          = [SELECT Id, Name, DeveloperName, SobjectType FROM RecordType where DeveloperName = 'TW1_Approval_Step_VVW_Attachment'];
        IDStep__c  customSettingSTEP = new IDStep__c();
        customSettingSTEP.Id_RecordType_Procurement_Manager__c = recStep.id;
        customSettingSTEP.Id_RecordType_VVW_Attachment__c      = recStep2.Id;
        insert customSettingSTEP;

        //Buscando fila para preencher custom settings

        Group filaPmanager = new Group();
        filaPmanager.Type = 'Queue';
        filaPmanager.Name = 'Procurement_Manager';
        insert       filaPmanager;
        QueueSobject mappingObjectStep    = new QueueSobject(QueueId = filaPmanager.Id, SobjectType = 'TW1_Step__c');
        QueueSobject mappingObjectRequest = new QueueSobject(QueueId = filaPmanager.Id, SobjectType = 'TW1_Request__c');
        System.runAs(new User(Id = UserInfo.getUserId()))
        {
            insert mappingObjectStep;
            insert mappingObjectRequest;
        }
        ID_Queues__c customIdQueues = new ID_Queues__c();
        customIdQueues.ID_Procurement_Manager_Queue__c = filaPmanager.Id;
        insert customIdQueues;

        /*******************************************/

        T_Debug_Setting__mdt testsetting;

        testsetting                                = new T_Debug_Setting__mdt();
        testsetting.Label                          = 'Teste';
        testsetting.DeveloperName                  = 'Teste';
        testsetting.T_Armazenar_Cause__c           = true;
        testsetting.T_Armazenar_linha_debug__c     = true;
        testsetting.T_Armazenar_StackTrace__c      = true;
        testsetting.T_Armazenar_texto_Exception__c = true;
        T_SDK_DebugLog_Test.testsetting            = testsetting;
    }

    public static TW1_Request__c CreateInspectionRequest()
    {
        TW1_Facility__c Unit = new TW1_Facility__c();

        Unit.TW1_Type__c = 'Office';
        Unit.Name        = 'Unit Mock';
        insert Unit;

        TW1_Request__c Inspection = new TW1_Request__c();

        Inspection.RecordTypeId                           = Schema.SObjectType.TW1_Request__c.getRecordTypeInfosByDeveloperName().get('Inspection').getRecordTypeId();
        Inspection.TW1_Purchase_Order__c                  = 'Purchase';
        Inspection.TW1_Work_Order__c                      = 'Work Order Mock';
        Inspection.TW1_Change_and_Repair_Project__c       = 'Change & Repair Project Mock';
        Inspection.TW1_Project_Number__c                  = '123456';
        Inspection.TW1_Management_Of_Change__c            = 'Management of change mock';
        Inspection.TW1_WO_Due_Date__c                     = date.today().addDays(10);
        Inspection.TW1_Planned_Delivery_Date__c           = date.today().addDays(15);
        Inspection.Technical_Inspection_Recommendation__c = 'Technical Inspection Rec Mock';
        Inspection.TW1_Facility__c                        = Unit.Id;
        Inspection.TW1_Inspection_Perfomed__c             = 'Pressure Test';
        Inspection.TW1_Inspection_Contact_Number__c       = '(21) 99999-9999';
        Inspection.TW1_Inspection_Address__c              = 'Macaé';
        Inspection.Inspection_Type__c                     = 'Normal';
        Inspection.TW1_Inspection_Status__c               = 'Not Submitted';
        Inspection.TW1_Status__c                          = 'Open';
        insert Inspection;

        return Inspection;
    }

    /**
     * @description test method to cover the T_MODEC_ScheduleInspection_Ctrl class
     * @author Rafael Hadama | 29/06/2020
     * @return void
     **/
    @isTest
    public static void ScheduleWithRequestInController()
    {
        Test.startTest();
        T_MODEC_ScheduleInspection_App ScheduleApp = new T_MODEC_ScheduleInspection_App();
        TW1_Request__c                 Inspection  = CreateInspectionRequest();

        T_MODEC_InspectionItem_TST.CreateInspectionItem(Inspection.Id, 1);

        Inspection.TW1_Inspection_Status__c = 'Inspection Scheduled';
        update Inspection;

        system.debug('Inspection >' + Inspection);
        T_MODEC_ScheduleInspection_Ctrl.InspectionDatesDto scheduletestDto = new T_MODEC_ScheduleInspection_Ctrl.InspectionDatesDto();

        scheduletestDto.InspectionDate1         = Date.today().addDays(1);
        scheduletestDto.InspectionDate2         = Date.today().addDays(2);
        scheduletestDto.InspectionDate3         = Date.today().addDays(4);
        scheduletestDto.EmergencyInspectionDate = null;
        scheduletestDto.InspectionNote          = 'Inspection Note Mock';
        scheduletestDto.InspectionType          = 'normal';
        scheduletestDto.RequestId = Inspection.Id;
        string strRequest = JSON.serialize(scheduletestDto);
        Test.stopTest();
        string controllerresponse = T_MODEC_ScheduleInspection_Ctrl.ScheduleInspection(strRequest);
        system.debug('controllerresponse' + controllerresponse);
        T_MODEC_ScheduleInspection_Ctrl.InspectionResponseDto request = (T_MODEC_ScheduleInspection_Ctrl.InspectionResponseDto)JSON.deserialize(controllerresponse, T_MODEC_ScheduleInspection_Ctrl.InspectionResponseDto.class);
        system.debug('request' + request);

        system.assertEquals('Erro', request.Status);
        //system.assertEquals(true, InspectionResponse.MessageList.get(0).contains('is invalid'));
    }

    /**
     * @description Test method to validate the inspection status of the Request
     * @author Rafael Hadama | 29/06/2020
     * @return void
     **/
    @isTest
    public static void ScheduleWithRequestStatusInvalid()
    {
        Test.startTest();
        T_MODEC_ScheduleInspection_App ScheduleApp = new T_MODEC_ScheduleInspection_App();
        TW1_Request__c                 Inspection  = CreateInspectionRequest();
        T_MODEC_InspectionItem_TST.CreateInspectionItem(Inspection.Id, 1);
        Inspection.TW1_Inspection_Status__c = 'Inspection Scheduled';
        update Inspection;

        system.debug('Inspection >' + Inspection);
        T_MODEC_ScheduleInspection_Ctrl.InspectionDatesDto scheduletestDto = new T_MODEC_ScheduleInspection_Ctrl.InspectionDatesDto();

        scheduletestDto.InspectionDate1         = Date.today().addDays(1);
        scheduletestDto.InspectionDate2         = Date.today().addDays(2);
        scheduletestDto.InspectionDate3         = Date.today().addDays(4);
        scheduletestDto.EmergencyInspectionDate = null;
        scheduletestDto.InspectionNote          = 'Inspection Note Mock';
        scheduletestDto.InspectionType          = 'normal';
        scheduletestDto.RequestId = Inspection.Id;

        Test.stopTest();
        T_MODEC_ScheduleInspection_Ctrl.InspectionResponseDto InspectionResponse = ScheduleApp.ValidateScheduledInspection(scheduletestDto, true);
        system.debug('InspectionResponse' + InspectionResponse);

        system.assertEquals('Erro', InspectionResponse.Status);
        //system.assertEquals(true, InspectionResponse.MessageList.get(0).contains('is invalid'));
    }

    /**
     * @description test method to validate Dates in the past
     * @author Rafael Hadama | 29/06/2020
     * @return void
     **/
    @isTest
    public static void ScheduleWithDatesInThePast()
    {
        T_MODEC_ScheduleInspection_App ScheduleApp = new T_MODEC_ScheduleInspection_App();
        TW1_Request__c                 Inspection  = CreateInspectionRequest();

        system.debug('Inspection >' + Inspection);
        T_MODEC_ScheduleInspection_Ctrl.InspectionDatesDto scheduletestDto = new T_MODEC_ScheduleInspection_Ctrl.InspectionDatesDto();

        scheduletestDto.InspectionDate1         = Date.today().addDays(-1);
        scheduletestDto.InspectionDate2         = Date.today().addDays(2);
        scheduletestDto.InspectionDate3         = Date.today().addDays(4);
        scheduletestDto.EmergencyInspectionDate = null;
        scheduletestDto.InspectionNote          = 'Inspection Note Mock';
        scheduletestDto.InspectionType          = 'normal';
        scheduletestDto.RequestId = Inspection.Id;


        T_MODEC_ScheduleInspection_Ctrl.InspectionResponseDto InspectionResponse = ScheduleApp.ValidateScheduledInspection(scheduletestDto, true);
        system.debug('InspectionResponse' + InspectionResponse);

        system.assertEquals('Erro', InspectionResponse.Status);
        //system.assertEquals(true, InspectionResponse.MessageList.get(0).contains('is invalid'));
    }

    @isTest
    public static void ScheduleWithDuplicateDates()
    {
        T_MODEC_ScheduleInspection_App ScheduleApp = new T_MODEC_ScheduleInspection_App();
        TW1_Request__c                 Inspection  = CreateInspectionRequest();

        system.debug('Inspection >' + Inspection);
        T_MODEC_ScheduleInspection_Ctrl.InspectionDatesDto scheduletestDto = new T_MODEC_ScheduleInspection_Ctrl.InspectionDatesDto();

        scheduletestDto.InspectionDate1         = Date.today().addDays(2);
        scheduletestDto.InspectionDate2         = Date.today().addDays(2);
        scheduletestDto.InspectionDate3         = Date.today().addDays(4);
        scheduletestDto.EmergencyInspectionDate = null;
        scheduletestDto.InspectionNote          = 'Inspection Note Mock';
        scheduletestDto.InspectionType          = 'normal';
        scheduletestDto.RequestId = Inspection.Id;


        T_MODEC_ScheduleInspection_Ctrl.InspectionResponseDto InspectionResponse = ScheduleApp.ValidateScheduledInspection(scheduletestDto, true);
        system.debug('InspectionResponse' + InspectionResponse);

        system.assertEquals('Erro', InspectionResponse.Status);
        //system.assertEquals(true, InspectionResponse.MessageList.get(0).contains('There are duplicate dates'));
    }

    @isTest
    public static void ScheduleWithDatesinWrongOrder()
    {
        T_MODEC_ScheduleInspection_App ScheduleApp = new T_MODEC_ScheduleInspection_App();
        TW1_Request__c                 Inspection  = CreateInspectionRequest();

        system.debug('Inspection >' + Inspection);
        T_MODEC_ScheduleInspection_Ctrl.InspectionDatesDto scheduletestDto = new T_MODEC_ScheduleInspection_Ctrl.InspectionDatesDto();

        scheduletestDto.InspectionDate1         = Date.today().addDays(1);
        scheduletestDto.InspectionDate2         = Date.today().addDays(4);
        scheduletestDto.InspectionDate3         = Date.today().addDays(2);
        scheduletestDto.EmergencyInspectionDate = null;
        scheduletestDto.InspectionNote          = 'Inspection Note Mock';
        scheduletestDto.InspectionType          = 'normal';
        scheduletestDto.RequestId = Inspection.Id;


        T_MODEC_ScheduleInspection_Ctrl.InspectionResponseDto InspectionResponse = ScheduleApp.ValidateScheduledInspection(scheduletestDto, true);
        system.debug('InspectionResponse' + InspectionResponse);

        system.assertEquals('Erro', InspectionResponse.Status);
        //system.assertEquals(true, InspectionResponse.MessageList.get(0).contains('The order of the dates should be Date 1 > Date 2 > Date 3'));
    }

    @isTest
    public static void ScheduleWithNotWorkingDays()
    {
        T_MODEC_ScheduleInspection_App ScheduleApp = new T_MODEC_ScheduleInspection_App();
        TW1_Request__c                 Inspection  = CreateInspectionRequest();

        system.debug('Inspection >' + Inspection);
        T_MODEC_ScheduleInspection_Ctrl.InspectionDatesDto scheduletestDto = new T_MODEC_ScheduleInspection_Ctrl.InspectionDatesDto();

        boolean dateIsNotWeekend = false;
        Date    DateAux          = Date.today().addDays(1);
        while (!dateIsNotWeekend)
        {
            dateIsNotWeekend = ScheduleApp.CheckIfDateIsWeekend(DateAux);

            if (!dateIsNotWeekend)
            {
                DateAux = DateAux.addDays(1);
            }
        }
        system.debug('DateAux :' + DateAux);

        scheduletestDto.InspectionDate1         = DateAux;
        scheduletestDto.InspectionDate2         = DateAux.addDays(3);
        scheduletestDto.InspectionDate3         = DateAux.addDays(4);
        scheduletestDto.EmergencyInspectionDate = null;
        scheduletestDto.InspectionNote          = 'Inspection Note Mock';
        scheduletestDto.InspectionType          = 'normal';
        scheduletestDto.RequestId = Inspection.Id;


        T_MODEC_ScheduleInspection_Ctrl.InspectionResponseDto InspectionResponse = ScheduleApp.ValidateScheduledInspection(scheduletestDto, true);
        system.debug('InspectionResponse' + InspectionResponse);

        system.assertEquals('Erro', InspectionResponse.Status);
        //system.assertEquals(true, InspectionResponse.MessageList.get(0).contains('The Date Option 1 is a'));
    }

    @isTest
    public static void ScheduleWithDatesOutOfRange()
    {
        T_MODEC_ScheduleInspection_App ScheduleApp = new T_MODEC_ScheduleInspection_App();
        TW1_Request__c                 Inspection  = CreateInspectionRequest();

        system.debug('Inspection >' + Inspection);
        T_MODEC_ScheduleInspection_Ctrl.InspectionDatesDto scheduletestDto = new T_MODEC_ScheduleInspection_Ctrl.InspectionDatesDto();

        boolean dateIsNotWeekend = false;
        integer count            = 0;
        Date    DateAux          = Date.today();
        while (!dateIsNotWeekend)
        {
            dateIsNotWeekend = ScheduleApp.CheckIfDateIsWeekend(DateAux);

            if (!dateIsNotWeekend)
            {
                DateAux = DateAux.addDays(1);
                count++;
            }
        }
        system.debug('DateAux :' + DateAux);

        scheduletestDto.InspectionDate1         = DateAux.addDays(-count);
        scheduletestDto.InspectionDate2         = DateAux.addDays(3);
        scheduletestDto.InspectionDate3         = DateAux.addDays(4);
        scheduletestDto.EmergencyInspectionDate = null;
        scheduletestDto.InspectionNote          = 'Inspection Note Mock';
        scheduletestDto.InspectionType          = 'normal';
        scheduletestDto.RequestId = Inspection.Id;


        T_MODEC_ScheduleInspection_Ctrl.InspectionResponseDto InspectionResponse = ScheduleApp.ValidateScheduledInspection(scheduletestDto, true);
        system.debug('InspectionResponse' + InspectionResponse);

        system.assertEquals('Erro', InspectionResponse.Status);
        //system.assertEquals(true, InspectionResponse.MessageList.get(0).contains('is earlier then the Minimum schedule date'));
    }

    @isTest
    public static void ScheduleWithSucessEmergencial()
    {
        T_MODEC_ScheduleInspection_App ScheduleApp = new T_MODEC_ScheduleInspection_App();
        TW1_Request__c                 Inspection  = CreateInspectionRequest();

        system.debug('Inspection >' + Inspection);

        //Criando TW1_Email_List__c para passar da trigger.
        TW1_Email_List__c emailList = new TW1_Email_List__c();
        emailList.TW1_Email__c  = 'teste@teste.com';
        emailList.TW1_Status__c = 'Ativo';
        emailList.RecordTypeId  = Schema.SObjectType.TW1_Email_List__c.getRecordTypeInfosByDeveloperName().get('TW1_Inspection_Email').getRecordTypeId();
        insert emailList;

        T_MODEC_ScheduleInspection_Ctrl.InspectionDatesDto scheduletestDto = new T_MODEC_ScheduleInspection_Ctrl.InspectionDatesDto();


        scheduletestDto.InspectionDate1         = null;
        scheduletestDto.InspectionDate2         = null;
        scheduletestDto.InspectionDate3         = null;
        scheduletestDto.EmergencyInspectionDate = Date.today().addDays(2);
        scheduletestDto.InspectionNote          = 'Inspection Note Mock';
        scheduletestDto.InspectionType          = 'emergencial';
        scheduletestDto.RequestId      = Inspection.Id;
        scheduletestDto.EmergencyEmail = 'teste@teste.com';


        T_MODEC_ScheduleInspection_Ctrl.InspectionResponseDto InspectionResponse = ScheduleApp.ValidateScheduledInspection(scheduletestDto, true);
        system.debug('InspectionResponse' + InspectionResponse);

        system.assertEquals('Sucesso', InspectionResponse.Status);
    }

    @isTest
    public static void ScheduleWithErrorEmergencial()
    {
        T_MODEC_ScheduleInspection_App ScheduleApp = new T_MODEC_ScheduleInspection_App();
        TW1_Request__c                 Inspection  = CreateInspectionRequest();

        system.debug('Inspection >' + Inspection);

        //Criando TW1_Email_List__c para passar da trigger.
        TW1_Email_List__c emailList = new TW1_Email_List__c();
        emailList.TW1_Email__c  = 'teste2@teste.com';
        emailList.TW1_Status__c = 'Ativo';
        emailList.RecordTypeId  = Schema.SObjectType.TW1_Email_List__c.getRecordTypeInfosByDeveloperName().get('TW1_Inspection_Email').getRecordTypeId();
        insert emailList;

        T_MODEC_ScheduleInspection_Ctrl.InspectionDatesDto scheduletestDto = new T_MODEC_ScheduleInspection_Ctrl.InspectionDatesDto();


        scheduletestDto.InspectionDate1         = null;
        scheduletestDto.InspectionDate2         = null;
        scheduletestDto.InspectionDate3         = null;
        scheduletestDto.EmergencyInspectionDate = Date.today().addDays(2);
        scheduletestDto.InspectionNote          = 'Inspection Note Mock';
        scheduletestDto.InspectionType          = 'emergencial';
        scheduletestDto.RequestId      = Inspection.Id;
        scheduletestDto.EmergencyEmail = 'teste@teste.com';


        T_MODEC_ScheduleInspection_Ctrl.InspectionResponseDto InspectionResponse = ScheduleApp.ValidateScheduledInspection(scheduletestDto, true);
        system.debug('InspectionResponse' + InspectionResponse);

        system.assertEquals('Erro', InspectionResponse.Status);
    }

    @isTest
    public static void ScheduleWithDatesSucess()
    {
        T_MODEC_ScheduleInspection_App ScheduleApp = new T_MODEC_ScheduleInspection_App();
        TW1_Request__c                 Inspection  = CreateInspectionRequest();

        system.debug('Inspection >' + Inspection);
        T_MODEC_ScheduleInspection_Ctrl.InspectionDatesDto scheduletestDto = new T_MODEC_ScheduleInspection_Ctrl.InspectionDatesDto();

        boolean dateIsNotWeekend = false;
        integer count            = 0;
        Date    DateAux          = Date.today();
        while (!dateIsNotWeekend)
        {
            dateIsNotWeekend = ScheduleApp.CheckIfDateIsWeekend(DateAux);

            if (!dateIsNotWeekend)
            {
                DateAux = DateAux.addDays(1);
                count++;
            }
        }
        system.debug('DateAux :' + DateAux);

        scheduletestDto.InspectionDate1         = DateAux.addDays(4);
        scheduletestDto.InspectionDate2         = DateAux.addDays(11);
        scheduletestDto.InspectionDate3         = DateAux.addDays(18);
        scheduletestDto.EmergencyInspectionDate = null;
        scheduletestDto.InspectionNote          = 'Inspection Note Mock';
        scheduletestDto.InspectionType          = 'normal';
        scheduletestDto.RequestId = Inspection.Id;


        T_MODEC_ScheduleInspection_Ctrl.InspectionResponseDto InspectionResponse = ScheduleApp.ValidateScheduledInspection(scheduletestDto, true);
        system.debug('InspectionResponse' + InspectionResponse);

        //system.assertEquals('Sucesso', InspectionResponse.Status);
    }

    @isTest
    public static void ValidateSendInspectionAction()
    {
        T_MODEC_ScheduleInspection_App ScheduleApp = new T_MODEC_ScheduleInspection_App();
        TW1_Request__c                 Inspection  = CreateInspectionRequest();

        T_MODEC_InspectionItem_TST.CreateInspectionItem(Inspection.Id, 1);

        try{
            Inspection.TW1_Inspection_Sent__c          = true;
            Inspection.TW1_Emergency_Date__c           = null;
            Inspection.TW1_Inspection_Date_Option_1__c = Date.today().addDays(-1);
            Inspection.TW1_Inspection_Date_Option_2__c = Date.today().addDays(3);
            Inspection.TW1_Inspection_Date_Option_3__c = Date.today().addDays(4);
            Inspection.TW1_Note__c = 'Note mock';
            update Inspection;
            system.debug('Inspection >' + Inspection);
        }
        catch (Exception e) {
            string mensagem        = e.getMessage();
            String currentuserId   = UserInfo.getUserId();
            User   currentUserInfo = [select LanguageLocaleKey from User where Id = :UserInfo.getUserId()];
            if (currentUserInfo.LanguageLocaleKey == 'pt_BR')
            {
                system.assert (mensagem.contains('por favor agende novamente'));
            }
            else
            {
                system.assert (mensagem.contains('please schedule inspection again'));
            }
        }
    }

    /**
     * @description Validating the method in the request app validateCancelInspectionAction
     * TW1_Inspection_Scheduled_Date__c is more than 24h from now().
     * @author Rafael Hadama | 07-16-2020
     **/
    @isTest
    public static void ValidateCancelInspectionActionCanceled()
    {
        T_MODEC_Request_Rep            RequestREP  = new T_MODEC_Request_Rep();
        T_MODEC_ScheduleInspection_App ScheduleApp = new T_MODEC_ScheduleInspection_App();
        TW1_Request__c                 Inspection  = CreateInspectionRequest();

        T_MODEC_InspectionItem_TST.CreateInspectionItem(Inspection.Id, 1);


        Inspection.TW1_Cancel_Inspection__c   = true;
        Inspection.TW1_Inspection_Status__c   = 'Canceled';
        Inspection.TW1_Instant_Cancel_Date__c = Datetime.now();
        Inspection.TW1_Status__c      = 'Canceled';
        Inspection.TW1_Cancel_Note__c = '<html><body><div style="color: red;"><b>In case you have to cancel this inspection, you can clone it and restart your request anytime pressing the Clone button.</b></div></body></html>';
        Inspection.TW1_Inspection_Scheduled_Date__c = Datetime.now().addDays(2);
        update Inspection;
        system.debug('Inspection >' + Inspection);

        TW1_Request__c InspectionAssert = RequestREP.getInspectionAndInspectionLines(Inspection.Id);

        system.assertEquals('Canceled', InspectionAssert.TW1_Inspection_Status__c);
    }

    /**
     * @description Validating the method in the request app validateCancelInspectionAction
     * TW1_Inspection_Scheduled_Date__c is too close to Now()
     * @author Rafael Hadama | 07-16-2020
     **/
    @isTest
    public static void ValidateCancelInspectionActionReproved()
    {
        T_MODEC_Request_Rep            RequestREP  = new T_MODEC_Request_Rep();
        T_MODEC_ScheduleInspection_App ScheduleApp = new T_MODEC_ScheduleInspection_App();
        TW1_Request__c                 Inspection  = CreateInspectionRequest();

        T_MODEC_InspectionItem_TST.CreateInspectionItem(Inspection.Id, 1);


        Inspection.TW1_Cancel_Inspection__c   = true;
        Inspection.TW1_Inspection_Status__c   = 'Canceled';
        Inspection.TW1_Instant_Cancel_Date__c = Datetime.now();
        Inspection.TW1_Status__c      = 'Canceled';
        Inspection.TW1_Cancel_Note__c = '<html><body><div style="color: red;"><b>In case you have to cancel this inspection, you can clone it and restart your request anytime pressing the Clone button.</b></div></body></html>';
        Inspection.TW1_Inspection_Scheduled_Date__c = Datetime.now();
        update Inspection;
        system.debug('Inspection >' + Inspection);

        TW1_Request__c InspectionAssert = RequestREP.getInspectionAndInspectionLines(Inspection.Id);

        system.assertEquals('Reproved', InspectionAssert.TW1_Inspection_Status__c);
    }

    /**
     * @description Validating the method in the request app validateCancelInspectionAction
     * TW1_Inspection_Scheduled_Date__c = null
     * @author Rafael Hadama | 07-16-2020
     **/
    @isTest
    public static void ValidateCancelInspectionDateIsNull()
    {
        T_MODEC_Request_Rep            RequestREP  = new T_MODEC_Request_Rep();
        T_MODEC_ScheduleInspection_App ScheduleApp = new T_MODEC_ScheduleInspection_App();
        TW1_Request__c                 Inspection  = CreateInspectionRequest();

        T_MODEC_InspectionItem_TST.CreateInspectionItem(Inspection.Id, 1);


        Inspection.TW1_Cancel_Inspection__c   = true;
        Inspection.TW1_Inspection_Status__c   = 'Canceled';
        Inspection.TW1_Instant_Cancel_Date__c = Datetime.now();
        Inspection.TW1_Status__c      = 'Canceled';
        Inspection.TW1_Cancel_Note__c = '<html><body><div style="color: red;"><b>In case you have to cancel this inspection, you can clone it and restart your request anytime pressing the Clone button.</b></div></body></html>';
        Inspection.TW1_Inspection_Scheduled_Date__c = null;
        update Inspection;
        system.debug('Inspection >' + Inspection);

        TW1_Request__c InspectionAssert = RequestREP.getInspectionAndInspectionLines(Inspection.Id);

        system.assertEquals('Canceled', InspectionAssert.TW1_Inspection_Status__c);
    }
}