force-app/main/default/objects/TW1_Request__c/TW1_Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>REQ{000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Request__c/fields/BM_Status__c.field-meta.xml
<CustomField>
    <fullName>BM_Status__c</fullName>
    <defaultValue>&quot;Não enviado&quot;</defaultValue>
    <label>BM Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BM_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/BM_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Aguardando</fullName>
    </customValue>
    <customValue>
        <fullName>Aceita</fullName>
    </customValue>
    <customValue>
        <fullName>Rejeitada</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelada</fullName>
    </customValue>
    <customValue>
        <fullName>Não enviado</fullName>
        <default>true</default>
        <label>Não enviado</label>
    </customValue>
    <masterLabel>BM Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/T_MODEC_AnexosFornecedor_Ctrl.cls
/**
 * @File Name          : T_MODEC_AnexosFornecedor_Ctrl.cls
 * @Description        :
 * @Author             : Rafael Hadama
 * @Group              :
 * @Last Modified By   : Rafael Hadama
 * @Last Modified On   : 28/01/2020 19:56:05
 * @Modification Log   :
 * Ver       Date            Author              Modification
 * 1.0    13/12/2019   Rafael Hadama     Initial Version
 **/
public class T_MODEC_AnexosFornecedor_Ctrl {
   /**
    * @description Metodo para validar status.
    * @author Rafael Hadama | 15/12/2019
    * @param recordId Id do objeto TW1_Request__c (BM)
    * @return string
    **/
   @AuraEnabled
   public static string searchBMStatus(string recordId)
   {
      T_MODEC_Request_Rep requestREP = new T_MODEC_Request_Rep();
      TW1_Request__c      req        = requestREP.getRequestBMStatus(recordId);

      string status = req.BM_Status__c;

      return status;
   }

   /**
    * @description Metodo para validar status.
    * @author Rafael Hadama | 15/12/2019
    * @param recordId Id do objeto TW1_Request__c (BM)
    * @return string
    **/
   @AuraEnabled
   public static string searchNFStatus(string recordId)
   {
      T_SDK_DebugLog.EscreverLog('Entrou no método searchNFStatus');
      T_MODEC_Request_Rep requestREP = new T_MODEC_Request_Rep();
      TW1_Request__c      req        = requestREP.getRequestNFStatus(recordId);
      T_SDK_DebugLog.EscreverLog('Request BM> ' + req);
      T_MODEC_AnexosFornecedor_App anexoFornecedorApp = new T_MODEC_AnexosFornecedor_App();
      NFDTO notafiscalDTO = anexoFornecedorApp.ValidateNFUpload(req);
      T_SDK_DebugLog.EscreverLog('notafiscalDTO>' + notafiscalDTO);

      string response = JSON.serialize(notafiscalDTO);
      T_SDK_DebugLog.EscreverLog('response>' + response);

      return response;
   }

   /**
    * @description Método feito para retornar id do usuário corrente, preenchendo o mesmo no componente de FileUpload
    * @author Rafael Hadama | 16/01/2020
    * @return string
    **/
   @AuraEnabled
   public static string getCurrentUserId()
   {
      return UserInfo.getUserId();
   }

   /**
    * @description
    * @author Rafael Hadama | 15/12/2019
    * @param ListrecordId (Lista de <registro do Anexo( *ContentVersion ).id> criado para anexar no documentation)
    * @return string
    **/
   @AuraEnabled
   public static string relateToDocumentation(list<string> ListrecordId, boolean isNTAttachment, string recId, string NF)
   {
      T_MODEC_AnexosFornecedor_App anexoFornecedorApp = new T_MODEC_AnexosFornecedor_App();

      T_SDK_DebugLog.EscreverLog('booleano isNF:' + isNTAttachment);

      string retorno = anexoFornecedorApp.createDocumentationAndLink(ListrecordId, isNTAttachment, recId, NF);
      return retorno;
   }

   public class NFDTO {
      public string message;
      public boolean blockNF;
   }
}