force-app/main/default/objects/TW1_Request__c/TW1_Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>REQ{000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Final_Measurement__c.field-meta.xml
<CustomField>
    <fullName>TW1_Final_Measurement__c</fullName>
    <label>Final Measurement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Modec_Requester_Email__c.field-meta.xml
<CustomField>
    <fullName>TW1_Modec_Requester_Email__c</fullName>
    <label>Modec Requester Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_PO__c.field-meta.xml
<CustomField>
    <fullName>TW1_PO__c</fullName>
    <label>PO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Purchase_Item__c.field-meta.xml
<CustomField>
    <fullName>TW1_Purchase_Item__c</fullName>
    <label>Purchase Item</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Service_Description__c.field-meta.xml
<CustomField>
    <fullName>TW1_Service_Description__c</fullName>
    <label>Service Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Service_End_Date__c.field-meta.xml
<CustomField>
    <fullName>TW1_Service_End_Date__c</fullName>
    <label>Service End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Service_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>TW1_Service_Start_Date__c</fullName>
    <label>Service Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Supplier_Email__c.field-meta.xml
<CustomField>
    <fullName>TW1_Supplier_Email__c</fullName>
    <label>Supplier Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Supplier_Reference_Number_for_BM__c.field-meta.xml
<CustomField>
    <fullName>TW1_Supplier_Reference_Number_for_BM__c</fullName>
    <label>Supplier Reference Number for BM</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/T_MODEC_Request_Rep_TST.cls
@isTest
public class T_MODEC_Request_Rep_TST {
    @TestSetup
    Public static void TestSetup(){
        Account conta = new Account();
        conta.name = 'TestClass';
        insert conta;
        
        TW1_Request__c req = new TW1_Request__c();
        req.TW1_Supplier_Email__c = 'teste@teste.com';
        req.TW1_Modec_Requester_Email__c = 'suportemodec@triscal.com.br';
        req.TW1_Supplier_Reference_Number_for_BM__c = '4334fdff';
        req.TW1_PO__c = 'dk489hg';
        req.TW1_Purchase_Item__c = 'fgfd';
        req.TW1_Final_Measurement__c = 'Yes';
        req.TW1_Service_Start_Date__c = Date.today();
        req.TW1_Service_End_Date__c = Date.today().addDays(5);
        req.TW1_Service_Description__c = 'dahfdfskdfhd';
        insert req;
    }
    
    @isTest
    Public static void testMethod1(){
        TW1_Request__c req = [select id from TW1_Request__c limit 1];
        T_MODEC_Request_Rep rep = new T_MODEC_Request_Rep();
        rep.getRequestBMStatus(req.id);
        rep.getRequestNFStatus(req.id);
        rep.getRequestById(req.id);
        rep.getRequestByListIds(new List<String>());
        rep.getBMsEnvioAnexos();
        rep.getInspectionAndInspectionLines(req.id);
        rep.getInspectionAndInspectionLinesCLONE(req.id);
    }
}