force-app/main/default/objects/VesselContract__c/VesselContract__c.object-meta.xml
<CustomObject>
    <label>Vessel Contract</label>
    <nameField>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vessel Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VesselContract__c/fields/ActualDailyRateBRL__c.field-meta.xml
<CustomField>
    <fullName>ActualDailyRateBRL__c</fullName>
    <label>Actual Daily Rate (BRL)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VesselContract__c/fields/ActualDailyRateUSD__c.field-meta.xml
<CustomField>
    <fullName>ActualDailyRateUSD__c</fullName>
    <label>Actual Daily Rate (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VesselContract__c/fields/Pilot__c.field-meta.xml
<CustomField>
    <fullName>Pilot__c</fullName>
    <label>Pilot Gas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VesselContract__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Charter</fullName>
            </value>
            <value>
                <fullName>Cost Plus</fullName>
            </value>
            <value>
                <fullName>O&amp;M Support</fullName>
            </value>
            <value>
                <fullName>Pre-Ops</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VesselContractBOTest.cls
@isTest
public with sharing class VesselContractBOTest {
    
    @isTest
    public static void populateDailyRateHistoryTestCharter(){
        
        List<VesselContract__c> lstVessel = new List<VesselContract__c>();
        Map<Id, VesselContract__c> mapVessel = new Map<Id, VesselContract__c>();

        Test.startTest();

        VesselContract__c vessel = new VesselContract__c();
        vessel.ActualDailyRateUSD__c = 1.0;
        vessel.ActualDailyRateBRL__c = 2.0;
        vessel.Type__c = 'Charter';
        Insert vessel;
        System.debug('LST: '+ lstVessel);


        vessel.ActualDailyRateUSD__c = 5.0; 
        vessel.ActualDailyRateBRL__c = 15.0;
        update vessel;
   
        Test.stopTest();
    }

    @isTest
    public static void populateDailyRateHistoryTestServices(){
        
        List<VesselContract__c> lstVessel = new List<VesselContract__c>();
        Map<Id, VesselContract__c> mapVessel = new Map<Id, VesselContract__c>();

        Test.startTest();

        VesselContract__c vessel2 = new VesselContract__c();
        vessel2.ActualDailyRateUSD__c = 1.0;
        vessel2.ActualDailyRateBRL__c = 2.0;
        vessel2.Pilot__c = 500;
        vessel2.Type__c = 'Services';
        Insert vessel2;
        System.debug('LST: '+ lstVessel);


        vessel2.ActualDailyRateUSD__c = 5.0; 
        vessel2.ActualDailyRateBRL__c = 15.0;
        update vessel2;
   
        Test.stopTest();

    }
}