force-app/main/default/objects/VesselContract__c/VesselContract__c.object-meta.xml
<CustomObject>
    <label>Vessel Contract</label>
    <nameField>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vessel Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VesselContract__c/fields/ContractAnniversary__c.field-meta.xml
<CustomField>
    <fullName>ContractAnniversary__c</fullName>
    <label>Contract Anniversary</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/BatchUpdateVesselContractAnniverssary.cls
global class BatchUpdateVesselContractAnniverssary implements Database.Batchable<sObject> {

    global static void init() {
        Database.executeBatch(new BatchUpdateVesselContractAnniverssary());
    }

    global BatchUpdateVesselContractAnniverssary() {

    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query;
        Datetime filterDate = System.today();

        query = 'SELECT Id, ContractAnniversary__c FROM VesselContract__c WHERE ContractAnniversary__c < TODAY';

        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<VesselContract__c> lstVesselContract) {
        
        for(VesselContract__c contract : lstVesselContract)
        {
           contract.ContractAnniversary__c = contract.ContractAnniversary__c.addYears(1);
        }

        update lstVesselContract;
    }

    global void finish(Database.BatchableContext BC) {}

}