force-app/main/default/objects/VesselContract__c/VesselContract__c.object-meta.xml
<CustomObject>
    <label>Vessel Contract</label>
    <nameField>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vessel Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VesselContract__c/fields/BOMEndDate__c.field-meta.xml
<CustomField>
    <fullName>BOMEndDate__c</fullName>
    <formula>ADDMONTHS(BOMStartDate__c ,1) - 1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BOM End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VesselContract__c/fields/BOMStartDate__c.field-meta.xml
<CustomField>
    <fullName>BOMStartDate__c</fullName>
    <label>BOM Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/BatchUpdateBOMStartDate.cls
global class BatchUpdateBOMStartDate implements Database.Batchable<sObject> {

    private static final BatchUpdateBOMStartDate instance = new BatchUpdateBOMStartDate();

    public static BatchUpdateBOMStartDate getInstance() {
		return instance;
    }

    global static void init() {
        Database.executeBatch(new BatchUpdateBOMStartDate(), 2);
    }

    global BatchUpdateBOMStartDate() {

    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query;
        Datetime filterDate = System.today();

        query = 'SELECT Id, BOMStartDate__c, BOMEndDate__c FROM VesselContract__c WHERE BOMEndDate__c < TODAY';

        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<VesselContract__c> lstVesselContract) {
        
        for(VesselContract__c contract : lstVesselContract)
        {
            contract.BOMStartDate__c = System.today();
        }

        update lstVesselContract;
    }

    global void finish(Database.BatchableContext BC) {}

}