force-app/main/default/objects/VesselContract__c/VesselContract__c.object-meta.xml
<CustomObject>
    <label>Vessel Contract</label>
    <nameField>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vessel Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VesselContract__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Charter</fullName>
            </value>
            <value>
                <fullName>Cost Plus</fullName>
            </value>
            <value>
                <fullName>O&amp;M Support</fullName>
            </value>
            <value>
                <fullName>Pre-Ops</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VesselContractDAOTest.cls
@isTest
public with sharing class VesselContractDAOTest {
    
    @isTest
    public static void VesselContractDAOTest(){

        VesselContract__c vesselContract = TestUtil.createVesselContractServices();

        Test.startTest();
        VesselContractDAO.getVesselContractById(vesselContract.Id);
        VesselContractDAO.getVesselContractByContractNumber(vesselContract.Name, 'Teste', vesselContract.Type__c);
        VesselContractDAO.getVesselContractByIdAndType(vesselContract.Id, vesselContract.Type__c);
        VesselContractDAO.getMealAllowanceByNumber(vesselContract.Name);
        Test.stopTest();
    }
}