force-app/main/default/objects/RDO__c/RDO__c.object-meta.xml
<CustomObject>
    <label>RDO</label>
    <nameField>
        <label>Num RDO</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RDOs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RDO__c/fields/WIAmountReceived__c.field-meta.xml
<CustomField>
    <fullName>WIAmountReceived__c</fullName>
    <label>Volume Received</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RDO__c/fields/WIAmountSent__c.field-meta.xml
<CustomField>
    <fullName>WIAmountSent__c</fullName>
    <label>Volume Sent</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WaterCompensation__c/WaterCompensation__c.object-meta.xml
<CustomObject>
    <label>Water Compensation</label>
    <nameField>
        <displayFormat>WC-{0000}</displayFormat>
        <label>Compensation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Water Compensations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WaterCompensation__c/fields/ReceivingRDO__c.field-meta.xml
<CustomField>
    <fullName>ReceivingRDO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Receiving RDO</label>
    <referenceTo>RDO__c</referenceTo>
    <relationshipLabel>Water Compensations</relationshipLabel>
    <relationshipName>Water_Compensations_Receiving</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WaterCompensation__c/fields/SendingRDO__c.field-meta.xml
<CustomField>
    <fullName>SendingRDO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sending RDO</label>
    <referenceTo>RDO__c</referenceTo>
    <relationshipLabel>Water Compensations (Sending RDO)</relationshipLabel>
    <relationshipName>Water_Compensations_Sending</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/WaterCompensationBO.cls
public with sharing class WaterCompensationBO {
    
    private static final WaterCompensationBO instance = new WaterCompensationBO();

	public static WaterCompensationBO getInstance() {
		return instance;
    }

    public void updateRDOs(List<WaterCompensation__c> lstWaterComp)
    {
        List<RDO__c> lstRDOSending = new List<RDO__c>();
        List<RDO__c> lstRDOReceiving = new List<RDO__c>();
        List<RDO__c> rdosToUpdate = new List<RDO__c>();
        RDO__c rdoSending = new RDO__c();
        RDO__c rdoReceiving = new RDO__c();
        WaterCompensation__c wComp = new WaterCompensation__c();
        String sendingId;
        String receivingId;

        for(WaterCompensation__c waterComp : lstWaterComp)
        {
            sendingId = waterComp.SendingRDO__c;
            receivingId = waterComp.ReceivingRDO__c;
        }

        wComp = lstWaterComp[0];

        lstRDOSending = RDODAO.getRDOById(sendingId);
        lstRDOReceiving = RDODAO.getRDOById(receivingId);

        if(!lstRDOSending.isEmpty())
        {
            rdoSending = lstRDOSending[0];

            if(rdoSending.WIAmountSent__c == null)
                rdoSending.WIAmountSent__c = 0;

            rdoSending.WIAmountSent__c += wComp.Amount__c;
            rdosToUpdate.add(rdoSending);
        } 

        if(!lstRDOReceiving.isEmpty())
        {
            rdoReceiving = lstRDOReceiving[0];

            if(rdoReceiving.WIAmountReceived__c == null)
                rdoReceiving.WIAmountReceived__c = 0;

            rdoReceiving.WIAmountReceived__c += wComp.Amount__c;
            rdosToUpdate.add(rdoReceiving);
        }

        update rdosToUpdate;
    }

}