force-app/main/default/objects/Account/recordTypes/Business.recordType-meta.xml
<RecordType>
    <fullName>Business</fullName>
    <active>true</active>
    <label>Business</label>
</RecordType>

force-app/main/default/objects/NAM__c/NAM__c.object-meta.xml
<CustomObject>
    <label>NAM</label>
    <nameField>
        <label>NAM Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NAMs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NAM__c/fields/Revision__c.field-meta.xml
<CustomField>
    <fullName>Revision__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Revision</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Contractor__c.field-meta.xml
<CustomField>
    <fullName>Contractor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contractor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>WorkOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/ISS__c.field-meta.xml
<CustomField>
    <fullName>ISS__c</fullName>
    <defaultValue>0.02</defaultValue>
    <inlineHelpText>MdB/Brazil portion only</inlineHelpText>
    <label>ISS (Brazil portion only)</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/MarkUp__c.field-meta.xml
<CustomField>
    <fullName>MarkUp__c</fullName>
    <defaultValue>0.08</defaultValue>
    <label>Mark Up</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/NAM__c.field-meta.xml
<CustomField>
    <fullName>NAM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NAM</label>
    <referenceTo>NAM__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>WorkOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Revision__c.field-meta.xml
<CustomField>
    <fullName>Revision__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Revision</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/MS__c.field-meta.xml
<CustomField>
    <fullName>MS__c</fullName>
    <label>M/S</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Material</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>F</fullName>
                <isActive>false</isActive>
                <label>F</label>
            </value>
            <value>
                <fullName>I</fullName>
                <isActive>false</isActive>
                <label>I</label>
            </value>
            <value>
                <fullName>M/S</fullName>
                <isActive>false</isActive>
                <label>M/S</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/NAM__c.field-meta.xml
<CustomField>
    <fullName>NAM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NAM</label>
    <referenceTo>NAM__c</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>WorkOrderLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <inlineHelpText>USD</inlineHelpText>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/ResponsibleCountry__c.field-meta.xml
<CustomField>
    <fullName>ResponsibleCountry__c</fullName>
    <label>Responsible</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Outside of Brazil</fullName>
            </value>
            <value>
                <fullName>MODEC, Inc</fullName>
                <isActive>false</isActive>
                <label>MODEC, Inc</label>
            </value>
            <value>
                <fullName>MdB</fullName>
                <isActive>false</isActive>
                <label>MdB</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WorkOrderFactory.cls
public class WorkOrderFactory {
    public static WorkOrder createWO( NAM__c nam, string contractor){
        WorkOrder wo = new WorkOrder(
            NAM__c = nam.Id,
            Revision__c = 0,
            AccountId = AccountFactory.insertAcc(Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business').getRecordTypeId(), '').Id,
            Contractor__c = AccountFactory.insertAcc(Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business').getRecordTypeId(), contractor).Id,
            MarkUp__c = 0.08,
            ISS__c = 0.02
        );
        insert wo;
        return wo;
    }

    public static WorkOrderLineItem createWOLineItem(WorkOrder wo, decimal amount ){
        WorkOrderLineItem woItem = new WorkOrderLineItem(
            WorkOrderId = wo.Id,
            Status = 'Estimation',
            MS__c = 'Service',
            Product__c = 'Product 1',
            responsibleCountry__c = 'Brazil',
            Price__c = amount);
        insert woItem;
        return woItem;
    }

    public static WorkOrderLineItem createWOLineItem(WorkOrder wo, decimal amount, String responsibleCountry ){
        WorkOrderLineItem woItem = new WorkOrderLineItem(
            WorkOrderId = wo.Id,
            Status = 'Estimation',
            MS__c = 'Service',
            Product__c = 'Product 1',
            responsibleCountry__c = responsibleCountry,
            Price__c = amount);
        insert woItem;
        return woItem;
    }
}