force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <label>Claim</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Claim Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/AmountUnderDisputeBRL__c.field-meta.xml
<CustomField>
    <fullName>AmountUnderDisputeBRL__c</fullName>
    <label>Amount under dispute (BRL)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/AmountUnderDisputeSum__c.field-meta.xml
<CustomField>
    <fullName>AmountUnderDisputeSum__c</fullName>
    <label>Amount under dispute sum (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/AmountUnderDisputeUSD__c.field-meta.xml
<CustomField>
    <fullName>AmountUnderDisputeUSD__c</fullName>
    <label>Amount under dispute (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Letter__c.field-meta.xml
<CustomField>
    <fullName>Letter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Letter</label>
    <referenceTo>Letter__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/LetterGroup__c.field-meta.xml
<CustomField>
    <fullName>LetterGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Letter Group</label>
    <referenceTo>LetterGroup__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/RDO__c.field-meta.xml
<CustomField>
    <fullName>RDO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RDO</label>
    <referenceTo>RDO__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/ResultsBRL__c.field-meta.xml
<CustomField>
    <fullName>ResultsBRL__c</fullName>
    <label>Results (BRL)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/ResultsSum__c.field-meta.xml
<CustomField>
    <fullName>ResultsSum__c</fullName>
    <label>Results sum (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/ResultsUSD__c.field-meta.xml
<CustomField>
    <fullName>ResultsUSD__c</fullName>
    <label>Results (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/TotalAmountBRL__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountBRL__c</fullName>
    <label>Total amount (BRL)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/TotalAmountSum__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountSum__c</fullName>
    <label>Total amount sum (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/TotalAmountUSD__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountUSD__c</fullName>
    <label>Total amount (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Claim__c/recordTypes/Letter.recordType-meta.xml
<RecordType>
    <fullName>Letter</fullName>
    <active>false</active>
    <label>Letter</label>
</RecordType>

force-app/main/default/objects/Claim__c/recordTypes/RDO.recordType-meta.xml
<RecordType>
    <fullName>RDO</fullName>
    <active>false</active>
    <label>RDO</label>
</RecordType>

force-app/main/default/objects/ClaimRDOAssociation__c/ClaimRDOAssociation__c.object-meta.xml
<CustomObject>
    <label>Claim RDO Association</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claim RDO Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClaimRDOAssociation__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <label>Claim</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Claim RDO Associations</relationshipLabel>
    <relationshipName>ClaimRDOAssociationsClaim</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClaimRDOAssociation__c/fields/RDO__c.field-meta.xml
<CustomField>
    <fullName>RDO__c</fullName>
    <label>RDO</label>
    <referenceTo>RDO__c</referenceTo>
    <relationshipLabel>Claim RDO Associations</relationshipLabel>
    <relationshipName>ClaimRDOAssociationsRDO</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Letter__c/Letter__c.object-meta.xml
<CustomObject>
    <label>Letter</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Letter Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Letters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Letter__c/fields/LetterGroup__c.field-meta.xml
<CustomField>
    <fullName>LetterGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Letter Group</label>
    <referenceTo>LetterGroup__c</referenceTo>
    <relationshipLabel>Letters</relationshipLabel>
    <relationshipName>Letters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LetterGroup__c/LetterGroup__c.object-meta.xml
<CustomObject>
    <label>Letter Group</label>
    <nameField>
        <displayFormat>LG-{00000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Letter Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LetterGroup__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Modec</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RDO__c/RDO__c.object-meta.xml
<CustomObject>
    <label>RDO</label>
    <nameField>
        <label>Num RDO</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RDOs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ClaimBO.cls
public with sharing class ClaimBO {

    private static final ClaimBO instance = new ClaimBO();

	public static ClaimBO getInstance() {
		return instance;
    }

    public void calculateDollar (List<Claim__c> lstClaim)
    {
        Double actualDollar = Double.valueOf(Label.ActualDollar);

        for(Claim__c claim : lstClaim)
        {
            if(claim.AmountUnderDisputeBRL__c == null)
                claim.AmountUnderDisputeBRL__c = 0;
            
            if(claim.AmountUnderDisputeUSD__c == null)
                claim.AmountUnderDisputeUSD__c = 0;

            if(claim.ResultsBRL__c == null)
                claim.ResultsBRL__c = 0;
            
            if(claim.ResultsUSD__c == null)
                claim.ResultsUSD__c = 0;

            if(claim.TotalAmountBRL__c == null)
                claim.TotalAmountBRL__c = 0;
            
            if(claim.TotalAmountUSD__c == null)
                claim.TotalAmountUSD__c = 0;                

            claim.AmountUnderDisputeSum__c = (claim.AmountUnderDisputeBRL__c/actualDollar) + claim.AmountUnderDisputeUSD__c;
            claim.ResultsSum__c = (claim.ResultsBRL__c/actualDollar) + claim.ResultsUSD__c;
            claim.TotalAmountSum__c = (claim.TotalAmountBRL__c/actualDollar) + claim.TotalAmountUSD__c;
        }
    }

    public void fillLetterGroup(List<Claim__c> lstClaim)
    {
        List<Letter__c> lstLetter = new List<Letter__c>();
        String idLetter;
        String idLetterGroup;

        for(Claim__c claim : lstClaim)
        {
            if(claim.Source__c == 'Letter' && claim.Letter__c != null)
            {
                idLetter = claim.Letter__c;
            }
            else 
            {
                return;    
            }
        }

        lstLetter = LetterDAO.getLetterById(idLetter);

        if(!lstLetter.isEmpty())
        {
            for(Letter__c letter : lstLetter)
            {
                if(letter.LetterGroup__c != null)
                {
                    idLetterGroup = letter.LetterGroup__c;

                    for(Claim__c claim : lstClaim)
                    {
                        claim.LetterGroup__c = idLetterGroup;
                    }
                }
            }
        }
    }

    public void createRDOAssociation(List<Claim__c> lstClaim)
    {
        Claim__c claimInstance = new Claim__c();

        claimInstance = lstClaim[0];

        if(claimInstance.Source__c != 'RDO')
        {
            return;
        }
        else
        {
            ClaimRDOAssociation__c claimRDOAssoc = new ClaimRDOAssociation__c();
            claimRDOAssoc.Claim__c = claimInstance.Id;
            claimRDOAssoc.RDO__c = claimInstance.RDO__c;

            insert claimRDOAssoc;
        }
    }
}