force-app/main/default/objects/Clarification__c/Clarification__c.object-meta.xml
<CustomObject>
    <label>Clarification</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Clarification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Clarification__c/fields/NAM__c.field-meta.xml
<CustomField>
    <fullName>NAM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NAM</label>
    <referenceTo>NAM__c</referenceTo>
    <relationshipLabel>Clarifications</relationshipLabel>
    <relationshipName>Clarifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Clarification__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <label>Partner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mitsui</fullName>
            </value>
            <value>
                <fullName>Marubeni</fullName>
            </value>
            <value>
                <fullName>MOL</fullName>
            </value>
            <value>
                <fullName>MINC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clarification__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NAM</fullName>
            </value>
            <value>
                <fullName>Closed Out</fullName>
            </value>
            <value>
                <fullName>MINC</fullName>
                <isActive>false</isActive>
                <label>MINC</label>
            </value>
            <value>
                <fullName>MOL</fullName>
                <isActive>false</isActive>
                <label>MOL</label>
            </value>
            <value>
                <fullName>Marubeni</fullName>
                <isActive>false</isActive>
                <label>Marubeni</label>
            </value>
            <value>
                <fullName>Mitsui</fullName>
                <isActive>false</isActive>
                <label>Mitsui</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClarificationTopic__c/ClarificationTopic__c.object-meta.xml
<CustomObject>
    <label>Clarification Topic</label>
    <nameField>
        <label>Clarification Topic  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarifications Topics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClarificationTopic__c/fields/Clarification__c.field-meta.xml
<CustomField>
    <fullName>Clarification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clarification</label>
    <referenceTo>Clarification__c</referenceTo>
    <relationshipLabel>Clarifications Topics</relationshipLabel>
    <relationshipName>ClarificationsTopics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClarificationTopic__c/fields/NAM1__c.field-meta.xml
<CustomField>
    <fullName>NAM1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NAM</label>
    <referenceTo>NAM__c</referenceTo>
    <relationshipLabel>Clarifications Topics</relationshipLabel>
    <relationshipName>ClarificationsTopics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClarificationTopic__c/fields/NAM__c.field-meta.xml
<CustomField>
    <fullName>NAM__c</fullName>
    <formula>HYPERLINK(Clarification__r.NAM__c,Clarification__r.NAM__r.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>NAM</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClarificationTopic__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <formula>Text(Clarification__r.Partner__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Partner</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NAM__c/NAM__c.object-meta.xml
<CustomObject>
    <label>NAM</label>
    <nameField>
        <label>NAM Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NAMs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NAM__c/fields/ClosedOutClarificationCreated__c.field-meta.xml
<CustomField>
    <fullName>ClosedOutClarificationCreated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Closed Out Clarification Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ClarificationTopicBO.cls
public class ClarificationTopicBO {
    private static final ClarificationTopicBO instance = new ClarificationTopicBO();

	public static ClarificationTopicBO getInstance() {
		return instance;
	}

	public void fillClarification(List<ClarificationTopic__c> lstClarificationTopic) {
		Map<Id, User> mapUserById = new Map<Id, User>();
		Map<String, NAM__c> mapNamById = new Map<String, NAM__c>();

		for(ClarificationTopic__c objClarificationTopic : lstClarificationTopic) {
			mapUserById.put(objClarificationTopic.OwnerId, null);
			mapNamById.put(objClarificationTopic.NAM1__c, null);
		}

		CollectionUtil.carregarMap(mapUserById, 'Id', UserDAO.getById(mapUserById.keySet()));
		CollectionUtil.carregarMap(mapNamById, 'Id', NamDAO.getById(mapNamById.keySet()));

		for(ClarificationTopic__c objClarificationTopic : lstClarificationTopic) {
			User objUser = mapUserById.get(objClarificationTopic.OwnerId);
			NAM__c objNam = mapNamById.get(objClarificationTopic.NAM1__c);
			if(objNam != null){
				String clarificationType = objNam.ClosedOutClarificationCreated__c ? 'Closed Out' : 'NAM';

				for(Clarification__c objClarification : objNam.Clarifications__r) {
					Boolean isClarificationPartner = objUser.UserRole.DeveloperName.contains(objClarification.Partner__c);
					if(objClarification.Type__c == clarificationType && isClarificationPartner)	objClarificationTopic.Clarification__c = objClarification.Id;
				}

				if(objClarificationTopic.Clarification__c == null) {
					objClarificationTopic.Clarification__c = objNam.Clarifications__r[0].Id;
				}
			}
		}
	}
}