force-app/main/default/objects/Clarification__c/Clarification__c.object-meta.xml
<CustomObject>
    <label>Clarification</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Clarification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Clarification__c/fields/NAM__c.field-meta.xml
<CustomField>
    <fullName>NAM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NAM</label>
    <referenceTo>NAM__c</referenceTo>
    <relationshipLabel>Clarifications</relationshipLabel>
    <relationshipName>Clarifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Clarification__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <label>Partner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mitsui</fullName>
            </value>
            <value>
                <fullName>Marubeni</fullName>
            </value>
            <value>
                <fullName>MOL</fullName>
            </value>
            <value>
                <fullName>MINC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clarification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clarification__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NAM</fullName>
            </value>
            <value>
                <fullName>Closed Out</fullName>
            </value>
            <value>
                <fullName>MINC</fullName>
                <isActive>false</isActive>
                <label>MINC</label>
            </value>
            <value>
                <fullName>MOL</fullName>
                <isActive>false</isActive>
                <label>MOL</label>
            </value>
            <value>
                <fullName>Marubeni</fullName>
                <isActive>false</isActive>
                <label>Marubeni</label>
            </value>
            <value>
                <fullName>Mitsui</fullName>
                <isActive>false</isActive>
                <label>Mitsui</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClarificationTopic__c/ClarificationTopic__c.object-meta.xml
<CustomObject>
    <label>Clarification Topic</label>
    <nameField>
        <label>Clarification Topic  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarifications Topics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClarificationTopic__c/fields/Clarification__c.field-meta.xml
<CustomField>
    <fullName>Clarification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clarification</label>
    <referenceTo>Clarification__c</referenceTo>
    <relationshipLabel>Clarifications Topics</relationshipLabel>
    <relationshipName>ClarificationsTopics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClarificationTopic__c/fields/NAM1__c.field-meta.xml
<CustomField>
    <fullName>NAM1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NAM</label>
    <referenceTo>NAM__c</referenceTo>
    <relationshipLabel>Clarifications Topics</relationshipLabel>
    <relationshipName>ClarificationsTopics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClarificationTopic__c/fields/NAM__c.field-meta.xml
<CustomField>
    <fullName>NAM__c</fullName>
    <formula>HYPERLINK(Clarification__r.NAM__c,Clarification__r.NAM__r.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>NAM</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClarificationTopic__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <formula>Text(Clarification__r.Partner__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Partner</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NAM__c/NAM__c.object-meta.xml
<CustomObject>
    <label>NAM</label>
    <nameField>
        <label>NAM Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NAMs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NAM__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AMC</fullName>
                <default>true</default>
                <label>AMC</label>
            </value>
            <value>
                <fullName>OM</fullName>
            </value>
            <value>
                <fullName>PEM</fullName>
            </value>
            <value>
                <fullName>Tech Team</fullName>
            </value>
            <value>
                <fullName>SPC Partners</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>SPC Modec</fullName>
                <isActive>false</isActive>
                <label>SPC Modec</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ClarificationFactory.cls
public class ClarificationFactory {
    public static Clarification__c createClarification (NAM__c nam, string type) {
        Clarification__c clarificartion = new Clarification__c(
            NAM__c = nam.Id,
            Status__c = 'Pending',
            Partner__c = 'Mitsui',
            Type__c = type
        );
        insert clarificartion;
        return clarificartion;
    }

    public static Clarification__c createClarificationPartner (NAM__c nam, string type, string partner) {
        Clarification__c clarificartion = new Clarification__c(
            NAM__c = nam.Id,
            Status__c = 'Pending',
            Partner__c = partner,
            Type__c = type
        );
        insert clarificartion;
        return clarificartion;
    }


     public static ClarificationTopic__c createClarificationTopic (Clarification__c clarification) {
        ClarificationTopic__c clarificartionTopic = new ClarificationTopic__c(
            NAM1__c = clarification.NAM__c,
            Clarification__c = clarification.Id,
            Name = 'Clarification 1'
        );
        insert clarificartionTopic;
        return clarificartionTopic;
    }
}