force-app/main/default/objects/Clarification__c/Clarification__c.object-meta.xml
<CustomObject>
    <label>Clarification</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Clarification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Clarification__c/fields/ClosedOutStatus__c.field-meta.xml
<CustomField>
    <fullName>ClosedOutStatus__c</fullName>
    <formula>Text(NAM__r.ClosedOutStatus__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Closed Out Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Clarification__c/fields/FinalComment__c.field-meta.xml
<CustomField>
    <fullName>FinalComment__c</fullName>
    <label>Final Comment</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Clarification__c/fields/NAM__c.field-meta.xml
<CustomField>
    <fullName>NAM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NAM</label>
    <referenceTo>NAM__c</referenceTo>
    <relationshipLabel>Clarifications</relationshipLabel>
    <relationshipName>Clarifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Clarification__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <label>Partner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mitsui</fullName>
            </value>
            <value>
                <fullName>Marubeni</fullName>
            </value>
            <value>
                <fullName>MOL</fullName>
            </value>
            <value>
                <fullName>MINC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clarification__c/fields/RejectReason__c.field-meta.xml
<CustomField>
    <fullName>RejectReason__c</fullName>
    <label>Reject Reason</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Clarification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clarification__c/fields/Vessel__c.field-meta.xml
<CustomField>
    <fullName>Vessel__c</fullName>
    <formula>NAM__r.Vessel__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vessel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClarificationTopic__c/ClarificationTopic__c.object-meta.xml
<CustomObject>
    <label>Clarification Topic</label>
    <nameField>
        <label>Clarification Topic  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clarifications Topics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClarificationTopic__c/fields/Clarification__c.field-meta.xml
<CustomField>
    <fullName>Clarification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clarification</label>
    <referenceTo>Clarification__c</referenceTo>
    <relationshipLabel>Clarifications Topics</relationshipLabel>
    <relationshipName>ClarificationsTopics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClarificationTopic__c/fields/NAM1__c.field-meta.xml
<CustomField>
    <fullName>NAM1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NAM</label>
    <referenceTo>NAM__c</referenceTo>
    <relationshipLabel>Clarifications Topics</relationshipLabel>
    <relationshipName>ClarificationsTopics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClarificationTopic__c/fields/NAM__c.field-meta.xml
<CustomField>
    <fullName>NAM__c</fullName>
    <formula>HYPERLINK(Clarification__r.NAM__c,Clarification__r.NAM__r.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>NAM</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClarificationTopic__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <formula>Text(Clarification__r.Partner__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Partner</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FinalClarification__c/FinalClarification__c.object-meta.xml
<CustomObject>
    <label>Final Clarification</label>
    <nameField>
        <displayFormat>CL-{000000}</displayFormat>
        <label>Final Partner Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Final Clarifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FinalClarification__c/fields/Clarification__c.field-meta.xml
<CustomField>
    <fullName>Clarification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clarification</label>
    <referenceTo>Clarification__c</referenceTo>
    <relationshipLabel>Final Clarifications</relationshipLabel>
    <relationshipName>FinalClarifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinalClarification__c/fields/FinalComment__c.field-meta.xml
<CustomField>
    <fullName>FinalComment__c</fullName>
    <label>Final Comment</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FinalClarification__c/fields/NAM__c.field-meta.xml
<CustomField>
    <fullName>NAM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NAM</label>
    <referenceTo>NAM__c</referenceTo>
    <relationshipLabel>Final Clarifications</relationshipLabel>
    <relationshipName>FinalClarifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinalClarification__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <label>Partner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mitsui</fullName>
            </value>
            <value>
                <fullName>MOL</fullName>
            </value>
            <value>
                <fullName>Marubeni</fullName>
            </value>
            <value>
                <fullName>MINC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NAM__c/NAM__c.object-meta.xml
<CustomObject>
    <label>NAM</label>
    <nameField>
        <label>NAM Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NAMs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NAM__c/fields/ClosedOutStatus__c.field-meta.xml
<CustomField>
    <fullName>ClosedOutStatus__c</fullName>
    <label>Closed Out Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Execution</fullName>
            </value>
            <value>
                <fullName>EM</fullName>
            </value>
            <value>
                <fullName>PEM</fullName>
            </value>
            <value>
                <fullName>Tech Team</fullName>
            </value>
            <value>
                <fullName>SPC Partners</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NAM__c/fields/MarubeniApprovalDate__c.field-meta.xml
<CustomField>
    <fullName>MarubeniApprovalDate__c</fullName>
    <label>Marubeni Approval Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/MarubeniClosedOutApprovalDate__c.field-meta.xml
<CustomField>
    <fullName>MarubeniClosedOutApprovalDate__c</fullName>
    <label>Marubeni Closed Out Approval Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/MarubeniClosedOutStatus__c.field-meta.xml
<CustomField>
    <fullName>MarubeniClosedOutStatus__c</fullName>
    <label>Marubeni Closed Out Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ClarificationStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/NAM__c/fields/MarubeniStatus__c.field-meta.xml
<CustomField>
    <fullName>MarubeniStatus__c</fullName>
    <label>Marubeni Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ClarificationStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/NAM__c/fields/MINCApprovalDate__c.field-meta.xml
<CustomField>
    <fullName>MINCApprovalDate__c</fullName>
    <label>MINC Approval Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/MINCStatus__c.field-meta.xml
<CustomField>
    <fullName>MINCStatus__c</fullName>
    <label>MINC Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ClarificationStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/NAM__c/fields/MitsuiApprovalDate__c.field-meta.xml
<CustomField>
    <fullName>MitsuiApprovalDate__c</fullName>
    <label>Mitsui Approval Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/MitsuiClosedOutApprovalDate__c.field-meta.xml
<CustomField>
    <fullName>MitsuiClosedOutApprovalDate__c</fullName>
    <label>Mitsui Closed Out Approval Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/MitsuiClosedOutStatus__c.field-meta.xml
<CustomField>
    <fullName>MitsuiClosedOutStatus__c</fullName>
    <label>Mitsui Closed Out Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ClarificationStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/NAM__c/fields/MitsuiStatus__c.field-meta.xml
<CustomField>
    <fullName>MitsuiStatus__c</fullName>
    <label>Mitsui Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ClarificationStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/NAM__c/fields/MOLApprovalDate__c.field-meta.xml
<CustomField>
    <fullName>MOLApprovalDate__c</fullName>
    <label>MOL Approval Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/MOLClosedOutStatus__c.field-meta.xml
<CustomField>
    <fullName>MOLClosedOutStatus__c</fullName>
    <label>MOL Closed Out Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ClarificationStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/NAM__c/fields/MOLStatus__c.field-meta.xml
<CustomField>
    <fullName>MOLStatus__c</fullName>
    <label>MOL Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ClarificationStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/NAM__c/fields/RCA__c.field-meta.xml
<CustomField>
    <fullName>RCA__c</fullName>
    <label>RCA</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Required</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NAM__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AMC</fullName>
                <default>true</default>
                <label>AMC</label>
            </value>
            <value>
                <fullName>OM</fullName>
            </value>
            <value>
                <fullName>PEM</fullName>
            </value>
            <value>
                <fullName>Tech Team</fullName>
            </value>
            <value>
                <fullName>SPC Partners</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>SPC Modec</fullName>
                <isActive>false</isActive>
                <label>SPC Modec</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NAM__c/fields/TechFinalComment__c.field-meta.xml
<CustomField>
    <fullName>TechFinalComment__c</fullName>
    <label>Tech Final Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/Vessel__c.field-meta.xml
<CustomField>
    <fullName>Vessel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vessel</label>
    <referenceTo>Vessel__c</referenceTo>
    <relationshipLabel>NAMs</relationshipLabel>
    <relationshipName>NAMs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vessel__c/Vessel__c.object-meta.xml
<CustomObject>
    <label>Vessel</label>
    <nameField>
        <label>Vessel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vessels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vessel__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Decommissioned</fullName>
            </value>
            <value>
                <fullName>EPCI</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>In Operation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/ClarificationStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <masterLabel>ClarificationStatus</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ClarificationBOTest.cls
@isTest
public with sharing class ClarificationBOTest {

    @istest static void finalCommentsApproved() {
        Test.startTest();
        Vessel__c vessel = VesselFactory.createVessel();
        NAM__c nam = NAMFactory.createNAM(vessel, 'NAM-MV24-20-001');
        Clarification__c clarification = ClarificationFactory.createClarification(nam, 'NAM');
        Test.stopTest();

        nam.RCA__c = 'Required';
        nam.TechFinalComment__c = 'aaaa';
        nam.Status__c = 'SPC Partners';
        update nam;
        
        clarification.FinalComment__c = 'My test final comment';
        update clarification;
        
        Clarification__c c = [SELECT Id, FinalComment__c, Status__c, NAM__c FROM Clarification__c WHERE Id =: clarification.Id];
        System.assertEquals(null, c.FinalComment__c);
        System.assertEquals('Approved', c.Status__c);

        FinalClarification__c finalClarification = [SELECT Id, Clarification__c, NAM__c, FinalComment__c, Partner__c FROM FinalClarification__c WHERE Clarification__c =: clarification.Id LIMIT 1];
        System.assertEquals(finalClarification.Clarification__c, c.Id);
        System.assertEquals(finalClarification.NAM__c, c.NAM__c);
        System.assertEquals(finalClarification.FinalComment__c, clarification.FinalComment__c);
        System.assertEquals(finalClarification.Partner__c, 'Mitsui');
    }
    @istest static void finalCommentsApprovedError1() {
        Test.startTest();
        Vessel__c vessel = VesselFactory.createVessel();
        NAM__c nam = NAMFactory.createNAM(vessel, 'NAM-MV24-20-001');
        Clarification__c clarification = ClarificationFactory.createClarification(nam, 'NAM');
        
        try {
            clarification.FinalComment__c = 'My test final comment';
            update clarification;
        } catch (Exception e) {
            System.Assert(e.getMessage().contains('You only can edit the clarification when NAM record status is "SPC Partners"'));
            Clarification__c c = [SELECT Id, FinalComment__c FROM Clarification__c WHERE Id =: clarification.Id];
            System.assertEquals(null, c.FinalComment__c);
        }
        Test.stopTest();
    }

    @istest static void finalCommentsApprovedError2() {
        Test.startTest();
        Vessel__c vessel = VesselFactory.createVessel();
        NAM__c nam = NAMFactory.createNAM(vessel, 'NAM-MV24-20-001');
        Clarification__c clarification = ClarificationFactory.createClarification(nam, 'NAM');

        nam.RCA__c = 'Required';
        nam.TechFinalComment__c = 'aaaa';
        nam.Status__c = 'SPC Partners';
        update nam;
        
        try {
            clarification.Status__c = 'Rejected';
            clarification.FinalComment__c = 'My test final comment';
            update clarification;
        } catch (Exception e) {
            System.Assert(e.getMessage().contains('You cannot Approve a Rejected record'));
            Clarification__c c = [SELECT Id, FinalComment__c, RejectReason__c FROM Clarification__c WHERE Id =: clarification.Id];
            System.assertEquals(null, c.RejectReason__c);
        }
        Test.stopTest();
    }

    @istest static void finalCommentsRejectedError1() {
        Test.startTest();
        Vessel__c vessel = VesselFactory.createVessel();
        NAM__c nam = NAMFactory.createNAM(vessel, 'NAM-MV24-20-001');
        Clarification__c clarification = ClarificationFactory.createClarification(nam, 'NAM');
        
        try {
            clarification.RejectReason__c = 'My test rejected comment';
            update clarification;
        } catch (Exception e) {
            System.Assert(e.getMessage().contains('You only can edit the clarification when NAM record status is "SPC Partners"'));
            Clarification__c c = [SELECT Id, RejectReason__c FROM Clarification__c WHERE Id =: clarification.Id];
            System.assertEquals(null, c.RejectReason__c);
        }
        Test.stopTest();
    }

    @istest static void finalCommentsRejectedError2() {
        Test.startTest();
        Vessel__c vessel = VesselFactory.createVessel();
        NAM__c nam = NAMFactory.createNAM(vessel, 'NAM-MV24-20-001');
        Clarification__c clarification = ClarificationFactory.createClarification(nam, 'NAM');

        nam.RCA__c = 'Required';
        nam.TechFinalComment__c = 'aaaa';
        nam.Status__c = 'SPC Partners';
        update nam;
        
        try {
            clarification.Status__c = 'Approved';
            clarification.RejectReason__c = 'My test rejection comment';
            update clarification;
        } catch (Exception e) {
            System.Assert(e.getMessage().contains('You cannot Reject an Approved record'));
            Clarification__c c = [SELECT Id, FinalComment__c, RejectReason__c FROM Clarification__c WHERE Id =: clarification.Id];
            System.assertEquals(null, c.RejectReason__c);
        }
        Test.stopTest();
    }
    @isTest static void getClarification(){
        Test.startTest();
        Vessel__c vessel = VesselFactory.createVessel();
        NAM__c nam = NAMFactory.createNAM(vessel, 'NAM-MV24-20-001');
        Clarification__c clarification = ClarificationFactory.createClarification(nam, 'NAM');
        ClarificationTopic__c topic = ClarificationFactory.createClarificationTopic(clarification);
        Test.stopTest();

        Clarification__c c = ClarificationDAO.getById(clarification.Id);
        Set<String> setClarificationId = new Set<String>{clarification.Id};
        List<Clarification__c> lstC = ClarificationDAO.getById(setClarificationId);

        System.assertEquals(c.NAM__c, clarification.NAM__c);
        System.assertEquals(1, lstC.size());

        try{
            Clarification__c cError = ClarificationDAO.getById('a0h3I000001lSYxQAM'); //invalid clarification id
            System.assertEquals(null, cError);
        }catch (Exception e){ }
    }

    @isTest static void fillClarificationTopicTest(){
        Test.startTest();
        Vessel__c vessel = VesselFactory.createVessel();
        NAM__c nam = NAMFactory.createNAM(vessel, 'NAM-MV24-20-001');
        Clarification__c clarification = ClarificationFactory.createClarification(nam, 'NAM');
        Clarification__c clarification2 = ClarificationFactory.createClarificationPartner(nam, 'NAM', 'MINC');
        ClarificationTopic__c topic = ClarificationFactory.createClarificationTopic(clarification);
        Test.stopTest();

        ClarificationTopic__c clarificationTopic = new ClarificationTopic__c(
            NAM1__c = clarification.NAM__c,
            Name = 'Clarification 1'
        );
        insert clarificationTopic;
    }

    @isTest static void clarificationStatusAfterPartnerRejection1(){
        Test.startTest();
        Vessel__c vessel = VesselFactory.createVessel();
        NAM__c nam = NAMFactory.createNAM(vessel, 'NAM-MV24-20-001');
        Clarification__c clarificationMitsui = ClarificationFactory.createClarificationPartner(nam, 'NAM', 'Mitsui');
        Clarification__c clarificationMarubeni = ClarificationFactory.createClarificationPartner(nam, 'NAM', 'Marubeni');
        Clarification__c clarificationMOL = ClarificationFactory.createClarificationPartner(nam, 'NAM', 'MOL');
        Clarification__c clarificationMINC = ClarificationFactory.createClarificationPartner(nam, 'NAM', 'MINC');

        nam.RCA__c = 'Required';
        nam.TechFinalComment__c = 'aaaa';
        nam.Status__c = 'SPC Partners';
        update nam;
        
        clarificationMarubeni.status__c = 'Approved';
        clarificationMOL.status__c = 'Approved';
        clarificationMINC.status__c = 'Approved';

        List<Clarification__c> lstClarificationUpdate = new List<Clarification__c>{clarificationMarubeni, clarificationMOL, clarificationMINC};
        update lstClarificationUpdate;

        clarificationMitsui.RejectReason__c = 'My test rejection comment';
        update clarificationMitsui;

        Test.stopTest();
        
        NAM__c n = [SELECT MitsuiStatus__c, MarubeniStatus__c, MOLStatus__c, MINCStatus__c, MitsuiApprovalDate__c, MarubeniApprovalDate__c, MOLApprovalDate__c, MINCApprovalDate__c FROM NAM__c WHERE Id =: nam.Id];
        System.assertEquals('Rejected', n.MitsuiStatus__c);
        System.assertEquals('Pending',  n.MarubeniStatus__c);
        System.assertEquals( null,      n.MarubeniApprovalDate__c);
        System.assertEquals('Pending',  n.MOLStatus__c);
        System.assertEquals( null,      n.MOLApprovalDate__c);
        System.assertEquals('Pending',  n.MINCStatus__c);
        System.assertEquals( null,      n.MINCApprovalDate__c);        
    }

    @isTest static void clarificationStatusAfterPartnerRejection2(){
        Test.startTest();
        Vessel__c vessel = VesselFactory.createVessel();
        NAM__c nam = NAMFactory.createNAM(vessel, 'NAM-MV24-20-001');
        Clarification__c clarificationMitsui = ClarificationFactory.createClarificationPartner(nam, 'NAM', 'Mitsui');
        Clarification__c clarificationMarubeni = ClarificationFactory.createClarificationPartner(nam, 'NAM', 'Marubeni');
        Clarification__c clarificationMOL = ClarificationFactory.createClarificationPartner(nam, 'NAM', 'MOL');
        Clarification__c clarificationMINC = ClarificationFactory.createClarificationPartner(nam, 'NAM', 'MINC');

        nam.RCA__c = 'Required';
        nam.TechFinalComment__c = 'aaaa';
        nam.Status__c = 'SPC Partners';
        update nam;
        
        clarificationMitsui.status__c = 'Approved';
        clarificationMOL.status__c = 'Approved';
        clarificationMINC.status__c = 'Approved';

        List<Clarification__c> lstClarificationUpdate = new List<Clarification__c>{clarificationMitsui, clarificationMOL, clarificationMINC};
        update lstClarificationUpdate;

        clarificationMarubeni.RejectReason__c = 'My test rejection comment';
        update clarificationMarubeni;

        Test.stopTest();
        
        NAM__c n = [SELECT MitsuiStatus__c, MitsuiApprovalDate__c FROM NAM__c WHERE Id =: nam.Id];

        System.assertEquals('Pending', n.MitsuiStatus__c);
        System.assertEquals(null,      n.MitsuiApprovalDate__c);        
    }

    @isTest static void namStatusAfterAllFinalClarificationsApproved(){
        Test.startTest();
        Vessel__c vessel = VesselFactory.createVessel();
        NAM__c nam = NAMFactory.createNAM(vessel, 'NAM-MV24-20-001');
        Clarification__c clarificationMitsui = ClarificationFactory.createClarificationPartner(nam, 'Closed Out', 'Mitsui');
        Clarification__c clarificationMarubeni = ClarificationFactory.createClarificationPartner(nam, 'Closed Out', 'Marubeni');
        Clarification__c clarificationMOL = ClarificationFactory.createClarificationPartner(nam, 'Closed Out', 'MOL');
        Clarification__c clarificationMINC = ClarificationFactory.createClarificationPartner(nam, 'Closed Out', 'MINC');

        nam.Status__c = 'Approved';
        nam.ClosedOutStatus__c = 'Execution';
        nam.RCA__c = 'Required';
        nam.TechFinalComment__c = 'Tech comment test';
        update nam;

        clarificationMitsui.Status__c = 'Approved';
        clarificationMOL.Status__c = 'Approved';
        clarificationMINC.Status__c = 'Approved';
        clarificationMarubeni.Status__c = 'Approved';
        List<Clarification__c> lstClarification = new List<Clarification__c> {clarificationMitsui, clarificationMOL, clarificationMINC, clarificationMarubeni};
        update lstClarification;

        Test.stopTest();

        NAM__c n = [SELECT MitsuiClosedOutStatus__c, MitsuiClosedOutApprovalDate__c, MarubeniClosedOutStatus__c, MarubeniClosedOutApprovalDate__c, MOLClosedOutStatus__c, MOLClosedOutApprovalDate__c, MINCClosedOutStatus__c, MINCClosedOutApprovalDate__c FROM NAM__c WHERE Id =: nam.Id];
        Date approvedDate = Date.today();
        System.assertEquals('Approved', n.MitsuiClosedOutStatus__c);
        System.assertEquals(approvedDate, n.MitsuiClosedOutApprovalDate__c);
        System.assertEquals('Approved', n.MarubeniClosedOutStatus__c);
        System.assertEquals(approvedDate, n.MarubeniClosedOutApprovalDate__c);
        System.assertEquals('Approved', n.MOLClosedOutStatus__c);
        System.assertEquals(approvedDate, n.MOLClosedOutApprovalDate__c);
        System.assertEquals('Approved', n.MINCClosedOutStatus__c);
        System.assertEquals(approvedDate, n.MINCClosedOutApprovalDate__c);
    }
}