force-app/main/default/objects/Clarification__c/Clarification__c.object-meta.xml
<CustomObject>
    <label>Clarification</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Clarification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Clarification__c/fields/NAM__c.field-meta.xml
<CustomField>
    <fullName>NAM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NAM</label>
    <referenceTo>NAM__c</referenceTo>
    <relationshipLabel>Clarifications</relationshipLabel>
    <relationshipName>Clarifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NAM__c/NAM__c.object-meta.xml
<CustomObject>
    <label>NAM</label>
    <nameField>
        <label>NAM Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NAMs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/ClarificationDAO.cls
public with sharing class ClarificationDAO {
   public static Clarification__c getById(String idCla){
        List<Clarification__c> lst = getById(new Set<String> {idCla});
        if(lst.size() > 0) return lst[0];
        else return null;
   }
   public static List<Clarification__c> getById(Set<String> ids){
        return [SELECT OwnerId, 
                        Owner.Email ,
                        Name,
                        NAM__c
                FROM Clarification__c
                WHERE ID IN : ids];
   }
}