force-app/main/default/objects/Clarification__c/Clarification__c.object-meta.xml
<CustomObject>
    <label>Clarification</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Clarification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Clarification__c/fields/ClosedOutStatus__c.field-meta.xml
<CustomField>
    <fullName>ClosedOutStatus__c</fullName>
    <formula>Text(NAM__r.ClosedOutStatus__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Closed Out Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Clarification__c/fields/FinalComment__c.field-meta.xml
<CustomField>
    <fullName>FinalComment__c</fullName>
    <label>Final Comment</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Clarification__c/fields/NAM__c.field-meta.xml
<CustomField>
    <fullName>NAM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NAM</label>
    <referenceTo>NAM__c</referenceTo>
    <relationshipLabel>Clarifications</relationshipLabel>
    <relationshipName>Clarifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Clarification__c/fields/RejectReason__c.field-meta.xml
<CustomField>
    <fullName>RejectReason__c</fullName>
    <label>Reject Reason</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Clarification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clarification__c/fields/Vessel__c.field-meta.xml
<CustomField>
    <fullName>Vessel__c</fullName>
    <formula>NAM__r.Vessel__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vessel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NAM__c/NAM__c.object-meta.xml
<CustomObject>
    <label>NAM</label>
    <nameField>
        <label>NAM Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NAMs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NAM__c/fields/ClarificationCreated__c.field-meta.xml
<CustomField>
    <fullName>ClarificationCreated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Clarification Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/ClosedOutClarificationCreated__c.field-meta.xml
<CustomField>
    <fullName>ClosedOutClarificationCreated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Closed Out Clarification Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/ClosedOutStatus__c.field-meta.xml
<CustomField>
    <fullName>ClosedOutStatus__c</fullName>
    <label>Closed Out Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Execution</fullName>
            </value>
            <value>
                <fullName>EM</fullName>
            </value>
            <value>
                <fullName>PEM</fullName>
            </value>
            <value>
                <fullName>Tech Team</fullName>
            </value>
            <value>
                <fullName>SPC Partners</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NAM__c/fields/FutherAssetDamage__c.field-meta.xml
<CustomField>
    <fullName>FutherAssetDamage__c</fullName>
    <label>Further Asset Damage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>&lt;USD 20K</fullName>
            </value>
            <value>
                <fullName>&lt;USD 100K</fullName>
            </value>
            <value>
                <fullName>&lt;USD 500K</fullName>
            </value>
            <value>
                <fullName>&lt;USD 1M</fullName>
            </value>
            <value>
                <fullName>&gt;USD 1M</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NAM__c/fields/FutherRating__c.field-meta.xml
<CustomField>
    <fullName>FutherRating__c</fullName>
    <formula>IF(TEXT( FutherAssetDamage__c ) = &apos;&lt;USD 20K&apos;, 1,  
  IF(TEXT(FutherAssetDamage__c) = &apos;&lt;USD 100K&apos;, 2,
     IF(TEXT(FutherAssetDamage__c) = &apos;&lt;USD 500K&apos;, 3,
       IF(TEXT(FutherAssetDamage__c) = &apos;&lt;USD 1M&apos;, 4,
          IF(TEXT(FutherAssetDamage__c) = &apos;&gt;USD 1M&apos;, 5, 0)
       )
     )
   )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Futher Rating</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/PotentialPenalty__c.field-meta.xml
<CustomField>
    <fullName>PotentialPenalty__c</fullName>
    <label>Potential Penalty / Rate Reduction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>&lt;USD 100K</fullName>
            </value>
            <value>
                <fullName>&lt;USD 500K</fullName>
            </value>
            <value>
                <fullName>&lt;USD 1M</fullName>
            </value>
            <value>
                <fullName>&gt;USD 1M</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NAM__c/fields/PotentialRating__c.field-meta.xml
<CustomField>
    <fullName>PotentialRating__c</fullName>
    <formula>IF(text(PotentialPenalty__c) =&apos;No&apos;, 1,
  IF(Text(PotentialPenalty__c) = &apos;&lt;USD 100K&apos;, 2,
    IF(text(PotentialPenalty__c) = &apos;&gt;USD 1M&apos;, 5,
      IF(Text(PotentialPenalty__c) = &apos;&lt;USD 1M&apos;, 4, 
        IF(text(PotentialPenalty__c) = &apos;&lt;USD 500K&apos;, 3, 0)
      ) 
    )
  )
)</formula>
    <label>Potential Rating</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/RatingSafety__c.field-meta.xml
<CustomField>
    <fullName>RatingSafety__c</fullName>
    <formula>IF(TEXT(Safety__c) = &apos;No injury&apos;, 1,  
    IF(TEXT(Safety__c) = &apos;Slight injury&apos;, 2,
     IF(TEXT(Safety__c) = &apos;Minor injury&apos;, 3,
       IF(TEXT(Safety__c) = &apos;Major injury&apos;, 4,
          IF(TEXT(Safety__c) = &apos;Single fatality&apos;, 5, 0 )
     )
   )
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rating People</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/RCA__c.field-meta.xml
<CustomField>
    <fullName>RCA__c</fullName>
    <label>RCA</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Required</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NAM__c/fields/Revision__c.field-meta.xml
<CustomField>
    <fullName>Revision__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Revision</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/Safety__c.field-meta.xml
<CustomField>
    <fullName>Safety__c</fullName>
    <label>People</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No injury</fullName>
            </value>
            <value>
                <fullName>Slight injury</fullName>
            </value>
            <value>
                <fullName>Minor injury</fullName>
            </value>
            <value>
                <fullName>Major injury</fullName>
            </value>
            <value>
                <fullName>Single fatality</fullName>
            </value>
            <value>
                <fullName>Lost time injury</fullName>
                <isActive>false</isActive>
                <label>Lost time injury</label>
            </value>
            <value>
                <fullName>Multiple facilities</fullName>
                <isActive>false</isActive>
                <label>Multiple facilities</label>
            </value>
            <value>
                <fullName>Multiple fatalities</fullName>
                <isActive>false</isActive>
                <label>Multiple fatalities</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NAM__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AMC</fullName>
                <default>true</default>
                <label>AMC</label>
            </value>
            <value>
                <fullName>OM</fullName>
            </value>
            <value>
                <fullName>PEM</fullName>
            </value>
            <value>
                <fullName>Tech Team</fullName>
            </value>
            <value>
                <fullName>SPC Partners</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>SPC Modec</fullName>
                <isActive>false</isActive>
                <label>SPC Modec</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NAM__c/fields/TechFinalComment__c.field-meta.xml
<CustomField>
    <fullName>TechFinalComment__c</fullName>
    <label>Tech Final Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/Vessel__c.field-meta.xml
<CustomField>
    <fullName>Vessel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vessel</label>
    <referenceTo>Vessel__c</referenceTo>
    <relationshipLabel>NAMs</relationshipLabel>
    <relationshipName>NAMs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TechnicalMemberSupport__c/TechnicalMemberSupport__c.object-meta.xml
<CustomObject>
    <label>Technical Member Support</label>
    <nameField>
        <displayFormat>TTS-{00000}</displayFormat>
        <label>Technical Member Support  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Technical Members Supports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TechnicalMemberSupport__c/fields/NAM__c.field-meta.xml
<CustomField>
    <fullName>NAM__c</fullName>
    <label>NAM</label>
    <referenceTo>NAM__c</referenceTo>
    <relationshipLabel>Technical Members Supports</relationshipLabel>
    <relationshipName>TechTeamsSupports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TechnicalMemberSupport__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Supported</fullName>
            </value>
            <value>
                <fullName>Not Supported</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vessel__c/Vessel__c.object-meta.xml
<CustomObject>
    <label>Vessel</label>
    <nameField>
        <label>Vessel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vessels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vessel__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Decommissioned</fullName>
            </value>
            <value>
                <fullName>EPCI</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>In Operation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/NAM__c.field-meta.xml
<CustomField>
    <fullName>NAM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NAM</label>
    <referenceTo>NAM__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>WorkOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Revision__c.field-meta.xml
<CustomField>
    <fullName>Revision__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Revision</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/NAM__c.field-meta.xml
<CustomField>
    <fullName>NAM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NAM</label>
    <referenceTo>NAM__c</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>WorkOrderLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <inlineHelpText>USD</inlineHelpText>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/NAMTest.cls
@isTest
public with sharing class NAMTest {
    @isTest static void testNAMRename(){
        
        Test.startTest();
        Vessel__c vessel = VesselFactory.createVessel();
        NAM__c nam = NAMFactory.createNAM(vessel, 'NAM-MV24-20-001');
        Test.stopTest();

        System.assertEquals(nam.Name, 'NAM-MV24-20-001'); 
    }
    @isTest static void testCalculateNAM(){

        Test.startTest();
        NAMFactory.createExchange();
        Vessel__c vessel = VesselFactory.createVessel();
        NAM__c nam = NAMFactory.createNAM(vessel, 'NAM-MV24-20-001');        
        WorkOrder wo = WorkOrderFactory.createWO(nam, 'MdB');
        WorkOrderLineItem woItem = WorkOrderFactory.createWOLineItem(wo, 1000);
        Test.stopTest();
    }
    @isTest static void testCreateNAMClarification(){

        Test.startTest();
        NAMFactory.createExchange();
        Vessel__c vessel = VesselFactory.createVessel();
        NAM__c nam = NAMFactory.createNAM(vessel, 'NAM-MV24-20-001');        
        WorkOrder wo = WorkOrderFactory.createWO(nam, 'MdB');
        WorkOrderLineItem woItem = WorkOrderFactory.createWOLineItem(wo, 1000);
         
        woItem.Price__c = 1500;
        update woItem;

        update wo;

        nam.Revision__c = 1;
        update nam;


        nam.Status__c = 'PEM';
        update nam;

        nam.ClarificationCreated__c = true;
        nam.Status__c = 'Tech Team';
        update nam;
    
        Test.stopTest();
    }

    @isTest static void testCreateNAM1(){

        Test.startTest();
        NAMFactory.createExchange();
        Vessel__c vessel = VesselFactory.createVessel();
        NAM__c nam = NAMFactory.createNAM(vessel, 'NAM-MV24-20-001');        
        WorkOrder wo = WorkOrderFactory.createWO(nam, 'MdB');
        WorkOrderLineItem woItem = WorkOrderFactory.createWOLineItem(wo, 1000);
         
        woItem.Price__c = 1500;
        update woItem;

        update wo;

        nam.Revision__c = 1;
        update nam;

        Test.stopTest();
    }

    @isTest static void testCreateNAM2(){

        Test.startTest();
        NAMFactory.createExchange();
        Vessel__c vessel = VesselFactory.createVessel();
        NAM__c nam = NAMFactory.createNAM(vessel, 'NAM-MV24-20-001');        
        WorkOrder wo = WorkOrderFactory.createWO(nam, 'MdB');
        WorkOrderLineItem woItem = WorkOrderFactory.createWOLineItem(wo, 1000);
         
        woItem.Price__c = 1500;
        update woItem;

        update wo;

        nam.Status__c = 'PEM';
        update nam;

        nam.ClarificationCreated__c = true;
        nam.Status__c = 'Tech Team';
        update nam;

        Test.stopTest();
    }

     @isTest static void testCreateNAM3(){

        Test.startTest();
        NAMFactory.createExchange();
        Vessel__c vessel = VesselFactory.createVessel();
        NAM__c nam = NAMFactory.createNAM(vessel, 'NAM-MV24-20-001');        
        WorkOrder wo = WorkOrderFactory.createWO(nam, 'MdB');
        WorkOrderLineItem woItem = WorkOrderFactory.createWOLineItem(wo, 1000);
         
        nam.Status__c = 'Approved';
        nam.ClosedOutStatus__c = 'Execution';
        nam.RCA__c = 'Required';
        nam.TechFinalComment__c = 'aaaa';
        update nam;

        nam.ClosedOutStatus__c = 'PEM';
        update nam;
        
        nam.ClosedOutClarificationCreated__c = true; 
        nam.ClosedOutStatus__c = 'Tech Team';
        update nam;
    
        Test.stopTest();
    }
   
     

    @isTest static void testCreateClarificationApproved(){

        Test.startTest();
        
        Vessel__c vessel = VesselFactory.createVessel();
        NAM__c nam = NAMFactory.createNAM(vessel, 'NAM-MV24-20-001');        
        
        nam.RCA__c = 'Required';
        nam.TechFinalComment__c = 'aaaa';
        nam.Status__c = 'SPC Partners';
        update nam;

        Clarification__c clarificationNAM = ClarificationFactory.createClarification(nam, 'NAM');
        clarificationNAM.FinalComment__c = 'finnalcccccc';
        update clarificationNAM;

        Test.stopTest();
    }

    @isTest static void testCreateClarificationRejected(){

        Test.startTest();
        
        Vessel__c vessel = VesselFactory.createVessel();
        NAM__c nam = NAMFactory.createNAM(vessel, 'NAM-MV24-20-001');        
        
        nam.RCA__c = 'Required';
        nam.TechFinalComment__c = 'aaaa';
        nam.Status__c = 'SPC Partners';
        update nam;

        Clarification__c clarificationNAM = ClarificationFactory.createClarification(nam, 'NAM');

        ClarificationFactory.createClarificationTopic(clarificationNAM);
        
        clarificationNAM.RejectReason__c = 'finnalcccccc';
        update clarificationNAM;

        Test.stopTest();
    }
    @isTest static void testCreateClarificationTopic(){
        Test.startTest();
        
        Vessel__c vessel = VesselFactory.createVessel();
        NAM__c nam = NAMFactory.createNAM(vessel, 'NAM-MV24-20-001');        
        
        nam.RCA__c = 'Required';
        nam.TechFinalComment__c = 'aaaa';
        nam.Status__c = 'SPC Partners';
        update nam;

        Clarification__c clarificationNAM = ClarificationFactory.createClarification(nam, 'NAM');

        clarificationNAM.RejectReason__c = 'finnalcccccc';
        update clarificationNAM;

        Test.stopTest();
    }

    @isTest static void testColorRatingRed1(){
        Test.startTest();
        Vessel__c vessel = VesselFactory.createVessel();
        NAM__c nam = NAMFactory.createNAM(vessel, 'NAM-MV24-20-001');
 
        //1 RatingSafety__c > FutherRating__c && RatingSafety__c > PotentialRating__c
        nam.Safety__c = 'Single fatality';      //represents RatingSafety__c = 5 in scoring
        nam.FutherAssetDamage__c = '<USD 20K';  //represents FutherRating__c = 1 in scoring
        nam.PotentialPenalty__c = 'No';         //represents PotentialRating__c = 1 in scoring
        nam.Probability__c = 'A';
        
        update nam;
        Test.stopTest();

        NAM__c n = [SELECT Id, ColorRating__c FROM NAM__c WHERE Name = 'NAM-MV24-20-001'];
        
        System.assertEquals('red', n.ColorRating__c);
    }

    @isTest static void testColorRatingRed2(){
        Test.startTest();
        Vessel__c vessel = VesselFactory.createVessel();
        NAM__c nam = NAMFactory.createNAM(vessel, 'NAM-MV24-20-001');
        
        //2 PotentialRating__c > RatingSafety__c && PotentialRating__c > FutherRating__c
        nam.Safety__c = 'No injury';            //represents RatingSafety__c = 1 in scoring
        nam.FutherAssetDamage__c = '<USD 20K';  //represents FutherRating__c = 1 in scoring
        nam.PotentialPenalty__c = '<USD 500K';  //represents PotentialRating__c = 3 in scoring
        nam.Probability__c = 'D';
        
        update nam;
        Test.stopTest();

        NAM__c n = [SELECT Id, ColorRating__c FROM NAM__c WHERE Name = 'NAM-MV24-20-001'];

        System.assertEquals('red', n.ColorRating__c);
    }

    @isTest static void testColorRatingRed3(){
        Test.startTest();
        Vessel__c vessel = VesselFactory.createVessel();
        NAM__c nam = NAMFactory.createNAM(vessel, 'NAM-MV24-20-001');
        
        //2 PotentialRating__c > RatingSafety__c && PotentialRating__c > FutherRating__c
        nam.Safety__c = 'No injury';            //represents RatingSafety__c = 1 in scoring
        nam.FutherAssetDamage__c = '<USD 20K';  //represents FutherRating__c = 1 in scoring
        nam.PotentialPenalty__c = '<USD 1M';    //represents PotentialRating__c = 4 in scoring
        nam.Probability__c = 'D';
        
        update nam;
        Test.stopTest();

        NAM__c n = [SELECT Id, ColorRating__c FROM NAM__c WHERE Name = 'NAM-MV24-20-001'];

        System.assertEquals('red', n.ColorRating__c);
    }

    @isTest static void testReasonWithoutTechSupport(){
        String username = 'technicalspc' + DateTime.now().getTime() + '@testorg.com';
        Profile profile = [SELECT Id FROM Profile WHERE Name = 'Technical SPC'];
        User user = new User(Alias = 'tech', 
                             Email = 'technicalspc@testorg.com', 
                             EmailEncodingKey = 'UTF-8', 
                             LastName = 'SPC', 
                             LanguageLocaleKey = 'en_US',
                             LocaleSidKey='en_US', 
                             ProfileId = profile.Id,
                             TimeZoneSidKey = 'America/Los_Angeles',
                             UserName = username);
        
        System.runAs(user){
            Test.startTest();
            Vessel__c vessel = VesselFactory.createVessel();
            NAM__c nam = NAMFactory.createNAM(vessel, 'NAM-MV24-20-001');
            nam.ReasonWithoutAllTechSupport__c = 'Test';
            nam.ReasonWithoutAllTechSupportCO__c = 'Test';
            update nam;
        }

        Test.stopTest();

        NAM__c n = [SELECT Id, TechSpc__c, TechSpcCO__c FROM NAM__c WHERE Name = 'NAM-MV24-20-001'];

        System.assertEquals(user.Id, n.TechSpc__c);
        System.assertEquals(user.Id, n.TechSpcCO__c);
    }

    @isTest static void renameNAMTest1(){
        Test.startTest();
        Vessel__c vessel = VesselFactory.createVessel();
        NAM__c nam = NAMFactory.createNAM(vessel, 'NAM-MV24-20-001');

        try{
            nam.Status__c = 'PEM';
            nam.Revision__c = 1;
            update nam;
        }catch(Exception e){
            System.Assert(e.getMessage().contains('You only can create a revision in the AMC stages'));
        }
    }

    @isTest static void renameNAMTest2(){
        Test.startTest();
        Vessel__c vessel = VesselFactory.createVessel();
        NAM__c nam = NAMFactory.createNAM(vessel, 'NAM-MV24-20-001');
        nam.Status__c = 'Approved';
        nam.ClosedOutStatus__c = 'Execution';
        nam.RCA__c = 'Required';
        nam.TechFinalComment__c = 'aaaa';
        update nam;

        nam.ClosedOutStatus__c = 'PEM';
        update nam;

        try{
            nam.RevisionCO__c = 1;
            update nam;
        }catch(Exception e){
            System.Assert(e.getMessage().contains('You only can create a revision in the Execution stage'));
        }
    }

    @isTest static void validateNAMNameTest1(){
        
        Test.startTest();
        Vessel__c vessel = VesselFactory.createVessel();
        try {
            NAM__c nam = NAMFactory.createNAM(vessel, 'NAMMV2420001');
        } catch (Exception e) {
            System.Assert(e.getMessage().contains('NAM number format has to be: NAM-MVxx-xx-xxx'));
        }
        Test.stopTest();
    }

    @isTest static void validateNAMNameTest2(){
        
        Test.startTest();
        Vessel__c vessel = VesselFactory.createVessel();
        try {
            NAM__c nam = NAMFactory.createNAM(vessel, 'NAM-XX24-20-001');
        } catch (Exception e) {
            System.Assert(e.getMessage().contains('NAM number format has to be: NAM-MVxx-xx-xxx'));
        }
        Test.stopTest(); 
    }

    @isTest static void updateSPCTechMember1(){
        Test.startTest();
        Vessel__c vessel = VesselFactory.createVessel();
        NAM__c nam = NAMFactory.createNAM(vessel, 'NAM-MV24-20-001');
        User user = TechnicalMemberSupportFactory.createUser('test@modec.com', 'System Administrator');
        TechnicalMemberSupport__c techSupport = TechnicalMemberSupportFactory.createTechSupport(nam, 'Supported', user, 'NAM');

        nam.Revision__c = 1;
        update nam;
        Test.stopTest();

        TechnicalMemberSupport__c t = [SELECT Id, Status__c, Description__c FROM TechnicalMemberSupport__c LIMIT 1];
        System.assertEquals('Pending', t.Status__c);
    }

    @isTest static void updateSPCTechMember2(){
        Test.startTest();
        Vessel__c vessel = VesselFactory.createVessel();
        NAM__c nam = NAMFactory.createNAM(vessel, 'NAM-MV24-20-001');
        User user = TechnicalMemberSupportFactory.createUser('test@modec.com', 'System Administrator');
        TechnicalMemberSupport__c techSupport = TechnicalMemberSupportFactory.createTechSupport(nam, 'Supported', user, 'Closed Out');

        nam.Status__c = 'Approved';
        nam.ClosedOutStatus__c = 'Execution';
        update nam;

        nam.RevisionCO__c = 1;
        update nam;
        Test.stopTest();

        TechnicalMemberSupport__c t = [SELECT Id, Status__c, Description__c FROM TechnicalMemberSupport__c LIMIT 1];
        System.assertEquals('Pending', t.Status__c);
    }

    @isTest static void getNAMById(){
        Test.startTest();
        Vessel__c vessel = VesselFactory.createVessel();
        NAM__c nam = NAMFactory.createNAM(vessel, 'NAM-MV24-20-001');
        Test.stopTest();

        NAM__c n = NamDAO.getById(nam.Id);
        System.assertEquals(nam.Id, n.Id);

        try{
            NAM__c nError = NamDAO.getById('a0g3I00000063q2QAA'); //invalid nam id
            System.assertEquals(null, nError);
        }catch (Exception e){ }
    }

    @isTest static void aggregateResultTest(){
        Test.startTest();
        Vessel__c vessel = VesselFactory.createVessel();
        NAM__c nam = NAMFactory.createNAM(vessel, 'NAM-MV24-20-001');
        Test.stopTest();

        Set<String> setVesselIds = new Set<String>{vessel.Id};
        AggregateResult[] a = NamDAO.getByYear('', setVesselIds);
        System.assertEquals(1, a.size());

    }

    @isTest static void getTest() 
    {
        ClassCoverage t = new ClassCoverage();
        t.declarar();
        t.declarar2();
        t.declarar3();
        t.declarar4();
    }
}