force-app/main/default/objects/Clarification__c/Clarification__c.object-meta.xml
<CustomObject>
    <label>Clarification</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Clarification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Clarification__c/fields/NAM__c.field-meta.xml
<CustomField>
    <fullName>NAM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NAM</label>
    <referenceTo>NAM__c</referenceTo>
    <relationshipLabel>Clarifications</relationshipLabel>
    <relationshipName>Clarifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Clarification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clarification__c/fields/Vessel__c.field-meta.xml
<CustomField>
    <fullName>Vessel__c</fullName>
    <formula>NAM__r.Vessel__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vessel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NAM__c/NAM__c.object-meta.xml
<CustomObject>
    <label>NAM</label>
    <nameField>
        <label>NAM Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NAMs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NAM__c/fields/ActionTaken__c.field-meta.xml
<CustomField>
    <fullName>ActionTaken__c</fullName>
    <label>Action Taken</label>
    <length>10000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/ActualAmountTotal__c.field-meta.xml
<CustomField>
    <fullName>ActualAmountTotal__c</fullName>
    <formula>ActualMdBAmount__c + ActualMINCAmount__c + ActualMIIAmount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Actual Amount Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/BRLAmount__c.field-meta.xml
<CustomField>
    <fullName>BRLAmount__c</fullName>
    <label>BRL Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/ClosedOutClarificationCreated__c.field-meta.xml
<CustomField>
    <fullName>ClosedOutClarificationCreated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Closed Out Clarification Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/MdBAmount__c.field-meta.xml
<CustomField>
    <fullName>MdBAmount__c</fullName>
    <inlineHelpText>Imported from 1nd WO</inlineHelpText>
    <label>MdB Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/MIIAmount__c.field-meta.xml
<CustomField>
    <fullName>MIIAmount__c</fullName>
    <inlineHelpText>Imported from 2nd WO</inlineHelpText>
    <label>MII Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/MINCAmount__c.field-meta.xml
<CustomField>
    <fullName>MINCAmount__c</fullName>
    <inlineHelpText>Imported from 3nd WO</inlineHelpText>
    <label>MINC Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <formula>IF(
    NOT(ISPICKVAL(Status__c, &apos;Approved&apos;)),
    &apos;NAM&apos;,
    &apos;Closed Out&apos;
)</formula>
    <label>Phase</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/RootCause__c.field-meta.xml
<CustomField>
    <fullName>RootCause__c</fullName>
    <label>Root Cause</label>
    <length>10000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AMC</fullName>
                <default>true</default>
                <label>AMC</label>
            </value>
            <value>
                <fullName>OM</fullName>
            </value>
            <value>
                <fullName>PEM</fullName>
            </value>
            <value>
                <fullName>Tech Team</fullName>
            </value>
            <value>
                <fullName>SPC Partners</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>SPC Modec</fullName>
                <isActive>false</isActive>
                <label>SPC Modec</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NAM__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/TypeEvent__c.field-meta.xml
<CustomField>
    <fullName>TypeEvent__c</fullName>
    <label>Type of Event</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accident</fullName>
            </value>
            <value>
                <fullName>Mechanical Failure</fullName>
            </value>
            <value>
                <fullName>Wear &amp; Tear</fullName>
            </value>
            <value>
                <fullName>Design Error</fullName>
            </value>
            <value>
                <fullName>Preventive</fullName>
            </value>
            <value>
                <fullName>Upgrade/Modification</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NAM__c/fields/Vessel__c.field-meta.xml
<CustomField>
    <fullName>Vessel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vessel</label>
    <referenceTo>Vessel__c</referenceTo>
    <relationshipLabel>NAMs</relationshipLabel>
    <relationshipName>NAMs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/WorkOrderPrimaryNumber__c.field-meta.xml
<CustomField>
    <fullName>WorkOrderPrimaryNumber__c</fullName>
    <label>Work Order Primary Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TechnicalMemberSupport__c/TechnicalMemberSupport__c.object-meta.xml
<CustomObject>
    <label>Technical Member Support</label>
    <nameField>
        <displayFormat>TTS-{00000}</displayFormat>
        <label>Technical Member Support  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Technical Members Supports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TechnicalMemberSupport__c/fields/NAM__c.field-meta.xml
<CustomField>
    <fullName>NAM__c</fullName>
    <label>NAM</label>
    <referenceTo>NAM__c</referenceTo>
    <relationshipLabel>Technical Members Supports</relationshipLabel>
    <relationshipName>TechTeamsSupports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TechnicalMemberSupport__c/fields/Responsible__c.field-meta.xml
<CustomField>
    <fullName>Responsible__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsible</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TechTeamsSupports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TechnicalMemberSupport__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Supported</fullName>
            </value>
            <value>
                <fullName>Not Supported</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vessel__c/Vessel__c.object-meta.xml
<CustomObject>
    <label>Vessel</label>
    <nameField>
        <label>Vessel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vessels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vessel__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Decommissioned</fullName>
            </value>
            <value>
                <fullName>EPCI</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>In Operation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vessel__c/fields/WOAttention__c.field-meta.xml
<CustomField>
    <fullName>WOAttention__c</fullName>
    <label>WO Attention</label>
    <length>31072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Vessel__c/fields/WOAttentionMINC__c.field-meta.xml
<CustomField>
    <fullName>WOAttentionMINC__c</fullName>
    <label>WO Attention MINC</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/ActionTaken__c.field-meta.xml
<CustomField>
    <fullName>ActionTaken__c</fullName>
    <label>Action Taken</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Material__c.field-meta.xml
<CustomField>
    <fullName>Material__c</fullName>
    <label>Material</label>
    <summarizedField>WorkOrderLineItem.Price__c</summarizedField>
    <summaryFilterItems>
        <field>WorkOrderLineItem.MS__c</field>
        <operation>equals</operation>
        <value>Material</value>
    </summaryFilterItems>
    <summaryForeignKey>WorkOrderLineItem.WorkOrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/NAM__c.field-meta.xml
<CustomField>
    <fullName>NAM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NAM</label>
    <referenceTo>NAM__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>WorkOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/PortionAmount__c.field-meta.xml
<CustomField>
    <fullName>PortionAmount__c</fullName>
    <label>Portion Amount</label>
    <summarizedField>WorkOrderLineItem.Price__c</summarizedField>
    <summaryForeignKey>WorkOrderLineItem.WorkOrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Responsible__c.field-meta.xml
<CustomField>
    <fullName>Responsible__c</fullName>
    <formula>Contractor__r.ShortName__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Responsible</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/RootCause__c.field-meta.xml
<CustomField>
    <fullName>RootCause__c</fullName>
    <label>Root Cause</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <summarizedField>WorkOrderLineItem.Price__c</summarizedField>
    <summaryFilterItems>
        <field>WorkOrderLineItem.MS__c</field>
        <operation>equals</operation>
        <value>Service</value>
    </summaryFilterItems>
    <summaryForeignKey>WorkOrderLineItem.WorkOrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <formula>PortionAmount__c +  MarkUpAmount__c +  TaxISS2__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/TotalBRL__c.field-meta.xml
<CustomField>
    <fullName>TotalBRL__c</fullName>
    <formula>PortionBRL__c +  TaxISS2BRL__c +  MarkupAmountBRL__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total BRL</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/WOAttention__c.field-meta.xml
<CustomField>
    <fullName>WOAttention__c</fullName>
    <label>WO Attention</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>WorkOrder__c</fullName>
    <externalId>true</externalId>
    <label>Work Order</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/WorkOrderPrimaryNumber__c.field-meta.xml
<CustomField>
    <fullName>WorkOrderPrimaryNumber__c</fullName>
    <label>WorkOrder Primary Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NamDAO.cls
public without sharing class NamDAO {
    public static NAM__c getById(String idNAM){
        List<NAM__c> lst = getById(new Set<String> {idNAM});
        if(lst.size() > 0) return lst[0];
        else return null;
    }
    public static List<NAM__c> getById(List<String> lstIds){
        Set<String> setString = new Set<String>(lstIds);
        return getById(setString);
    }
    public static List<NAM__c> getById(Set<String> idNAM){

        return [SELECT OwnerId, 
                        Owner.Email ,
                        ActualAmountTotal__c,
                        Owner.Name,
                        Subject__c,
                        Name,
                        Vessel__r.WOAttention__c,
                        Vessel__r.WOAttentionMINC__c,
                        MdbAmount__c,
                        MIIAmount__c,
						MINCAmount__c,
						Description__c,
						BRLAmount__c,
						ClosedOutClarificationCreated__c,
						TypeEvent__c,
						ActionTaken__c,
                        RootCause__c,
                        Phase__c,
                        WorkOrderPrimaryNumber__c,
                        Status__c,
                        (SELECT 
                            Id,
                            WorkOrder__c,
                            Responsible__c,
                            PortionAmount__c,
                            Service__c,
                            Material__c,
                            TotalBRL__c,
                            // TotalAmountWithoutTax__c,
                            // TotalAmountWithTax__c,
                            TotalAmount__c,
                            // MIITotal__c,
                            // MINCTotal__c
                            ContractTerm__c                        
                         FROM WorkOrders__r),
                        (SELECT 
							Id,
							Partner__c,
							Status__c,
							Type__c
                         FROM Clarifications__r),
                         (SELECT
                            Id,
                            Status__c,
                            Type__c,
                            Description__c
                         FROM TechTeamsSupports__r)
                FROM NAM__c 
                WHERE Id in: idNAM];
    }
    public static List<NAM__c> getByName(Set<String> setNames){
        return [
            SELECT  
                NAME,
                NameWithoutRevision__c
            FROM 
                NAM__c
            WHERE 
                NameWithoutRevision__c IN : setNames
        ];
    }
    public static AggregateResult[] getByYear(String year, Set<String> setVessel){

        return [SELECT 
                    Count(NAME) total,
                    Vessel__r.ShortName__c,
                    Vessel__c,
                    Year__c
                FROM 
                    NAM__c 
                WHERE 
                    Year__c =: year
                AND Vessel__c in : setVessel
                GROUP BY 
                    Year__c,
                    Vessel__c,
                    Vessel__r.ShortName__c];
    }
}