force-app/main/default/objects/Clarification__c/Clarification__c.object-meta.xml
<CustomObject>
    <label>Clarification</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Clarification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clarifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Clarification__c/fields/ClosedOutStatus__c.field-meta.xml
<CustomField>
    <fullName>ClosedOutStatus__c</fullName>
    <formula>Text(NAM__r.ClosedOutStatus__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Closed Out Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Clarification__c/fields/FinalComment__c.field-meta.xml
<CustomField>
    <fullName>FinalComment__c</fullName>
    <label>Final Comment</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Clarification__c/fields/NAM__c.field-meta.xml
<CustomField>
    <fullName>NAM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NAM</label>
    <referenceTo>NAM__c</referenceTo>
    <relationshipLabel>Clarifications</relationshipLabel>
    <relationshipName>Clarifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Clarification__c/fields/NAMStatus__c.field-meta.xml
<CustomField>
    <fullName>NAMStatus__c</fullName>
    <formula>TEXT(NAM__r.Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>NAM Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Clarification__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <label>Partner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mitsui</fullName>
            </value>
            <value>
                <fullName>Marubeni</fullName>
            </value>
            <value>
                <fullName>MOL</fullName>
            </value>
            <value>
                <fullName>MINC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clarification__c/fields/RejectReason__c.field-meta.xml
<CustomField>
    <fullName>RejectReason__c</fullName>
    <label>Reject Reason</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Clarification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clarification__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NAM</fullName>
            </value>
            <value>
                <fullName>Closed Out</fullName>
            </value>
            <value>
                <fullName>MINC</fullName>
                <isActive>false</isActive>
                <label>MINC</label>
            </value>
            <value>
                <fullName>MOL</fullName>
                <isActive>false</isActive>
                <label>MOL</label>
            </value>
            <value>
                <fullName>Marubeni</fullName>
                <isActive>false</isActive>
                <label>Marubeni</label>
            </value>
            <value>
                <fullName>Mitsui</fullName>
                <isActive>false</isActive>
                <label>Mitsui</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FinalClarification__c/FinalClarification__c.object-meta.xml
<CustomObject>
    <label>Final Clarification</label>
    <nameField>
        <displayFormat>CL-{000000}</displayFormat>
        <label>Final Partner Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Final Clarifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FinalClarification__c/fields/Clarification__c.field-meta.xml
<CustomField>
    <fullName>Clarification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clarification</label>
    <referenceTo>Clarification__c</referenceTo>
    <relationshipLabel>Final Clarifications</relationshipLabel>
    <relationshipName>FinalClarifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinalClarification__c/fields/FinalComment__c.field-meta.xml
<CustomField>
    <fullName>FinalComment__c</fullName>
    <label>Final Comment</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FinalClarification__c/fields/NAM__c.field-meta.xml
<CustomField>
    <fullName>NAM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NAM</label>
    <referenceTo>NAM__c</referenceTo>
    <relationshipLabel>Final Clarifications</relationshipLabel>
    <relationshipName>FinalClarifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FinalClarification__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <label>Partner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mitsui</fullName>
            </value>
            <value>
                <fullName>MOL</fullName>
            </value>
            <value>
                <fullName>Marubeni</fullName>
            </value>
            <value>
                <fullName>MINC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FinalClarification__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>Text(Clarification__r.Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NAM__c/NAM__c.object-meta.xml
<CustomObject>
    <label>NAM</label>
    <nameField>
        <label>NAM Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NAMs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NAM__c/fields/ClosedOutStatus__c.field-meta.xml
<CustomField>
    <fullName>ClosedOutStatus__c</fullName>
    <label>Closed Out Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Execution</fullName>
            </value>
            <value>
                <fullName>EM</fullName>
            </value>
            <value>
                <fullName>PEM</fullName>
            </value>
            <value>
                <fullName>Tech Team</fullName>
            </value>
            <value>
                <fullName>SPC Partners</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NAM__c/fields/MarubeniApprovalDate__c.field-meta.xml
<CustomField>
    <fullName>MarubeniApprovalDate__c</fullName>
    <label>Marubeni Approval Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/MarubeniClosedOutApprovalDate__c.field-meta.xml
<CustomField>
    <fullName>MarubeniClosedOutApprovalDate__c</fullName>
    <label>Marubeni Closed Out Approval Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/MarubeniClosedOutStatus__c.field-meta.xml
<CustomField>
    <fullName>MarubeniClosedOutStatus__c</fullName>
    <label>Marubeni Closed Out Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ClarificationStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/NAM__c/fields/MarubeniStatus__c.field-meta.xml
<CustomField>
    <fullName>MarubeniStatus__c</fullName>
    <label>Marubeni Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ClarificationStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/NAM__c/fields/MINCApprovalDate__c.field-meta.xml
<CustomField>
    <fullName>MINCApprovalDate__c</fullName>
    <label>MINC Approval Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/MINCStatus__c.field-meta.xml
<CustomField>
    <fullName>MINCStatus__c</fullName>
    <label>MINC Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ClarificationStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/NAM__c/fields/MitsuiApprovalDate__c.field-meta.xml
<CustomField>
    <fullName>MitsuiApprovalDate__c</fullName>
    <label>Mitsui Approval Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/MitsuiClosedOutApprovalDate__c.field-meta.xml
<CustomField>
    <fullName>MitsuiClosedOutApprovalDate__c</fullName>
    <label>Mitsui Closed Out Approval Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/MitsuiClosedOutStatus__c.field-meta.xml
<CustomField>
    <fullName>MitsuiClosedOutStatus__c</fullName>
    <label>Mitsui Closed Out Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ClarificationStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/NAM__c/fields/MitsuiStatus__c.field-meta.xml
<CustomField>
    <fullName>MitsuiStatus__c</fullName>
    <label>Mitsui Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ClarificationStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/NAM__c/fields/MOLApprovalDate__c.field-meta.xml
<CustomField>
    <fullName>MOLApprovalDate__c</fullName>
    <label>MOL Approval Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/MOLStatus__c.field-meta.xml
<CustomField>
    <fullName>MOLStatus__c</fullName>
    <label>MOL Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ClarificationStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/NAM__c/fields/NAMStatus__c.field-meta.xml
<CustomField>
    <fullName>NAMStatus__c</fullName>
    <formula>if(Text(ClosedOutStatus__c ) = &apos;Approved&apos;, IMAGE(&quot;/resource/nam_status/completed.png&quot; , &quot;Chat&quot;, 20,20 ), 
   if(Text(Status__c ) = &apos;Cancelled&apos;, IMAGE(&quot;/resource/nam_status/cancelled.png&quot;, &quot;Cancelled&quot;, 20,20 ), IMAGE(&quot;/resource/nam_status/pending1.png&quot;, &quot;In Progress&quot;, 20, 20))
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>NAM Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AMC</fullName>
                <default>true</default>
                <label>AMC</label>
            </value>
            <value>
                <fullName>OM</fullName>
            </value>
            <value>
                <fullName>PEM</fullName>
            </value>
            <value>
                <fullName>Tech Team</fullName>
            </value>
            <value>
                <fullName>SPC Partners</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>SPC Modec</fullName>
                <isActive>false</isActive>
                <label>SPC Modec</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPCRejectComment__c/SPCRejectComment__c.object-meta.xml
<CustomObject>
    <label>SPC Reject Comment</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>SPC Reject Comment  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPC Rejects Comments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPCRejectComment__c/fields/Clarification__c.field-meta.xml
<CustomField>
    <fullName>Clarification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clarification</label>
    <referenceTo>Clarification__c</referenceTo>
    <relationshipLabel>SPC Rejects Comments</relationshipLabel>
    <relationshipName>SPCRejectsComments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPCRejectComment__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <label>Comment</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SPCRejectComment__c/fields/NAM__c.field-meta.xml
<CustomField>
    <fullName>NAM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NAM</label>
    <referenceTo>NAM__c</referenceTo>
    <relationshipLabel>SPC Rejects Comments</relationshipLabel>
    <relationshipName>SPCRejectsComments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPCRejectComment__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <label>Partner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Marubeni</fullName>
            </value>
            <value>
                <fullName>Mitsui</fullName>
            </value>
            <value>
                <fullName>MOL</fullName>
            </value>
            <value>
                <fullName>MINC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPCRejectComment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>Text(Clarification__r.Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/ClarificationStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <masterLabel>ClarificationStatus</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ClarificationBO.cls
public without sharing class ClarificationBO {
    private static final ClarificationBO instance = new ClarificationBO();
	public static ClarificationBO getInstance() {
		return instance;
	}
    public void finalComments(List<Clarification__c> lst, Map<Id, Clarification__c> mapOld){
        List<FinalClarification__c> lstFinnalClarification = new List<FinalClarification__c>();
        List<SPCRejectComment__c> lstSPCRejectComment = new List<SPCRejectComment__c>();          
        Map<String, String> mapNAMReproved = new Map<String, String>();
        Set<String> setNAMApproved =  new Set<String>();
        Map<String, String> mapNAMvsStatus =  new Map<String, String>();

        Integer value = 0;

        for(Clarification__c clarification : lst){
            if(!String.IsBlank(clarification.FinalComment__c)){
                if((clarification.Type__c == 'NAM' && clarification.NAMStatus__c != 'SPC Partners') || (clarification.Type__c == 'Closed Out' && clarification.ClosedOutStatus__c != 'SPC Partners')){
                    clarification.addError('You only can edit the clarification when NAM record status is "SPC Partners"');
                    clarification.FinalComment__c = null;
                }
                else if(clarification.Status__c == 'Rejected'){
                    clarification.addError('You cannot Approve a Rejected record');
                    clarification.RejectReason__c = null;
                }
                else{
                    lstFinnalClarification.add(new FinalClarification__c(
                        Clarification__c = clarification.Id,
                        NAM__c = clarification.NAM__c,
                        FinalComment__c = clarification.FinalComment__c,
                        Partner__c = clarification.Partner__c
                    ) );
                    clarification.FinalComment__c = null;
                    clarification.Status__c = 'Approved';
                    setNAMApproved.add(clarification.NAM__c);
                }
            }
            if(!String.IsBlank(clarification.RejectReason__c)){
                if((clarification.Type__c == 'NAM' && clarification.NAMStatus__c != 'SPC Partners') || (clarification.Type__c == 'Closed Out' && clarification.ClosedOutStatus__c != 'SPC Partners')){
                    clarification.addError('You only can edit the clarification when NAM record status is "SPC Partners"');
                    // clarification.RejectReason__c = null;
                }
                else if(clarification.Status__c == 'Approved'){
                    clarification.addError('You cannot Reject an Approved record');
                    // clarification.RejectReason__c = null;
                }else{
                    lstSPCRejectComment.add(new SPCRejectComment__c(
                        Clarification__c = clarification.Id,
                        NAM__c = clarification.NAM__c,
                        Comment__c = clarification.RejectReason__c,
                        Partner__c = clarification.Partner__c
                    ) );
                    mapNAMReproved.put(clarification.NAM__c, clarification.RejectReason__c);
                    clarification.RejectReason__c = null;
                    clarification.Status__c = 'Rejected';
                }
            }
            if(mapOld != null && (clarification.Status__c != mapOld.get(clarification.Id).Status__c)){
                mapNAMvsStatus.put(clarification.Partner__c + '|' + clarification.Status__c + '|' + clarification.Type__c, clarification.NAM__c);
            }
        }
        System.debug('RejectComment - ' + lstSPCRejectComment);
        if(lstSPCRejectComment.size() > 0){ 
            insert lstSPCRejectComment;

            Map<Id ,NAM__c> mapNAM = new Map<Id,NAM__c>( NamDAO.getById(mapNAMReproved.keySet()));

            List<Clarification__c> lstClarificationUpdate = new List<Clarification__c>(); 
            for(SPCRejectComment__c comment :lstSPCRejectComment){
                NAM__c nam = mapNAM.get(comment.NAM__c);
                for(Clarification__c clarification : nam.Clarifications__r){
                    if(clarification.Id != comment.Clarification__c && clarification.Status__c == 'Approved'){
                        clarification.Status__c = 'Pending';
                        switch on clarification.Partner__c {
                            when  'Mitsui' {
                                nam.MitsuiStatus__c = 'Pending'; 
                                nam.MitsuiApprovalDate__c = null;
                            }
                            when 'Marubeni' {
                                nam.MarubeniStatus__c = 'Pending';
                                nam.MarubeniApprovalDate__c = null;
                            }
                            when 'MOL' {
                                nam.MOLStatus__c = 'Pending';
                                nam.MOLApprovalDate__c = null;                                
                            }
                            when else  {
                                nam.MINCStatus__c = 'Pending';
                                nam.MINCApprovalDate__c = null; 
                            }
                        }
                        lstClarificationUpdate.add(clarification);
                    }
                }
            }
            update lstClarificationUpdate;
            update mapNAM.values();

            List<Approval.ProcessWorkitemRequest> lstReq = new List<Approval.ProcessWorkitemRequest>();
            for(ProcessInstanceWorkitem workItem  : [Select p.Id, p.ProcessInstance.TargetObjectId From ProcessInstanceWorkitem p Where p.ProcessInstance.TargetObjectId In : mapNAMReproved.keySet()]){
                
                Approval.ProcessWorkitemRequest req = new Approval.ProcessWorkitemRequest();
                req.setComments(mapNAMReproved.get(workItem.ProcessInstance.TargetObjectId));
                req.setAction('Reject');
                req.setWorkitemId(workItem.Id);
                lstReq.add(req);
            }

            if(lstReq.size() > 0){
                System.debug('>>> lstReq.size() >>>' + lstReq.size());
                List<Approval.ProcessResult> result =  Approval.process(lstReq);
            }
        }
        System.debug('lstFinnalClarification - ' + lstFinnalClarification);
        if(lstFinnalClarification.size() > 0){
            insert lstFinnalClarification;
            Map<Id, NAM__c> mapNAM =  new Map<Id, NAM__c>(NamDAO.getById(setNAMApproved));
            Boolean allApproved = true;
            Set<Id> setNamApproval = new Set<Id>();
            System.debug('mapNAM - ' + mapNAM);
            for(FinalClarification__c finalClar : lstFinnalClarification){
                allApproved = true;
                for(Clarification__c clarification : mapNAM.get(finalClar.NAM__c).Clarifications__r){

                    if(mapNAM.get(finalClar.NAM__c).Status__c == 'Approved' &&  clarification.type__c == 'NAM') continue;
                    if(mapNAM.get(finalClar.NAM__c).Status__c != 'Approved' &&  clarification.type__c != 'NAM') continue;
                
                    if(clarification.Id != finalClar.Clarification__c &&  clarification.Status__c != 'Approved'){
                        allApproved = false;
                        System.debug('clarification - ' + clarification + ' - ' + clarification.Status__c );
                    }
                }
                if(allApproved) setNamApproval.add(finalClar.NAM__c);
                
            }
            if(setNamApproval.size()> 0 ){
                List<Approval.ProcessWorkitemRequest> lstReq = new List<Approval.ProcessWorkitemRequest>();
                for(ProcessInstanceWorkitem workItem  : [Select p.Id, p.ProcessInstance.TargetObjectId From ProcessInstanceWorkitem p Where p.ProcessInstance.TargetObjectId In : setNamApproval]){
                    
                    Approval.ProcessWorkitemRequest req = new Approval.ProcessWorkitemRequest();
                    req.setComments('Approved by SPC Partners');
                    req.setAction('Approve');
                    req.setWorkitemId(workItem.Id);
                    lstReq.add(req);
                }

                if(lstReq.size() > 0){
                    System.debug('>>> lstReq.size() >>>' + lstReq.size());
                    List<Approval.ProcessResult> result =  Approval.process(lstReq);
                }
            }
        }

        if(mapNAMvsStatus.size() > 0){
            Map<Id, NAM__c> mapNAM =  new Map<Id, NAM__c>(NamDAO.getById(mapNAMvsStatus.values()));
            NAM__c namEdit;
            for(string itemClarification : mapNAMvsStatus.keySet()){
                string partner = itemClarification.split('\\|')[0];
                string status = itemClarification.split('\\|')[1];
                string type = itemClarification.split('\\|')[2];
                namEdit = mapNAM.get(mapNAMvsStatus.get(itemClarification));
                switch on partner {
                    when 'Mitsui' {
                        if(type == 'NAM'){ 
                            namEdit.MitsuiStatus__c = status;
                            if(status == 'Approved') namEdit.MitsuiApprovalDate__c = Date.Today();
                        }        
                        else{ 
                            namEdit.MitsuiClosedOutStatus__c = status;
                            if(status == 'Approved') namEdit.MitsuiClosedOutApprovalDate__c = Date.Today();
                        }

                    }
                    when 'Marubeni' {
                        if(type == 'NAM'){ 
                            namEdit.MarubeniStatus__c = status; 
                            if(status == 'Approved') namEdit.MarubeniApprovalDate__c = Date.Today();    
                        }   
                        else{ 
                            namEdit.MarubeniClosedOutStatus__c = status;
                            if(status == 'Approved') namEdit.MarubeniClosedOutApprovalDate__c = Date.Today();                            
                        }
                    }
                    when 'MOL' {
                        if(type == 'NAM'){ 
                            namEdit.MOLStatus__c = status;
                            if(status == 'Approved') namEdit.MOLApprovalDate__c = Date.Today();    
                        }   
                        else{ 
                            namEdit.MOLClosedOutStatus__c = status;
                            if(status == 'Approved') namEdit.MOLClosedOutApprovalDate__c = Date.Today();                                
                        }
                    }
                    when else  {
                        if(type == 'NAM'){
                            namEdit.MINCStatus__c = status; 
                            if(status == 'Approved') namEdit.MINCApprovalDate__c = Date.Today();    
                        }       
                        else{
                            namEdit.MINCClosedOutStatus__c = status; 
                            if(status == 'Approved') namEdit.MINCClosedOutApprovalDate__c = Date.Today();
                        }                       
                    }
                }
            }
            update mapNAM.values();
        }
    }
}