force-app/main/default/objects/Account/fields/RegimeExclusivo__c.field-meta.xml
<CustomField>
    <fullName>RegimeExclusivo__c</fullName>
    <label>Local Content Regime</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Exclusive Regime</fullName>
            </value>
            <value>
                <fullName>Mixed Regime</fullName>
            </value>
            <value>
                <fullName>Non-Exclusive Regime</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_CNPJ__c.field-meta.xml
<CustomField>
    <fullName>TW1_CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_Company_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>TW1_Company_Email_Address__c</fullName>
    <label>Company Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_Contact_email_address__c.field-meta.xml
<CustomField>
    <fullName>TW1_Contact_email_address__c</fullName>
    <label>Contact email address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>TW1_Contact_Name__c</fullName>
    <label>Contact Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>TW1_Contact_Phone__c</fullName>
    <label>Contact Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_Country__c.field-meta.xml
<CustomField>
    <fullName>TW1_Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>Senegal</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia-Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Brunei</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Burkina</fullName>
            </value>
            <value>
                <fullName>Burma</fullName>
            </value>
            <value>
                <fullName>Burundi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_CPF__c.field-meta.xml
<CustomField>
    <fullName>TW1_CPF__c</fullName>
    <label>CPF</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_Supplier_Type__c.field-meta.xml
<CustomField>
    <fullName>TW1_Supplier_Type__c</fullName>
    <label>Supplier Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BANK</fullName>
            </value>
            <value>
                <fullName>GOVERNMENT OFFICE</fullName>
            </value>
            <value>
                <fullName>INDIRECTLY AFFILIATED COMPANY</fullName>
            </value>
            <value>
                <fullName>INDIVIDUAL REAL ESTATE OWNER</fullName>
            </value>
            <value>
                <fullName>LAW FIRM</fullName>
            </value>
            <value>
                <fullName>MUNICIPALITY</fullName>
            </value>
            <value>
                <fullName>NON-PROFIT PROFESSIONAL TRADE ORGANIZATION</fullName>
            </value>
            <value>
                <fullName>OTHER</fullName>
            </value>
            <value>
                <fullName>STATE UNIVERSITY</fullName>
            </value>
            <value>
                <fullName>TAX/AUDIT FIRM</fullName>
            </value>
            <value>
                <fullName>TAXING AUTHORITY</fullName>
            </value>
            <value>
                <fullName>UTILITY PROVIDER</fullName>
            </value>
            <value>
                <fullName>WORLDWIDE TRANSPORTATION</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_Trade_Name__c.field-meta.xml
<CustomField>
    <fullName>TW1_Trade_Name__c</fullName>
    <label>Trade Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW2_Ninea__c.field-meta.xml
<CustomField>
    <fullName>TW2_Ninea__c</fullName>
    <label>Ninea</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW3_From_Portal__c.field-meta.xml
<CustomField>
    <fullName>TW3_From_Portal__c</fullName>
    <label>From Portal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Senegal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/TW3_Taxpayer_Identification__c.field-meta.xml
<CustomField>
    <fullName>TW3_Taxpayer_Identification__c</fullName>
    <label>Taxpayer Identification</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/TW1_Vendor_Not_Homologated.recordType-meta.xml
<RecordType>
    <fullName>TW1_Vendor_Not_Homologated</fullName>
    <active>true</active>
    <label>Supplier Not Homologated</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/TW3_Supplier_Not_Homologated_Senegal.recordType-meta.xml
<RecordType>
    <fullName>TW3_Supplier_Not_Homologated_Senegal</fullName>
    <active>true</active>
    <label>Supplier Not Homologated - Senegal</label>
</RecordType>

force-app/main/default/objects/TW1_Category__c/TW1_Category__c.object-meta.xml
<CustomObject>
    <label>Category</label>
    <nameField>
        <displayFormat>CT{000000}</displayFormat>
        <label>Category Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Category__c/fields/TW1_Category__c.field-meta.xml
<CustomField>
    <fullName>TW1_Category__c</fullName>
    <label>Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Category__c/fields/TW1_Category_EN__c.field-meta.xml
<CustomField>
    <fullName>TW1_Category_EN__c</fullName>
    <label>Category (EN)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Category__c/fields/TW1_Country__c.field-meta.xml
<CustomField>
    <fullName>TW1_Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Category__c/fields/TW1_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>TW1_Sub_Category__c</fullName>
    <label>Sub-Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Category__c/fields/TW1_SUB_CATEGORY_EN__c.field-meta.xml
<CustomField>
    <fullName>TW1_SUB_CATEGORY_EN__c</fullName>
    <label>Sub Categoria (EN)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Category__c/fields/TW3_Category_FR__c.field-meta.xml
<CustomField>
    <fullName>TW3_Category_FR__c</fullName>
    <label>Category (FR)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Category__c/fields/TW3_Sub_Categoria_FR__c.field-meta.xml
<CustomField>
    <fullName>TW3_Sub_Categoria_FR__c</fullName>
    <label>Sub Categoria (FR)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Category__c/recordTypes/TW1_Service.recordType-meta.xml
<RecordType>
    <fullName>TW1_Service</fullName>
    <active>true</active>
    <label>Service</label>
</RecordType>

force-app/main/default/objects/TW1_Vendor_Category__c/TW1_Vendor_Category__c.object-meta.xml
<CustomObject>
    <description>Antigo Vendor category</description>
    <label>Supplier Category</label>
    <nameField>
        <displayFormat>VC{00000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suppliers Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Vendor_Category__c/fields/TW1_Category__c.field-meta.xml
<CustomField>
    <fullName>TW1_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <referenceTo>TW1_Category__c</referenceTo>
    <relationshipName>Vendors_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Vendor_Category__c/fields/TW1_Vendor__c.field-meta.xml
<CustomField>
    <fullName>TW1_Vendor__c</fullName>
    <label>Supplier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Suppliers Categories</relationshipLabel>
    <relationshipName>Vendors_Categories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/T_MODEC_SenegalCadastroApp.cls
/**
 * @File Name          : T_MODEC_SenegalCadastroApp.cls
 * @Description        :
 * @Author             : Rafael Hadama
 * @Group              :
 * @Last Modified By   : Rafael Hadama
 * @Last Modified On   : 10-23-2020
 * @Modification Log   :
 * Ver       Date            Author              Modification
 * 1.0    01/07/2020   Rafael Hadama     Initial Version
 **/
public without sharing class T_MODEC_SenegalCadastroApp {
    T_MODEC_Category_Rep categoryRep = new T_MODEC_Category_Rep();
    T_MODEC_Account_REP accountRep   = new T_MODEC_Account_REP();

    public void CriarFornecedor(T_MODEC_SenegalCadastroCtrl.CadastroFornecedorDto cadastroFornecedorDto)
    {
        system.debug('TipoFornecedor >>' + cadastroFornecedorDto.TipoFornecedor);
        Account conta = new Account();

        string recordtypeSenegal = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('TW3_Supplier_Not_Homologated_Senegal').getRecordTypeId();
        //RecordType recordTypeAccount = [Select id from RecordType where DeveloperName = 'TW1_Vendor_Not_Homologated'];

        //TW1_CNPJ__c / TW1_CPF__c
        conta.Name = cadastroFornecedorDto.NomeEmpresa;

        conta.TW2_Ninea__c = cadastroFornecedorDto.CpfCnpj;
        conta.TW3_Taxpayer_Identification__c = cadastroFornecedorDto.TaxPayerNumber;

        conta.TW1_Trade_Name__c            = cadastroFornecedorDto.NomeFantasia;
        conta.TW1_Company_Email_Address__c = cadastroFornecedorDto.Email;
        conta.TW1_Supplier_Type__c         = cadastroFornecedorDto.TipoFornecedor;
        conta.BillingStreet  = cadastroFornecedorDto.Endereco;
        conta.BillingCity    = cadastroFornecedorDto.Cidade;
        conta.BillingState   = cadastroFornecedorDto.Estado;
        conta.BillingCountry = cadastroFornecedorDto.Pais;
        system.debug('BillingCountry >' + cadastroFornecedorDto.Pais);
        conta.TW1_Country__c = cadastroFornecedorDto.Pais;
        system.debug('Country >' + conta.TW1_Country__c);
        conta.TW1_Contact_Name__c          = cadastroFornecedorDto.ContatoResponsavel;
        conta.TW1_Contact_Phone__c         = cadastroFornecedorDto.ContatoTelefone;
        conta.TW1_Contact_email_address__c = cadastroFornecedorDto.ContatoEmail;
        conta.RegimeExclusivo__c           = cadastroFornecedorDto.RegimeExclusivo;
        conta.RecordTypeId       = recordtypeSenegal;
        conta.TW3_From_Portal__c = 'Senegal';
        insert conta;
        system.debug('conta >' + conta);
        List<TW1_Vendor_Category__c> lstCategorias = new List<TW1_Vendor_Category__c> ();
        for (T_MODEC_SenegalCadastroCtrl.CategoriaDTO categoriaDto : cadastroFornecedorDto.CategoriasSelecionadas.values())
        {
            system.debug('categoriaDto >' + categoriaDto);
            TW1_Vendor_Category__c categoria = new TW1_Vendor_Category__c();
            categoria.TW1_Vendor__c   = conta.Id;
            categoria.TW1_Category__c = categoriaDto.value;
            lstCategorias.add(categoria);
        }

        insert lstCategorias;
        system.debug('lstCategorias >' + lstCategorias);
    }

    public Map<string, Map<String, T_MODEC_SenegalCadastroCtrl.CategoriaDTO> > montarListaCategoriasDTO()
    {
        Map<string, Map<String, T_MODEC_SenegalCadastroCtrl.CategoriaDTO> > mapCategorias = new Map<string, Map<String, T_MODEC_SenegalCadastroCtrl.CategoriaDTO> >();

        list<TW1_Category__c> listaCategorias = categoryRep.getAllCategories();

        //Criando map a ser preenchido

        for (TW1_Category__c cat:listaCategorias)
        {
            Map<String, T_MODEC_SenegalCadastroCtrl.CategoriaDTO> mapDTO = mapCategorias.get(cat.RecordType.DeveloperName);

            if (mapDTO == null)
            {
                mapDTO = new Map<String, T_MODEC_SenegalCadastroCtrl.CategoriaDTO>();
            }


            T_MODEC_SenegalCadastroCtrl.CategoriaDTO categoriaDTO = new T_MODEC_SenegalCadastroCtrl.CategoriaDTO();
            if (cat.RecordType.DeveloperName != 'TW1_Service')
            {
                categoriaDTO.label   = cat.TW1_Category__c;
                categoriaDTO.labelEN = cat.TW1_Category_EN__c;
                categoriaDTO.labelFR = cat.TW3_Category_FR__c;
            }
            else
            {
                categoriaDTO.label   = cat.TW1_Sub_Category__c;
                categoriaDTO.labelEN = cat.TW1_SUB_CATEGORY_EN__c;
                categoriaDTO.labelFR = cat.TW3_Sub_Categoria_FR__c;
            }

            //Map here the translation fields.
            //TW1_SUB_CATEGORY_EN__c, TW1_Category_EN__c, TW3_Category_FR__c, TW3_Sub_Categoria_FR__c
            //labelFR , labelEN
            categoriaDTO.value = cat.Id;
            mapDTO.put(cat.Id, categoriaDTO);
            mapCategorias.put(cat.RecordType.DeveloperName, mapDTO);
        }

        return mapCategorias;
    }
}