force-app/main/default/objects/Account/fields/ShortName__c.field-meta.xml
<CustomField>
    <fullName>ShortName__c</fullName>
    <label>Short Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_CNPJ__c.field-meta.xml
<CustomField>
    <fullName>TW1_CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountFactory.cls
public class AccountFactory {
    public static Account insertAcc(string recordTypeId, string shortName){
        Account acc = new Account(Name = 'MODEC ' + shortName, 
                                    RecordTypeId = recordTypeId, 
                                    TW1_CNPJ__c = '48855909000158',
                                    ShortName__c = shortName);
         insert acc;
         return acc;
    }
}