force-app/main/default/objects/Account/fields/ShortName__c.field-meta.xml
<CustomField>
    <fullName>ShortName__c</fullName>
    <label>Short Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Business.recordType-meta.xml
<RecordType>
    <fullName>Business</fullName>
    <active>true</active>
    <label>Business</label>
</RecordType>

force-app/main/default/objects/Vessel__c/Vessel__c.object-meta.xml
<CustomObject>
    <label>Vessel</label>
    <nameField>
        <label>Vessel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vessels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vessel__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vessel__c/fields/FieldLocation__c.field-meta.xml
<CustomField>
    <fullName>FieldLocation__c</fullName>
    <label>Field Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vessel__c/fields/ShortName__c.field-meta.xml
<CustomField>
    <fullName>ShortName__c</fullName>
    <label>Short Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vessel__c/fields/SPC__c.field-meta.xml
<CustomField>
    <fullName>SPC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SPC</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vessels</relationshipLabel>
    <relationshipName>Vessels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vessel__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Decommissioned</fullName>
            </value>
            <value>
                <fullName>EPCI</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>In Operation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vessel__c/fields/WOAttention__c.field-meta.xml
<CustomField>
    <fullName>WOAttention__c</fullName>
    <label>WO Attention</label>
    <length>31072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/VesselFactory.cls
public  class VesselFactory {
    public static Vessel__c createVessel() {

        Vessel__c vessel = new Vessel__c(
                        Name = 'FPSO MV24',
                        ShortName__c = 'MV24',
                        Status__c = 'In Operation',
                        SPC__c = AccountFactory.insertAcc(Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business').getRecordTypeId(), '').Id,
                        WOAttention__c = 'WO Attention',
                        Country__c = 'Brazil',
                        FieldLocation__c = 'Iracema Sul area');
        insert vessel;
        return vessel;       
    }
}