force-app/main/default/objects/Account/fields/T_Quantity_of_Service_Supplier_Category__c.field-meta.xml
<CustomField>
    <fullName>T_Quantity_of_Service_Supplier_Category__c</fullName>
    <description>Number of supplier category records of type service.</description>
    <inlineHelpText>Number of supplier category records of type service.</inlineHelpText>
    <label>Quantity of Service Supplier Category</label>
    <summaryFilterItems>
        <field>TW1_Vendor_Category__c.T_Category_Type__c</field>
        <operation>equals</operation>
        <value>Service</value>
    </summaryFilterItems>
    <summaryForeignKey>TW1_Vendor_Category__c.TW1_Vendor__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/T_QuantityMaterialSupplierCategory__c.field-meta.xml
<CustomField>
    <fullName>T_QuantityMaterialSupplierCategory__c</fullName>
    <label>Quantity of Material Supplier Category</label>
    <summaryFilterItems>
        <field>TW1_Vendor_Category__c.T_Category_Type__c</field>
        <operation>equals</operation>
        <value>Material</value>
    </summaryFilterItems>
    <summaryForeignKey>TW1_Vendor_Category__c.TW1_Vendor__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_CNPJ__c.field-meta.xml
<CustomField>
    <fullName>TW1_CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_Shelf_Life_Vetting_Date__c.field-meta.xml
<CustomField>
    <fullName>TW1_Shelf_Life_Vetting_Date__c</fullName>
    <label>Vetting expiration date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_Supplier_Type__c.field-meta.xml
<CustomField>
    <fullName>TW1_Supplier_Type__c</fullName>
    <label>Supplier Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BANK</fullName>
            </value>
            <value>
                <fullName>GOVERNMENT OFFICE</fullName>
            </value>
            <value>
                <fullName>INDIRECTLY AFFILIATED COMPANY</fullName>
            </value>
            <value>
                <fullName>INDIVIDUAL REAL ESTATE OWNER</fullName>
            </value>
            <value>
                <fullName>LAW FIRM</fullName>
            </value>
            <value>
                <fullName>MUNICIPALITY</fullName>
            </value>
            <value>
                <fullName>NON-PROFIT PROFESSIONAL TRADE ORGANIZATION</fullName>
            </value>
            <value>
                <fullName>OTHER</fullName>
            </value>
            <value>
                <fullName>STATE UNIVERSITY</fullName>
            </value>
            <value>
                <fullName>TAX/AUDIT FIRM</fullName>
            </value>
            <value>
                <fullName>TAXING AUTHORITY</fullName>
            </value>
            <value>
                <fullName>UTILITY PROVIDER</fullName>
            </value>
            <value>
                <fullName>WORLDWIDE TRANSPORTATION</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_Vendor_Vetting__c.field-meta.xml
<CustomField>
    <fullName>TW1_Vendor_Vetting__c</fullName>
    <defaultValue>&quot;Vetting Not Requested&quot;</defaultValue>
    <label>Vendor Vetting</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>No Registered</fullName>
            </value>
            <value>
                <fullName>Ongoing</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Vetting Not Requested</fullName>
            </value>
            <value>
                <fullName>Vetting Rejected</fullName>
            </value>
            <value>
                <fullName>Vetting Approved with Red Flag</fullName>
            </value>
            <value>
                <fullName>Vetting Approved</fullName>
            </value>
            <value>
                <fullName>Vetting Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/TW1_Vendor_Homologated.recordType-meta.xml
<RecordType>
    <fullName>TW1_Vendor_Homologated</fullName>
    <active>true</active>
    <label>Supplier Homologated</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/TW1_Vendor_Not_Homologated.recordType-meta.xml
<RecordType>
    <fullName>TW1_Vendor_Not_Homologated</fullName>
    <active>true</active>
    <label>Supplier Not Homologated</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/TW3_Supplier_Homologated_Senegal.recordType-meta.xml
<RecordType>
    <fullName>TW3_Supplier_Homologated_Senegal</fullName>
    <active>true</active>
    <label>Supplier Homologated - Senegal</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/TW3_Supplier_Not_Homologated_Senegal.recordType-meta.xml
<RecordType>
    <fullName>TW3_Supplier_Not_Homologated_Senegal</fullName>
    <active>true</active>
    <label>Supplier Not Homologated - Senegal</label>
</RecordType>

force-app/main/default/objects/TW1_Category__c/TW1_Category__c.object-meta.xml
<CustomObject>
    <label>Category</label>
    <nameField>
        <displayFormat>CT{000000}</displayFormat>
        <label>Category Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Category__c/fields/TW1_Category__c.field-meta.xml
<CustomField>
    <fullName>TW1_Category__c</fullName>
    <label>Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Category__c/fields/TW1_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>TW1_Sub_Category__c</fullName>
    <label>Sub-Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Category__c/recordTypes/TW1_Material.recordType-meta.xml
<RecordType>
    <fullName>TW1_Material</fullName>
    <active>true</active>
    <label>Material</label>
</RecordType>

force-app/main/default/objects/TW1_Category__c/recordTypes/TW1_Service.recordType-meta.xml
<RecordType>
    <fullName>TW1_Service</fullName>
    <active>true</active>
    <label>Service</label>
</RecordType>

force-app/main/default/objects/TW1_Request__c/TW1_Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>REQ{000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Supplier_Type__c.field-meta.xml
<CustomField>
    <fullName>TW1_Supplier_Type__c</fullName>
    <formula>TEXT(TW1_Vendor__r.TW1_Supplier_Type__c)</formula>
    <label>Supplier Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Vendor__c.field-meta.xml
<CustomField>
    <fullName>TW1_Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4) OR (6 AND (5 OR 7))</booleanFilter>
        <errorMessage>Make sure the selected vendor is already homologated or not.</errorMessage>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>BM, Contract - New Contract, Contract - Amendment, Material Packing List (Third-party), Inspection</value>
        </filterItems>
        <filterItems>
            <field>Account.TW1_Vendor_Vetting__c</field>
            <operation>equals</operation>
            <value>Active, No Registered, Ongoing, Blocked, Vetting Not Requested, Vetting Rejected, Vetting Approved with Red Flag, Vetting Approved, Vetting Expired</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vendor Vetting, Vendor Vetting - Senegal</value>
        </filterItems>
        <filterItems>
            <field>Account.TW1_Vendor_Vetting__c</field>
            <operation>equals</operation>
            <value>Active, No Registered, Ongoing, Blocked, Vetting Not Requested, Vetting Rejected, Vetting Approved with Red Flag, Vetting Approved, Vetting Expired</value>
        </filterItems>
        <filterItems>
            <field>Account.TW1_Step_Owner__c</field>
            <operation>equals</operation>
            <valueField>$User.Id</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>PO Review Form</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator, VV Team</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/recordTypes/TW1_Vendor_Vetting.recordType-meta.xml
<RecordType>
    <fullName>TW1_Vendor_Vetting</fullName>
    <active>true</active>
    <label>Vendor Vetting</label>
</RecordType>

force-app/main/default/objects/TW1_Vendor_Category__c/TW1_Vendor_Category__c.object-meta.xml
<CustomObject>
    <description>Antigo Vendor category</description>
    <label>Supplier Category</label>
    <nameField>
        <displayFormat>VC{00000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suppliers Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Vendor_Category__c/fields/TW1_Category__c.field-meta.xml
<CustomField>
    <fullName>TW1_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <referenceTo>TW1_Category__c</referenceTo>
    <relationshipName>Vendors_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Vendor_Category__c/fields/TW1_Vendor__c.field-meta.xml
<CustomField>
    <fullName>TW1_Vendor__c</fullName>
    <label>Supplier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Suppliers Categories</relationshipLabel>
    <relationshipName>Vendors_Categories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/T_MODEC_Account_REP.cls
/**
 * @File Name          : T_MODEC_Account_REP.cls
 * @Description        : 
 * @Author             : Mario Oliveira
 * @Group              : 
 * @Last Modified By   : Rafael Hadama
 * @Last Modified On   : 29/01/2020 15:09:32
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    06/11/2019   Mario Oliveira     Initial Version
**/
public class T_MODEC_Account_REP {
    
    /**
    * @description Buscando categorias relacionadas a conta do fornecedor que não estão homelogadas.
    * @author Mario Oliveira | 06/11/2019 
    * @param accountId referente a TW1_Request__c com recordtype - TW1_Vendor_Vetting
    * @return list<TW1_Vendor_Category__c> 
    **/
    private static Id RTAccountSupplierHomologated;
    private static Id RTAccountSupplierHomologatedSenegal;
    private static Id RTAccountSupplierNotHomologated;
    private static Id RTAccountSupplierNotHomologatedSenegal;
    
    private static Id VendorVettingActive;    
    
    public static List<Schema.PicklistEntry> getPicklistVendorVetting(String apiFieldName){   
        List<Schema.PicklistEntry> entries;
        if(apiFieldName == 'TW1_Vendor_Vetting__c'){
            entries = Account.TW1_Vendor_Vetting__c.getDescribe().getPicklistValues();
        }
		List<Schema.PicklistEntry> activeEntries = new List<Schema.PicklistEntry>();
    	for (Schema.PicklistEntry entry : entries) {
        	if (entry.isActive()) {                
            	activeEntries.add(entry);
        	}
    	}
        return activeEntries;
    }    
    
    private static void getRecordTypes(){
        RTAccountSupplierHomologated = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('TW1_Vendor_Homologated').getRecordTypeId();
        //RTAccountSupplierHomologatedSenegal = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('TW3_Supplier_Homologated_Senegal').getRecordTypeId();
        RTAccountSupplierNotHomologated = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('TW1_Vendor_Not_Homologated').getRecordTypeId();
        //RTAccountSupplierNotHomologatedSenegal = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('TW3_Supplier_Not_Homologated_Senegal').getRecordTypeId();
    }
    
    public static list<TW1_Vendor_Category__c> getVendorCategoryById(String accountId){ 
        return [SELECT id, Name, TW1_VEndor__c, TW1_Category__c, TW1_Category__r.TW1_Category__c, TW1_Category__r.TW1_Sub_Category__c
                FROM TW1_Vendor_Category__c
                WHERE TW1_VEndor__c =: accountId];
    }

    public static list<Account> buscarContasExpiradas(){ 
        return [SELECT id, Name, TW1_Shelf_Life_Vetting_Date__c, RecordType.developerName
                FROM Account
                WHERE TW1_Shelf_Life_Vetting_Date__c < TODAY AND RecordType.developerName = 'TW1_Vendor_Homologated'];
    }
    
    public list<Account> SearchAccountByCNPJ(string cnpj){
        return [SELECT id, Name, TW1_CNPJ__c
                FROM Account
                WHERE TW1_CNPJ__c =:cnpj];
    }
    
    public static List<Account> getSuppliersByNameAndCategoryType(String name, String categoryType, String vendorVetting){
        List<Account> retorno = new List<Account>();
        
        try {
            String soql = 'select id, Name, TW1_CNPJ__c, TW1_Supplier_Type__c, TW1_Vendor_Vetting__c from Account where Id != null ';
            
            IF(name != null && name != ''){
                soql += 'and Name like \'%'+name+'%\' ';
            }
            
            IF(categoryType == 'TW1_Service'){
                soql += 'and T_Quantity_of_Service_Supplier_Category__c > 0 ';
            } else if(categoryType == 'TW1_Material'){
                soql += 'and T_QuantityMaterialSupplierCategory__c > 0 ';
            }
            
            IF(vendorVetting != null && vendorVetting != '') {
                soql += 'and TW1_Vendor_Vetting__c like \'%'+vendorVetting+'%\' ';
            }
            
            getRecordTypes();
            soql += 'and (';
            soql += 'RecordTypeId = \''+ RTAccountSupplierHomologated + '\' or ';
            //soql += 'RecordTypeId = \''+ RTAccountSupplierHomologatedSenegal + '\' or ';
            soql += 'RecordTypeId = \''+ RTAccountSupplierNotHomologated + '\'';
            //soql += 'RecordTypeId = \''+ RTAccountSupplierNotHomologatedSenegal + '\'';
            soql += ') ';
            soql += 'order by Name asc ';
            soql += 'limit 10000';
            
            retorno = Database.query(soql);
        } catch(Exception e) {
            retorno = null;
            System.debug('Error - T_MODEC_Account_REP.class - Method: getSuppliersByNameAndCategoryType() - Description error: '+e.getMessage());
        }
        return retorno;
    }
    
    public static List<Account> getSuppliersByCategoryAndSubCategory(String category, String SubCategory, String vendorVetting){
        List<Account> retorno = new List<Account>();
        
        try {            
            String soql = 'select id, Name, TW1_CNPJ__c, TW1_Supplier_Type__c, TW1_Vendor_Vetting__c from Account ';
            
            soql += 'where Id IN (SELECT TW1_Vendor__c FROM TW1_Vendor_Category__c where id != null ';
            
            IF(category != null && category != '') {
                soql += 'and TW1_Category__r.TW1_Category__c like \'%'+category+'%\' ';
            }
            
            IF(SubCategory != null && SubCategory != ''){
                soql += ' and TW1_Category__r.TW1_Sub_Category__c like \'%'+SubCategory+'%\' ';
            }      
            
            soql += ') ';
            
            IF(vendorVetting != null && vendorVetting != '') {
                soql += 'and TW1_Vendor_Vetting__c like \'%'+vendorVetting+'%\' ';
            }
            
            getRecordTypes();
            soql += 'and (';
            soql += 'RecordTypeId = \''+ RTAccountSupplierHomologated + '\' or ';
            //soql += 'RecordTypeId = \''+ RTAccountSupplierHomologatedSenegal + '\' or ';
            soql += 'RecordTypeId = \''+ RTAccountSupplierNotHomologated + '\'';
            //soql += 'RecordTypeId = \''+ RTAccountSupplierNotHomologatedSenegal + '\'';
            soql += ') ';
            soql += 'order by Name asc ';
            soql += ' limit 10000';
            
            retorno = Database.query(soql);
            
        } catch(Exception e) {
            retorno = null;
            System.debug('Error - T_MODEC_Account_REP.class - Method: getSuppliersByCategoryAndSubCategory() - Description error: '+e.getMessage());
        }
        return retorno;
    }
}