force-app/main/default/objects/Account/fields/TCF_HSEQResponsibleEmail__c.field-meta.xml
<CustomField>
    <fullName>TCF_HSEQResponsibleEmail__c</fullName>
    <label>HSEQ Responsible Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_CNPJ__c.field-meta.xml
<CustomField>
    <fullName>TW1_CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_Contact_email_address__c.field-meta.xml
<CustomField>
    <fullName>TW1_Contact_email_address__c</fullName>
    <label>Contact email address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>TW1_Contact_Name__c</fullName>
    <label>Contact Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>TW1_Contact_Phone__c</fullName>
    <label>Contact Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_CPF__c.field-meta.xml
<CustomField>
    <fullName>TW1_CPF__c</fullName>
    <label>CPF</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_Shelf_Life_Vetting_Date__c.field-meta.xml
<CustomField>
    <fullName>TW1_Shelf_Life_Vetting_Date__c</fullName>
    <label>Vetting expiration date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_Step_Owner__c.field-meta.xml
<CustomField>
    <fullName>TW1_Step_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Step Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Supplier</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/TW1_Vendor_Homologated.recordType-meta.xml
<RecordType>
    <fullName>TW1_Vendor_Homologated</fullName>
    <active>true</active>
    <label>Supplier Homologated</label>
</RecordType>

force-app/main/default/objects/TOBJ_Participants__c/TOBJ_Participants__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>PN-{YYYY}{MM}-{0000}</displayFormat>
        <label>Nome do Participante</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TOBJ_Participants__c/fields/RequiredSendEmail__c.field-meta.xml
<CustomField>
    <fullName>RequiredSendEmail__c</fullName>
    <formula>TEXT(Warning__r.RequiredSendEmail__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Necessita envio de e-mail?</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TOBJ_Participants__c/fields/TCF_Supplier__c.field-meta.xml
<CustomField>
    <fullName>TCF_Supplier__c</fullName>
    <label>Fornecedor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>TRN_ParticipantsAccount</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TOBJ_Participants__c/fields/Warning__c.field-meta.xml
<CustomField>
    <fullName>Warning__c</fullName>
    <label>Warning</label>
    <referenceTo>TOBJ_Warning__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>TRN_ParticipantsWarning</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TOBJ_Warning__c/TOBJ_Warning__c.object-meta.xml
<CustomObject>
    <label>Warning</label>
    <nameField>
        <displayFormat>WARN-{00000000}</displayFormat>
        <label>Nome do Aviso</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Warning</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/TOBJ_Warning__c/fields/PublicationDate__c.field-meta.xml
<CustomField>
    <fullName>PublicationDate__c</fullName>
    <label>Data de publicação</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TOBJ_Warning__c/fields/RequiredSendEmail__c.field-meta.xml
<CustomField>
    <fullName>RequiredSendEmail__c</fullName>
    <label>Requer envio de e-mail?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TOBJ_Warning__c/fields/TCF_DueDate__c.field-meta.xml
<CustomField>
    <fullName>TCF_DueDate__c</fullName>
    <label>Data de vencimento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TOBJ_Warning__c/fields/TCF_HSEQWarning__c.field-meta.xml
<CustomField>
    <fullName>TCF_HSEQWarning__c</fullName>
    <label>Comunicado HSEQ?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TOBJ_Warning__c/fields/TCF_Notice__c.field-meta.xml
<CustomField>
    <fullName>TCF_Notice__c</fullName>
    <label>Notícia</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/TOBJ_Warning__c/fields/TCF_RequiresConfirmation__c.field-meta.xml
<CustomField>
    <fullName>TCF_RequiresConfirmation__c</fullName>
    <label>Requer confirmação?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TOBJ_Warning__c/fields/TCF_Subject__c.field-meta.xml
<CustomField>
    <fullName>TCF_Subject__c</fullName>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/T_WarningApp_TST.cls
@isTest
public class T_WarningApp_TST {

    Private static Id vendorHomologated = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('TW1_Vendor_Homologated').getRecordTypeId();
    
    @TestSetup
    public static void TestSetup(){
        Account acc = new Account();
        acc.RecordTypeId = vendorHomologated;
        acc.TW1_CNPJ__c = '00151720000158';
        acc.TW1_CPF__c = '17582277023';
        acc.Name = 'TestAcc HPB';
        acc.TW1_Contact_Name__c = 'TestCont HPB';
        acc.TW1_Contact_Phone__c = '(11) 1 1111-1111';
        acc.TW1_Contact_email_address__c = 'test@test.com.br';
        acc.TCF_HSEQResponsibleEmail__c = 'test@test.com.br';
        acc.TW1_Shelf_Life_Vetting_Date__c = Date.today().addDays(-2);        
        insert acc;
        
        Contact cont = new Contact();
        cont.LastName = 'TestCont HPB';
        cont.Email = 'test@test.com.br';
        cont.Phone = '(11) 1 1111-1111';
        cont.AccountId = acc.id;
        insert cont;        
        
        User newUser = new User();
        newUser.profileId = [SELECT Id FROM Profile WHERE Name='Supplier User'].id;        
        newUser.username = 'supplierUser@test.com';
        newUser.email = 'test@test.com';
        newUser.emailencodingkey = 'ISO-8859-1';
        newUser.localesidkey = 'pt_BR';
        newUser.languagelocalekey = 'en_US';
        newUser.timezonesidkey = 'America/Sao_Paulo';
        newUser.alias='nuser';
        newUser.lastname='lastname';
        newUser.contactId = cont.id;
        insert newUser;
        
        TOBJ_Warning__c warning = new TOBJ_Warning__c();
        warning.PublicationDate__c = Date.today().addDays(-2);        
        warning.TCF_DueDate__c = Date.today().addDays(2);
        warning.RequiredSendEmail__c = 'Yes';
        warning.TCF_HSEQWarning__c = 'Yes';
        warning.TCF_Subject__c = 'Teste de Setup 1';
        warning.TCF_Notice__c = '<p>Teste com warnings 1</p>';
        warning.TCF_RequiresConfirmation__c = 'No';
        insert warning;
        
        acc.TW1_Step_Owner__c = newUser.id;
        update acc; 
        
        TOBJ_Participants__c participante = new TOBJ_Participants__c();
        participante.TCF_Supplier__c = acc.id;
        participante.Warning__c = warning.id; 
        insert participante; 
        
        ContentVersion arquivo = new ContentVersion();
        arquivo.Title = 'Titulo do arquivo';
        arquivo.VersionData = Blob.toPdf('Classe de teste');
        arquivo.Description = 'Texto comum';
        arquivo.PathOnClient = 'Qualquer texto';
        insert arquivo;
        
        ContentVersion versao = [select id, contentDocumentId from ContentVersion where Title= 'Titulo do arquivo' limit 1];
        
        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.Visibility = 'AllUsers';
        Cdl.LinkedEntityId = participante.Warning__c;
        cdl.ContentDocumentId = versao.ContentDocumentId;
        insert cdl;
    }
    
    @isTest
    public static void TestMethod_warningEmailAlertToSuppliers(){
        TOBJ_Warning__c warn = [select id from TOBJ_Warning__c where TCF_Subject__c = 'Teste de Setup 1' limit 1];
        T_WarningEmailAlertToSupplierInvocable.warningEmailAlertToSuppliers(new List<TOBJ_Warning__c>{warn});
    }
    
    @isTest
    public static void TestMethod_warningEmailAlertToSuppliers_Future(){
        T_WarningApp.warningEmailAlertToSuppliers();
    }
}