force-app/main/default/objects/Account/fields/TW1_Main_Contact__c.field-meta.xml
<CustomField>
    <fullName>TW1_Main_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Main Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>TW1_SAP_Code__c</fullName>
    <label>SAP Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_Vendor_Vetting__c.field-meta.xml
<CustomField>
    <fullName>TW1_Vendor_Vetting__c</fullName>
    <defaultValue>&quot;Vetting Not Requested&quot;</defaultValue>
    <label>Vendor Vetting</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>No Registered</fullName>
            </value>
            <value>
                <fullName>Ongoing</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Vetting Not Requested</fullName>
            </value>
            <value>
                <fullName>Vetting Rejected</fullName>
            </value>
            <value>
                <fullName>Vetting Approved with Red Flag</fullName>
            </value>
            <value>
                <fullName>Vetting Approved</fullName>
            </value>
            <value>
                <fullName>Vetting Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/TW1_MODEC_Contract__c.object-meta.xml
<CustomObject>
    <label>MODEC Contract</label>
    <nameField>
        <label>MODEC Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MODEC Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Accumulated_Contract_Amout__c.field-meta.xml
<CustomField>
    <fullName>TW1_Accumulated_Contract_Amout__c</fullName>
    <formula>TW1_Previous_Contract_Amount_A__c + TW1_Contracted_Value_B__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Accumulated Contract Amout (A+B)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Annual_Estimate__c.field-meta.xml
<CustomField>
    <fullName>TW1_Annual_Estimate__c</fullName>
    <label>Annual Estimate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_BID__c.field-meta.xml
<CustomField>
    <fullName>TW1_BID__c</fullName>
    <label>BID?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Budgeted_2019__c.field-meta.xml
<CustomField>
    <fullName>TW1_Budgeted_2019__c</fullName>
    <label>Budgeted 2019?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Contempled_in_this_Agreement__c.field-meta.xml
<CustomField>
    <fullName>TW1_Contempled_in_this_Agreement__c</fullName>
    <label>Contempled in this Agreement</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Contracted_Value_B__c.field-meta.xml
<CustomField>
    <fullName>TW1_Contracted_Value_B__c</fullName>
    <label>Contracted Value (B)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Cost_Center__c.field-meta.xml
<CustomField>
    <fullName>TW1_Cost_Center__c</fullName>
    <label>Cost Center</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Cost_Controller__c.field-meta.xml
<CustomField>
    <fullName>TW1_Cost_Controller__c</fullName>
    <label>Cost Controller</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Date__c.field-meta.xml
<CustomField>
    <fullName>TW1_Date__c</fullName>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Department_Code__c.field-meta.xml
<CustomField>
    <fullName>TW1_Department_Code__c</fullName>
    <label>Department Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Duration__c.field-meta.xml
<CustomField>
    <fullName>TW1_Duration__c</fullName>
    <label>Duration</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>24 Months</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_End_Date__c.field-meta.xml
<CustomField>
    <fullName>TW1_End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Escalation__c.field-meta.xml
<CustomField>
    <fullName>TW1_Escalation__c</fullName>
    <label>Escalation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>IGPM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Increase__c.field-meta.xml
<CustomField>
    <fullName>TW1_Increase__c</fullName>
    <label>Increase</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Job_Title__c.field-meta.xml
<CustomField>
    <fullName>TW1_Job_Title__c</fullName>
    <label>Job Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Justification__c.field-meta.xml
<CustomField>
    <fullName>TW1_Justification__c</fullName>
    <label>Justification</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Main_Contact__c.field-meta.xml
<CustomField>
    <fullName>TW1_Main_Contact__c</fullName>
    <formula>TW1_Vendor__r.TW1_Main_Contact__r.FirstName +&quot; &quot;+ TW1_Vendor__r.TW1_Main_Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Main Contact</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Monthly_If_Fixed__c.field-meta.xml
<CustomField>
    <fullName>TW1_Monthly_If_Fixed__c</fullName>
    <label>Monthly (If Fixed)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Depends Demand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Party_Email__c.field-meta.xml
<CustomField>
    <fullName>TW1_Party_Email__c</fullName>
    <formula>TW1_Vendor__r.TW1_Company_Email_Address__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Party Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Payment_Conditions__c.field-meta.xml
<CustomField>
    <fullName>TW1_Payment_Conditions__c</fullName>
    <label>Payment Conditions</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>TW1_Payment_Term__c</fullName>
    <label>Payment Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>30 Days</fullName>
            </value>
            <value>
                <fullName>45 Days</fullName>
            </value>
            <value>
                <fullName>60 Days</fullName>
            </value>
            <value>
                <fullName>75 Days</fullName>
            </value>
            <value>
                <fullName>90 Days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_PO_Number__c.field-meta.xml
<CustomField>
    <fullName>TW1_PO_Number__c</fullName>
    <label>PO Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Previous_Contract_Amount_A__c.field-meta.xml
<CustomField>
    <fullName>TW1_Previous_Contract_Amount_A__c</fullName>
    <label>Previous Contract Amount (A):</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Requestor_Sponsor__c.field-meta.xml
<CustomField>
    <fullName>TW1_Requestor_Sponsor__c</fullName>
    <label>Requestor/Sponsor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_SAP_Outline_Agreement_Number__c.field-meta.xml
<CustomField>
    <fullName>TW1_SAP_Outline_Agreement_Number__c</fullName>
    <label>SAP Outline Agreement Number</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>TW1_Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Termination_Conditions_Penalty__c.field-meta.xml
<CustomField>
    <fullName>TW1_Termination_Conditions_Penalty__c</fullName>
    <label>Termination: Conditions/Penalty</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Type_of_Contract__c.field-meta.xml
<CustomField>
    <fullName>TW1_Type_of_Contract__c</fullName>
    <label>Type of Contract</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rent/Lease</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Material</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Vendor__c.field-meta.xml
<CustomField>
    <fullName>TW1_Vendor__c</fullName>
    <label>Supplier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>MODEC Contracts</relationshipLabel>
    <relationshipName>MODEC_Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Vendor_CNPJ__c.field-meta.xml
<CustomField>
    <fullName>TW1_Vendor_CNPJ__c</fullName>
    <formula>TW1_Vendor__r.TW1_CNPJ__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Supplier CNPJ</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Vendor_Vetting__c.field-meta.xml
<CustomField>
    <fullName>TW1_Vendor_Vetting__c</fullName>
    <formula>TEXT(TW1_Vendor__r.TW1_Vendor_Vetting__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vendor Vetting</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_WBS_Number__c.field-meta.xml
<CustomField>
    <fullName>TW1_WBS_Number__c</fullName>
    <label>WBS Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/T_MODEC_ContratoSuporteReq_App.cls
/**
 * @File Name          : T_MODEC_ContratoSuporteReq_App.cls
 * @Description        : 
 * @Author             : Mario Oliveira
 * @Group              : 
 * @Last Modified By   : Mario Oliveira
 * @Last Modified On   : 04/12/2019 11:17:30
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    01/11/2019   Mario Oliveira     Initial Version
**/
public with sharing class T_MODEC_ContratoSuporteReq_App {

    /*
     *  Metodo "mapearDto" é usado na classe "T_MODEC_ContratoSuporteReq_CTRL"
     *  para, atraves do id da pagina "T_ContratoSuporteReqVF", buscar registros
     *  nos campos do objeto e atribuir tais valores às variaveis no DTO da controller  
    */
    public static T_MODEC_ContratoSuporteReq_CTRL.ModecContractDTO mapearDto(string contratoId){

        /*
        *  Metodo "buscarElemento" vem da classe "T_MODEC_ContratoSuporteReq_REP",
        *  está sendo atribuido à variavel "contrato" de tipo "TW1_MODEC_Contract__c" (sObject)
        *  e, para o parametro do metodo é passado o id da pagina "T_ContratoSuporteReqVF",
        *  que vem atraves da classe controller
        */
        TW1_MODEC_Contract__c contrato = T_MODEC_ContratoSuporteReq_REP.buscarElemento(contratoId);

        /*
         *  Atribuição dos valores dos registros do objeto "TW1_MODEC_Contract__c",
         *  que vem da classe repositorio "T_MODEC_ContratoSuporteReq_CTRL" às variaveis
         *  do DTO, na classe controller
         */
        T_MODEC_ContratoSuporteReq_CTRL.ModecContractDTO contratoDto = new T_MODEC_ContratoSuporteReq_CTRL.ModecContractDTO();
        
        contratoDto.NameDTO = contrato.Name;
        contratoDto.SapOutlineAgreementNumberDTO = contrato.TW1_SAP_Outline_Agreement_Number__c;
        contratoDto.TypeOfContractDTO = contrato.TW1_Type_of_Contract__c;
        contratoDto.RequestorSponsorDTO = contrato.TW1_Requestor_Sponsor__c;
        contratoDto.JobTitleDTO = contrato.TW1_Job_Title__c;
        contratoDto.DateDTO = contrato.TW1_Date__c;
        contratoDto.VendorDTO = contrato.TW1_Vendor__r.Name;
        contratoDto.SAPCodeDTO = contrato.TW1_Vendor__r.TW1_SAP_Code__c;
        contratoDto.VendorCNPJDTO = contrato.TW1_Vendor_CNPJ__c;
        contratoDto.VendorVettingDTO = contrato.TW1_Vendor_Vetting__c;
        contratoDto.MainContactDTO = contrato.TW1_Main_Contact__c;
        contratoDto.PartyEmailDTO = contrato.TW1_Party_Email__c;
        contratoDto.BIDDTO = contrato.TW1_BID__c;
        contratoDto.JustificationDTO = contrato.TW1_Justification__c;
        contratoDto.ContempledInThisAgreementDTO = contrato.TW1_Contempled_in_this_Agreement__c; //NewField - 03/12/2019
        contratoDto.TerminationConditionsPenaltyDTO = contrato.TW1_Termination_Conditions_Penalty__c;
        contratoDto.PreviousContractAmountADTO = contrato.TW1_Previous_Contract_Amount_A__c;
        contratoDto.AccumulatedContractAmoutDTO = contrato.TW1_Accumulated_Contract_Amout__c;
        contratoDto.ContractedValueBDTO = contrato.TW1_Contracted_Value_B__c;
        contratoDto.IncreaseDTO = contrato.TW1_Increase__c;
        contratoDto.AnnualEstimateDTO = contrato.TW1_Annual_Estimate__c;
        contratoDto.CurrencyIsoCodeDTO = contrato.CurrencyIsoCode;
        contratoDto.MonthlyIfFixedDTO = contrato.TW1_Monthly_If_Fixed__c;
        contratoDto.EscalationDTO = contrato.TW1_Escalation__c;
        contratoDto.DurationDTO = contrato.TW1_Duration__c;
        contratoDto.PaymentTermDTO = contrato.TW1_Payment_Term__c;
        contratoDto.StartDateDTO = contrato.TW1_Start_Date__c;
        contratoDto.EndDateDTO = contrato.TW1_End_Date__c;
        contratoDto.PaymentConditionsDTO = contrato.TW1_Payment_Conditions__c;
        contratoDto.PONumberDTO = contrato.TW1_PO_Number__c;
        contratoDto.Budgeted2019DTO = contrato.TW1_Budgeted_2019__c;
        contratoDto.BudgetedJustificationDTO = contrato.TW1_Budgeted_Justification__c;
        contratoDto.CostCenterDTO = contrato.TW1_Cost_Center__c;
        contratoDto.WBSNumberDTO = contrato.TW1_WBS_Number__c;
        contratoDto.DepartmentCodeDTO = contrato.TW1_Department_Code__c;
        contratoDto.CostControllerDTO = contrato.TW1_Cost_Controller__c;

        return contratoDto;
    }
}