force-app/main/default/objects/Account/fields/TW1_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>TW1_Contact_Name__c</fullName>
    <label>Contact Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_CPF__c.field-meta.xml
<CustomField>
    <fullName>TW1_CPF__c</fullName>
    <label>CPF</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW3_From_Portal__c.field-meta.xml
<CustomField>
    <fullName>TW3_From_Portal__c</fullName>
    <label>From Portal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Senegal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/TW1_Vendor_Homologated.recordType-meta.xml
<RecordType>
    <fullName>TW1_Vendor_Homologated</fullName>
    <active>true</active>
    <label>Supplier Homologated</label>
</RecordType>

force-app/main/default/objects/TW1_Documentation__c/TW1_Documentation__c.object-meta.xml
<CustomObject>
    <label>Documentation</label>
    <nameField>
        <displayFormat>DOC{000000}</displayFormat>
        <label>Documentation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documentations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Documentation__c/fields/TW1_Request__c.field-meta.xml
<CustomField>
    <fullName>TW1_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request</label>
    <referenceTo>TW1_Request__c</referenceTo>
    <relationshipLabel>Documentations</relationshipLabel>
    <relationshipName>Documentations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Documentation__c/fields/TW1_Vendor__c.field-meta.xml
<CustomField>
    <fullName>TW1_Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Documentations</relationshipLabel>
    <relationshipName>Documentations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/TW1_MODEC_Contract__c.object-meta.xml
<CustomObject>
    <label>MODEC Contract</label>
    <nameField>
        <label>MODEC Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MODEC Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Request__c.field-meta.xml
<CustomField>
    <fullName>TW1_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request</label>
    <referenceTo>TW1_Request__c</referenceTo>
    <relationshipLabel>MODEC Contracts</relationshipLabel>
    <relationshipName>MODEC_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Status__c.field-meta.xml
<CustomField>
    <fullName>TW1_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Vendor__c.field-meta.xml
<CustomField>
    <fullName>TW1_Vendor__c</fullName>
    <label>Supplier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>MODEC Contracts</relationshipLabel>
    <relationshipName>MODEC_Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/TW1_Request__c/TW1_Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>REQ{000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>TW1_Contact_Name__c</fullName>
    <formula>TW1_Vendor__r.TW1_Contact_Name__c</formula>
    <label>Contact Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Inspection_Status__c.field-meta.xml
<CustomField>
    <fullName>TW1_Inspection_Status__c</fullName>
    <label>Inspection Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TW1_Inspection_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Status__c.field-meta.xml
<CustomField>
    <fullName>TW1_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Vendor__c.field-meta.xml
<CustomField>
    <fullName>TW1_Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4) OR (6 AND (5 OR 7))</booleanFilter>
        <errorMessage>Make sure the selected vendor is already homologated or not.</errorMessage>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>BM, Contract - New Contract, Contract - Amendment, Material Packing List (Third-party), Inspection</value>
        </filterItems>
        <filterItems>
            <field>Account.TW1_Vendor_Vetting__c</field>
            <operation>equals</operation>
            <value>Active, No Registered, Ongoing, Blocked, Vetting Not Requested, Vetting Rejected, Vetting Approved with Red Flag, Vetting Approved, Vetting Expired</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vendor Vetting, Vendor Vetting - Senegal</value>
        </filterItems>
        <filterItems>
            <field>Account.TW1_Vendor_Vetting__c</field>
            <operation>equals</operation>
            <value>Active, No Registered, Ongoing, Blocked, Vetting Not Requested, Vetting Rejected, Vetting Approved with Red Flag, Vetting Approved, Vetting Expired</value>
        </filterItems>
        <filterItems>
            <field>Account.TW1_Step_Owner__c</field>
            <operation>equals</operation>
            <valueField>$User.Id</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>PO Review Form</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator, VV Team</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/recordTypes/Inspection.recordType-meta.xml
<RecordType>
    <fullName>Inspection</fullName>
    <active>true</active>
    <label>Inspection</label>
</RecordType>

force-app/main/default/objects/TW1_Step__c/TW1_Step__c.object-meta.xml
<CustomObject>
    <label>Step</label>
    <nameField>
        <displayFormat>S{000000}</displayFormat>
        <label>Steps Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Step__c/fields/TW1_Inspection_Scheduled_Date__c.field-meta.xml
<CustomField>
    <fullName>TW1_Inspection_Scheduled_Date__c</fullName>
    <label>Inspection Scheduled Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TW1_Step__c/fields/TW1_Request__c.field-meta.xml
<CustomField>
    <fullName>TW1_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request</label>
    <referenceTo>TW1_Request__c</referenceTo>
    <relationshipLabel>Steps</relationshipLabel>
    <relationshipName>Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Step__c/fields/TW1_Status__c.field-meta.xml
<CustomField>
    <fullName>TW1_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opened</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Step__c/fields/TW1_Vendor__c.field-meta.xml
<CustomField>
    <fullName>TW1_Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Steps</relationshipLabel>
    <relationshipName>Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Step__c/recordTypes/Approval_Step_Date_Confirmation.recordType-meta.xml
<RecordType>
    <fullName>Approval_Step_Date_Confirmation</fullName>
    <active>true</active>
    <label>Approval Step - Date Confirmation</label>
</RecordType>

force-app/main/default/globalValueSets/TW1_Inspection_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Inspection Rescheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Reproved</fullName>
    </customValue>
    <customValue>
        <fullName>Awaiting Date Confirmation</fullName>
    </customValue>
    <customValue>
        <fullName>Verifying Date Availability</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>Inspection Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Rescheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <customValue>
        <fullName>Emergency Inspection</fullName>
    </customValue>
    <customValue>
        <fullName>Not Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Approved with Restriction</fullName>
    </customValue>
    <masterLabel>Inspection Status</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/T_MODEC_UpdateFromPortal_TST.cls
/**
 * @description       :
 * @author            : Rafael Hadama
 * @group             :
 * @last modified on  : 10-29-2020
 * @last modified by  : Rafael Hadama
 * Modifications Log
 * Ver   Date         Author          Modification
 * 1.0   10-29-2020   Rafael Hadama   Initial Version
 **/
@Istest
public class T_MODEC_UpdateFromPortal_TST {
    @isTest
    public static void RequestTst()
    {
        T_MODEC_Request_App_TST.criarCustomSettings();
        TW1_Request__c req = T_MODEC_Request_App_TST.criarRegistroMock();

        system.debug('req ' + req);
        Test.startTest();
        string objecttype         = 'TW1_Request__c';
        Id     batchEnvioAnexosId = Database.executeBatch(new T_MODEC_UpdateFromPortal(objecttype), 5);

        system.debug('Batch process id:' + batchEnvioAnexosId);

        Test.stopTest();
        TW1_Request__c reqValidate = [Select id, TW3_From_Portal__c from TW1_Request__c where id =:req.Id];
        system.debug('reqValidate ' + reqValidate);
        system.assertEquals(true, reqValidate.TW3_From_Portal__c == 'Brazil');
    }

    @Istest
    public static void DocTst()
    {
        T_MODEC_DeleteDocumentationTST.MakeMetadataAndCustomSettings();
        RecordType accRec_VendorHomologated = [Select id from Recordtype where developername = 'TW1_Vendor_Homologated'];
        Account    contamock = new Account();

        contamock.recordtypeId        = accRec_VendorHomologated.id;
        contamock.name                = 'Conta ENVIO Boletim';
        contamock.TW1_CPF__c          = '57034551030';
        contamock.TW1_Contact_Name__c = 'Contato Mock';
        insert contamock;

        //Query no recordType e criação do Request do tipo BM

        TW1_MODEC_Contract__c ContractMock = new TW1_MODEC_Contract__c();
        ContractMock.TW1_Vendor__c = contamock.Id;
        ContractMock.Name          = 'Contrato Mock';


        insert ContractMock;

        list<T_MODEC_CreateDoc_CTRL.recTypesDto> listRecTypes = T_MODEC_CreateDoc_CTRL.getlistRecTypesDocumentation(ContractMock.Id);

        string DocCreatedId = T_MODEC_CreateDoc_CTRL.createDocumentationAuxiliar(listRecTypes[0].value, ContractMock.Id);
        system.debug('DocCreatedId:' + DocCreatedId);
        Test.startTest();
        string objecttype         = 'TW1_Documentation__c';
        Id     batchEnvioAnexosId = Database.executeBatch(new T_MODEC_UpdateFromPortal(objecttype), 5);

        system.debug('Batch process id:' + batchEnvioAnexosId);

        Test.stopTest();
        TW1_Documentation__c docValidate = [Select id, TW3_From_Portal__c from TW1_Documentation__c where id =:DocCreatedId];
        system.debug('docValidate ' + docValidate);
        system.assertEquals(true, docValidate.TW3_From_Portal__c == 'Brazil');
    }

    @Istest
    public static void StepTst()
    {
        T_MODEC_StepTrigger_TST.criarCustomSettings();
        T_MODEC_Request_Rep RequestREP = new T_MODEC_Request_Rep();
        String              RecTypeStepDateConfirmation = Schema.SObjectType.TW1_Step__c.getRecordTypeInfosByDeveloperName().get('Approval_Step_Date_Confirmation').getRecordTypeId();
        //Creating inspection
        TW1_Request__c InspectionRequest = T_MODEC_ScheduleInspection_TST.CreateInspectionRequest();

        //Creating Inspection item
        T_MODEC_InspectionItem_TST.CreateInspectionItem(InspectionRequest.Id, 1);

        InspectionRequest.TW1_Inspection_Status__c         = 'Awaiting Date Confirmation';
        InspectionRequest.TW1_Inspection_Scheduled_Date__c = Datetime.now().addDays(5);
        update InspectionRequest;

        //Criada pelo process builder.
        TW1_Step__c StepDateConfirmation = new TW1_Step__c();
        StepDateConfirmation.TW1_Request__c = InspectionRequest.Id;
        StepDateConfirmation.TW1_Inspection_Scheduled_Date__c = InspectionRequest.TW1_Inspection_Scheduled_Date__c;
        StepDateConfirmation.TW1_Status__c = 'Opened';
        StepDateConfirmation.RecordTypeId  = RecTypeStepDateConfirmation;
        insert StepDateConfirmation;
        //[Select id, TW1_Request__c from TW1_Step__c where TW1_Request__c =:InspectionRequest.Id AND RecordtypeId =:RecTypeStepDateConfirmation];
        system.debug('StepDateConfirmation >>' + StepDateConfirmation);

        Test.startTest();
        string objecttype         = 'TW1_Step__c';
        Id     batchEnvioAnexosId = Database.executeBatch(new T_MODEC_UpdateFromPortal(objecttype), 5);

        system.debug('Batch process id:' + batchEnvioAnexosId);

        Test.stopTest();
        TW1_Step__c stepValidate = [Select id, TW3_From_Portal__c from TW1_Step__c where id =:StepDateConfirmation.Id];
        system.debug('stepValidate ' + stepValidate);
        system.assertEquals(true, stepValidate.TW3_From_Portal__c == 'Brazil');
    }

    @Istest
    public static void IntTst()
    {
    }
}