force-app/main/default/objects/Account/fields/TW1_CNPJ__c.field-meta.xml
<CustomField>
    <fullName>TW1_CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_Contact_email_address__c.field-meta.xml
<CustomField>
    <fullName>TW1_Contact_email_address__c</fullName>
    <label>Contact email address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>TW1_Contact_Name__c</fullName>
    <label>Contact Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>TW1_Contact_Phone__c</fullName>
    <label>Contact Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_CPF__c.field-meta.xml
<CustomField>
    <fullName>TW1_CPF__c</fullName>
    <label>CPF</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_Shelf_Life_Vetting_Date__c.field-meta.xml
<CustomField>
    <fullName>TW1_Shelf_Life_Vetting_Date__c</fullName>
    <label>Vetting expiration date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/TW1_Vendor_Homologated.recordType-meta.xml
<RecordType>
    <fullName>TW1_Vendor_Homologated</fullName>
    <active>true</active>
    <label>Supplier Homologated</label>
</RecordType>

force-app/main/default/objects/TW1_Documentation__c/TW1_Documentation__c.object-meta.xml
<CustomObject>
    <label>Documentation</label>
    <nameField>
        <displayFormat>DOC{000000}</displayFormat>
        <label>Documentation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documentations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Documentation__c/fields/TW1_Request__c.field-meta.xml
<CustomField>
    <fullName>TW1_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request</label>
    <referenceTo>TW1_Request__c</referenceTo>
    <relationshipLabel>Documentations</relationshipLabel>
    <relationshipName>Documentations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Documentation__c/fields/TW1_Vendor__c.field-meta.xml
<CustomField>
    <fullName>TW1_Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Documentations</relationshipLabel>
    <relationshipName>Documentations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Documentation__c/recordTypes/TW1_Inspection_Documentation.recordType-meta.xml
<RecordType>
    <fullName>TW1_Inspection_Documentation</fullName>
    <active>true</active>
    <label>Inspection Documentation</label>
</RecordType>

force-app/main/default/objects/TW1_Request__c/TW1_Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>REQ{000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Contact_email_address__c.field-meta.xml
<CustomField>
    <fullName>TW1_Contact_email_address__c</fullName>
    <formula>TW1_Vendor__r.TW1_Contact_email_address__c</formula>
    <label>Contact email address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>TW1_Contact_Name__c</fullName>
    <formula>TW1_Vendor__r.TW1_Contact_Name__c</formula>
    <label>Contact Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Vendor__c.field-meta.xml
<CustomField>
    <fullName>TW1_Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4) OR (6 AND (5 OR 7))</booleanFilter>
        <errorMessage>Make sure the selected vendor is already homologated or not.</errorMessage>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>BM, Contract - New Contract, Contract - Amendment, Material Packing List (Third-party), Inspection</value>
        </filterItems>
        <filterItems>
            <field>Account.TW1_Vendor_Vetting__c</field>
            <operation>equals</operation>
            <value>Active, No Registered, Ongoing, Blocked, Vetting Not Requested, Vetting Rejected, Vetting Approved with Red Flag, Vetting Approved, Vetting Expired</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vendor Vetting, Vendor Vetting - Senegal</value>
        </filterItems>
        <filterItems>
            <field>Account.TW1_Vendor_Vetting__c</field>
            <operation>equals</operation>
            <value>Active, No Registered, Ongoing, Blocked, Vetting Not Requested, Vetting Rejected, Vetting Approved with Red Flag, Vetting Approved, Vetting Expired</value>
        </filterItems>
        <filterItems>
            <field>Account.TW1_Step_Owner__c</field>
            <operation>equals</operation>
            <valueField>$User.Id</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>PO Review Form</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator, VV Team</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/recordTypes/Inspection.recordType-meta.xml
<RecordType>
    <fullName>Inspection</fullName>
    <active>true</active>
    <label>Inspection</label>
</RecordType>

force-app/main/default/classes/T_MODEC_ContentDocumentApp_TST.cls
@isTest
public class T_MODEC_ContentDocumentApp_TST {

    Private static Id vendorHomologated = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('TW1_Vendor_Homologated').getRecordTypeId();
    Private static Id requestInspection = Schema.SObjectType.TW1_Request__c.getRecordTypeInfosByDeveloperName().get('Inspection').getRecordTypeId();
    Private static Id documentationInspection = Schema.SObjectType.TW1_Documentation__c.getRecordTypeInfosByDeveloperName().get('TW1_Inspection_Documentation').getRecordTypeId();
    
    @TestSetup
    public static void TestSetup(){
        
        Account acc = new Account();
        acc.RecordTypeId = vendorHomologated;
        acc.TW1_CNPJ__c = '00151720000158';
        acc.TW1_CPF__c = '17582277023';
        acc.Name = 'TestAcc HPB';
        acc.TW1_Contact_Name__c = 'TestCont HPB';
        acc.TW1_Contact_Phone__c = '(11) 1 1111-1111';
        acc.TW1_Contact_email_address__c = 'test@test.com.br';
        acc.TW1_Shelf_Life_Vetting_Date__c = Date.today().addDays(-2);        
        insert acc;
        
        Contact cont = new Contact();
        cont.LastName = 'TestCont HPB';
        cont.Email = 'test@test.com.br';
        cont.Phone = '(11) 1 1111-1111';
        cont.AccountId = acc.id;
        insert cont;        
        
        User newUser = new User();
        newUser.profileId = [SELECT Id FROM Profile WHERE Name='Supplier User'].id;        
        newUser.username = 'supplierUser@test.com';
        newUser.email = 'test@test.com';
        newUser.emailencodingkey = 'ISO-8859-1';
        newUser.localesidkey = 'pt_BR';
        newUser.languagelocalekey = 'en_US';
        newUser.timezonesidkey = 'America/Sao_Paulo';
        newUser.alias='nuser';
        newUser.lastname='lastname';
        newUser.contactId = cont.id;
        insert newUser;
        
        TW1_Request__c request = new TW1_Request__c();
        request.TW1_Vendor__c = acc.id;
        request.OwnerId = newUser.id;
        request.RecordTypeId = requestInspection;
        insert request;
        
        ContentVersion arquivo = new ContentVersion();
        arquivo.Title = 'Titulo do arquivo';
        arquivo.VersionData = Blob.toPdf('Classe de teste');
        arquivo.Description = 'Texto comum';
        arquivo.PathOnClient = 'Qualquer texto';
        insert arquivo;
        
        TW1_Documentation__c doc = new TW1_Documentation__c();
        doc.RecordTypeId = documentationInspection;
        doc.TW1_Request__c = request.id;
        insert doc;
        
        ContentVersion versao = [select id, contentDocumentId from ContentVersion where Title= 'Titulo do arquivo' limit 1];
        
        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.Visibility = 'AllUsers';
        cdl.ShareType = 'V';
        cdl.LinkedEntityId = doc.id;
        cdl.ContentDocumentId = versao.ContentDocumentId;
        insert cdl;
        
        ContentDocument cd = [select id from ContentDocument limit 1];
        cd.OwnerId = newUser.id;
        update cd;
    }
    
    @isTest
    public static void TestMethod1(){
        User oUser = [select id from User where username = 'supplierUser@test.com' limit 1];
        
        System.runAs(oUser){
            try{
                ContentDocument cd = [select id from ContentDocument limit 1];
                delete cd;
                System.assertEquals(true, false);
            } catch(Exception e){
                IF(e.getMessage().contains('Não é possível deletar o arquivo da inspeção. Por favor, entre em contato com a Modec.')){
                    //no error
                } else {
                    System.assertEquals(true, false);
                }
            }
        }
    }
}