force-app/main/default/objects/Account/fields/TW1_CNPJ__c.field-meta.xml
<CustomField>
    <fullName>TW1_CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_Contact_email_address__c.field-meta.xml
<CustomField>
    <fullName>TW1_Contact_email_address__c</fullName>
    <label>Contact email address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>TW1_Contact_Name__c</fullName>
    <label>Contact Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>TW1_Contact_Phone__c</fullName>
    <label>Contact Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_CPF__c.field-meta.xml
<CustomField>
    <fullName>TW1_CPF__c</fullName>
    <label>CPF</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_Shelf_Life_Vetting_Date__c.field-meta.xml
<CustomField>
    <fullName>TW1_Shelf_Life_Vetting_Date__c</fullName>
    <label>Vetting expiration date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_Step_Owner__c.field-meta.xml
<CustomField>
    <fullName>TW1_Step_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Step Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Supplier</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/TW1_Vendor_Homologated.recordType-meta.xml
<RecordType>
    <fullName>TW1_Vendor_Homologated</fullName>
    <active>true</active>
    <label>Supplier Homologated</label>
</RecordType>

force-app/main/default/objects/TOBJ_Participants__c/TOBJ_Participants__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>PN-{YYYY}{MM}-{0000}</displayFormat>
        <label>Nome do Participante</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TOBJ_Participants__c/fields/RequiredSendEmail__c.field-meta.xml
<CustomField>
    <fullName>RequiredSendEmail__c</fullName>
    <formula>TEXT(Warning__r.RequiredSendEmail__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Necessita envio de e-mail?</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TOBJ_Participants__c/fields/TCF_Supplier__c.field-meta.xml
<CustomField>
    <fullName>TCF_Supplier__c</fullName>
    <label>Fornecedor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>TRN_ParticipantsAccount</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TOBJ_Participants__c/fields/Warning__c.field-meta.xml
<CustomField>
    <fullName>Warning__c</fullName>
    <label>Warning</label>
    <referenceTo>TOBJ_Warning__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>TRN_ParticipantsWarning</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TOBJ_Warning__c/TOBJ_Warning__c.object-meta.xml
<CustomObject>
    <label>Warning</label>
    <nameField>
        <displayFormat>WARN-{00000000}</displayFormat>
        <label>Nome do Aviso</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Warning</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/TOBJ_Warning__c/fields/PublicationDate__c.field-meta.xml
<CustomField>
    <fullName>PublicationDate__c</fullName>
    <label>Data de publicação</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TOBJ_Warning__c/fields/RequiredSendEmail__c.field-meta.xml
<CustomField>
    <fullName>RequiredSendEmail__c</fullName>
    <label>Requer envio de e-mail?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TOBJ_Warning__c/fields/TCF_DueDate__c.field-meta.xml
<CustomField>
    <fullName>TCF_DueDate__c</fullName>
    <label>Data de vencimento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TOBJ_Warning__c/fields/TCF_HSEQWarning__c.field-meta.xml
<CustomField>
    <fullName>TCF_HSEQWarning__c</fullName>
    <label>Comunicado HSEQ?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TOBJ_Warning__c/fields/TCF_Notice__c.field-meta.xml
<CustomField>
    <fullName>TCF_Notice__c</fullName>
    <label>Notícia</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/TOBJ_Warning__c/fields/TCF_RequiresConfirmation__c.field-meta.xml
<CustomField>
    <fullName>TCF_RequiresConfirmation__c</fullName>
    <label>Requer confirmação?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TOBJ_Warning__c/fields/TCF_Subject__c.field-meta.xml
<CustomField>
    <fullName>TCF_Subject__c</fullName>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Documentation__c/TW1_Documentation__c.object-meta.xml
<CustomObject>
    <label>Documentation</label>
    <nameField>
        <displayFormat>DOC{000000}</displayFormat>
        <label>Documentation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documentations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Documentation__c/fields/TW1_Request__c.field-meta.xml
<CustomField>
    <fullName>TW1_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request</label>
    <referenceTo>TW1_Request__c</referenceTo>
    <relationshipLabel>Documentations</relationshipLabel>
    <relationshipName>Documentations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Documentation__c/fields/TW1_Vendor__c.field-meta.xml
<CustomField>
    <fullName>TW1_Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Documentations</relationshipLabel>
    <relationshipName>Documentations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Documentation__c/recordTypes/TW1_Inspection_Documentation.recordType-meta.xml
<RecordType>
    <fullName>TW1_Inspection_Documentation</fullName>
    <active>true</active>
    <label>Inspection Documentation</label>
</RecordType>

force-app/main/default/objects/TW1_Inspection_Item__c/TW1_Inspection_Item__c.object-meta.xml
<CustomObject>
    <label>Inspection Item</label>
    <nameField>
        <displayFormat>Item-{000000}</displayFormat>
        <label>Inspection Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspection Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Inspection_Item__c/fields/TW1_Item_Description__c.field-meta.xml
<CustomField>
    <fullName>TW1_Item_Description__c</fullName>
    <label>Item Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Inspection_Item__c/fields/TW1_Quantity__c.field-meta.xml
<CustomField>
    <fullName>TW1_Quantity__c</fullName>
    <label>Quantity</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TW1_Inspection_Item__c/fields/TW1_Request__c.field-meta.xml
<CustomField>
    <fullName>TW1_Request__c</fullName>
    <label>Request</label>
    <referenceTo>TW1_Request__c</referenceTo>
    <relationshipLabel>Inspection Items</relationshipLabel>
    <relationshipName>Inspection_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TW1_Inspection_Item__c/fields/TW1_Tag_or_Certificate_Number__c.field-meta.xml
<CustomField>
    <fullName>TW1_Tag_or_Certificate_Number__c</fullName>
    <inlineHelpText>In case of Inspection in parts/spools, the tag must be inserted in this field</inlineHelpText>
    <label>Tag or Certificate Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Inspection_Item__c/fields/TW5_Isometric_Drawing__c.field-meta.xml
<CustomField>
    <fullName>TW5_Isometric_Drawing__c</fullName>
    <label>Isometric / Drawing Item Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Inspection_Item__c/fields/TW5_PO_Item_Number__c.field-meta.xml
<CustomField>
    <fullName>TW5_PO_Item_Number__c</fullName>
    <inlineHelpText>You have to insert a maximum of 5 characters.</inlineHelpText>
    <label>PO Item Number</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/TW1_Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>REQ{000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Contact_email_address__c.field-meta.xml
<CustomField>
    <fullName>TW1_Contact_email_address__c</fullName>
    <formula>TW1_Vendor__r.TW1_Contact_email_address__c</formula>
    <label>Contact email address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>TW1_Contact_Name__c</fullName>
    <formula>TW1_Vendor__r.TW1_Contact_Name__c</formula>
    <label>Contact Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Inspection_Status__c.field-meta.xml
<CustomField>
    <fullName>TW1_Inspection_Status__c</fullName>
    <label>Inspection Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TW1_Inspection_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Vendor__c.field-meta.xml
<CustomField>
    <fullName>TW1_Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4) OR (6 AND (5 OR 7))</booleanFilter>
        <errorMessage>Make sure the selected vendor is already homologated or not.</errorMessage>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>BM, Contract - New Contract, Contract - Amendment, Material Packing List (Third-party), Inspection</value>
        </filterItems>
        <filterItems>
            <field>Account.TW1_Vendor_Vetting__c</field>
            <operation>equals</operation>
            <value>Active, No Registered, Ongoing, Blocked, Vetting Not Requested, Vetting Rejected, Vetting Approved with Red Flag, Vetting Approved, Vetting Expired</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vendor Vetting, Vendor Vetting - Senegal</value>
        </filterItems>
        <filterItems>
            <field>Account.TW1_Vendor_Vetting__c</field>
            <operation>equals</operation>
            <value>Active, No Registered, Ongoing, Blocked, Vetting Not Requested, Vetting Rejected, Vetting Approved with Red Flag, Vetting Approved, Vetting Expired</value>
        </filterItems>
        <filterItems>
            <field>Account.TW1_Step_Owner__c</field>
            <operation>equals</operation>
            <valueField>$User.Id</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>PO Review Form</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator, VV Team</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/recordTypes/Inspection.recordType-meta.xml
<RecordType>
    <fullName>Inspection</fullName>
    <active>true</active>
    <label>Inspection</label>
</RecordType>

force-app/main/default/globalValueSets/TW1_Inspection_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Inspection Rescheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Reproved</fullName>
    </customValue>
    <customValue>
        <fullName>Awaiting Date Confirmation</fullName>
    </customValue>
    <customValue>
        <fullName>Verifying Date Availability</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>Inspection Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Rescheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <customValue>
        <fullName>Emergency Inspection</fullName>
    </customValue>
    <customValue>
        <fullName>Not Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Approved with Restriction</fullName>
    </customValue>
    <masterLabel>Inspection Status</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/T_ContentDocumentLinkValidationApp_TST.cls
/**
* @description       :
* @author            : Hugo Brito
* @group             :
* @last modified on  : 05-14-2021
* @last modified by  : Hugo Brito
* Modifications Log
* Ver   Date         Author       Modification
* 1.0   05-14-2021   Hugo Brito   Criação da classe
**/
@isTest
public class T_ContentDocumentLinkValidationApp_TST {

    Private static Id vendorHomologated = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('TW1_Vendor_Homologated').getRecordTypeId();
    Private static Id requestInspection = Schema.SObjectType.TW1_Request__c.getRecordTypeInfosByDeveloperName().get('Inspection').getRecordTypeId();
    Private static Id documentationInspection = Schema.SObjectType.TW1_Documentation__c.getRecordTypeInfosByDeveloperName().get('TW1_Inspection_Documentation').getRecordTypeId();
    
    @TestSetup
    public static void TestSetup(){
        ContentVersion arquivo = new ContentVersion();
        arquivo.Title = 'Titulo do arquivo';
        arquivo.VersionData = Blob.toPdf('Classe de teste');
        arquivo.Description = 'Texto comum';
        arquivo.PathOnClient = 'Qualquer texto';
        insert arquivo;
        
        Account acc = new Account();
        acc.RecordTypeId = vendorHomologated;
        acc.TW1_CNPJ__c = '00151720000158';
        acc.TW1_CPF__c = '17582277023';
        acc.Name = 'TestAcc HPB';
        acc.TW1_Contact_Name__c = 'TestCont HPB';
        acc.TW1_Contact_Phone__c = '(11) 1 1111-1111';
        acc.TW1_Contact_email_address__c = 'test@test.com.br';
        acc.TW1_Shelf_Life_Vetting_Date__c = Date.today().addDays(-2);        
        insert acc;
        
        Contact cont = new Contact();
        cont.LastName = 'TestCont HPB';
        cont.Email = 'test@test.com.br';
        cont.Phone = '(11) 1 1111-1111';
        cont.AccountId = acc.id;
        insert cont;        
        
        User newUser = new User();
        newUser.profileId = [SELECT Id FROM Profile WHERE Name='Supplier User'].id;        
        newUser.username = 'supplierUser@test.com';
        newUser.email = 'test@test.com';
        newUser.emailencodingkey = 'ISO-8859-1';
        newUser.localesidkey = 'pt_BR';
        newUser.languagelocalekey = 'en_US';
        newUser.timezonesidkey = 'America/Sao_Paulo';
        newUser.alias='nuser';
        newUser.lastname='lastname';
        newUser.contactId = cont.id;
        insert newUser;
        
        TOBJ_Warning__c warning = new TOBJ_Warning__c();
        warning.PublicationDate__c = Date.newInstance(2021, 04, 01);        
        warning.TCF_DueDate__c = Date.newInstance(2021, 06, 15);
        warning.RequiredSendEmail__c = 'No';
        warning.TCF_HSEQWarning__c = 'No';
        warning.TCF_Subject__c = 'Teste de Setup 1';
        warning.TCF_Notice__c = '<p>Teste com warnings 1</p>';
        warning.TCF_RequiresConfirmation__c = 'No';
        insert warning;
        
        acc.TW1_Step_Owner__c = newUser.id;
        update acc; 
        
        TOBJ_Participants__c participante = new TOBJ_Participants__c();
        participante.TCF_Supplier__c = acc.id;
        participante.Warning__c = warning.id; 
        insert participante; 
    }
    
    @isTest
    public static void TestMethod_ValidateInsertDocument(){
        
        User supplierUser = [select id, contact.AccountId from User where username = 'supplierUser@test.com' limit 1];
        ContentVersion versao = [select id, contentDocumentId from ContentVersion where Title= 'Titulo do arquivo' limit 1];
        TOBJ_Participants__c participante = [select id, Warning__c from TOBJ_Participants__c where TCF_Supplier__c =: supplierUser.contact.AccountId limit 1];
        
        try{
            System.runAs(supplierUser){
                ContentDocumentLink cdl = new ContentDocumentLink();
                cdl.Visibility = 'AllUsers';
                cdl.LinkedEntityId = participante.Warning__c;
                cdl.ContentDocumentId = versao.ContentDocumentId;
                insert cdl;
            }
            System.assertEquals(true, false);
        } catch(Exception e){
            IF(e.getMessage().contains('Não é possível adicionar o arquivo. Por favor, entre em contato com a Modec.')){
                //no error
            } else {
                System.assertEquals(true, false);
            }
        }
    }
    
    @isTest
    public static void TestMethod_ValidateDeleteDocument(){
        
        Account conta = [select id from account limit 1];
        
        TW1_Request__c request = new TW1_Request__c();
        request.TW1_Vendor__c = conta.id;
        request.RecordTypeId = requestInspection;
        insert request;
        
        TW1_Documentation__c doc = new TW1_Documentation__c();
        doc.RecordTypeId = documentationInspection;
        doc.TW1_Request__c = request.id;
        insert doc;
        
        ContentVersion versao = [select id, contentDocumentId from ContentVersion where Title= 'Titulo do arquivo' limit 1];
        
        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.Visibility = 'AllUsers';
        cdl.LinkedEntityId = doc.id;
        cdl.ContentDocumentId = versao.ContentDocumentId;
        insert cdl;
        
        TW1_Inspection_Item__c item = new TW1_Inspection_Item__c();
        item.TW1_Item_Description__c = '45546546';
        item.TW1_Quantity__c = 46;
        item.TW1_Tag_or_Certificate_Number__c = '446';
        item.TW5_PO_Item_Number__c = 4546;
        item.TW5_Isometric_Drawing__c = '4546';
        item.TW1_Request__c = request.id;
        insert item;
        
        request.TW1_Inspection_Status__c = 'Canceled';
        update request;
        
        try{
            delete cdl;
            System.assertEquals(true, false);
        } catch(Exception e){
            IF(e.getMessage().contains('Não é possível deletar o arquivo. Por favor, entre em contato com o administrador.')){
                //no error
            } else {
                System.assertEquals(true, false);
            }
        }
    }
}