force-app/main/default/objects/Account/fields/TW1_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>TW1_Contact_Name__c</fullName>
    <label>Contact Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_CPF__c.field-meta.xml
<CustomField>
    <fullName>TW1_CPF__c</fullName>
    <label>CPF</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/TW1_Vendor_Homologated.recordType-meta.xml
<RecordType>
    <fullName>TW1_Vendor_Homologated</fullName>
    <active>true</active>
    <label>Supplier Homologated</label>
</RecordType>

force-app/main/default/objects/Controle_de_Triggers__c/Controle_de_Triggers__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Controle de triggers para facilitar controle de acesso e configuração.</description>
    <label>Controle de Triggers</label>
</CustomObject>

force-app/main/default/objects/Controle_de_Triggers__c/fields/Request_Vendor_Vetting_RecId__c.field-meta.xml
<CustomField>
    <fullName>Request_Vendor_Vetting_RecId__c</fullName>
    <label>Request Vendor Vetting RecId</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Controle_de_Triggers__c/fields/Trigger_Account__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Trigger Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Controle_de_Triggers__c/fields/Trigger_Request__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Request__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Trigger_Request</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ID_Account__c/ID_Account__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ID - Account</label>
</CustomObject>

force-app/main/default/objects/ID_Account__c/fields/Id_IntegrationUser__c.field-meta.xml
<CustomField>
    <fullName>Id_IntegrationUser__c</fullName>
    <label>Id_IntegrationUser</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/T_Debug_Setting__mdt/T_Debug_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Configurações de Debug</description>
    <label>Triscal debug setting</label>
    <pluralLabel>Triscal debug setting</pluralLabel>
</CustomObject>

force-app/main/default/objects/T_Debug_Setting__mdt/fields/T_Armazenar_Cause__c.field-meta.xml
<CustomField>
    <fullName>T_Armazenar_Cause__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Se true armazena a causa da exception caso exista</description>
    <label>Armazenar Cause?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/T_Debug_Setting__mdt/fields/T_Armazenar_linha_debug__c.field-meta.xml
<CustomField>
    <fullName>T_Armazenar_linha_debug__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Se true armazena linha de debug</description>
    <label>Armazenar linha debug?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/T_Debug_Setting__mdt/fields/T_Armazenar_StackTrace__c.field-meta.xml
<CustomField>
    <fullName>T_Armazenar_StackTrace__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Se true então armazena o StackTrace da exceção</description>
    <inlineHelpText>Se true então armazena o StackTrace da exceção</inlineHelpText>
    <label>Armazenar StackTrace?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/T_Debug_Setting__mdt/fields/T_Armazenar_texto_Exception__c.field-meta.xml
<CustomField>
    <fullName>T_Armazenar_texto_Exception__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Se true então armazena o texto da exceção</description>
    <inlineHelpText>Se true então armazena o texto da exceção</inlineHelpText>
    <label>Armazenar texto Exception?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TW1_Email_List__c/TW1_Email_List__c.object-meta.xml
<CustomObject>
    <label>Email List</label>
    <nameField>
        <displayFormat>EL-{0000}</displayFormat>
        <label>Email List Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Email_List__c/fields/TW1_Email__c.field-meta.xml
<CustomField>
    <fullName>TW1_Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/TW1_Email_List__c/fields/TW1_Status__c.field-meta.xml
<CustomField>
    <fullName>TW1_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ativo</fullName>
                <default>true</default>
                <label>Ativo</label>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Email_List__c/recordTypes/TW1_BM_Email.recordType-meta.xml
<RecordType>
    <fullName>TW1_BM_Email</fullName>
    <active>true</active>
    <label>BM Email</label>
</RecordType>

force-app/main/default/objects/TW1_Request__c/TW1_Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>REQ{000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Request__c/fields/BM_Status__c.field-meta.xml
<CustomField>
    <fullName>BM_Status__c</fullName>
    <defaultValue>&quot;Não enviado&quot;</defaultValue>
    <label>BM Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BM_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_BM_Reference_Number_in_SAP_MODEC__c.field-meta.xml
<CustomField>
    <fullName>TW1_BM_Reference_Number_in_SAP_MODEC__c</fullName>
    <inlineHelpText>This field is read-only. Do not try to fill it.</inlineHelpText>
    <label>BM Reference Number in SAP MODEC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>TW1_Contact_Name__c</fullName>
    <formula>TW1_Vendor__r.TW1_Contact_Name__c</formula>
    <label>Contact Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Modec_Requester_Email__c.field-meta.xml
<CustomField>
    <fullName>TW1_Modec_Requester_Email__c</fullName>
    <label>Modec Requester Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Status__c.field-meta.xml
<CustomField>
    <fullName>TW1_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Vendor__c.field-meta.xml
<CustomField>
    <fullName>TW1_Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4) OR (6 AND (5 OR 7))</booleanFilter>
        <errorMessage>Make sure the selected vendor is already homologated or not.</errorMessage>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>BM, Contract - New Contract, Contract - Amendment, Material Packing List (Third-party), Inspection</value>
        </filterItems>
        <filterItems>
            <field>Account.TW1_Vendor_Vetting__c</field>
            <operation>equals</operation>
            <value>Active, No Registered, Ongoing, Blocked, Vetting Not Requested, Vetting Rejected, Vetting Approved with Red Flag, Vetting Approved, Vetting Expired</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vendor Vetting, Vendor Vetting - Senegal</value>
        </filterItems>
        <filterItems>
            <field>Account.TW1_Vendor_Vetting__c</field>
            <operation>equals</operation>
            <value>Active, No Registered, Ongoing, Blocked, Vetting Not Requested, Vetting Rejected, Vetting Approved with Red Flag, Vetting Approved, Vetting Expired</value>
        </filterItems>
        <filterItems>
            <field>Account.TW1_Step_Owner__c</field>
            <operation>equals</operation>
            <valueField>$User.Id</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>PO Review Form</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator, VV Team</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/recordTypes/TW1_BM.recordType-meta.xml
<RecordType>
    <fullName>TW1_BM</fullName>
    <active>true</active>
    <label>BM</label>
</RecordType>

force-app/main/default/objects/TW1_Request__c/recordTypes/TW1_Vendor_Vetting.recordType-meta.xml
<RecordType>
    <fullName>TW1_Vendor_Vetting</fullName>
    <active>true</active>
    <label>Vendor Vetting</label>
</RecordType>

force-app/main/default/globalValueSets/BM_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Aguardando</fullName>
    </customValue>
    <customValue>
        <fullName>Aceita</fullName>
    </customValue>
    <customValue>
        <fullName>Rejeitada</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelada</fullName>
    </customValue>
    <customValue>
        <fullName>Não enviado</fullName>
        <default>true</default>
        <label>Não enviado</label>
    </customValue>
    <masterLabel>BM Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/T_MODEC_StatusBoletim_TST.cls
/**
 * @File Name          : T_MODEC_StatusBoletim_TST.cls
 * @Description        : Classe de teste do serviço Rest /StatusBoletim/*
 * @Author             : Rafael Hadama
 * @Group              :
 * @Last Modified By   : Rafael Hadama
 * @Last Modified On   : 07-22-2020
 * @Modification Log   :
 * Ver       Date            Author              Modification
 * 1.0    19/11/2019   Rafael Hadama     Initial Version
 **/
@istest
public class T_MODEC_StatusBoletim_TST {
    static void MakeMetadataAndCustomSettings()
    {
        system.debug('Teste system debug dentro do testSetupmetodo');
        T_Debug_Setting__mdt testSetting = new T_Debug_Setting__mdt();
        testSetting.Label                          = 'Teste';
        testSetting.DeveloperName                  = 'Teste';
        testSetting.T_Armazenar_Cause__c           = true;
        testSetting.T_Armazenar_linha_debug__c     = true;
        testSetting.T_Armazenar_StackTrace__c      = true;
        testSetting.T_Armazenar_texto_Exception__c = true;
        T_SDK_DebugLog_Test.testSetting            = testSetting;

        //Creating Custom Settings
        ID_Account__c customSettingIdAccount = new ID_Account__c();
        customSettingIdAccount.Id_IntegrationUser__c = UserInfo.getUserId();
        insert customSettingIdAccount;

        Controle_de_Triggers__c customControleTrigger = new Controle_de_Triggers__c();
        customControleTrigger.Trigger_Request__c = true;
        customControleTrigger.Trigger_Account__c = true;
        customControleTrigger.Request_Vendor_Vetting_RecId__c = Schema.SObjectType.TW1_Request__c.getRecordTypeInfosByDeveloperName().get('TW1_Vendor_Vetting').getRecordTypeId();
        insert customControleTrigger;
    }

    @Istest
    static void TestarPostStatusBoletim()
    {
        //Criar Account
        //Criar Request do tipo BM
        //Preencher com um numero de BM
        //Criar uma list<Itemrequest> REQUEST
        //Validar se o status do BM foi atualizado

        //Query no recordtype e criação de conta


        MakeMetadataAndCustomSettings();
        RecordType accRec_VendorHomologated = [Select id from Recordtype where developername = 'TW1_Vendor_Homologated'];
        Account    contamock = new Account();

        contamock.recordtypeId        = accRec_VendorHomologated.id;
        contamock.name                = 'Conta Status Boletim';
        contamock.TW1_CPF__c          = '57034551030';
        contamock.TW1_Contact_Name__c = 'Contato Mock';
        insert contamock;

        //Criando TW1_Email_List__c para passar da trigger.
        TW1_Email_List__c emailList = new TW1_Email_List__c();
        emailList.TW1_Email__c  = 'emailRequestermock@mock.com';
        emailList.TW1_Status__c = 'Ativo';
        emailList.RecordTypeId  = Schema.SObjectType.TW1_Email_List__c.getRecordTypeInfosByDeveloperName().get('TW1_BM_Email').getRecordTypeId();
        insert emailList;

        //Query no recordType e criação do Request do tipo BM
        RecordType           requestRec_BM = [Select id from Recordtype where developername = 'TW1_BM'];
        list<TW1_Request__c> listBMs       = new list<TW1_Request__c>();


        for (integer i = 0; i <= 150; i++)
        {
            TW1_Request__c BMmock1 = new TW1_Request__c();
            BMmock1.recordTypeId  = requestRec_BM.id;
            BMmock1.TW1_Vendor__c = contamock.id;
            BMmock1.BM_Status__c  = 'Aguardando';
            BMmock1.TW1_BM_Reference_Number_in_SAP_MODEC__c = String.valueOf(i);
            BMmock1.TW1_Modec_Requester_Email__c            = 'emailRequestermock@mock.com';
            listBMs.add(BMmock1);
        }
        TriggerFactory.validateRequesterEmail = false;
        TriggerFactory.stopRequestTrigger     = false;
        //Inserindo lista de Boletins
        insert listBMs;

        list<T_MODEC_StatusBoletim_WS.Itemrequest> Listrequest = new list<T_MODEC_StatusBoletim_WS.Itemrequest>();
        for (TW1_Request__c BM:listBMs)
        {
            T_MODEC_StatusBoletim_WS.Itemrequest itemReq = new T_MODEC_StatusBoletim_WS.Itemrequest();
            itemReq.ENTRYSHEET = BM.TW1_BM_Reference_Number_in_SAP_MODEC__c;
            itemReq.STATUS     = '1';
            itemReq.MESSAGE    = '';
            Listrequest.add(itemReq);
        }

        //Adicionado um ItemRequest com um Numero de referencia inexistente na base
        T_MODEC_StatusBoletim_WS.Itemrequest itemReqInexistente = new T_MODEC_StatusBoletim_WS.Itemrequest();
        itemReqInexistente.ENTRYSHEET = '8885552221';
        itemReqInexistente.STATUS     = '1';
        itemReqInexistente.MESSAGE    = '';
        Listrequest.add(itemReqInexistente);


        T_MODEC_StatusBoletim_WS.StatusRequest REQUEST = new T_MODEC_StatusBoletim_WS.StatusRequest();
        REQUEST.item = Listrequest;

        Test.startTest();
        //Chamando método do serviço rest
        T_MODEC_StatusBoletim_WS.Response response = T_MODEC_StatusBoletim_WS.receberStatusBoletins(REQUEST);
        T_SDK_DebugLog.EscreverLog('Response Status BM>>' + response);
        //for(T_MODEC_StatusBoletim_WS.ItemResponse iResponse:response.RESPONSE){
        //  system.assertEquals('x', iResponse.PROCESSADO);
        //}
        Test.stopTest();
        //Validando se os BMs tiveram status atualizados
        list<TW1_Request__c> listaBoletins = [Select id, BM_Status__c from TW1_Request__c where TW1_Vendor__c =:contamock.id];
        for (TW1_Request__c req:listaBoletins)
        {
            system.assertEquals('Aceita', req.BM_Status__c);
        }
    }
}