force-app/main/default/objects/Account/fields/TW1_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>TW1_Contact_Name__c</fullName>
    <label>Contact Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_Shelf_Life_Vetting_Date__c.field-meta.xml
<CustomField>
    <fullName>TW1_Shelf_Life_Vetting_Date__c</fullName>
    <label>Vetting expiration date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_Vendor_Vetting__c.field-meta.xml
<CustomField>
    <fullName>TW1_Vendor_Vetting__c</fullName>
    <defaultValue>&quot;Vetting Not Requested&quot;</defaultValue>
    <label>Vendor Vetting</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>No Registered</fullName>
            </value>
            <value>
                <fullName>Ongoing</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Vetting Not Requested</fullName>
            </value>
            <value>
                <fullName>Vetting Rejected</fullName>
            </value>
            <value>
                <fullName>Vetting Approved with Red Flag</fullName>
            </value>
            <value>
                <fullName>Vetting Approved</fullName>
            </value>
            <value>
                <fullName>Vetting Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/TW1_Vendor_Homologated.recordType-meta.xml
<RecordType>
    <fullName>TW1_Vendor_Homologated</fullName>
    <active>true</active>
    <label>Supplier Homologated</label>
</RecordType>

force-app/main/default/objects/Controle_de_Triggers__c/Controle_de_Triggers__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Controle de triggers para facilitar controle de acesso e configuração.</description>
    <label>Controle de Triggers</label>
</CustomObject>

force-app/main/default/objects/Controle_de_Triggers__c/fields/Trigger_Account__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Trigger Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Controle_de_Triggers__c/fields/Trigger_Request__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Request__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Trigger_Request</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ID_Account__c/ID_Account__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ID - Account</label>
</CustomObject>

force-app/main/default/objects/ID_Account__c/fields/Id_IntegrationUser__c.field-meta.xml
<CustomField>
    <fullName>Id_IntegrationUser__c</fullName>
    <label>Id_IntegrationUser</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/T_Debug_Setting__mdt/T_Debug_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Configurações de Debug</description>
    <label>Triscal debug setting</label>
    <pluralLabel>Triscal debug setting</pluralLabel>
</CustomObject>

force-app/main/default/objects/T_Debug_Setting__mdt/fields/T_Armazenar_Cause__c.field-meta.xml
<CustomField>
    <fullName>T_Armazenar_Cause__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Se true armazena a causa da exception caso exista</description>
    <label>Armazenar Cause?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/T_Debug_Setting__mdt/fields/T_Armazenar_linha_debug__c.field-meta.xml
<CustomField>
    <fullName>T_Armazenar_linha_debug__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Se true armazena linha de debug</description>
    <label>Armazenar linha debug?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/T_Debug_Setting__mdt/fields/T_Armazenar_StackTrace__c.field-meta.xml
<CustomField>
    <fullName>T_Armazenar_StackTrace__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Se true então armazena o StackTrace da exceção</description>
    <inlineHelpText>Se true então armazena o StackTrace da exceção</inlineHelpText>
    <label>Armazenar StackTrace?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/T_Debug_Setting__mdt/fields/T_Armazenar_texto_Exception__c.field-meta.xml
<CustomField>
    <fullName>T_Armazenar_texto_Exception__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Se true então armazena o texto da exceção</description>
    <inlineHelpText>Se true então armazena o texto da exceção</inlineHelpText>
    <label>Armazenar texto Exception?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/T_MODEC_ExpirarConta_TST.cls
/**
 * @File Name          : T_MODEC_ExpirarConta_TST.cls
 * @Description        :
 * @Author             : Mario Oliveira
 * @Group              :
 * @Last Modified By   : Rafael Hadama
 * @Last Modified On   : 30/01/2020 16:37:44
 * @Modification Log   :
 * Ver       Date            Author              Modification
 * 1.0    18/11/2019   Mario Oliveira     Initial Version
 **/
@isTest
public with sharing class T_MODEC_ExpirarConta_TST {
   static void MakeMetadataAndCustomSettings()
   {
      system.debug('Teste system debug dentro do testSetupmetodo');
      T_Debug_Setting__mdt testSetting = new T_Debug_Setting__mdt();
      testSetting.Label                          = 'Teste';
      testSetting.DeveloperName                  = 'Teste';
      testSetting.T_Armazenar_Cause__c           = true;
      testSetting.T_Armazenar_linha_debug__c     = true;
      testSetting.T_Armazenar_StackTrace__c      = true;
      testSetting.T_Armazenar_texto_Exception__c = true;
      T_SDK_DebugLog_Test.testSetting            = testSetting;

      //Creating Custom Settings
      ID_Account__c customSettingIdAccount = new ID_Account__c();
      customSettingIdAccount.Id_IntegrationUser__c = UserInfo.getUserId();
      insert customSettingIdAccount;

      Controle_de_Triggers__c customControleTrigger = new Controle_de_Triggers__c();
      customControleTrigger.Trigger_Request__c = true;
      customControleTrigger.Trigger_Account__c = true;
      insert customControleTrigger;
   }

   @isTest public static void ExpirarConta_TST()
   {
      MakeMetadataAndCustomSettings();
      RecordType recAcc = [SELECT Id, DeveloperName, SObjectType FROM RecordType WHERE SObjectType = 'Account' And DeveloperName = 'TW1_Vendor_Homologated'];

      Account conta = new Account();
      conta.Name = 'Mario Teste';
      conta.TW1_Shelf_Life_Vetting_Date__c = Date.today().addDays(-2);
      conta.RecordTypeId        = recAcc.id;
      conta.TW1_Contact_Name__c = 'Contato Mock';
      insert conta;

      Test.startTest();
      T_SDK_ScheaduleUtils.scheadule('T_MODEC_SCH_ExpirarConta', 1);
      Test.stopTest();

      Account accTest = [SELECT Id, RecordTypeId, TW1_Vendor_Vetting__c FROM Account where id =: conta.id];

      System.assertEquals('Vetting Expired', accTest.TW1_Vendor_Vetting__c, 'Campo "TW1_Vendor_Vetting__c" diferente de "No Registered"');
      System.assertEquals(true, accTest.RecordTypeId != recAcc.id, 'Mudou o Recordtype');
   }
}