force-app/main/default/objects/Account/fields/TW1_CNPJ__c.field-meta.xml
<CustomField>
    <fullName>TW1_CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_Contact_email_address__c.field-meta.xml
<CustomField>
    <fullName>TW1_Contact_email_address__c</fullName>
    <label>Contact email address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>TW1_Contact_Name__c</fullName>
    <label>Contact Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>TW1_Contact_Phone__c</fullName>
    <label>Contact Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_CPF__c.field-meta.xml
<CustomField>
    <fullName>TW1_CPF__c</fullName>
    <label>CPF</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_Shelf_Life_Vetting_Date__c.field-meta.xml
<CustomField>
    <fullName>TW1_Shelf_Life_Vetting_Date__c</fullName>
    <label>Vetting expiration date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_Step_Owner__c.field-meta.xml
<CustomField>
    <fullName>TW1_Step_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Step Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Supplier</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_Vendor_Vetting__c.field-meta.xml
<CustomField>
    <fullName>TW1_Vendor_Vetting__c</fullName>
    <defaultValue>&quot;Vetting Not Requested&quot;</defaultValue>
    <label>Vendor Vetting</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>No Registered</fullName>
            </value>
            <value>
                <fullName>Ongoing</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Vetting Not Requested</fullName>
            </value>
            <value>
                <fullName>Vetting Rejected</fullName>
            </value>
            <value>
                <fullName>Vetting Approved with Red Flag</fullName>
            </value>
            <value>
                <fullName>Vetting Approved</fullName>
            </value>
            <value>
                <fullName>Vetting Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/TW1_Vendor_Homologated.recordType-meta.xml
<RecordType>
    <fullName>TW1_Vendor_Homologated</fullName>
    <active>true</active>
    <label>Supplier Homologated</label>
</RecordType>

force-app/main/default/objects/TW1_Category__c/TW1_Category__c.object-meta.xml
<CustomObject>
    <label>Category</label>
    <nameField>
        <displayFormat>CT{000000}</displayFormat>
        <label>Category Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Category__c/fields/TW1_Category__c.field-meta.xml
<CustomField>
    <fullName>TW1_Category__c</fullName>
    <label>Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Category__c/fields/TW1_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>TW1_Sub_Category__c</fullName>
    <label>Sub-Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Category__c/recordTypes/TW1_Material.recordType-meta.xml
<RecordType>
    <fullName>TW1_Material</fullName>
    <active>true</active>
    <label>Material</label>
</RecordType>

force-app/main/default/objects/TW1_Category__c/recordTypes/TW1_Service.recordType-meta.xml
<RecordType>
    <fullName>TW1_Service</fullName>
    <active>true</active>
    <label>Service</label>
</RecordType>

force-app/main/default/objects/TW1_Vendor_Category__c/TW1_Vendor_Category__c.object-meta.xml
<CustomObject>
    <description>Antigo Vendor category</description>
    <label>Supplier Category</label>
    <nameField>
        <displayFormat>VC{00000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suppliers Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Vendor_Category__c/fields/TW1_Category__c.field-meta.xml
<CustomField>
    <fullName>TW1_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <referenceTo>TW1_Category__c</referenceTo>
    <relationshipName>Vendors_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Vendor_Category__c/fields/TW1_Vendor__c.field-meta.xml
<CustomField>
    <fullName>TW1_Vendor__c</fullName>
    <label>Supplier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Suppliers Categories</relationshipLabel>
    <relationshipName>Vendors_Categories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/T_MODEC_Account_REP_TST.cls
@isTest
public class T_MODEC_Account_REP_TST {
    Private static Id vendorHomologated = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('TW1_Vendor_Homologated').getRecordTypeId();
    Private static Id material = Schema.SObjectType.TW1_Category__c.getRecordTypeInfosByDeveloperName().get('TW1_Material').getRecordTypeId();
  	Private static Id service = Schema.SObjectType.TW1_Category__c.getRecordTypeInfosByDeveloperName().get('TW1_Service').getRecordTypeId();

    @TestSetup
    public static void TestSetup(){
		List<SObject> listSObject = new List<SObject>();        
        
        Account acc = new Account();
        acc.RecordTypeId = vendorHomologated;
        acc.TW1_CNPJ__c = '00151720000158';
        acc.TW1_CPF__c = '17582277023';
        acc.Name = 'TestAcc HPB';
        acc.TW1_Contact_Name__c = 'TestCont HPB';
        acc.TW1_Contact_Phone__c = '(11) 1 1111-1111';
        acc.TW1_Contact_email_address__c = 'test@test.com.br';
		acc.TW1_Shelf_Life_Vetting_Date__c = Date.today().addDays(-2);        
        insert acc;        
        
        Contact cont = new Contact();
        cont.LastName = 'TestCont HPB';
        cont.Email = 'test@test.com.br';
        cont.Phone = '(11) 1 1111-1111';
        cont.AccountId = acc.id;
        insert cont;        
        
        User newUser = new User();
        newUser.profileId = '00e3i000000uGicAAE';
        newUser.username = 'userTest@test.com';
        newUser.email = 'test@test.com';
        newUser.emailencodingkey = 'ISO-8859-1';
        newUser.localesidkey = 'pt_BR';
        newUser.languagelocalekey = 'en_US';
        newUser.timezonesidkey = 'America/Sao_Paulo';
        newUser.alias='nuser';
        newUser.lastname='lastname';
        newUser.contactId = cont.id;
        listSObject.add(newUser);
        
        TW1_Category__c categm = new TW1_Category__c();
        categm.RecordTypeId = material;
		categm.TW1_Category__c = 'TesteCategoriaMaterial';
    	categm.TW1_Sub_Category__c  = 'TesteSubCategoriaMaterial';
        listSObject.add(categm);
        
        TW1_Category__c categs = new TW1_Category__c();
        categs.RecordTypeId = service;
		categs.TW1_Category__c = 'TesteCategoriaService';
    	categs.TW1_Sub_Category__c  = 'TesteSubCategoriaService'; 
        listSObject.add(categs);       
        
        insert listSObject;
        
        TW1_Vendor_Category__c  supplierCategory = new TW1_Vendor_Category__c();        
    	supplierCategory.TW1_Category__c = categm.id;
        supplierCategory.TW1_Vendor__c = acc.id;
        insert supplierCategory;
        
        
        supplierCategory = new TW1_Vendor_Category__c();        
    	supplierCategory.TW1_Category__c = categs.id;
        supplierCategory.TW1_Vendor__c = acc.id;
        insert supplierCategory;
        
        acc.TW1_Step_Owner__c = newUser.id;
        update acc;
    }
    
    @isTest
    public static void TestMethod_getPicklistVendorVetting(){        
        Account acc = [SELECT id, TW1_CNPJ__c  FROM Account LIMIT 1];
         List<Schema.PicklistEntry> entries = T_MODEC_Account_REP.getPicklistVendorVetting('TW1_Vendor_Vetting__c');
    }
    
    
    @isTest
    public static void TestMethod_getVendorCategoryById(){        
        Account acc = [SELECT id, TW1_CNPJ__c  FROM Account LIMIT 1];
        List<TW1_Vendor_Category__c> listVendorCategory = T_MODEC_Account_REP.getVendorCategoryById(acc.id);
    }
    
    @isTest
    public static void TestMethod_buscarContasExpiradas(){
        
        list<Account> listAccount = T_MODEC_Account_REP.buscarContasExpiradas();
    }
    
    @isTest
    public static void TestMethod_SearchAccountByCNPJ(){
        Account acc = [SELECT id, TW1_CNPJ__c  FROM Account LIMIT 1];
        T_MODEC_Account_REP accRep = new T_MODEC_Account_REP();       
        list<Account> listAccount = accRep.SearchAccountByCNPJ(acc.TW1_CNPJ__c);
    }
    
    @isTest
    public static void TestMethod_getSuppliersByNameAndCategoryType_Service(){
        
        list<Account> listAccount = T_MODEC_Account_REP.getSuppliersByNameAndCategoryType('TestAcc HPB', 'TW1_Service', 'Active');
    }
    
    @isTest
    public static void TestMethod_getSuppliersByNameAndCategoryType_Material(){
        
        list<Account> listAccount = T_MODEC_Account_REP.getSuppliersByNameAndCategoryType('TestAcc HPB', 'TW1_Material', 'Active');
    }
    
    @isTest
    public static void TestMethod_getSuppliersByCategoryAndSubCategory(){
        list<Account> listAccount = T_MODEC_Account_REP.getSuppliersByCategoryAndSubCategory('TesteCategoriaService', 'TesteSubCategoriaService', ' ');
    }
}