force-app/main/default/objects/Account/fields/TW1_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>TW1_Contact_Name__c</fullName>
    <label>Contact Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_CPF__c.field-meta.xml
<CustomField>
    <fullName>TW1_CPF__c</fullName>
    <label>CPF</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/TW1_Vendor_Homologated.recordType-meta.xml
<RecordType>
    <fullName>TW1_Vendor_Homologated</fullName>
    <active>true</active>
    <label>Supplier Homologated</label>
</RecordType>

force-app/main/default/objects/Controle_de_Triggers__c/Controle_de_Triggers__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Controle de triggers para facilitar controle de acesso e configuração.</description>
    <label>Controle de Triggers</label>
</CustomObject>

force-app/main/default/objects/Controle_de_Triggers__c/fields/Trigger_Account__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Trigger Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Controle_de_Triggers__c/fields/Trigger_Request__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Request__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Trigger_Request</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Controle_de_Triggers__c/fields/Triscal_User_Id__c.field-meta.xml
<CustomField>
    <fullName>Triscal_User_Id__c</fullName>
    <description>User Id, for Triscal support.</description>
    <label>Triscal User Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ID_Account__c/ID_Account__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ID - Account</label>
</CustomObject>

force-app/main/default/objects/ID_Account__c/fields/Id_IntegrationUser__c.field-meta.xml
<CustomField>
    <fullName>Id_IntegrationUser__c</fullName>
    <label>Id_IntegrationUser</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/T_Debug_Setting__mdt/T_Debug_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Configurações de Debug</description>
    <label>Triscal debug setting</label>
    <pluralLabel>Triscal debug setting</pluralLabel>
</CustomObject>

force-app/main/default/objects/T_Debug_Setting__mdt/fields/T_Armazenar_Cause__c.field-meta.xml
<CustomField>
    <fullName>T_Armazenar_Cause__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Se true armazena a causa da exception caso exista</description>
    <label>Armazenar Cause?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/T_Debug_Setting__mdt/fields/T_Armazenar_linha_debug__c.field-meta.xml
<CustomField>
    <fullName>T_Armazenar_linha_debug__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Se true armazena linha de debug</description>
    <label>Armazenar linha debug?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/T_Debug_Setting__mdt/fields/T_Armazenar_StackTrace__c.field-meta.xml
<CustomField>
    <fullName>T_Armazenar_StackTrace__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Se true então armazena o StackTrace da exceção</description>
    <inlineHelpText>Se true então armazena o StackTrace da exceção</inlineHelpText>
    <label>Armazenar StackTrace?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/T_Debug_Setting__mdt/fields/T_Armazenar_texto_Exception__c.field-meta.xml
<CustomField>
    <fullName>T_Armazenar_texto_Exception__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Se true então armazena o texto da exceção</description>
    <inlineHelpText>Se true então armazena o texto da exceção</inlineHelpText>
    <label>Armazenar texto Exception?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TW1_Step__c/TW1_Step__c.object-meta.xml
<CustomObject>
    <label>Step</label>
    <nameField>
        <displayFormat>S{000000}</displayFormat>
        <label>Steps Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Step__c/fields/TW1_VVW_Doc_Uploaded__c.field-meta.xml
<CustomField>
    <fullName>TW1_VVW_Doc_Uploaded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>VVW Doc Uploaded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TW1_Step__c/recordTypes/BM_NF.recordType-meta.xml
<RecordType>
    <fullName>BM_NF</fullName>
    <active>true</active>
    <label>BM - NF</label>
</RecordType>

force-app/main/default/classes/T_MODEC_UploadVVWDocTST.cls
/**
 * @File Name          : T_MODEC_UploadVVWDocTST.cls
 * @Description        : 
 * @Author             : Rafael Hadama
 * @Group              : 
 * @Last Modified By   : Rafael Hadama
 * @Last Modified On   : 10/02/2020 13:10:23
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    05/02/2020   Rafael Hadama     Initial Version
**/
@IsTest
public class T_MODEC_UploadVVWDocTST {
    static void MakeMetadataAndCustomSettings()
   {
    system.debug('Teste system debug dentro do testSetupmetodo');
    T_Debug_Setting__mdt testSetting = new T_Debug_Setting__mdt();
    testSetting.Label                          = 'Teste';
    testSetting.DeveloperName                  = 'Teste';
    testSetting.T_Armazenar_Cause__c           = true;
    testSetting.T_Armazenar_linha_debug__c     = true;
    testSetting.T_Armazenar_StackTrace__c      = true;
    testSetting.T_Armazenar_texto_Exception__c = true;
    T_SDK_DebugLog_Test.testSetting            = testSetting;

    //Creating Custom Settings
    ID_Account__c customSettingIdAccount = new ID_Account__c();
    customSettingIdAccount.Id_IntegrationUser__c = UserInfo.getUserId();
    insert customSettingIdAccount;

    Controle_de_Triggers__c customControleTrigger = new Controle_de_Triggers__c();
    customControleTrigger.Trigger_Request__c = true;
    customControleTrigger.Trigger_Account__c = true;
    customControleTrigger.Triscal_User_Id__c = UserInfo.getUserId();
    insert customControleTrigger;
   }

   
   @isTest public static void CreateDocumentationVVWAuxiliarTST()
   {
      MakeMetadataAndCustomSettings();
      
      Test.startTest();
      string DocCreatedId = T_MODEC_UploadVVWDoc_CTRL.createDocumentationVVWAuxiliar();
      Test.stopTest();
      
      System.assertEquals(true,DocCreatedId != '');
   }

   
   @isTest public static void UpdateDocumentationVVWAuxiliarTST()
   {
      MakeMetadataAndCustomSettings();
      RecordType accRec_VendorHomologated = [Select id from Recordtype where developername = 'TW1_Vendor_Homologated'];
      Account    contamock = new Account();

      contamock.recordtypeId        = accRec_VendorHomologated.id;
      contamock.name                = 'Conta ENVIO Boletim';
      contamock.TW1_CPF__c          = '57034551030';
      contamock.TW1_Contact_Name__c = 'Contato Mock';
      insert contamock;

      //Query no recordType e criação do Request do tipo BM
      RecordType  StepRec_BMNF = [Select id from Recordtype where developername = 'BM_NF'];
      TW1_Step__c StepMock      = new TW1_Step__c();
      StepMock.RecordTypeId = StepRec_BMNF.Id;


      insert StepMock;

      
      Test.startTest();
      string DocCreatedId = T_MODEC_UploadVVWDoc_CTRL.createDocumentationVVWAuxiliar();

      string DocUpdatedId = T_MODEC_UploadVVWDoc_CTRL.updateDocumentationVVWAuxiliar(DocCreatedId,StepMock.Id,'Comments Mock');
      Test.stopTest();
      
      System.assertEquals(true,DocUpdatedId != '');
   }

   @isTest public static void UpdateStepTST()
   {
      MakeMetadataAndCustomSettings();
      RecordType accRec_VendorHomologated = [Select id from Recordtype where developername = 'TW1_Vendor_Homologated'];
      Account    contamock = new Account();

      contamock.recordtypeId        = accRec_VendorHomologated.id;
      contamock.name                = 'Conta ENVIO Boletim';
      contamock.TW1_CPF__c          = '57034551030';
      contamock.TW1_Contact_Name__c = 'Contato Mock';
      insert contamock;

      //Query no recordType e criação do Request do tipo BM
      RecordType  StepRec_BMNF = [Select id from Recordtype where developername = 'BM_NF'];
      TW1_Step__c StepMock      = new TW1_Step__c();
      StepMock.RecordTypeId = StepRec_BMNF.Id;


      insert StepMock;

      
      Test.startTest();
      T_MODEC_UploadVVWDoc_CTRL.updateStep(StepMock.Id);      
      Test.stopTest();
      TW1_Step__c step = [Select Id,TW1_VVW_Doc_Uploaded__c  from TW1_Step__c where Id =:StepMock.Id ];
      System.assertEquals(true,step.TW1_VVW_Doc_Uploaded__c);
   }
}