force-app/main/default/objects/Account/fields/TW1_Country__c.field-meta.xml
<CustomField>
    <fullName>TW1_Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>Senegal</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia-Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Brunei</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Burkina</fullName>
            </value>
            <value>
                <fullName>Burma</fullName>
            </value>
            <value>
                <fullName>Burundi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Controle_de_Triggers__c/Controle_de_Triggers__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Controle de triggers para facilitar controle de acesso e configuração.</description>
    <label>Controle de Triggers</label>
</CustomObject>

force-app/main/default/objects/Controle_de_Triggers__c/fields/Trigger_Account__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Trigger Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Controle_de_Triggers__c/fields/Trigger_Request__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Request__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Trigger_Request</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ID_Account__c/ID_Account__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ID - Account</label>
</CustomObject>

force-app/main/default/objects/ID_Account__c/fields/Id_IntegrationUser__c.field-meta.xml
<CustomField>
    <fullName>Id_IntegrationUser__c</fullName>
    <label>Id_IntegrationUser</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Supplier_Portal_Content__c/Supplier_Portal_Content__c.object-meta.xml
<CustomObject>
    <description>Object to store information to be displayed on the supplier&apos;s portal website.</description>
    <label>Supplier Portal Content</label>
    <nameField>
        <label>Supplier Portal Content Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Portal Contents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Portal_Content__c/fields/TW1_Page_Language__c.field-meta.xml
<CustomField>
    <fullName>TW1_Page_Language__c</fullName>
    <label>Page Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>Portuguese</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Supplier_Portal_Content__c/recordTypes/Supplier_Portal_Senegal.recordType-meta.xml
<RecordType>
    <fullName>Supplier_Portal_Senegal</fullName>
    <active>true</active>
    <description>Content do portal destinado a Senegal</description>
    <label>Supplier Portal Senegal</label>
</RecordType>

force-app/main/default/objects/T_Debug_Setting__mdt/T_Debug_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Configurações de Debug</description>
    <label>Triscal debug setting</label>
    <pluralLabel>Triscal debug setting</pluralLabel>
</CustomObject>

force-app/main/default/objects/T_Debug_Setting__mdt/fields/T_Armazenar_Cause__c.field-meta.xml
<CustomField>
    <fullName>T_Armazenar_Cause__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Se true armazena a causa da exception caso exista</description>
    <label>Armazenar Cause?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/T_Debug_Setting__mdt/fields/T_Armazenar_linha_debug__c.field-meta.xml
<CustomField>
    <fullName>T_Armazenar_linha_debug__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Se true armazena linha de debug</description>
    <label>Armazenar linha debug?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/T_Debug_Setting__mdt/fields/T_Armazenar_StackTrace__c.field-meta.xml
<CustomField>
    <fullName>T_Armazenar_StackTrace__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Se true então armazena o StackTrace da exceção</description>
    <inlineHelpText>Se true então armazena o StackTrace da exceção</inlineHelpText>
    <label>Armazenar StackTrace?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/T_Debug_Setting__mdt/fields/T_Armazenar_texto_Exception__c.field-meta.xml
<CustomField>
    <fullName>T_Armazenar_texto_Exception__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Se true então armazena o texto da exceção</description>
    <inlineHelpText>Se true então armazena o texto da exceção</inlineHelpText>
    <label>Armazenar texto Exception?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TW1_Category__c/TW1_Category__c.object-meta.xml
<CustomObject>
    <label>Category</label>
    <nameField>
        <displayFormat>CT{000000}</displayFormat>
        <label>Category Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Category__c/fields/TW1_Category__c.field-meta.xml
<CustomField>
    <fullName>TW1_Category__c</fullName>
    <label>Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Category__c/fields/TW1_Code__c.field-meta.xml
<CustomField>
    <fullName>TW1_Code__c</fullName>
    <label>Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Category__c/fields/TW1_Country__c.field-meta.xml
<CustomField>
    <fullName>TW1_Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Category__c/fields/TW1_Material_Group__c.field-meta.xml
<CustomField>
    <fullName>TW1_Material_Group__c</fullName>
    <label>Material Group</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Category__c/fields/TW1_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>TW1_Sub_Category__c</fullName>
    <label>Sub-Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Category__c/recordTypes/TW1_Material.recordType-meta.xml
<RecordType>
    <fullName>TW1_Material</fullName>
    <active>true</active>
    <label>Material</label>
</RecordType>

force-app/main/default/objects/TW1_Category__c/recordTypes/TW1_Service.recordType-meta.xml
<RecordType>
    <fullName>TW1_Service</fullName>
    <active>true</active>
    <label>Service</label>
</RecordType>

force-app/main/default/classes/T_MODEC_SenegalCadastroTest.cls
/**
 * @File Name          : T_MODEC_SenegalCadastroTest.cls
 * @Description        :
 * @Author             : Rafael Hadama
 * @Group              :
 * @Last Modified By   : Rafael Hadama
 * @Last Modified On   : 10-15-2020
 * @Modification Log   :
 * Ver       Date            Author              Modification
 * 1.0    01/07/2020   Rafael Hadama     Initial Version
 **/
@isTest
public class T_MODEC_SenegalCadastroTest {
    /**
     * @description Criando massa de teste para cadastro de um novo fornecedor
     * @author Felipe Cardozo | 05/12/2019
     * @return void
     **/
    @testSetup static void Setup()
    {
        RecordType tipoMaterial = [SELECT id, DeveloperName FROM RecordType WHERE SobjectType = 'TW1_Category__c' AND DeveloperName = 'TW1_Material'];
        RecordType tipoService  = [SELECT id, DeveloperName FROM RecordType WHERE SobjectType = 'TW1_Category__c' AND DeveloperName = 'TW1_Service'];

        // Criando categorias para serem selecionadas e testada.
        TW1_Category__c categoriaServico = new TW1_Category__c();

        categoriaServico.RecordTypeId          = tipoService.Id;
        categoriaServico.TW1_Category__c       = 'Serv Catering Offshore';
        categoriaServico.TW1_Sub_Category__c   = 'Catering Offshore';
        categoriaServico.TW1_Code__c           = 'SERV_14.01';
        categoriaServico.TW1_Material_Group__c = '36814000';
        categoriaServico.TW1_Country__c        = 'Brazil';

        TW1_Category__c categoriaMaterial = new TW1_Category__c();
        categoriaMaterial.RecordTypeId          = tipoMaterial.Id;
        categoriaMaterial.TW1_Category__c       = 'Mail and cargo transport';
        categoriaMaterial.TW1_Material_Group__c = '78100000';
        categoriaMaterial.TW1_Country__c        = 'Brazil';


        insert new TW1_Category__c[] { categoriaServico, categoriaMaterial };

        //Buscando Usuário de integração para preencher custom settings devido ao process builder Account - General process
        //User userIntegracao = [Select id from User where Name = 'Modec Integração'];
        ID_Account__c customSettingsIDAccount = new ID_Account__c();
        customSettingsIDAccount.Id_IntegrationUser__c = UserInfo.getUserId();
        insert customSettingsIDAccount;
    }

    @istest static void TesteCadastroFornecedorSucesso()
    {
        List<TW1_Category__c> categorias = [SELECT id, TW1_Category__c FROM TW1_Category__c];

        T_MODEC_SenegalCadastroCtrl.CadastroFornecedorDto cadastroFornecedorDto = new T_MODEC_SenegalCadastroCtrl.CadastroFornecedorDto();
        cadastroFornecedorDto.NomeEmpresa        = 'Empresa de teste LTDA';
        cadastroFornecedorDto.NomeFantasia       = 'Empresa de teste';
        cadastroFornecedorDto.Email              = 'Empresa@email.com';
        cadastroFornecedorDto.TipoFornecedor     = 'MUNICIPALITY';
        cadastroFornecedorDto.Endereco           = 'Rua teste, 134 - Bairro';
        cadastroFornecedorDto.Cidade             = 'Cidade';
        cadastroFornecedorDto.Estado             = 'Estado';
        cadastroFornecedorDto.Pais               = 'Brazil';
        cadastroFornecedorDto.ContatoResponsavel = 'Contato teste';
        cadastroFornecedorDto.ContatoTelefone    = '212345678';
        cadastroFornecedorDto.ContatoEmail       = 'conato@email.com.br';

        Map<String, T_MODEC_SenegalCadastroCtrl.CategoriaDTO> mapCategorias = new Map<String, T_MODEC_SenegalCadastroCtrl.CategoriaDTO>();
        for (TW1_Category__c cat : categorias)
        {
            T_MODEC_SenegalCadastroCtrl.CategoriaDTO categoriaDto = new T_MODEC_SenegalCadastroCtrl.CategoriaDTO();
            categoriaDto.value = cat.Id;
            mapCategorias.put(cat.Id, categoriaDto);
        }
        cadastroFornecedorDto.CategoriasSelecionadas = mapCategorias;

        String jsonTeste = JSON.serialize(cadastroFornecedorDto);
        T_MODEC_SenegalCadastroCtrl.SalvarCadastroFornecedor(jsonTeste);
    }

    @istest static void TestaBuscarCategoriasEPickList()
    {
        T_MODEC_SenegalCadastroCtrl.getCategorias();
        T_MODEC_SenegalCadastroCtrl.montarCamposPicklists();

        string strJson = T_MODEC_SenegalCadastroCtrl.getCategoriesDTO();
        System.assert (!string.isEmpty(strJson));
    }

    @isTest static void testSupplierContents()
    {
        list<Supplier_Portal_Content__c> listDML             = new List<Supplier_Portal_Content__c>();
        Supplier_Portal_Content__c       spContentPortuguese = new Supplier_Portal_Content__c();
        string recordtypeSN = Schema.SObjectType.Supplier_Portal_Content__c.getRecordTypeInfosByDeveloperName().get('Supplier_Portal_Senegal').getRecordTypeId();

        spContentPortuguese.name = 'SPContent French';
        spContentPortuguese.TW1_Page_Language__c = 'French';
        spContentPortuguese.recordtypeId         = recordtypeSN;

        listDML.add(spContentPortuguese);
        insert listDML;

        Test.startTest();

        Map<string, Supplier_Portal_Content__c> mapSpContents = T_MODEC_SenegalCadastroCtrl.GetSupplierPortalContent();

        system.debug('mapSpContents :' + mapSpContents);
        system.assertEquals(1, mapSpContents.size());

        Test.stopTest();
    }

    static void MakeMetadataAndCustomSettings()
    {
        system.debug('Teste system debug dentro do testSetupmetodo');
        T_Debug_Setting__mdt testSetting = new T_Debug_Setting__mdt();
        testSetting.Label                          = 'Teste';
        testSetting.DeveloperName                  = 'Teste';
        testSetting.T_Armazenar_Cause__c           = true;
        testSetting.T_Armazenar_linha_debug__c     = true;
        testSetting.T_Armazenar_StackTrace__c      = true;
        testSetting.T_Armazenar_texto_Exception__c = true;
        T_SDK_DebugLog_Test.testSetting            = testSetting;

        //Creating Custom Settings

        /*ID_Account__c customSettingIdAccount = new ID_Account__c();
         * customSettingIdAccount.Id_IntegrationUser__c = UserInfo.getUserId();
         * insert customSettingIdAccount;*/

        Controle_de_Triggers__c customControleTrigger = new Controle_de_Triggers__c();
        customControleTrigger.Trigger_Request__c = true;
        customControleTrigger.Trigger_Account__c = true;
        insert customControleTrigger;
    }
}