force-app/main/default/objects/Account/fields/TW1_CNPJ__c.field-meta.xml
<CustomField>
    <fullName>TW1_CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_Contact_email_address__c.field-meta.xml
<CustomField>
    <fullName>TW1_Contact_email_address__c</fullName>
    <label>Contact email address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>TW1_Contact_Name__c</fullName>
    <label>Contact Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>TW1_Contact_Phone__c</fullName>
    <label>Contact Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_CPF__c.field-meta.xml
<CustomField>
    <fullName>TW1_CPF__c</fullName>
    <label>CPF</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_Shelf_Life_Vetting_Date__c.field-meta.xml
<CustomField>
    <fullName>TW1_Shelf_Life_Vetting_Date__c</fullName>
    <label>Vetting expiration date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_Step_Owner__c.field-meta.xml
<CustomField>
    <fullName>TW1_Step_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Step Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Supplier</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_Vendor_Vetting__c.field-meta.xml
<CustomField>
    <fullName>TW1_Vendor_Vetting__c</fullName>
    <defaultValue>&quot;Vetting Not Requested&quot;</defaultValue>
    <label>Vendor Vetting</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>No Registered</fullName>
            </value>
            <value>
                <fullName>Ongoing</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Vetting Not Requested</fullName>
            </value>
            <value>
                <fullName>Vetting Rejected</fullName>
            </value>
            <value>
                <fullName>Vetting Approved with Red Flag</fullName>
            </value>
            <value>
                <fullName>Vetting Approved</fullName>
            </value>
            <value>
                <fullName>Vetting Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/TW1_Vendor_Homologated.recordType-meta.xml
<RecordType>
    <fullName>TW1_Vendor_Homologated</fullName>
    <active>true</active>
    <label>Supplier Homologated</label>
</RecordType>

force-app/main/default/objects/TOBJ_Participants__c/TOBJ_Participants__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>PN-{YYYY}{MM}-{0000}</displayFormat>
        <label>Nome do Participante</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TOBJ_Participants__c/fields/RequiredSendEmail__c.field-meta.xml
<CustomField>
    <fullName>RequiredSendEmail__c</fullName>
    <formula>TEXT(Warning__r.RequiredSendEmail__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Necessita envio de e-mail?</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TOBJ_Participants__c/fields/TCF_Supplier__c.field-meta.xml
<CustomField>
    <fullName>TCF_Supplier__c</fullName>
    <label>Fornecedor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>TRN_ParticipantsAccount</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TOBJ_Participants__c/fields/Warning__c.field-meta.xml
<CustomField>
    <fullName>Warning__c</fullName>
    <label>Warning</label>
    <referenceTo>TOBJ_Warning__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>TRN_ParticipantsWarning</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TOBJ_Warning__c/TOBJ_Warning__c.object-meta.xml
<CustomObject>
    <label>Warning</label>
    <nameField>
        <displayFormat>WARN-{00000000}</displayFormat>
        <label>Nome do Aviso</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Warning</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/TOBJ_Warning__c/fields/PublicationDate__c.field-meta.xml
<CustomField>
    <fullName>PublicationDate__c</fullName>
    <label>Data de publicação</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TOBJ_Warning__c/fields/RequiredSendEmail__c.field-meta.xml
<CustomField>
    <fullName>RequiredSendEmail__c</fullName>
    <label>Requer envio de e-mail?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TOBJ_Warning__c/fields/TCF_DueDate__c.field-meta.xml
<CustomField>
    <fullName>TCF_DueDate__c</fullName>
    <label>Data de vencimento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TOBJ_Warning__c/fields/TCF_HSEQWarning__c.field-meta.xml
<CustomField>
    <fullName>TCF_HSEQWarning__c</fullName>
    <label>Comunicado HSEQ?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TOBJ_Warning__c/fields/TCF_Notice__c.field-meta.xml
<CustomField>
    <fullName>TCF_Notice__c</fullName>
    <label>Notícia</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/TOBJ_Warning__c/fields/TCF_RequiresConfirmation__c.field-meta.xml
<CustomField>
    <fullName>TCF_RequiresConfirmation__c</fullName>
    <label>Requer confirmação?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TOBJ_Warning__c/fields/TCF_Subject__c.field-meta.xml
<CustomField>
    <fullName>TCF_Subject__c</fullName>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Category__c/TW1_Category__c.object-meta.xml
<CustomObject>
    <label>Category</label>
    <nameField>
        <displayFormat>CT{000000}</displayFormat>
        <label>Category Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Category__c/fields/TW1_Category__c.field-meta.xml
<CustomField>
    <fullName>TW1_Category__c</fullName>
    <label>Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Category__c/fields/TW1_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>TW1_Sub_Category__c</fullName>
    <label>Sub-Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Category__c/recordTypes/TW1_Material.recordType-meta.xml
<RecordType>
    <fullName>TW1_Material</fullName>
    <active>true</active>
    <label>Material</label>
</RecordType>

force-app/main/default/objects/TW1_Category__c/recordTypes/TW1_Service.recordType-meta.xml
<RecordType>
    <fullName>TW1_Service</fullName>
    <active>true</active>
    <label>Service</label>
</RecordType>

force-app/main/default/objects/TW1_Vendor_Category__c/TW1_Vendor_Category__c.object-meta.xml
<CustomObject>
    <description>Antigo Vendor category</description>
    <label>Supplier Category</label>
    <nameField>
        <displayFormat>VC{00000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suppliers Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Vendor_Category__c/fields/TW1_Category__c.field-meta.xml
<CustomField>
    <fullName>TW1_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <referenceTo>TW1_Category__c</referenceTo>
    <relationshipName>Vendors_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Vendor_Category__c/fields/TW1_Vendor__c.field-meta.xml
<CustomField>
    <fullName>TW1_Vendor__c</fullName>
    <label>Supplier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Suppliers Categories</relationshipLabel>
    <relationshipName>Vendors_Categories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/T_SegmentacaoForcedoresController_TST.cls
@isTest
public class T_SegmentacaoForcedoresController_TST {
    
    Private static Id vendorHomologated = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('TW1_Vendor_Homologated').getRecordTypeId();
    Private static Id material = Schema.SObjectType.TW1_Category__c.getRecordTypeInfosByDeveloperName().get('TW1_Material').getRecordTypeId();
    Private static Id service = Schema.SObjectType.TW1_Category__c.getRecordTypeInfosByDeveloperName().get('TW1_Service').getRecordTypeId();
    
    
    @TestSetup
    public static void TestSetup(){
        List<SObject> listSObject = new List<SObject>();        
        
        Account acc = new Account();
        acc.RecordTypeId = vendorHomologated;
        acc.TW1_CNPJ__c = '00151720000158';
        acc.TW1_CPF__c = '17582277023';
        acc.Name = 'TestAcc HPB';
        acc.TW1_Contact_Name__c = 'TestCont HPB';
        acc.TW1_Contact_Phone__c = '(11) 1 1111-1111';
        acc.TW1_Contact_email_address__c = 'test@test.com.br';
        acc.TW1_Shelf_Life_Vetting_Date__c = Date.today().addDays(-2);        
        insert acc;        
        
        Contact cont = new Contact();
        cont.LastName = 'TestCont HPB';
        cont.Email = 'test@test.com.br';
        cont.Phone = '(11) 1 1111-1111';
        cont.AccountId = acc.id;
        insert cont;        
        
        User newUser = new User();
        newUser.profileId = '00e3i000000uGicAAE';
        newUser.username = 'userTest@test.com';
        newUser.email = 'test@test.com';
        newUser.emailencodingkey = 'ISO-8859-1';
        newUser.localesidkey = 'pt_BR';
        newUser.languagelocalekey = 'en_US';
        newUser.timezonesidkey = 'America/Sao_Paulo';
        newUser.alias='nuser';
        newUser.lastname='lastname';
        newUser.contactId = cont.id;
        listSObject.add(newUser);
        
        TOBJ_Warning__c warning = new TOBJ_Warning__c();
        warning.PublicationDate__c = Date.newInstance(2021, 04, 01);        
        warning.TCF_DueDate__c = Date.newInstance(2021, 06, 15);
        warning.RequiredSendEmail__c = 'No';
        warning.TCF_HSEQWarning__c = 'No';
        warning.TCF_Subject__c = 'Teste de Setup 1';
        warning.TCF_Notice__c = '<p>Teste com warnings 1</p>';
        warning.TCF_RequiresConfirmation__c = 'No';
        listSObject.add(warning);       
        
        warning = new TOBJ_Warning__c();
        warning.PublicationDate__c = Date.newInstance(2021, 04, 28);        
        warning.TCF_DueDate__c = Date.newInstance(2021, 05, 18);
        warning.RequiredSendEmail__c = 'No';
        warning.TCF_HSEQWarning__c = 'No';
        warning.TCF_Subject__c = 'Teste de Setup 2';
        warning.TCF_Notice__c = '<p>Teste com warnings 2</p>';
        warning.TCF_RequiresConfirmation__c = 'No';
        listSObject.add(warning);
        
        warning = new TOBJ_Warning__c();
        warning.PublicationDate__c = Date.newInstance(2021, 04, 15);        
        warning.TCF_DueDate__c = Date.newInstance(2021, 08, 20);
        warning.RequiredSendEmail__c = 'No';
        warning.TCF_HSEQWarning__c = 'No';
        warning.TCF_Subject__c = 'Teste de Setup 3';
        warning.TCF_Notice__c = '<p>Teste com warnings 3</p>';
        warning.TCF_RequiresConfirmation__c = 'No';
        listSObject.add(warning);
        
        TW1_Category__c categm = new TW1_Category__c();
        categm.RecordTypeId = material;
        categm.TW1_Category__c = 'TesteCategoriaMaterial';
        categm.TW1_Sub_Category__c  = 'TesteSubCategoriaMaterial';
        listSObject.add(categm);
        
        TW1_Category__c categs = new TW1_Category__c();
        categs.RecordTypeId = service;
        categs.TW1_Category__c = 'TesteCategoriaService';
        categs.TW1_Sub_Category__c  = 'TesteSubCategoriaService'; 
        listSObject.add(categs);       
        
        insert listSObject;
        
        TW1_Vendor_Category__c  supplierCategory = new TW1_Vendor_Category__c();        
        supplierCategory.TW1_Category__c = categm.id;
        supplierCategory.TW1_Vendor__c = acc.id;
        insert supplierCategory;
        
        
        supplierCategory = new TW1_Vendor_Category__c();        
        supplierCategory.TW1_Category__c = categs.id;
        supplierCategory.TW1_Vendor__c = acc.id;
        insert supplierCategory;
        
        acc.TW1_Step_Owner__c = newUser.id;
        update acc;  
        
        TOBJ_Participants__c participante = new TOBJ_Participants__c();
        participante.TCF_Supplier__c = acc.id;
        participante.Warning__c = warning.id; 
        insert participante;
        
    }
    
    @isTest
    public static void TestMethod_searchForSuppliers_NameFull(){
        T_SegmentacaoForcedoresController.SearchDTO pesquisa = new T_SegmentacaoForcedoresController.SearchDTO();
        pesquisa.SearchType = 'Name'; 
        pesquisa.recordId = [SELECT id FROM TOBJ_Warning__c WHERE TCF_Subject__c = 'Teste de Setup 2' LIMIT 1].id;
        pesquisa.SupplierName = 'TestAcc HPB';
        
        List<SObject> lista = T_SegmentacaoForcedoresController.searchForSuppliers(pesquisa);
		System.assertEquals( 'TestAcc HPB', (String) lista.get(0).get('Name'));         
        
    }
    @isTest
    public static void TestMethod_searchForSuppliers_ImcompleteName(){
        T_SegmentacaoForcedoresController.SearchDTO pesquisa = new T_SegmentacaoForcedoresController.SearchDTO();
        pesquisa.SearchType = 'Name'; 
        pesquisa.recordId = [SELECT id FROM TOBJ_Warning__c WHERE TCF_Subject__c = 'Teste de Setup 2' LIMIT 1].id;
        pesquisa.SupplierName = 'Test';
        
        List<SObject> lista = T_SegmentacaoForcedoresController.searchForSuppliers(pesquisa); 
  		System.assertEquals( 'TestAcc HPB', (String) lista.get(0).get('Name'));         

    }
    
    @isTest
    public static void TestMethod_searchForSuppliers_CategoryRT(){
        T_SegmentacaoForcedoresController.SearchDTO pesquisa = new T_SegmentacaoForcedoresController.SearchDTO();
        pesquisa.SearchType = 'Name'; 
        pesquisa.recordId = [SELECT id FROM TOBJ_Warning__c WHERE TCF_Subject__c = 'Teste de Setup 2' LIMIT 1].id;
        pesquisa.CategoryRT = 'TW1_Material';
        
        List<SObject> lista = T_SegmentacaoForcedoresController.searchForSuppliers(pesquisa);  
        System.assertEquals( 'TestAcc HPB', (String) lista.get(0).get('Name'));         

    }
    
    @isTest
    public static void TestMethod_searchForSuppliers_Category(){
        T_SegmentacaoForcedoresController.SearchDTO pesquisa = new T_SegmentacaoForcedoresController.SearchDTO();
        pesquisa.SearchType = 'Category'; 
        pesquisa.recordId = [SELECT id FROM TOBJ_Warning__c WHERE TCF_Subject__c = 'Teste de Setup 2' LIMIT 1].id;
        pesquisa.Category = 'TesteCategoriaService';        
                
        List<SObject> lista = T_SegmentacaoForcedoresController.searchForSuppliers(pesquisa);
		System.debug('HG - lista: ' + lista);
        System.assertEquals( 'TestAcc HPB', (String) lista.get(0).get('Name'));         
        
    }
    
    @isTest
    public static void TestMethod_searchForSuppliers_SubCategory(){
        T_SegmentacaoForcedoresController.SearchDTO pesquisa = new T_SegmentacaoForcedoresController.SearchDTO();
        pesquisa.SearchType = 'Category';   
        pesquisa.recordId = [SELECT id FROM TOBJ_Warning__c WHERE TCF_Subject__c = 'Teste de Setup 2' LIMIT 1].id;
        pesquisa.SubCategory = 'TesteSubCategoriaMaterial';
        
        List<SObject> lista = T_SegmentacaoForcedoresController.searchForSuppliers(pesquisa);
        System.debug('GUFS: '+(String) lista.get(0).get('Name'));
		System.assertEquals( 'TestAcc HPB', (String) lista.get(0).get('Name'));
    }
    
    @isTest
    public static void TestMethod_searchForSuppliers_CategoryAndSubCategory(){
        T_SegmentacaoForcedoresController.SearchDTO pesquisa = new T_SegmentacaoForcedoresController.SearchDTO();
        pesquisa.SearchType = 'Category';
        pesquisa.recordId = [SELECT id FROM TOBJ_Warning__c WHERE TCF_Subject__c = 'Teste de Setup 2' LIMIT 1].id;
        pesquisa.Category = 'TesteCategoriaService';
        pesquisa.SubCategory = 'TesteSubCategoriaService';
        
        List<SObject> lista = T_SegmentacaoForcedoresController.searchForSuppliers(pesquisa);
		System.assertEquals( 'TestAcc HPB', (String) lista.get(0).get('Name'));        
    }
    
     @isTest
    public static void TestMethod_searchForSuppliers_Participantes(){
        
        T_SegmentacaoForcedoresController.SearchDTO pesquisa = new T_SegmentacaoForcedoresController.SearchDTO();
        pesquisa.SearchType = 'Participantes';
        pesquisa.recordId = [SELECT Warning__c FROM TOBJ_Participants__c limit 1].Warning__c;
        
        List<SObject> lista = T_SegmentacaoForcedoresController.searchForSuppliers(pesquisa); 
        System.assertEquals( 'TestAcc HPB', (String) lista.get(0).getSObject('TCF_Supplier__r').get('Name'));
    }

    @isTest
    public static void TestMethod_addParticipantesApex(){
        TOBJ_Warning__c warning = [SELECT id FROM TOBJ_Warning__c WHERE TCF_Subject__c = 'Teste de Setup 1' LIMIT 1];
        T_SegmentacaoForcedoresController.SearchDTO pesquisa = new T_SegmentacaoForcedoresController.SearchDTO();
        pesquisa.SearchType = 'Name'; 
        pesquisa.SupplierName = 'TestAcc HPB';        
        List<Account> lista = T_SegmentacaoForcedoresController.searchForSuppliers(pesquisa); 
		        
        String resp = T_SegmentacaoForcedoresController.addParticipantesApex(lista, warning.id);
    }
    
    
    @isTest
    public static void TestMethod_removeParticipantesApex(){
        /*TOBJ_Participants__c part = [select id from TOBJ_Participants__c limit 1];
        String jsonStr = JSON.serialize(part);
        Object mapa = (Object) JSON.deserialize(jsonStr, Object.class);
        
        List<Object> objs = new List<Object>();
        objs.add(mapa);
        T_SegmentacaoForcedoresController.removeParticipantesApex(objs);*/
    }
    
    @isTest
    public static void TestMethod_getCategoryRecordTypes(){
        List<RecordType> listRecord = T_SegmentacaoForcedoresController.getCategoryRecordTypes();
        System.assertNotEquals(null, listRecord);
    }
    
    @isTest
    public static void TestMethod_getPicklistVendorVetting(){
        String Entries = T_SegmentacaoForcedoresController.getPicklistVendorVetting('TW1_Vendor_Vetting__c');
        System.assertNotEquals(null, Entries);
    }
    
}