force-app/main/default/objects/Account/fields/TW1_Contact_email_address__c.field-meta.xml
<CustomField>
    <fullName>TW1_Contact_email_address__c</fullName>
    <label>Contact email address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>TW1_Contact_Name__c</fullName>
    <label>Contact Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>TW1_Contact_Phone__c</fullName>
    <label>Contact Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/TW1_Vendor_Homologated.recordType-meta.xml
<RecordType>
    <fullName>TW1_Vendor_Homologated</fullName>
    <active>true</active>
    <label>Supplier Homologated</label>
</RecordType>

force-app/main/default/objects/Controle_de_Triggers__c/Controle_de_Triggers__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Controle de triggers para facilitar controle de acesso e configuração.</description>
    <label>Controle de Triggers</label>
</CustomObject>

force-app/main/default/objects/Controle_de_Triggers__c/fields/Trigger_Account__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Trigger Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ID_Account__c/ID_Account__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ID - Account</label>
</CustomObject>

force-app/main/default/objects/ID_Account__c/fields/Id_IntegrationUser__c.field-meta.xml
<CustomField>
    <fullName>Id_IntegrationUser__c</fullName>
    <label>Id_IntegrationUser</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ID_Queues__c/ID_Queues__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ID Queues</label>
</CustomObject>

force-app/main/default/objects/ID_Queues__c/fields/ID_Procurement_Manager_Queue__c.field-meta.xml
<CustomField>
    <fullName>ID_Procurement_Manager_Queue__c</fullName>
    <label>ID Procurement Manager Queue</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IDStep__c/IDStep__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ID - Step</label>
</CustomObject>

force-app/main/default/objects/IDStep__c/fields/Id_RecordType_Procurement_Manager__c.field-meta.xml
<CustomField>
    <fullName>Id_RecordType_Procurement_Manager__c</fullName>
    <label>Id RecordType Procurement Manager</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/T_Debug_Setting__mdt/T_Debug_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Configurações de Debug</description>
    <label>Triscal debug setting</label>
    <pluralLabel>Triscal debug setting</pluralLabel>
</CustomObject>

force-app/main/default/objects/T_Debug_Setting__mdt/fields/T_Armazenar_Cause__c.field-meta.xml
<CustomField>
    <fullName>T_Armazenar_Cause__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Se true armazena a causa da exception caso exista</description>
    <label>Armazenar Cause?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/T_Debug_Setting__mdt/fields/T_Armazenar_linha_debug__c.field-meta.xml
<CustomField>
    <fullName>T_Armazenar_linha_debug__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Se true armazena linha de debug</description>
    <label>Armazenar linha debug?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/T_Debug_Setting__mdt/fields/T_Armazenar_StackTrace__c.field-meta.xml
<CustomField>
    <fullName>T_Armazenar_StackTrace__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Se true então armazena o StackTrace da exceção</description>
    <inlineHelpText>Se true então armazena o StackTrace da exceção</inlineHelpText>
    <label>Armazenar StackTrace?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/T_Debug_Setting__mdt/fields/T_Armazenar_texto_Exception__c.field-meta.xml
<CustomField>
    <fullName>T_Armazenar_texto_Exception__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Se true então armazena o texto da exceção</description>
    <inlineHelpText>Se true então armazena o texto da exceção</inlineHelpText>
    <label>Armazenar texto Exception?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/TW1_Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>REQ{000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Contact_email_address__c.field-meta.xml
<CustomField>
    <fullName>TW1_Contact_email_address__c</fullName>
    <formula>TW1_Vendor__r.TW1_Contact_email_address__c</formula>
    <label>Contact email address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>TW1_Contact_Name__c</fullName>
    <formula>TW1_Vendor__r.TW1_Contact_Name__c</formula>
    <label>Contact Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Step__c/TW1_Step__c.object-meta.xml
<CustomObject>
    <label>Step</label>
    <nameField>
        <displayFormat>S{000000}</displayFormat>
        <label>Steps Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Step__c/fields/TW1_Request__c.field-meta.xml
<CustomField>
    <fullName>TW1_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request</label>
    <referenceTo>TW1_Request__c</referenceTo>
    <relationshipLabel>Steps</relationshipLabel>
    <relationshipName>Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Step__c/recordTypes/TW1_Approval_Step_Procurement_Manager.recordType-meta.xml
<RecordType>
    <fullName>TW1_Approval_Step_Procurement_Manager</fullName>
    <active>true</active>
    <label>Approval Step - Procurement Manager</label>
</RecordType>

force-app/main/default/classes/T_MODEC_Account_APP_TST.cls
/**
 * @File Name          : T_MODEC_Account_APP_TST.cls
 * @Description        :
 * @Author             : Mario Oliveira
 * @Group              :
 * @Last Modified By   : Rafael Hadama
 * @Last Modified On   : 06/02/2020 12:13:44
 * @Modification Log   :
 * Ver       Date            Author              Modification
 * 1.0    05/12/2019   Mario Oliveira     Initial Version
 **/
@isTest
public with sharing class T_MODEC_Account_APP_TST
{ 
   
   public static void criarCustomSettings()  //Obs.: Apenas Triggers que contêm este método serão liberadas
   {
      Controle_de_Triggers__c ctrlTriggers = new Controle_de_Triggers__c();

      ctrlTriggers.Trigger_Account__c = true; // ***** LEMBRAR ***** (Lembrar de mudar "Trigger_Account__c" ao reutilizar código)
      insert ctrlTriggers;

      //Buscando recordtype para preencher na custom settings
      RecordType recStep = [SELECT Id, Name, DeveloperName, SobjectType FROM RecordType where DeveloperName = 'TW1_Approval_Step_Procurement_Manager'];

      IDStep__c customSettingSTEP = new IDStep__c();
      customSettingSTEP.Id_RecordType_Procurement_Manager__c = recStep.id;
      insert customSettingSTEP;

      //Buscando fila para preencher custom settings     

      Group      filaPmanager         = new Group();
      filaPmanager.Type = 'Queue';
      filaPmanager.Name = 'Procurement_Manager';
      insert       filaPmanager;
      QueueSobject mappingObjectStep = new QueueSobject(QueueId = filaPmanager.Id, SobjectType = 'TW1_Step__c');
      QueueSobject mappingObjectRequest = new QueueSobject(QueueId = filaPmanager.Id, SobjectType = 'TW1_Request__c');
      System.runAs(new User(Id = UserInfo.getUserId()))
      {
         insert mappingObjectStep;
         insert mappingObjectRequest;
      }
      ID_Queues__c customIdQueues = new ID_Queues__c();
      customIdQueues.ID_Procurement_Manager_Queue__c = filaPmanager.Id;
      insert customIdQueues;

      //Buscando Usuário de integração para preencher custom settings devido ao process builder Account - General process
      
      ID_Account__c customSettingsIDAccount = new ID_Account__c();
      customSettingsIDAccount.Id_IntegrationUser__c = UserInfo.getUserId();
      insert customSettingsIDAccount;
      /*******************************************/

      T_Debug_Setting__mdt testsetting;

      testsetting                                = new T_Debug_Setting__mdt();
      testsetting.Label                          = 'Teste';
      testsetting.DeveloperName                  = 'Teste';
      testsetting.T_Armazenar_Cause__c           = true;
      testsetting.T_Armazenar_linha_debug__c     = true;
      testsetting.T_Armazenar_StackTrace__c      = true;
      testsetting.T_Armazenar_texto_Exception__c = true;
      T_SDK_DebugLog_Test.testsetting            = testsetting;
   }

   @isTest
   public static void criarContatoTST()
   {
      criarCustomSettings();

      Account account = new Account();
      account.RecordTypeId                 = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('TW1_Vendor_Homologated').getRecordTypeId();
      account.Name                         = 'Teste da Silva';
      account.TW1_Contact_Name__c          = 'Teste da Silva Silva';
      account.TW1_Contact_Phone__c         = '96949869';
      account.TW1_Contact_email_address__c = 'teste@teste.com';

      insert account;
      T_SDK_DebugLog.EscreverLog('Account Id: ' + account.id);

      Contact cont = [ SELECT Id, AccountId FROM Contact WHERE AccountId =: account.Id ];

      T_SDK_DebugLog.EscreverLog('Contact: ' + cont);

      System.assertEquals(account.id, cont.AccountId, 'Contato não foi criado.(1)');
   }

}