force-app/main/default/objects/Account/fields/TW1_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>TW1_Contact_Name__c</fullName>
    <label>Contact Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_CPF__c.field-meta.xml
<CustomField>
    <fullName>TW1_CPF__c</fullName>
    <label>CPF</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/TW1_Vendor_Homologated.recordType-meta.xml
<RecordType>
    <fullName>TW1_Vendor_Homologated</fullName>
    <active>true</active>
    <label>Supplier Homologated</label>
</RecordType>

force-app/main/default/objects/Controle_de_Triggers__c/Controle_de_Triggers__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Controle de triggers para facilitar controle de acesso e configuração.</description>
    <label>Controle de Triggers</label>
</CustomObject>

force-app/main/default/objects/Controle_de_Triggers__c/fields/Trigger_Account__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Trigger Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Controle_de_Triggers__c/fields/Trigger_Request__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Request__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Trigger_Request</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Controle_de_Triggers__c/fields/Triscal_User_Id__c.field-meta.xml
<CustomField>
    <fullName>Triscal_User_Id__c</fullName>
    <description>User Id, for Triscal support.</description>
    <label>Triscal User Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ID_Account__c/ID_Account__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ID - Account</label>
</CustomObject>

force-app/main/default/objects/ID_Account__c/fields/Id_IntegrationUser__c.field-meta.xml
<CustomField>
    <fullName>Id_IntegrationUser__c</fullName>
    <label>Id_IntegrationUser</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ID_Queues__c/ID_Queues__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ID Queues</label>
</CustomObject>

force-app/main/default/objects/ID_Queues__c/fields/ID_SED_Queue__c.field-meta.xml
<CustomField>
    <fullName>ID_SED_Queue__c</fullName>
    <label>ID SED Queue</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IDStep__c/IDStep__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ID - Step</label>
</CustomObject>

force-app/main/default/objects/IDStep__c/fields/Id_RecordType_Step_BM_NF__c.field-meta.xml
<CustomField>
    <fullName>Id_RecordType_Step_BM_NF__c</fullName>
    <label>Id RecordType Step BM-NF</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/T_Debug_Setting__mdt/T_Debug_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Configurações de Debug</description>
    <label>Triscal debug setting</label>
    <pluralLabel>Triscal debug setting</pluralLabel>
</CustomObject>

force-app/main/default/objects/T_Debug_Setting__mdt/fields/T_Armazenar_Cause__c.field-meta.xml
<CustomField>
    <fullName>T_Armazenar_Cause__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Se true armazena a causa da exception caso exista</description>
    <label>Armazenar Cause?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/T_Debug_Setting__mdt/fields/T_Armazenar_linha_debug__c.field-meta.xml
<CustomField>
    <fullName>T_Armazenar_linha_debug__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Se true armazena linha de debug</description>
    <label>Armazenar linha debug?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/T_Debug_Setting__mdt/fields/T_Armazenar_StackTrace__c.field-meta.xml
<CustomField>
    <fullName>T_Armazenar_StackTrace__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Se true então armazena o StackTrace da exceção</description>
    <inlineHelpText>Se true então armazena o StackTrace da exceção</inlineHelpText>
    <label>Armazenar StackTrace?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/T_Debug_Setting__mdt/fields/T_Armazenar_texto_Exception__c.field-meta.xml
<CustomField>
    <fullName>T_Armazenar_texto_Exception__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Se true então armazena o texto da exceção</description>
    <inlineHelpText>Se true então armazena o texto da exceção</inlineHelpText>
    <label>Armazenar texto Exception?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TW1_Email_List__c/TW1_Email_List__c.object-meta.xml
<CustomObject>
    <label>Email List</label>
    <nameField>
        <displayFormat>EL-{0000}</displayFormat>
        <label>Email List Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Email_List__c/fields/TW1_Email__c.field-meta.xml
<CustomField>
    <fullName>TW1_Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/TW1_Email_List__c/fields/TW1_Status__c.field-meta.xml
<CustomField>
    <fullName>TW1_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ativo</fullName>
                <default>true</default>
                <label>Ativo</label>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Email_List__c/recordTypes/TW1_BM_Email.recordType-meta.xml
<RecordType>
    <fullName>TW1_BM_Email</fullName>
    <active>true</active>
    <label>BM Email</label>
</RecordType>

force-app/main/default/objects/TW1_Request__c/TW1_Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>REQ{000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Request__c/fields/BM_Status__c.field-meta.xml
<CustomField>
    <fullName>BM_Status__c</fullName>
    <defaultValue>&quot;Não enviado&quot;</defaultValue>
    <label>BM Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BM_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_BM_Reference_Number_in_SAP_MODEC__c.field-meta.xml
<CustomField>
    <fullName>TW1_BM_Reference_Number_in_SAP_MODEC__c</fullName>
    <inlineHelpText>This field is read-only. Do not try to fill it.</inlineHelpText>
    <label>BM Reference Number in SAP MODEC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>TW1_Contact_Name__c</fullName>
    <formula>TW1_Vendor__r.TW1_Contact_Name__c</formula>
    <label>Contact Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_PO__c.field-meta.xml
<CustomField>
    <fullName>TW1_PO__c</fullName>
    <label>PO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Purchase_Item__c.field-meta.xml
<CustomField>
    <fullName>TW1_Purchase_Item__c</fullName>
    <label>Purchase Item</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Service_End_Date__c.field-meta.xml
<CustomField>
    <fullName>TW1_Service_End_Date__c</fullName>
    <label>Service End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Service_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>TW1_Service_Start_Date__c</fullName>
    <label>Service Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Status__c.field-meta.xml
<CustomField>
    <fullName>TW1_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Supplier_Email__c.field-meta.xml
<CustomField>
    <fullName>TW1_Supplier_Email__c</fullName>
    <label>Supplier Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Vendor__c.field-meta.xml
<CustomField>
    <fullName>TW1_Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4) OR (6 AND (5 OR 7))</booleanFilter>
        <errorMessage>Make sure the selected vendor is already homologated or not.</errorMessage>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>BM, Contract - New Contract, Contract - Amendment, Material Packing List (Third-party), Inspection</value>
        </filterItems>
        <filterItems>
            <field>Account.TW1_Vendor_Vetting__c</field>
            <operation>equals</operation>
            <value>Active, No Registered, Ongoing, Blocked, Vetting Not Requested, Vetting Rejected, Vetting Approved with Red Flag, Vetting Approved, Vetting Expired</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vendor Vetting, Vendor Vetting - Senegal</value>
        </filterItems>
        <filterItems>
            <field>Account.TW1_Vendor_Vetting__c</field>
            <operation>equals</operation>
            <value>Active, No Registered, Ongoing, Blocked, Vetting Not Requested, Vetting Rejected, Vetting Approved with Red Flag, Vetting Approved, Vetting Expired</value>
        </filterItems>
        <filterItems>
            <field>Account.TW1_Step_Owner__c</field>
            <operation>equals</operation>
            <valueField>$User.Id</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>PO Review Form</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator, VV Team</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/recordTypes/TW1_BM.recordType-meta.xml
<RecordType>
    <fullName>TW1_BM</fullName>
    <active>true</active>
    <label>BM</label>
</RecordType>

force-app/main/default/objects/TW1_Step__c/TW1_Step__c.object-meta.xml
<CustomObject>
    <label>Step</label>
    <nameField>
        <displayFormat>S{000000}</displayFormat>
        <label>Steps Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Step__c/fields/BM_Status__c.field-meta.xml
<CustomField>
    <fullName>BM_Status__c</fullName>
    <label>BM Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BM_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Step__c/fields/TW1_Email__c.field-meta.xml
<CustomField>
    <fullName>TW1_Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/TW1_Step__c/fields/TW1_PO__c.field-meta.xml
<CustomField>
    <fullName>TW1_PO__c</fullName>
    <formula>TW1_Request__r.TW1_PO__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PO (Packing List)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Step__c/fields/TW1_Request__c.field-meta.xml
<CustomField>
    <fullName>TW1_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request</label>
    <referenceTo>TW1_Request__c</referenceTo>
    <relationshipLabel>Steps</relationshipLabel>
    <relationshipName>Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Step__c/fields/TW1_Status__c.field-meta.xml
<CustomField>
    <fullName>TW1_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opened</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Step__c/fields/TW1_Vendor__c.field-meta.xml
<CustomField>
    <fullName>TW1_Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Steps</relationshipLabel>
    <relationshipName>Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Step__c/recordTypes/BM_NF.recordType-meta.xml
<RecordType>
    <fullName>BM_NF</fullName>
    <active>true</active>
    <label>BM - NF</label>
</RecordType>

force-app/main/default/globalValueSets/BM_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Aguardando</fullName>
    </customValue>
    <customValue>
        <fullName>Aceita</fullName>
    </customValue>
    <customValue>
        <fullName>Rejeitada</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelada</fullName>
    </customValue>
    <customValue>
        <fullName>Não enviado</fullName>
        <default>true</default>
        <label>Não enviado</label>
    </customValue>
    <masterLabel>BM Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/T_MODEC_AnexosFornecedorTST.cls
/**
 * @File Name          : T_MODEC_AnexosFornecedorTST.cls
 * @Description        :
 * @Author             : Rafael Hadama
 * @Group              :
 * @Last Modified By   : Rafael Hadama
 * @Last Modified On   : 07-22-2020
 * @Modification Log   :
 * Ver       Date            Author              Modification
 * 1.0    04/02/2020   Rafael Hadama     Initial Version
 **/
@Istest
public class T_MODEC_AnexosFornecedorTST {
    static TW1_Request__c BMRequest { get; set; }

    static void MakeMetadataAndCustomSettings()
    {
        system.debug('Teste system debug dentro do testSetupmetodo');
        T_Debug_Setting__mdt testSetting = new T_Debug_Setting__mdt();
        testSetting.Label                          = 'Teste';
        testSetting.DeveloperName                  = 'Teste';
        testSetting.T_Armazenar_Cause__c           = true;
        testSetting.T_Armazenar_linha_debug__c     = true;
        testSetting.T_Armazenar_StackTrace__c      = true;
        testSetting.T_Armazenar_texto_Exception__c = true;
        T_SDK_DebugLog_Test.testSetting            = testSetting;

        //Creating Custom Settings
        ID_Account__c customSettingIdAccount = new ID_Account__c();
        customSettingIdAccount.Id_IntegrationUser__c = UserInfo.getUserId();
        insert customSettingIdAccount;

        Controle_de_Triggers__c customControleTrigger = new Controle_de_Triggers__c();
        customControleTrigger.Trigger_Request__c = true;
        customControleTrigger.Trigger_Account__c = true;
        customControleTrigger.Triscal_User_Id__c = UserInfo.getUserId();
        insert customControleTrigger;

        RecordType StePRecTypeBMNF = [Select id, SobjectType from Recordtype where developername = 'BM_NF' AND SobjectType = 'TW1_Step__c'];
        Group      filaSED         = new Group();
        filaSED.Type = 'Queue';
        filaSED.Name = 'SedQueue';
        insert       filaSED;
        QueueSobject mappingObject = new QueueSobject(QueueId = filaSED.Id, SobjectType = 'TW1_Step__c');
        System.runAs(new User(Id = UserInfo.getUserId()))
        {
            insert mappingObject;
        }
        ID_Queues__c customIdQueues = new ID_Queues__c();
        customIdQueues.ID_SED_Queue__c = filaSED.Id;
        insert customIdQueues;

        IDStep__c customIdSteps = new IDStep__c();
        customIdSteps.Id_RecordType_Step_BM_NF__c = StePRecTypeBMNF.Id;
        insert customIdSteps;
        //Creating Test mock data
        RecordType accRec_VendorHomologated = [Select id from Recordtype where developername = 'TW1_Vendor_Homologated'];
        Account    contamock = new Account();

        contamock.recordtypeId        = accRec_VendorHomologated.id;
        contamock.name                = 'Conta ENVIO Boletim';
        contamock.TW1_CPF__c          = '57034551030';
        contamock.TW1_Contact_Name__c = 'Contato Mock';
        insert contamock;

        //Criando TW1_Email_List__c para passar da trigger.
        TW1_Email_List__c emailList = new TW1_Email_List__c();
        emailList.TW1_Email__c  = 'emailRequestermock@mock.com';
        emailList.TW1_Status__c = 'Ativo';
        emailList.RecordTypeId  = Schema.SObjectType.TW1_Email_List__c.getRecordTypeInfosByDeveloperName().get('TW1_BM_Email').getRecordTypeId();
        insert emailList;
        //Query no recordType e criação do Request do tipo BM
        RecordType     requestRec_BM = [Select id from Recordtype where developername = 'TW1_BM'];
        TW1_Request__c BMmock1       = new TW1_Request__c();
        BMmock1.recordTypeId  = requestRec_BM.id;
        BMmock1.TW1_Vendor__c = contamock.id;
        BMmock1.BM_Status__c  = 'Aguardando';
        BMmock1.TW1_BM_Reference_Number_in_SAP_MODEC__c = '1112223334';

        BMmock1.TW1_PO__c                    = '12345';
        BMmock1.TW1_Purchase_Item__c         = '00010';
        BMmock1.TW1_Service_Start_Date__c    = date.today();
        BMmock1.TW1_Service_End_Date__c      = date.today().addDays(50);
        BMmock1.TW1_Supplier_Email__c        = 'emailSuppliermock@mock.com';
        BMmock1.TW1_Modec_Requester_Email__c = 'emailRequestermock@mock.com';
        BMmock1.TW1_Final_Measurement__c     = 'Yes';
        BMmock1.TW1_Service_Description__c   = '12345';
        BMmock1.TW1_NF_Invoice_Status__c     = 'NF Accepted';

        insert BMmock1;
        //Relacionando com o Request static variable
        BMRequest = BMmock1;
    }

    @isTest
    public static void SearchBmStatusTST()
    {
        //BMRequest
        MakeMetadataAndCustomSettings();
        string status = T_MODEC_AnexosFornecedor_Ctrl.searchBMStatus(BMRequest.Id);

        system.assertEquals('Aguardando', status);
    }

    @isTest
    public static void searchNFStatusTST()
    {
        //BMRequest
        MakeMetadataAndCustomSettings();



        TW1_End_Fiscal_Period__c fpDates = new TW1_End_Fiscal_Period__c();
        fpDates.TW1_JAN_INI__c = Datetime.Now();
        fpDates.TW1_JAN_END__c = Datetime.Now();
        fpDates.TW1_FEB_INI__c = Datetime.Now();
        fpDates.TW1_FEB_END__c = Datetime.Now();
        fpDates.TW1_MAR_INI__c = Datetime.Now();
        fpDates.TW1_MAR_END__c = Datetime.Now();
        fpDates.TW1_APR_INI__c = Datetime.Now();
        fpDates.TW1_APR_END__c = Datetime.Now();
        fpDates.TW1_MAY_INI__c = Datetime.Now();
        fpDates.TW1_MAY_END__c = Datetime.Now();
        fpDates.TW1_JUN_INI__c = Datetime.Now();
        fpDates.TW1_JUN_END__c = Datetime.Now();
        fpDates.TW1_JUL_INI__c = Datetime.Now();
        fpDates.TW1_JUL_END__c = Datetime.Now();
        fpDates.TW1_AUG_INI__c = Datetime.Now();
        fpDates.TW1_AUG_END__c = Datetime.Now();
        fpDates.TW1_SEP_INI__c = Datetime.Now();
        fpDates.TW1_SEP_END__c = Datetime.Now();
        fpDates.TW1_OCT_INI__c = Datetime.Now();
        fpDates.TW1_OCT_END__c = Datetime.Now();
        fpDates.TW1_NOV_INI__c = Datetime.Now();
        fpDates.TW1_NOV_END__c = Datetime.Now();
        fpDates.TW1_DEC_INI__c = Datetime.Now();
        fpDates.TW1_DEC_END__c = Datetime.Now();
        insert fpDates;

        Test.startTest();
        string status = T_MODEC_AnexosFornecedor_Ctrl.searchNFStatus(BMRequest.Id);
        T_MODEC_AnexosFornecedor_Ctrl.NFDTO notafiscalDTO = (T_MODEC_AnexosFornecedor_Ctrl.NFDTO)JSON.deserialize(status, T_MODEC_AnexosFornecedor_Ctrl.NFDTO.class);
        Test.stopTest();
        system.assertEquals('NF Accepted or Awaiting evaluation.', notafiscalDTO.message);
    }

    @isTest
    public static void searchNFStatusBlockFiscalPeriodTST()
    {
        //BMRequest
        MakeMetadataAndCustomSettings();



        TW1_End_Fiscal_Period__c fpDates = new TW1_End_Fiscal_Period__c();
        fpDates.TW1_JAN_INI__c = Datetime.Now().AddDays(-1);
        fpDates.TW1_JAN_END__c = Datetime.Now().AddDays(1);
        fpDates.TW1_FEB_INI__c = Datetime.Now();
        fpDates.TW1_FEB_END__c = Datetime.Now();
        fpDates.TW1_MAR_INI__c = Datetime.Now();
        fpDates.TW1_MAR_END__c = Datetime.Now();
        fpDates.TW1_APR_INI__c = Datetime.Now();
        fpDates.TW1_APR_END__c = Datetime.Now();
        fpDates.TW1_MAY_INI__c = Datetime.Now();
        fpDates.TW1_MAY_END__c = Datetime.Now();
        fpDates.TW1_JUN_INI__c = Datetime.Now();
        fpDates.TW1_JUN_END__c = Datetime.Now();
        fpDates.TW1_JUL_INI__c = Datetime.Now();
        fpDates.TW1_JUL_END__c = Datetime.Now();
        fpDates.TW1_AUG_INI__c = Datetime.Now();
        fpDates.TW1_AUG_END__c = Datetime.Now();
        fpDates.TW1_SEP_INI__c = Datetime.Now();
        fpDates.TW1_SEP_END__c = Datetime.Now();
        fpDates.TW1_OCT_INI__c = Datetime.Now();
        fpDates.TW1_OCT_END__c = Datetime.Now();
        fpDates.TW1_NOV_INI__c = Datetime.Now();
        fpDates.TW1_NOV_END__c = Datetime.Now();
        fpDates.TW1_DEC_INI__c = Datetime.Now();
        fpDates.TW1_DEC_END__c = Datetime.Now();
        insert fpDates;

        Test.startTest();
        string status = T_MODEC_AnexosFornecedor_Ctrl.searchNFStatus(BMRequest.Id);
        T_MODEC_AnexosFornecedor_Ctrl.NFDTO notafiscalDTO = (T_MODEC_AnexosFornecedor_Ctrl.NFDTO)JSON.deserialize(status, T_MODEC_AnexosFornecedor_Ctrl.NFDTO.class);
        Test.stopTest();
        system.assertEquals('NF Upload blocked by Fiscal Period', notafiscalDTO.message);
    }

    @isTest
    public static void CurrentUserIdTST()
    {
        string UserId = T_MODEC_AnexosFornecedor_Ctrl.getCurrentUserId();

        system.assertEquals(UserInfo.getUserId(), UserId);
    }

    @isTest
    public static void RelateToDocumentationTST()
    {
        //BMRequest
        MakeMetadataAndCustomSettings();
        ContentVersion contentVersion = new ContentVersion(Title = 'Penguins', PathOnClient = 'Penguins.jpg', VersionData = Blob.valueOf('Test Content'), IsMajorVersion = true);
        insert         contentVersion;
        T_SDK_DebugLog.EscreverLog('Content Version insert>' + contentVersion);

        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument where Title = 'Penguins'];
        T_SDK_DebugLog.EscreverLog('List ContentDocument' + documents);

        List<String> listDocIds = new List<String>();
        listDocIds.add(documents[0].Id);
        Test.startTest();
        string status = T_MODEC_AnexosFornecedor_Ctrl.relateToDocumentation(listDocIds, true, BMRequest.Id, '1234567890');
        Test.stopTest();
        system.assertEquals('Sucesso', status);
    }
}