force-app/main/default/objects/Account/fields/TW1_Main_Contact__c.field-meta.xml
<CustomField>
    <fullName>TW1_Main_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Main Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>TW1_SAP_Code__c</fullName>
    <label>SAP Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_Vendor_Vetting__c.field-meta.xml
<CustomField>
    <fullName>TW1_Vendor_Vetting__c</fullName>
    <defaultValue>&quot;Vetting Not Requested&quot;</defaultValue>
    <label>Vendor Vetting</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>No Registered</fullName>
            </value>
            <value>
                <fullName>Ongoing</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Vetting Not Requested</fullName>
            </value>
            <value>
                <fullName>Vetting Rejected</fullName>
            </value>
            <value>
                <fullName>Vetting Approved with Red Flag</fullName>
            </value>
            <value>
                <fullName>Vetting Approved</fullName>
            </value>
            <value>
                <fullName>Vetting Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ID_Account__c/ID_Account__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ID - Account</label>
</CustomObject>

force-app/main/default/objects/ID_Account__c/fields/Id_IntegrationUser__c.field-meta.xml
<CustomField>
    <fullName>Id_IntegrationUser__c</fullName>
    <label>Id_IntegrationUser</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/TW1_MODEC_Contract__c.object-meta.xml
<CustomObject>
    <label>MODEC Contract</label>
    <nameField>
        <label>MODEC Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MODEC Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Accumulated_Contract_Amout__c.field-meta.xml
<CustomField>
    <fullName>TW1_Accumulated_Contract_Amout__c</fullName>
    <formula>TW1_Previous_Contract_Amount_A__c + TW1_Contracted_Value_B__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Accumulated Contract Amout (A+B)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Annual_Estimate__c.field-meta.xml
<CustomField>
    <fullName>TW1_Annual_Estimate__c</fullName>
    <label>Annual Estimate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_BID__c.field-meta.xml
<CustomField>
    <fullName>TW1_BID__c</fullName>
    <label>BID?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Budgeted_2019__c.field-meta.xml
<CustomField>
    <fullName>TW1_Budgeted_2019__c</fullName>
    <label>Budgeted 2019?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Contempled_in_this_Agreement__c.field-meta.xml
<CustomField>
    <fullName>TW1_Contempled_in_this_Agreement__c</fullName>
    <label>Contempled in this Agreement</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Contracted_Value_B__c.field-meta.xml
<CustomField>
    <fullName>TW1_Contracted_Value_B__c</fullName>
    <label>Contracted Value (B)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Cost_Center__c.field-meta.xml
<CustomField>
    <fullName>TW1_Cost_Center__c</fullName>
    <label>Cost Center</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Cost_Controller__c.field-meta.xml
<CustomField>
    <fullName>TW1_Cost_Controller__c</fullName>
    <label>Cost Controller</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Date__c.field-meta.xml
<CustomField>
    <fullName>TW1_Date__c</fullName>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Department_Code__c.field-meta.xml
<CustomField>
    <fullName>TW1_Department_Code__c</fullName>
    <label>Department Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Duration__c.field-meta.xml
<CustomField>
    <fullName>TW1_Duration__c</fullName>
    <label>Duration</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>24 Months</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_End_Date__c.field-meta.xml
<CustomField>
    <fullName>TW1_End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Escalation__c.field-meta.xml
<CustomField>
    <fullName>TW1_Escalation__c</fullName>
    <label>Escalation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>IGPM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Increase__c.field-meta.xml
<CustomField>
    <fullName>TW1_Increase__c</fullName>
    <label>Increase</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Job_Title__c.field-meta.xml
<CustomField>
    <fullName>TW1_Job_Title__c</fullName>
    <label>Job Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Justification__c.field-meta.xml
<CustomField>
    <fullName>TW1_Justification__c</fullName>
    <label>Justification</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Main_Contact__c.field-meta.xml
<CustomField>
    <fullName>TW1_Main_Contact__c</fullName>
    <formula>TW1_Vendor__r.TW1_Main_Contact__r.FirstName +&quot; &quot;+ TW1_Vendor__r.TW1_Main_Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Main Contact</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Monthly_If_Fixed__c.field-meta.xml
<CustomField>
    <fullName>TW1_Monthly_If_Fixed__c</fullName>
    <label>Monthly (If Fixed)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Depends Demand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Party_Email__c.field-meta.xml
<CustomField>
    <fullName>TW1_Party_Email__c</fullName>
    <formula>TW1_Vendor__r.TW1_Company_Email_Address__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Party Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Payment_Conditions__c.field-meta.xml
<CustomField>
    <fullName>TW1_Payment_Conditions__c</fullName>
    <label>Payment Conditions</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>TW1_Payment_Term__c</fullName>
    <label>Payment Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>30 Days</fullName>
            </value>
            <value>
                <fullName>45 Days</fullName>
            </value>
            <value>
                <fullName>60 Days</fullName>
            </value>
            <value>
                <fullName>75 Days</fullName>
            </value>
            <value>
                <fullName>90 Days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_PO_Number__c.field-meta.xml
<CustomField>
    <fullName>TW1_PO_Number__c</fullName>
    <label>PO Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Previous_Contract_Amount_A__c.field-meta.xml
<CustomField>
    <fullName>TW1_Previous_Contract_Amount_A__c</fullName>
    <label>Previous Contract Amount (A):</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Requestor_Sponsor__c.field-meta.xml
<CustomField>
    <fullName>TW1_Requestor_Sponsor__c</fullName>
    <label>Requestor/Sponsor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_SAP_Outline_Agreement_Number__c.field-meta.xml
<CustomField>
    <fullName>TW1_SAP_Outline_Agreement_Number__c</fullName>
    <label>SAP Outline Agreement Number</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>TW1_Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Termination_Conditions_Penalty__c.field-meta.xml
<CustomField>
    <fullName>TW1_Termination_Conditions_Penalty__c</fullName>
    <label>Termination: Conditions/Penalty</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Type_of_Contract__c.field-meta.xml
<CustomField>
    <fullName>TW1_Type_of_Contract__c</fullName>
    <label>Type of Contract</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rent/Lease</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Material</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Vendor__c.field-meta.xml
<CustomField>
    <fullName>TW1_Vendor__c</fullName>
    <label>Supplier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>MODEC Contracts</relationshipLabel>
    <relationshipName>MODEC_Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Vendor_CNPJ__c.field-meta.xml
<CustomField>
    <fullName>TW1_Vendor_CNPJ__c</fullName>
    <formula>TW1_Vendor__r.TW1_CNPJ__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Supplier CNPJ</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Vendor_Vetting__c.field-meta.xml
<CustomField>
    <fullName>TW1_Vendor_Vetting__c</fullName>
    <formula>TEXT(TW1_Vendor__r.TW1_Vendor_Vetting__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vendor Vetting</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_WBS_Number__c.field-meta.xml
<CustomField>
    <fullName>TW1_WBS_Number__c</fullName>
    <label>WBS Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/T_MODEC_ContratoSuporteReq_TST.cls
/**
 * @File Name          : T_MODEC_ContratoSuporteReq_TST.cls
 * @Description        :
 * @Author             : Mario Oliveira
 * @Group              :
 * @Last Modified By   : Rafael Hadama
 * @Last Modified On   : 11/02/2020 12:37:04
 * @Modification Log   :
 * Ver       Date            Author              Modification
 * 1.0    04/11/2019   Mario Oliveira     Initial Version
 **/
@isTest
public with sharing class T_MODEC_ContratoSuporteReq_TST {
   @isTest
   public static void T_MODEC_ContratoSuporteReq_TST()
   {
      /*
       * Passo 1 - Referenciar pagina visualforce
       * que será usada (Dar um nome. Para este caso,
       * foi dado o nome "myVFPage")
       */
      Pagereference myVFPage = Page.T_ContratoSuporteReqVF;

      /*
       *    Passo 2 - Setar pagina corrente padrão
       *	(Neste caso, a pagina padrão será a pagina
       *	referenciada no passo 1)
       */
      Test.setCurrentPage(myVFPage);

      /*
       *	Passo 3 - Criar uma variavel do tipo do objeto
       *  e igualar à classe de teste, chamando o metodo de mock
       */
      TW1_MODEC_Contract__c contractTest = T_MODEC_ContratoSuporteReq_TST.criarRegistroMock();

      /*
       *    Passo 4 - Dar "put" do id do contrato mockado
       *	no parametro da pagina referenciada
       */
      ApexPages.currentPage().getParameters().put('contratoId', contractTest.id);

      /*
       *    Passo 5 - Criar conexão com a classe controller
       */
      T_MODEC_ContratoSuporteReq_CTRL ctrl = new T_MODEC_ContratoSuporteReq_CTRL();
   }

   //Passo 6 - Classe Mock
   public static TW1_MODEC_Contract__c criarRegistroMock()
   {
      /*
       *    Passo 7 - Inserir conta mock (Pois há um relacionamento
       *	entre "TW1_Vendor__c" e "Account", então, para que seja
       *	possivel criar um registro no campo "TW1_Vendor__c"
       *	deve ser criado antes este registro em "Account")
       */

      //Buscando Usuário de integração para preencher custom settings devido ao process builder Account - General process
      
      ID_Account__c customSettingsIDAccount = new ID_Account__c();

      customSettingsIDAccount.Id_IntegrationUser__c = UserInfo.getUserId();
      insert customSettingsIDAccount;

      Account conta = new Account();
      conta.Name            = 'Teste conta';
      conta.TW1_SAP_Code__c = '252525';
      Insert conta;

      /*
       *    Passo 8 - Inserir informações mock relativas ao contrato
       */
      TW1_MODEC_Contract__c contractTST = new TW1_MODEC_Contract__c();

      contractTST.TW1_SAP_Outline_Agreement_Number__c = '00000001';
      contractTST.TW1_Type_of_Contract__c             = 'Service';
      contractTST.TW1_Requestor_Sponsor__c            = 'Michael Carlson Test';
      contractTST.TW1_Job_Title__c = 'CEO';
      contractTST.TW1_Date__c      = date.parse('05/11/2019');
      T_SDK_DebugLog.EscreverLog('Conta :' + conta);
      contractTST.TW1_Vendor__c        = conta.Id;
      contractTST.TW1_BID__c           = 'Yes';
      contractTST.TW1_Justification__c = 'Sit amet, lorem consectetur adipiscing, sed eiusmod tempor  ut labore et dolore magna aliqua.';
      contractTST.TW1_Contempled_in_this_Agreement__c   = 'Lorem consectetur adipiscing, sed eiusmod tempor  ut labore et dolore';
      contractTST.TW1_Termination_Conditions_Penalty__c = 'String teste 0';
      contractTST.TW1_Previous_Contract_Amount_A__c     = 1000.00;
      contractTST.TW1_Contracted_Value_B__c             = 10000.50;
      contractTST.TW1_Increase__c               = 0.56;
      contractTST.TW1_Annual_Estimate__c        = 100000.80;
      contractTST.CurrencyIsoCode               = 'BRL';
      contractTST.TW1_Monthly_If_Fixed__c       = 'Depends Demand';
      contractTST.TW1_Escalation__c             = 'IGPM';
      contractTST.TW1_Duration__c               = '24 Months';
      contractTST.TW1_Payment_Term__c           = '30 Days';
      contractTST.TW1_Start_Date__c             = date.parse('11/11/2019');
      contractTST.TW1_End_Date__c               = date.parse('11/11/2019');
      contractTST.TW1_Payment_Conditions__c     = 'String teste 3';
      contractTST.TW1_PO_Number__c              = 'String teste 4';
      contractTST.TW1_Budgeted_2019__c          = 'Yes';
      contractTST.TW1_Budgeted_Justification__c = 'String teste 7';
      contractTST.TW1_Cost_Center__c            = 'String teste 8';
      contractTST.TW1_WBS_Number__c             = 'String teste 9';
      contractTST.TW1_Department_Code__c        = 'String teste 10';
      contractTST.TW1_Cost_Controller__c        = 'String teste 11';

      /*
       ***** NÃO PRECISAM SER PREENCHIDOS (CAMPOS FORMULA) *****
       *****contractTST.Name
       *****contractTST.TW1_Vendor_CNPJ__c
       *****contractTST.TW1_Vendor_Vetting__c
       *****contractTST.TW1_Main_Contact__c
       *****contractTST.TW1_Party_Email__c
       *****contractTST.TW1_Accumulated_Contract_Amout__c
       */

      insert contractTST;

      /*
       *    Passo 9 - Retornar informações de "contractTST" para
       *  a variavel "contractTest" (Passo 3)
       */
      return contractTST;
   }
}