force-app/main/default/objects/Account/fields/TW1_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>TW1_Contact_Name__c</fullName>
    <label>Contact Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_CPF__c.field-meta.xml
<CustomField>
    <fullName>TW1_CPF__c</fullName>
    <label>CPF</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/TW1_Vendor_Homologated.recordType-meta.xml
<RecordType>
    <fullName>TW1_Vendor_Homologated</fullName>
    <active>true</active>
    <label>Supplier Homologated</label>
</RecordType>

force-app/main/default/objects/Controle_de_Triggers__c/Controle_de_Triggers__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Controle de triggers para facilitar controle de acesso e configuração.</description>
    <label>Controle de Triggers</label>
</CustomObject>

force-app/main/default/objects/Controle_de_Triggers__c/fields/Trigger_Account__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Trigger Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Controle_de_Triggers__c/fields/Trigger_Request__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Request__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Trigger_Request</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Controle_de_Triggers__c/fields/Triscal_User_Id__c.field-meta.xml
<CustomField>
    <fullName>Triscal_User_Id__c</fullName>
    <description>User Id, for Triscal support.</description>
    <label>Triscal User Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ID_Account__c/ID_Account__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ID - Account</label>
</CustomObject>

force-app/main/default/objects/ID_Account__c/fields/Id_IntegrationUser__c.field-meta.xml
<CustomField>
    <fullName>Id_IntegrationUser__c</fullName>
    <label>Id_IntegrationUser</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ID_Queues__c/ID_Queues__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ID Queues</label>
</CustomObject>

force-app/main/default/objects/ID_Queues__c/fields/ID_VV_Team_Queue__c.field-meta.xml
<CustomField>
    <fullName>ID_VV_Team_Queue__c</fullName>
    <label>ID VV Team Queue</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/T_Debug_Setting__mdt/T_Debug_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Configurações de Debug</description>
    <label>Triscal debug setting</label>
    <pluralLabel>Triscal debug setting</pluralLabel>
</CustomObject>

force-app/main/default/objects/T_Debug_Setting__mdt/fields/T_Armazenar_Cause__c.field-meta.xml
<CustomField>
    <fullName>T_Armazenar_Cause__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Se true armazena a causa da exception caso exista</description>
    <label>Armazenar Cause?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/T_Debug_Setting__mdt/fields/T_Armazenar_linha_debug__c.field-meta.xml
<CustomField>
    <fullName>T_Armazenar_linha_debug__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Se true armazena linha de debug</description>
    <label>Armazenar linha debug?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/T_Debug_Setting__mdt/fields/T_Armazenar_StackTrace__c.field-meta.xml
<CustomField>
    <fullName>T_Armazenar_StackTrace__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Se true então armazena o StackTrace da exceção</description>
    <inlineHelpText>Se true então armazena o StackTrace da exceção</inlineHelpText>
    <label>Armazenar StackTrace?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/T_Debug_Setting__mdt/fields/T_Armazenar_texto_Exception__c.field-meta.xml
<CustomField>
    <fullName>T_Armazenar_texto_Exception__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Se true então armazena o texto da exceção</description>
    <inlineHelpText>Se true então armazena o texto da exceção</inlineHelpText>
    <label>Armazenar texto Exception?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TW1_Email_List__c/TW1_Email_List__c.object-meta.xml
<CustomObject>
    <label>Email List</label>
    <nameField>
        <displayFormat>EL-{0000}</displayFormat>
        <label>Email List Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Email_List__c/fields/TW1_Email__c.field-meta.xml
<CustomField>
    <fullName>TW1_Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/TW1_Email_List__c/fields/TW1_Status__c.field-meta.xml
<CustomField>
    <fullName>TW1_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ativo</fullName>
                <default>true</default>
                <label>Ativo</label>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Email_List__c/recordTypes/TW1_BM_Email.recordType-meta.xml
<RecordType>
    <fullName>TW1_BM_Email</fullName>
    <active>true</active>
    <label>BM Email</label>
</RecordType>

force-app/main/default/objects/TW1_Interaction__c/TW1_Interaction__c.object-meta.xml
<CustomObject>
    <label>Interaction</label>
    <nameField>
        <displayFormat>I-{000000}</displayFormat>
        <label>Interaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Interaction__c/fields/TW1_Status__c.field-meta.xml
<CustomField>
    <fullName>TW1_Status__c</fullName>
    <defaultValue>&quot;Open&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>In Validation By the Legal</fullName>
            </value>
            <value>
                <fullName>Validated Notification</fullName>
            </value>
            <value>
                <fullName>Awaiting Return</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>New Proposed Date</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved under restriction</fullName>
            </value>
            <value>
                <fullName>New incident treatment</fullName>
            </value>
            <value>
                <fullName>Sent incident to supplier</fullName>
            </value>
            <value>
                <fullName>Incident responded</fullName>
            </value>
            <value>
                <fullName>Awaiting evidence of treatment</fullName>
            </value>
            <value>
                <fullName>Evidence sent</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Incident treatment rejected</fullName>
            </value>
            <value>
                <fullName>Incident treatment approved</fullName>
            </value>
            <value>
                <fullName>Clarification Required</fullName>
            </value>
            <value>
                <fullName>Analyzing Audit Info</fullName>
            </value>
            <value>
                <fullName>Audit Scheduled</fullName>
            </value>
            <value>
                <fullName>Awaiting Action Plan</fullName>
            </value>
            <value>
                <fullName>Action Plan Evaluation</fullName>
            </value>
            <value>
                <fullName>Action Plan Validation</fullName>
            </value>
            <value>
                <fullName>Awaiting Evidences</fullName>
            </value>
            <value>
                <fullName>Evidences Sent</fullName>
            </value>
            <value>
                <fullName>Evidences Analyzed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Reproved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Interaction__c/recordTypes/TW1_QA_QC_Inspection.recordType-meta.xml
<RecordType>
    <fullName>TW1_QA_QC_Inspection</fullName>
    <active>true</active>
    <label>QA/QC Inspection</label>
</RecordType>

force-app/main/default/objects/TW1_MODEC_Contract__c/TW1_MODEC_Contract__c.object-meta.xml
<CustomObject>
    <label>MODEC Contract</label>
    <nameField>
        <label>MODEC Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MODEC Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Request__c.field-meta.xml
<CustomField>
    <fullName>TW1_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request</label>
    <referenceTo>TW1_Request__c</referenceTo>
    <relationshipLabel>MODEC Contracts</relationshipLabel>
    <relationshipName>MODEC_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Status__c.field-meta.xml
<CustomField>
    <fullName>TW1_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_MODEC_Contract__c/fields/TW1_Vendor__c.field-meta.xml
<CustomField>
    <fullName>TW1_Vendor__c</fullName>
    <label>Supplier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>MODEC Contracts</relationshipLabel>
    <relationshipName>MODEC_Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/TW1_Request__c/TW1_Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>REQ{000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>TW1_Contact_Name__c</fullName>
    <formula>TW1_Vendor__r.TW1_Contact_Name__c</formula>
    <label>Contact Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Status__c.field-meta.xml
<CustomField>
    <fullName>TW1_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Request__c/recordTypes/TW1_BM.recordType-meta.xml
<RecordType>
    <fullName>TW1_BM</fullName>
    <active>true</active>
    <label>BM</label>
</RecordType>

force-app/main/default/objects/TW1_Step__c/TW1_Step__c.object-meta.xml
<CustomObject>
    <label>Step</label>
    <nameField>
        <displayFormat>S{000000}</displayFormat>
        <label>Steps Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Step__c/fields/TW1_Email__c.field-meta.xml
<CustomField>
    <fullName>TW1_Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/TW1_Step__c/fields/TW1_Interaction__c.field-meta.xml
<CustomField>
    <fullName>TW1_Interaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interaction</label>
    <referenceTo>TW1_Interaction__c</referenceTo>
    <relationshipLabel>Steps</relationshipLabel>
    <relationshipName>Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Step__c/fields/TW1_Request__c.field-meta.xml
<CustomField>
    <fullName>TW1_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request</label>
    <referenceTo>TW1_Request__c</referenceTo>
    <relationshipLabel>Steps</relationshipLabel>
    <relationshipName>Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Step__c/fields/TW1_Status__c.field-meta.xml
<CustomField>
    <fullName>TW1_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opened</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Step__c/recordTypes/BM_NF.recordType-meta.xml
<RecordType>
    <fullName>BM_NF</fullName>
    <active>true</active>
    <label>BM - NF</label>
</RecordType>

force-app/main/default/classes/T_MODEC_CreateDocTST.cls
/**
 * @File Name          : T_MODEC_CreateDocTST.cls
 * @Description        : Classe de teste para Componente do lightning CreateDoc
 * @Author             : Rafael Hadama
 * @Group              :
 * @Last Modified By   : Rafael Hadama
 * @Last Modified On   : 07-22-2020
 * @Modification Log   :
 * Ver       Date            Author              Modification
 * 1.0    03/02/2020   Rafael Hadama     Initial Version
 **/
@IsTest
public class T_MODEC_CreateDocTST {
    static void MakeMetadataAndCustomSettings()
    {
        system.debug('Teste system debug dentro do testSetupmetodo');
        T_Debug_Setting__mdt testSetting = new T_Debug_Setting__mdt();
        testSetting.Label                          = 'Teste';
        testSetting.DeveloperName                  = 'Teste';
        testSetting.T_Armazenar_Cause__c           = true;
        testSetting.T_Armazenar_linha_debug__c     = true;
        testSetting.T_Armazenar_StackTrace__c      = true;
        testSetting.T_Armazenar_texto_Exception__c = true;
        T_SDK_DebugLog_Test.testSetting            = testSetting;

        //Creating Custom Settings
        ID_Account__c customSettingIdAccount = new ID_Account__c();
        customSettingIdAccount.Id_IntegrationUser__c = UserInfo.getUserId();
        insert customSettingIdAccount;

        Controle_de_Triggers__c customControleTrigger = new Controle_de_Triggers__c();
        customControleTrigger.Trigger_Request__c = true;
        customControleTrigger.Trigger_Account__c = true;
        customControleTrigger.Triscal_User_Id__c = UserInfo.getUserId();
        insert customControleTrigger;
        
        QueueSobject queue = [SELECT QueueId FROM QueueSobject where SobjectType =: 'TW1_Interaction__c' and Queue.DeveloperName =: 'VV_Team' limit 1];
        ID_Queues__c customSettingIDQueues = new ID_Queues__c();
        customSettingIDQueues.ID_VV_Team_Queue__c = queue.QueueId;
        insert customSettingIDQueues;
    }

    @isTest
    public static void findSobjectTypeTST()
    {
        MakeMetadataAndCustomSettings();
        Test.startTest();
        RecordType accRec_VendorHomologated = [Select id from Recordtype where developername = 'TW1_Vendor_Homologated'];
        Account    contamock = new Account();

        contamock.recordtypeId        = accRec_VendorHomologated.id;
        contamock.name                = 'Conta ENVIO Boletim';
        contamock.TW1_CPF__c          = '57034551030';
        contamock.TW1_Contact_Name__c = 'Contato Mock';
        insert contamock;

        T_MODEC_CreateDoc_CTRL.findSobjectType(string.valueOf(contamock.Id));

        list<T_MODEC_CreateDoc_CTRL.recTypesDto> listRecTypes = T_MODEC_CreateDoc_CTRL.getlistRecTypesDocumentation(contamock.Id);
        system.assertEquals(true, listRecTypes.size() > 0);
        map<string, String> mapRecTypes = T_MODEC_CreateDoc_CTRL.getRectypeMap(contamock.Id);
        system.assertEquals(true, mapRecTypes.size() > 0);
    }

    @isTest
    public static void CreateDocumentationTST()
    {
        MakeMetadataAndCustomSettings();
        Test.startTest();
        RecordType accRec_VendorHomologated = [Select id from Recordtype where developername = 'TW1_Vendor_Homologated'];
        Account    contamock = new Account();

        contamock.recordtypeId        = accRec_VendorHomologated.id;
        contamock.name                = 'Conta ENVIO Boletim';
        contamock.TW1_CPF__c          = '57034551030';
        contamock.TW1_Contact_Name__c = 'Contato Mock';
        insert contamock;

        //Criando TW1_Email_List__c para passar da trigger.
        TW1_Email_List__c emailList = new TW1_Email_List__c();
        emailList.TW1_Email__c  = 'emailRequestermock@mock.com';
        emailList.TW1_Status__c = 'Ativo';
        emailList.RecordTypeId  = Schema.SObjectType.TW1_Email_List__c.getRecordTypeInfosByDeveloperName().get('TW1_BM_Email').getRecordTypeId();
        insert emailList;
        
        //Query no recordType e criação do Request do tipo BM
        RecordType     requestRec_BM = [Select id from Recordtype where developername = 'TW1_BM'];
        TW1_Request__c BMmock1       = new TW1_Request__c();
        BMmock1.recordTypeId  = requestRec_BM.id;
        BMmock1.TW1_Vendor__c = contamock.id;
        BMmock1.BM_Status__c  = 'Não enviado';
        BMmock1.TW1_BM_Reference_Number_in_SAP_MODEC__c = '1112223334';

        BMmock1.TW1_PO__c                    = '12345';
        BMmock1.TW1_Purchase_Item__c         = '00010';
        BMmock1.TW1_Service_Start_Date__c    = date.today();
        BMmock1.TW1_Service_End_Date__c      = date.today().addDays(50);
        BMmock1.TW1_Supplier_Email__c        = 'emailSuppliermock@mock.com';
        BMmock1.TW1_Modec_Requester_Email__c = 'emailRequestermock@mock.com';
        BMmock1.TW1_Final_Measurement__c     = 'Yes';
        BMmock1.TW1_Service_Description__c   = '12345';

        insert BMmock1;

        list<T_MODEC_CreateDoc_CTRL.recTypesDto> listRecTypes = T_MODEC_CreateDoc_CTRL.getlistRecTypesDocumentation(contamock.Id);

        string DocCreatedId = T_MODEC_CreateDoc_CTRL.createDocumentationAuxiliar(listRecTypes[0].value, BMmock1.Id);
        system.assertEquals(true, DocCreatedId != '');
    }

    @isTest
    public static void UpdateDocRequestTST()
    {
        MakeMetadataAndCustomSettings();
        Test.startTest();
        RecordType accRec_VendorHomologated = [Select id from Recordtype where developername = 'TW1_Vendor_Homologated'];
        Account    contamock = new Account();

        contamock.recordtypeId        = accRec_VendorHomologated.id;
        contamock.name                = 'Conta ENVIO Boletim';
        contamock.TW1_CPF__c          = '57034551030';
        contamock.TW1_Contact_Name__c = 'Contato Mock';
        insert contamock;

        //Criando TW1_Email_List__c para passar da trigger.
        TW1_Email_List__c emailList = new TW1_Email_List__c();
        emailList.TW1_Email__c  = 'emailRequestermock@mock.com';
        emailList.TW1_Status__c = 'Ativo';
        emailList.RecordTypeId  = Schema.SObjectType.TW1_Email_List__c.getRecordTypeInfosByDeveloperName().get('TW1_BM_Email').getRecordTypeId();
        insert emailList;
        //Query no recordType e criação do Request do tipo BM
        RecordType     requestRec_BM = [Select id from Recordtype where developername = 'TW1_BM'];
        TW1_Request__c BMmock1       = new TW1_Request__c();
        BMmock1.recordTypeId  = requestRec_BM.id;
        BMmock1.TW1_Vendor__c = contamock.id;
        BMmock1.BM_Status__c  = 'Não enviado';
        BMmock1.TW1_BM_Reference_Number_in_SAP_MODEC__c = '1112223334';

        BMmock1.TW1_PO__c                    = '12345';
        BMmock1.TW1_Purchase_Item__c         = '00010';
        BMmock1.TW1_Service_Start_Date__c    = date.today();
        BMmock1.TW1_Service_End_Date__c      = date.today().addDays(50);
        BMmock1.TW1_Supplier_Email__c        = 'emailSuppliermock@mock.com';
        BMmock1.TW1_Modec_Requester_Email__c = 'emailRequestermock@mock.com';
        BMmock1.TW1_Final_Measurement__c     = 'Yes';
        BMmock1.TW1_Service_Description__c   = '12345';

        insert BMmock1;

        list<T_MODEC_CreateDoc_CTRL.recTypesDto> listRecTypes = T_MODEC_CreateDoc_CTRL.getlistRecTypesDocumentation(contamock.Id);

        string DocCreatedId = T_MODEC_CreateDoc_CTRL.createDocumentationAuxiliar(listRecTypes[0].value, BMmock1.Id);
        string UpdateDocId  = T_MODEC_CreateDoc_CTRL.updateDoc(DocCreatedId, BMmock1.Id, 'Comentarios Mock');

        system.assertEquals(true, DocCreatedId == UpdateDocId);
    }

    @isTest
    public static void UpdateDocStepTST()
    {
        MakeMetadataAndCustomSettings();
        RecordType accRec_VendorHomologated = [Select id from Recordtype where developername = 'TW1_Vendor_Homologated'];
        Account    contamock = new Account();

        contamock.recordtypeId        = accRec_VendorHomologated.id;
        contamock.name                = 'Conta ENVIO Boletim';
        contamock.TW1_CPF__c          = '57034551030';
        contamock.TW1_Contact_Name__c = 'Contato Mock';
        insert contamock;

        //Query no recordType e criação do Request do tipo BM
        RecordType  StepRec_BMNF = [Select id from Recordtype where developername = 'BM_NF'];
        TW1_Step__c StepMock     = new TW1_Step__c();
        StepMock.RecordTypeId = StepRec_BMNF.Id;


        insert StepMock;

        list<T_MODEC_CreateDoc_CTRL.recTypesDto> listRecTypes = T_MODEC_CreateDoc_CTRL.getlistRecTypesDocumentation(StepMock.Id);

        string DocCreatedId = T_MODEC_CreateDoc_CTRL.createDocumentationAuxiliar(listRecTypes[0].value, StepMock.Id);
        string UpdateDocId  = T_MODEC_CreateDoc_CTRL.updateDoc(DocCreatedId, StepMock.Id, 'Comentarios Mock');

        system.assertEquals(true, DocCreatedId == UpdateDocId);
    }

    @isTest
    public static void UpdateDocInteractionTST()
    {
        MakeMetadataAndCustomSettings();
        Test.startTest();
        RecordType accRec_VendorHomologated = [Select id from Recordtype where developername = 'TW1_Vendor_Homologated'];
        Account    contamock = new Account();

        contamock.recordtypeId        = accRec_VendorHomologated.id;
        contamock.name                = 'Conta ENVIO Boletim';
        contamock.TW1_CPF__c          = '57034551030';
        contamock.TW1_Contact_Name__c = 'Contato Mock';
        insert contamock;

        //Query no recordType e criação do Request do tipo BM
        RecordType         interactionRecType = [Select id from Recordtype where developername = 'TW1_QA_QC_Inspection'];
        TW1_Interaction__c InteractionMock    = new TW1_Interaction__c();
        InteractionMock.RecordTypeId = interactionRecType.Id;
        InteractionMock.TW3_From_Portal__c = 'Brazil';

        insert InteractionMock;

        list<T_MODEC_CreateDoc_CTRL.recTypesDto> listRecTypes = T_MODEC_CreateDoc_CTRL.getlistRecTypesDocumentation(InteractionMock.Id);

        string DocCreatedId = T_MODEC_CreateDoc_CTRL.createDocumentationAuxiliar(listRecTypes[0].value, InteractionMock.Id);
        string UpdateDocId  = T_MODEC_CreateDoc_CTRL.updateDoc(DocCreatedId, InteractionMock.Id, 'Comentarios Mock');

        system.assertEquals(true, DocCreatedId == UpdateDocId);
    }

    @isTest
    public static void UpdateDocModecContractTST()
    {
        MakeMetadataAndCustomSettings();
        Test.startTest();
        RecordType accRec_VendorHomologated = [Select id from Recordtype where developername = 'TW1_Vendor_Homologated'];
        Account    contamock = new Account();

        contamock.recordtypeId        = accRec_VendorHomologated.id;
        contamock.name                = 'Conta ENVIO Boletim';
        contamock.TW1_CPF__c          = '57034551030';
        contamock.TW1_Contact_Name__c = 'Contato Mock';
        insert contamock;

        //Query no recordType e criação do Request do tipo BM

        TW1_MODEC_Contract__c ContractMock = new TW1_MODEC_Contract__c();
        ContractMock.TW1_Vendor__c = contamock.Id;
        ContractMock.Name          = 'Contrato Mock';


        insert ContractMock;

        list<T_MODEC_CreateDoc_CTRL.recTypesDto> listRecTypes = T_MODEC_CreateDoc_CTRL.getlistRecTypesDocumentation(ContractMock.Id);

        string DocCreatedId = T_MODEC_CreateDoc_CTRL.createDocumentationAuxiliar(listRecTypes[0].value, ContractMock.Id);
        string UpdateDocId  = T_MODEC_CreateDoc_CTRL.updateDoc(DocCreatedId, ContractMock.Id, 'Comentarios Mock');

        system.assertEquals(true, DocCreatedId == UpdateDocId);
    }

    @isTest
    public static void InsertDocModecContractNegativeTST()
    {
        MakeMetadataAndCustomSettings();
        Test.startTest();
        RecordType accRec_VendorHomologated = [Select id from Recordtype where developername = 'TW1_Vendor_Homologated'];
        Account    contamock = new Account();

        contamock.recordtypeId        = accRec_VendorHomologated.id;
        contamock.name                = 'Conta ENVIO Boletim';
        contamock.TW1_CPF__c          = '57034551030';
        contamock.TW1_Contact_Name__c = 'Contato Mock';
        insert contamock;

        //Query no recordType e criação do Request do tipo BM

        TW1_MODEC_Contract__c ContractMock = new TW1_MODEC_Contract__c();
        ContractMock.TW1_Vendor__c = contamock.Id;
        ContractMock.Name          = 'Contrato Mock';


        insert ContractMock;

        list<T_MODEC_CreateDoc_CTRL.recTypesDto> listRecTypes = T_MODEC_CreateDoc_CTRL.getlistRecTypesDocumentation(ContractMock.Id);

        string DocCreatedId = T_MODEC_CreateDoc_CTRL.createDocumentationAuxiliar(listRecTypes[0].value, ContractMock.Id);

        string DocCreatedIdNegative = T_MODEC_CreateDoc_CTRL.createDocumentationAuxiliar('', ContractMock.Id);
        system.assertEquals(true, DocCreatedIdNegative == '');

        //Passing empty string as Id

        /*string UpdateDocIdNegative  = T_MODEC_CreateDoc_CTRL.updateDoc(DocCreatedId, '', 'Comentarios Mock');
         *
         * system.assertEquals(true, UpdateDocIdNegative == '');*/
    }

    @isTest
    public static void UpdateDocModecContractNegativeTST()
    {
        MakeMetadataAndCustomSettings();
        Test.startTest();
        RecordType accRec_VendorHomologated = [Select id from Recordtype where developername = 'TW1_Vendor_Homologated'];
        Account    contamock = new Account();

        contamock.recordtypeId        = accRec_VendorHomologated.id;
        contamock.name                = 'Conta ENVIO Boletim';
        contamock.TW1_CPF__c          = '57034551030';
        contamock.TW1_Contact_Name__c = 'Contato Mock';
        insert contamock;

        //Query no recordType e criação do Request do tipo BM

        TW1_MODEC_Contract__c ContractMock = new TW1_MODEC_Contract__c();
        ContractMock.TW1_Vendor__c = contamock.Id;
        ContractMock.Name          = 'Contrato Mock';


        insert ContractMock;

        list<T_MODEC_CreateDoc_CTRL.recTypesDto> listRecTypes = T_MODEC_CreateDoc_CTRL.getlistRecTypesDocumentation(ContractMock.Id);

        string DocCreatedId = T_MODEC_CreateDoc_CTRL.createDocumentationAuxiliar(listRecTypes[0].value, ContractMock.Id);

        //Passing empty string as Id
        string UpdateDocId         = T_MODEC_CreateDoc_CTRL.updateDoc(DocCreatedId, ContractMock.Id, 'Comentarios Mock');
        string UpdateDocIdNegative = T_MODEC_CreateDoc_CTRL.updateDoc('', ContractMock.Id, 'Comentarios Mock');

        system.assertEquals(true, UpdateDocIdNegative == '');
    }
    
    @isTest
    public static void getTypeOfRecordIdTST(){
        Lead record = new Lead();
        record.company = 'Test a Teste';
        record.lastName = 'Sr Teste';
        record.Email = 'test@teste.com';
        insert record;
        
        Test.startTest();        
        String msgComId = T_MODEC_CreateDoc_CTRL.getTypeOfRecordId(record.Id);
		Test.stopTest();

        System.assertEquals('Lead', msgComId);
    }
    
    @isTest
    public static void TestMethod_getMainSObjectRecordFromRecordId(){
        Lead l = new Lead();
        l.lastName = 'TestMethod_getMainSObjectRecordFromRecordId';
        l.company = 'TestMethod_getMainSObjectRecordFromRecordId';
        l.Email = 'test@test.com';
        insert l;
        Id recordId = l.id;
        T_MODEC_CreateDoc_CTRL.getMainSObjectRecordFromRecordId(recordId, 'Email');
    }
}