force-app/main/default/objects/Account/fields/TW1_Step_Owner__c.field-meta.xml
<CustomField>
    <fullName>TW1_Step_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Step Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Supplier</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TOBJ_Participants__c/TOBJ_Participants__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>PN-{YYYY}{MM}-{0000}</displayFormat>
        <label>Nome do Participante</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TOBJ_Participants__c/fields/EmailSent__c.field-meta.xml
<CustomField>
    <fullName>EmailSent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>E-mail enviado?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TOBJ_Participants__c/fields/TCF_EmailHSEQSupplier__c.field-meta.xml
<CustomField>
    <fullName>TCF_EmailHSEQSupplier__c</fullName>
    <formula>TCF_Supplier__r.TCF_HSEQResponsibleEmail__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>E-mail Fornecedor HSEQ</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TOBJ_Participants__c/fields/TCF_Supplier__c.field-meta.xml
<CustomField>
    <fullName>TCF_Supplier__c</fullName>
    <label>Fornecedor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>TRN_ParticipantsAccount</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TOBJ_Participants__c/fields/Warning__c.field-meta.xml
<CustomField>
    <fullName>Warning__c</fullName>
    <label>Warning</label>
    <referenceTo>TOBJ_Warning__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>TRN_ParticipantsWarning</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TOBJ_Warning__c/TOBJ_Warning__c.object-meta.xml
<CustomObject>
    <label>Warning</label>
    <nameField>
        <displayFormat>WARN-{00000000}</displayFormat>
        <label>Nome do Aviso</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Warning</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/TOBJ_Warning__c/fields/TCF_HSEQWarning__c.field-meta.xml
<CustomField>
    <fullName>TCF_HSEQWarning__c</fullName>
    <label>Comunicado HSEQ?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/T_WarningHelper.cls
public class T_WarningHelper {

    private List<TOBJ_Participants__c> participantes;
    private List<T_DefaultEmail.Email> emails;
    private Set<String> setWarningIds;
    private Map<String, List<SObject>> mapaContentDocumentLink;
    private Map<String, SObject> mapaContentVersion;
    private Map<String, List<T_DefaultEmail.EmailFile>> mapaFiles;
    
    public T_WarningHelper(){
        this.emails = new List<T_DefaultEmail.Email>();
        this.mapaFiles = new Map<String, List<T_DefaultEmail.EmailFile>>();
    }
    
    public void setParticipantes(List<TOBJ_Participants__c> participantes){
        this.participantes = participantes;
        setWarningIds();
    }
    
    private void setWarningIds(){
        this.setWarningIds = T_Utils.getSetIds(participantes, 'Warning__c');
    }
    
    public void getContentDocumentLinksForWarnings(){
        List<ContentDocumentLink> cdls = [select id, contentDocumentId, LinkedEntityId from ContentDocumentLink where LinkedEntityId in: this.setWarningIds];
        Set<String> setContentDocuments = T_Utils.getSetIds(cdls, 'contentDocumentId');
        List<ContentVersion> cvs = [select id, contentDocumentId, VersionData, ContentSize, Title, FileExtension from ContentVersion where contentDocumentId in: setContentDocuments];
        this.mapaContentDocumentLink = T_Utils.montaMapaListaSObjectComCampoComoChave('LinkedEntityId', cdls);
        this.mapaContentVersion = T_Utils.montaMapaSObjectComCampoComoChave('contentDocumentId', cvs);
        buildMapFromFilesByWarning();
    }
    
    private void buildMapFromFilesByWarning(){
        for(String warningId: this.setWarningIds){
            IF(this.mapaContentDocumentLink.containsKey(warningId)){
                Integer tam = 0;
                List<T_DefaultEmail.EmailFile> temp = new List<T_DefaultEmail.EmailFile>();
                for(SObject cdl: this.mapaContentDocumentLink.get(warningId)){
                    IF(this.mapaContentVersion.containsKey(String.valueOf(cdl.get('contentDocumentId')))){
                        ContentVersion cv = (ContentVersion) this.mapaContentVersion.get(String.valueOf(cdl.get('contentDocumentId')));
                        IF((tam+cv.ContentSize) < 25000000){
                            T_DefaultEmail.EmailFile arquivo = new T_DefaultEmail.EmailFile();
                            arquivo.file = cv.versionData;
                            arquivo.fileName = cv.Title + '.' + cv.FileExtension;
                            System.debug('FILENAME GUFS: '+ arquivo.fileName);
                            tam += cv.ContentSize;
                            temp.add(arquivo);
                        }
                    }
                }
                this.mapaFiles.put(warningId, temp);
            }
        }
    }
    
    public void montarEmailsWarning(){
        OrgWideEmailAddress owea = [select id, Address from OrgWideEmailAddress where Address =: 'noreply@modec.com' limit 1];
        
        for(TOBJ_Participants__c participante: participantes){
            T_DefaultEmail.Email email = new T_DefaultEmail.Email();
            email.emailTemplateDeveloperName = 'WarningEmailToSupplier';
            email.recordId = participante.Warning__c;
            email.ContactLeadOrUserId = participante.TCF_Supplier__r.TW1_Step_Owner__r.ContactId;
            email.OrgWideEmailAddressId = owea.id;
            email.ReplyTo = owea.Address;
            email.destinatarios = new List<String>();
            email.destinatarios.add(participante.TCF_Supplier__r.TW1_Step_Owner__r.Contact.Email);
            
            IF(participante.Warning__r.TCF_HSEQWarning__c == 'Yes'){
                email.destinatariosEmCopiaOculta = new List<String>();
                email.destinatariosEmCopiaOculta.add(participante.TCF_EmailHSEQSupplier__c);
            }
            
            IF(this.mapaFiles.containsKey(participante.Warning__c)) {
                email.files = this.mapaFiles.get(participante.Warning__c);
            }
            
            this.emails.add(email);
            participante.EmailSent__c = true;
        }
    }
    
    public void sendEmails(){
        T_DefaultEmail.sendEmail(this.emails);
    }
    
    public void updateParticipantes(){
        update this.participantes;
    }
}