force-app/main/default/objects/Account/fields/TW1_CNPJ__c.field-meta.xml
<CustomField>
    <fullName>TW1_CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_Step_Owner__c.field-meta.xml
<CustomField>
    <fullName>TW1_Step_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Step Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Supplier</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/TW1_Supplier_Type__c.field-meta.xml
<CustomField>
    <fullName>TW1_Supplier_Type__c</fullName>
    <label>Supplier Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BANK</fullName>
            </value>
            <value>
                <fullName>GOVERNMENT OFFICE</fullName>
            </value>
            <value>
                <fullName>INDIRECTLY AFFILIATED COMPANY</fullName>
            </value>
            <value>
                <fullName>INDIVIDUAL REAL ESTATE OWNER</fullName>
            </value>
            <value>
                <fullName>LAW FIRM</fullName>
            </value>
            <value>
                <fullName>MUNICIPALITY</fullName>
            </value>
            <value>
                <fullName>NON-PROFIT PROFESSIONAL TRADE ORGANIZATION</fullName>
            </value>
            <value>
                <fullName>OTHER</fullName>
            </value>
            <value>
                <fullName>STATE UNIVERSITY</fullName>
            </value>
            <value>
                <fullName>TAX/AUDIT FIRM</fullName>
            </value>
            <value>
                <fullName>TAXING AUTHORITY</fullName>
            </value>
            <value>
                <fullName>UTILITY PROVIDER</fullName>
            </value>
            <value>
                <fullName>WORLDWIDE TRANSPORTATION</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TOBJ_Participants__c/TOBJ_Participants__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>PN-{YYYY}{MM}-{0000}</displayFormat>
        <label>Nome do Participante</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TOBJ_Participants__c/fields/AvailableToSuppliers__c.field-meta.xml
<CustomField>
    <fullName>AvailableToSuppliers__c</fullName>
    <formula>AND(Warning__r.PublicationDate__c &lt;= TODAY(),
    Warning__r.TCF_DueDate__c &gt;= TODAY()
)</formula>
    <label>Disponível para fornecedores?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TOBJ_Participants__c/fields/EmailSent__c.field-meta.xml
<CustomField>
    <fullName>EmailSent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>E-mail enviado?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TOBJ_Participants__c/fields/RequiredSendEmail__c.field-meta.xml
<CustomField>
    <fullName>RequiredSendEmail__c</fullName>
    <formula>TEXT(Warning__r.RequiredSendEmail__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Necessita envio de e-mail?</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TOBJ_Participants__c/fields/TCF_EmailHSEQSupplier__c.field-meta.xml
<CustomField>
    <fullName>TCF_EmailHSEQSupplier__c</fullName>
    <formula>TCF_Supplier__r.TCF_HSEQResponsibleEmail__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>E-mail Fornecedor HSEQ</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TOBJ_Participants__c/fields/TCF_EmailStepOwner__c.field-meta.xml
<CustomField>
    <fullName>TCF_EmailStepOwner__c</fullName>
    <formula>TCF_Supplier__r.TW1_Step_Owner__r.Contact.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>E-mail do Proprietário</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TOBJ_Participants__c/fields/TCF_Supplier__c.field-meta.xml
<CustomField>
    <fullName>TCF_Supplier__c</fullName>
    <label>Fornecedor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>TRN_ParticipantsAccount</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TOBJ_Participants__c/fields/Warning__c.field-meta.xml
<CustomField>
    <fullName>Warning__c</fullName>
    <label>Warning</label>
    <referenceTo>TOBJ_Warning__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>TRN_ParticipantsWarning</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TOBJ_Warning__c/TOBJ_Warning__c.object-meta.xml
<CustomObject>
    <label>Warning</label>
    <nameField>
        <displayFormat>WARN-{00000000}</displayFormat>
        <label>Nome do Aviso</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Warning</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/TOBJ_Warning__c/fields/RequiredSendEmail__c.field-meta.xml
<CustomField>
    <fullName>RequiredSendEmail__c</fullName>
    <label>Requer envio de e-mail?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TOBJ_Warning__c/fields/TCF_DueDate__c.field-meta.xml
<CustomField>
    <fullName>TCF_DueDate__c</fullName>
    <label>Data de vencimento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TOBJ_Warning__c/fields/TCF_HSEQWarning__c.field-meta.xml
<CustomField>
    <fullName>TCF_HSEQWarning__c</fullName>
    <label>Comunicado HSEQ?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/T_ParticipantRep.cls
public class T_ParticipantRep {

    public static List<TOBJ_Participants__c> getParticipantWhereEmailNotSentYet(){
        List<TOBJ_Participants__c> retorno = new List<TOBJ_Participants__c>();
        try{
           retorno = [select id, Warning__r.TCF_DueDate__c, TCF_EmailStepOwner__c, Warning__c, TCF_EmailHSEQSupplier__c,
                    TCF_Supplier__r.TW1_Step_Owner__r.ContactId, Warning__r.TCF_HSEQWarning__c, TCF_Supplier__r.TW1_Step_Owner__r.Contact.Email
                    from TOBJ_Participants__c
                    where AvailableToSuppliers__c = true and EmailSent__c = false and Warning__r.RequiredSendEmail__c = 'Yes'
                          and TCF_Supplier__r.TW1_Step_Owner__r.Contact.Email != null
                    order by Warning__r.TCF_DueDate__c, Warning__c desc
                    limit 200];
        } catch(Exception e) {retorno = null;}
        return retorno;
    }
    
    public static List<TOBJ_Participants__c> getParticipantByWarningId(Set<String> warningIds){
        List<TOBJ_Participants__c> retorno = new List<TOBJ_Participants__c>();
        try{
            retorno = [select id, Warning__r.TCF_DueDate__c, TCF_EmailStepOwner__c, Warning__c, TCF_EmailHSEQSupplier__c,
                    TCF_Supplier__r.TW1_Step_Owner__r.ContactId, Warning__r.TCF_HSEQWarning__c, TCF_Supplier__r.TW1_Step_Owner__r.Contact.Email
                    from TOBJ_Participants__c
                    where AvailableToSuppliers__c = true and Warning__c in: warningIds and EmailSent__c = false and Warning__r.RequiredSendEmail__c = 'Yes'
                          and TCF_Supplier__r.TW1_Step_Owner__r.Contact.Email != null
                    order by Warning__r.TCF_DueDate__c, Warning__c desc
                    limit 200];
        } catch(Exception e) {retorno = null;}
        return retorno;
    }
    
    public static List<TOBJ_Participants__c> getParticipantsByWarning(String warningId){
        List<TOBJ_Participants__c> retorno = new List<TOBJ_Participants__c>();
        
        try {
            retorno = [select id, name, TCF_Supplier__r.Name, TCF_Supplier__r.TW1_CNPJ__c, TCF_Supplier__r.TW1_Supplier_Type__c
                       from TOBJ_Participants__c 
                       where Warning__c =: warningId
                       limit 10000];
        } catch(Exception e) {retorno = null;}
        return retorno;
    }
}