force-app/main/default/objects/TW1_Category__c/TW1_Category__c.object-meta.xml
<CustomObject>
    <label>Category</label>
    <nameField>
        <displayFormat>CT{000000}</displayFormat>
        <label>Category Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Category__c/fields/TW1_Category__c.field-meta.xml
<CustomField>
    <fullName>TW1_Category__c</fullName>
    <label>Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Category__c/fields/TW1_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>TW1_Sub_Category__c</fullName>
    <label>Sub-Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Vendor_Category__c/TW1_Vendor_Category__c.object-meta.xml
<CustomObject>
    <description>Antigo Vendor category</description>
    <label>Supplier Category</label>
    <nameField>
        <displayFormat>VC{00000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suppliers Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Vendor_Category__c/fields/TW1_Category__c.field-meta.xml
<CustomField>
    <fullName>TW1_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <referenceTo>TW1_Category__c</referenceTo>
    <relationshipName>Vendors_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Vendor_Category__c/fields/TW1_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>TW1_Expiration_Date__c</fullName>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TW1_Vendor_Category__c/fields/TW1_Status__c.field-meta.xml
<CustomField>
    <fullName>TW1_Status__c</fullName>
    <defaultValue>&quot;Not Homologated&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Homologated</fullName>
            </value>
            <value>
                <fullName>Not Homologated</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Vendor_Category__c/fields/TW1_Vendor__c.field-meta.xml
<CustomField>
    <fullName>TW1_Vendor__c</fullName>
    <label>Supplier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Suppliers Categories</relationshipLabel>
    <relationshipName>Vendors_Categories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/T_MODEC_VendorCategory_Rep.cls
/**
 * @File Name          : T_MODEC_VendorCategory_Rep.cls
 * @Description        : 
 * @Author             : Rafael Hadama
 * @Group              : 
 * @Last Modified By   : Rafael Hadama
 * @Last Modified On   : 19/02/2020 14:03:50
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    18/02/2020   Rafael Hadama     Initial Version
**/
public class T_MODEC_VendorCategory_Rep {
    
    public static list<TW1_Vendor_Category__c> getVendorCategoryById(String accountId){ 

        list<TW1_Vendor_Category__c> req = [
            SELECT
            id,
            Name,
            TW1_VEndor__c,
            TW1_Category__c,
            TW1_Category__r.TW1_Category__c,
            TW1_Category__r.TW1_Sub_Category__c
            FROM
            TW1_Vendor_Category__c
            WHERE
            TW1_VEndor__c =: accountId
        ];

        //AND TW1_Vendor_Category__c.TW1_Status__c != 'Homologated'
        return req;

    }

    public list<TW1_Vendor_Category__c> GetVendorCategoriesExpiring(){ 

        list<TW1_Vendor_Category__c> req = [
            SELECT
            id,
            Name,
            TW1_Vendor__c ,
            TW1_Category__c,
            TW1_Category__r.TW1_Category__c,
            TW1_Category__r.TW1_Sub_Category__c,
            TW1_Status__c 
            FROM
            TW1_Vendor_Category__c
            WHERE
            TW1_Expiration_Date__c  < TODAY
            AND TW1_Status__c = 'Homologated'
        ];

        return req;

    }
 }