force-app/main/default/objects/TW1_Category__c/TW1_Category__c.object-meta.xml
<CustomObject>
    <label>Category</label>
    <nameField>
        <displayFormat>CT{000000}</displayFormat>
        <label>Category Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Category__c/fields/TW1_Category__c.field-meta.xml
<CustomField>
    <fullName>TW1_Category__c</fullName>
    <label>Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Category__c/fields/TW1_Category_EN__c.field-meta.xml
<CustomField>
    <fullName>TW1_Category_EN__c</fullName>
    <label>Category (EN)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Category__c/fields/TW1_Code__c.field-meta.xml
<CustomField>
    <fullName>TW1_Code__c</fullName>
    <label>Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Category__c/fields/TW1_Country__c.field-meta.xml
<CustomField>
    <fullName>TW1_Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Category__c/fields/TW1_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>TW1_Sub_Category__c</fullName>
    <label>Sub-Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Category__c/fields/TW1_SUB_CATEGORY_EN__c.field-meta.xml
<CustomField>
    <fullName>TW1_SUB_CATEGORY_EN__c</fullName>
    <label>Sub Categoria (EN)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Category__c/fields/TW3_Category_FR__c.field-meta.xml
<CustomField>
    <fullName>TW3_Category_FR__c</fullName>
    <label>Category (FR)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Category__c/fields/TW3_Sub_Categoria_FR__c.field-meta.xml
<CustomField>
    <fullName>TW3_Sub_Categoria_FR__c</fullName>
    <label>Sub Categoria (FR)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/T_MODEC_Category_Rep.cls
/**
 * @File Name          : T_MODEC_Category_Rep.cls
 * @Description        :
 * @Author             : Rafael Hadama
 * @Group              :
 * @Last Modified By   : Rafael Hadama
 * @Last Modified On   : 09-23-2020
 * @Modification Log   :
 * Ver       Date            Author              Modification
 * 1.0    04/11/2019   Rafael Hadama     Initial Version
 **/
public class T_MODEC_Category_Rep {
    public list<TW1_Category__c> getCategoriesbyCountryAndRecType(string pais)
    {
        list<TW1_Category__c> listaCategorias = new list<TW1_Category__c>();

        listaCategorias = [SELECT Id, RecordType.DeveloperName, TW1_Code__c, TW1_Category__c, TW1_Sub_Category__c FROM TW1_Category__c WHERE TW1_Country__c =:pais ORDER BY TW1_Sub_Category__c DESC, TW1_Category__c DESC];

        return listaCategorias;
    }

    public list<TW1_Category__c> getAllCategories()
    {
        list<TW1_Category__c> listaCategorias = new list<TW1_Category__c>();

        listaCategorias = [SELECT Id, RecordType.DeveloperName, TW1_Code__c, TW1_Category__c, TW1_Sub_Category__c, TW1_SUB_CATEGORY_EN__c, TW1_Category_EN__c, TW3_Category_FR__c, TW3_Sub_Categoria_FR__c FROM TW1_Category__c ORDER BY TW1_Sub_Category__c DESC, TW1_Category__c DESC];

        return listaCategorias;
    }

    /*public list<RecordType> getRecordTypesforCategory()
     * {
     * list<RecordType> listRecTypes = [select id, DeveloperName from RecordType where SobjectType = 'TW1_Category__c'];
     *
     * return listRecTypes;
     * }*/
}