force-app/main/default/objects/Vessel__c/Vessel__c.object-meta.xml
<CustomObject>
    <label>Vessel</label>
    <nameField>
        <label>Vessel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vessels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vessel__c/fields/Management__c.field-meta.xml
<CustomField>
    <fullName>Management__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Management</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Vessels</relationshipLabel>
    <relationshipName>Vessels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vessel__c/fields/ManagementName__c.field-meta.xml
<CustomField>
    <fullName>ManagementName__c</fullName>
    <formula>Management__r.Name</formula>
    <label>Management Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VesselClientHistory__c/VesselClientHistory__c.object-meta.xml
<CustomObject>
    <label>Vessel Client History</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>History Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vessel Client Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VesselClientHistory__c/fields/Vessel__c.field-meta.xml
<CustomField>
    <fullName>Vessel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vessel</label>
    <referenceTo>Vessel__c</referenceTo>
    <relationshipLabel>Vessel Client Histories</relationshipLabel>
    <relationshipName>VesselClientHistories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/VesselBO.cls
public with sharing class VesselBO {

    private static final VesselBO instance = new VesselBO();

	public static VesselBO getInstance() {
		return instance;
    }

    public void populateVesselClientHistory (List<Vessel__c> lstVessel, Map<Id, Vessel__c> oldMap)
    {
        List<VesselClientHistory__c> historyToInsert = new List<VesselClientHistory__c>();

        if(oldMap == null)
        {
            for(Vessel__c vessel : lstVessel)
            {
                if(vessel.Management__c != null)
                {
                    VesselClientHistory__c clientHistory = new VesselClientHistory__c();
                    clientHistory.Vessel__c = vessel.Id;
                    clientHistory.Date__c = System.today();
                    clientHistory.Observation__c = 'Client set to ' + vessel.ManagementName__c + ' by ' + UserInfo.getName();
    
                    historyToInsert.add(clientHistory);
                }
            }

            insert historyToInsert;
        }
        else 
        {
            for(Vessel__c vessel : lstVessel)
            {
                if(vessel.Management__c != null)
                {
                    if(vessel.Management__c != oldMap.get(vessel.Id).Management__c)
                    {
                        VesselClientHistory__c clientHistory = new VesselClientHistory__c();
                        clientHistory.Vessel__c = vessel.Id;
                        clientHistory.Date__c = System.today();
                        clientHistory.Observation__c = 'Management was changed from ' + oldMap.get(vessel.Id).ManagementName__c + ' to ' + vessel.ManagementName__c + ' by ' + UserInfo.getName();
    
                        historyToInsert.add(clientHistory);
                    }
                }
            }

            insert historyToInsert;
        }
    }
}