force-app/main/default/objects/NAM__c/NAM__c.object-meta.xml
<CustomObject>
    <label>NAM</label>
    <nameField>
        <label>NAM Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NAMs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NAM__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AMC</fullName>
                <default>true</default>
                <label>AMC</label>
            </value>
            <value>
                <fullName>OM</fullName>
            </value>
            <value>
                <fullName>PEM</fullName>
            </value>
            <value>
                <fullName>Tech Team</fullName>
            </value>
            <value>
                <fullName>SPC Partners</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>SPC Modec</fullName>
                <isActive>false</isActive>
                <label>SPC Modec</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TechnicalMemberSupport__c/TechnicalMemberSupport__c.object-meta.xml
<CustomObject>
    <label>Technical Member Support</label>
    <nameField>
        <displayFormat>TTS-{00000}</displayFormat>
        <label>Technical Member Support  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Technical Members Supports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TechnicalMemberSupport__c/fields/NAM__c.field-meta.xml
<CustomField>
    <fullName>NAM__c</fullName>
    <label>NAM</label>
    <referenceTo>NAM__c</referenceTo>
    <relationshipLabel>Technical Members Supports</relationshipLabel>
    <relationshipName>TechTeamsSupports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TechnicalMemberSupport__c/fields/Responsible__c.field-meta.xml
<CustomField>
    <fullName>Responsible__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsible</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TechTeamsSupports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TechnicalMemberSupport__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Supported</fullName>
            </value>
            <value>
                <fullName>Not Supported</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TechnicalMemberSupport__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NAM</fullName>
            </value>
            <value>
                <fullName>Closed Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TechnicalMemberSupportFactory.cls
public class TechnicalMemberSupportFactory {
    
    public static TechnicalMemberSupport__c createTechSupport(NAM__c nam, String status, User user, String phase){
        TechnicalMemberSupport__c techSupport = new TechnicalMemberSupport__c(
            NAM__c = nam.Id,
            Description__c = 'Test',
            Status__c = status,
            Responsible__c = user.Id,
            Type__c = phase
        );

        insert techSupport;
        return techSupport;
    }

    public static User createUser(String username, String profileName){
        Profile profile = [SELECT Id FROM Profile WHERE Name =: profileName];
        User user = new User(Alias = 'user1',
                             isActive = true,
                             Email = 'user@modec-test.com', 
                             EmailEncodingKey = 'UTF-8', 
                             LastName = 'user1', 
                             LanguageLocaleKey = 'en_US',
                             LocaleSidKey='en_US', 
                             ProfileId = profile.Id,
                             TimeZoneSidKey = 'America/Los_Angeles',
                             UserName = username);
        insert user;
        return user;
    }
}