force-app/main/default/objects/NAM__c/NAM__c.object-meta.xml
<CustomObject>
    <label>NAM</label>
    <nameField>
        <label>NAM Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NAMs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NAM__c/fields/ActionTaken__c.field-meta.xml
<CustomField>
    <fullName>ActionTaken__c</fullName>
    <label>Action Taken</label>
    <length>10000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/RootCause__c.field-meta.xml
<CustomField>
    <fullName>RootCause__c</fullName>
    <label>Root Cause</label>
    <length>10000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/ActionTaken__c.field-meta.xml
<CustomField>
    <fullName>ActionTaken__c</fullName>
    <label>Action Taken</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/NAM__c.field-meta.xml
<CustomField>
    <fullName>NAM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NAM</label>
    <referenceTo>NAM__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>WorkOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/RootCause__c.field-meta.xml
<CustomField>
    <fullName>RootCause__c</fullName>
    <label>Root Cause</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>WorkOrder__c</fullName>
    <externalId>true</externalId>
    <label>Work Order</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NamReportPdfController.cls
public without sharing class NamReportPdfController {

    private final NAM__c objNAM;
	// private final String wkNames;
    public string WorkOrderNames{
		get; set;
	}
    public NamReportPdfController(ApexPages.StandardController stdController) {
		this.objNAM = NamDAO.getById(stdController.getId());
		WorkOrderNames = '';
		for(WorkOrder wk : this.objNAM.WorkOrders__r){
			this.WorkOrderNames += wk.WorkOrder__c + ', '; 
		}
		integer index = this.WorkOrderNames.lastIndexOf(',');
		if(index != -1) this.WorkOrderNames = this.WorkOrderNames.substring(0,index -1);
    }

    public String getCustomDescription() {
		return (String.isNotBlank(objNAM.Description__c) ? objNAM.Description__c.replaceAll('img', 'img style="width:730px;"') : null);
	}
	
	public String getCustomActionTaken() {
		return (String.isNotBlank(objNAM.ActionTaken__c) ? objNAM.ActionTaken__c.replaceAll('img', 'img style="width:730px;"') : null);
	}
	
	public String getCustomRootCause() {
		return (String.isNotBlank(objNAM.RootCause__c) ? objNAM.RootCause__c.replaceAll('img', 'img style="width:730px;"') : null);
    }
}