force-app/main/default/objects/NAM__c/NAM__c.object-meta.xml
<CustomObject>
    <label>NAM</label>
    <nameField>
        <label>NAM Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NAMs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkOrderLineItem/fields/BRL__c.field-meta.xml
<CustomField>
    <fullName>BRL__c</fullName>
    <inlineHelpText>R$</inlineHelpText>
    <label>Price BRL</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/MS__c.field-meta.xml
<CustomField>
    <fullName>MS__c</fullName>
    <label>M/S</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Material</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>F</fullName>
                <isActive>false</isActive>
                <label>F</label>
            </value>
            <value>
                <fullName>I</fullName>
                <isActive>false</isActive>
                <label>I</label>
            </value>
            <value>
                <fullName>M/S</fullName>
                <isActive>false</isActive>
                <label>M/S</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/NAM__c.field-meta.xml
<CustomField>
    <fullName>NAM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NAM</label>
    <referenceTo>NAM__c</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>WorkOrderLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <inlineHelpText>USD</inlineHelpText>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Responsible__c.field-meta.xml
<CustomField>
    <fullName>Responsible__c</fullName>
    <label>Responsible</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MII</fullName>
            </value>
            <value>
                <fullName>MdB</fullName>
            </value>
            <value>
                <fullName>MINC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/ResponsibleCountry__c.field-meta.xml
<CustomField>
    <fullName>ResponsibleCountry__c</fullName>
    <label>Responsible</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Outside of Brazil</fullName>
            </value>
            <value>
                <fullName>MODEC, Inc</fullName>
                <isActive>false</isActive>
                <label>MODEC, Inc</label>
            </value>
            <value>
                <fullName>MdB</fullName>
                <isActive>false</isActive>
                <label>MdB</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/ResponsibleWO__c.field-meta.xml
<CustomField>
    <fullName>ResponsibleWO__c</fullName>
    <formula>WorkOrder.Contractor__r.ShortName__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Responsible WO</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WorkOrderLineItemDAO.cls
public class WorkOrderLineItemDAO {
	
	public static List<WorkOrderLineItem> getWorkOrderLineItemByNAM(Id namId) {
		return [
			SELECT 
				Id,
				LineItemNumber,
				Description,
				Status,
				MS__c,
				Price__c,
				BRL__c,
				NAM__c,
				Responsible__c,
				ResponsibleWO__c,
				ResponsibleCountry__c,
				Product__c
			FROM
				WorkOrderLineItem
			WHERE
				NAM__c = :namId
		];
	}

	public static List<WorkOrderLineItem> getByWorkOrderId(Id workOrderId) {
		return [
			SELECT 
				Id,
				LineItemNumber,
				Description,
				Status,
				MS__c,
				Price__c,
				BRL__c,
				NAM__c,
				Responsible__c,
				ResponsibleWO__c,
				ResponsibleCountry__c,
				Product__c
			FROM
				WorkOrderLineItem
			WHERE
				WorkOrderId = : workOrderId
		];
	}
}