force-app/main/default/objects/NAM__c/NAM__c.object-meta.xml
<CustomObject>
    <label>NAM</label>
    <nameField>
        <label>NAM Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NAMs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NAM__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/Vessel__c.field-meta.xml
<CustomField>
    <fullName>Vessel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vessel</label>
    <referenceTo>Vessel__c</referenceTo>
    <relationshipLabel>NAMs</relationshipLabel>
    <relationshipName>NAMs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vessel__c/Vessel__c.object-meta.xml
<CustomObject>
    <label>Vessel</label>
    <nameField>
        <label>Vessel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vessels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VesselContact__c/VesselContact__c.object-meta.xml
<CustomObject>
    <label>Vessel Contact</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Vessel Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vessel Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VesselContact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Vessel Contacts</relationshipLabel>
    <relationshipName>Vessel_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VesselContact__c/fields/PDFAlert__c.field-meta.xml
<CustomField>
    <fullName>PDFAlert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PDF Alert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VesselContact__c/fields/Vessel__c.field-meta.xml
<CustomField>
    <fullName>Vessel__c</fullName>
    <label>Vessel</label>
    <referenceTo>Vessel__c</referenceTo>
    <relationshipLabel>Vessel Contacts</relationshipLabel>
    <relationshipName>VesselContacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/NAM__c.field-meta.xml
<CustomField>
    <fullName>NAM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NAM</label>
    <referenceTo>NAM__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>WorkOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>WorkOrder__c</fullName>
    <externalId>true</externalId>
    <label>Work Order</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/NAM__c.field-meta.xml
<CustomField>
    <fullName>NAM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NAM</label>
    <referenceTo>NAM__c</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>WorkOrderLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>WorkOrder__c</fullName>
    <formula>HYPERLINK(WorkOrder.Id, WorkOrder.WorkOrder__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>WorkOrder</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EmailUtilTest.cls
@isTest
public with sharing class EmailUtilTest {
    @isTest
    public static void sendNAMEmailsPdfTest(){
        Test.startTest();
        NAMFactory.createExchange();
        Vessel__c vessel = VesselFactory.createVessel();
        NAM__c nam = NAMFactory.createNAM(vessel, 'NAM-MV24-20-001');
        Contact c = new Contact(LastName = 'Test', Email = 'test@salesforce.com');
        VesselContact__c vesselContact = new VesselContact__c(Vessel__c = vessel.Id, Contact__c = c.Id, PDFAlert__c = true);
        WorkOrder wo = WorkOrderFactory.createWO(nam, 'MdB');
        WorkOrderLineItem woItem = WorkOrderFactory.createWOLineItem(wo, 1000);

        Map<String, List<String>> mapVesselVsContacts = new Map<String, List<String>>();
        Map<String, List<String>> mapIdVsContacts = new Map<String, List<String>>();
        Map<String, String> mapNAMvsName = new Map<String, String>();
        Map<String, String> mapIdVsName = new Map<String, String>();
        Map<String, String> mapIdVsWOName = new Map<String, String>();

        mapVesselVsContacts.put(nam.Vessel__c, new List<String>());
        mapIdVsContacts.put(nam.Id, mapVesselVsContacts.get(nam.Vessel__c));
        mapNAMvsName.put(nam.Id, nam.Name + ' - ' + nam.Subject__c);
        mapIdVsName.put(nam.Id, nam.Name + ' - ' + nam.Subject__c);
        mapIdVsWOName.put(wo.Id, wo.WorkOrder__c);

        GeneratePdfController.savePdf(nam.Id, 'NAM__c');
        GeneratePdfController.savePdfFuture(JSON.serialize(mapIdVsName), 'NAM__c');
        
        EmailUtil.sendNAMEmailsPdf(JSON.serialize(mapIdVsContacts), JSON.serialize(mapNAMvsName), nam.Name);
        Test.stopTest();
    }
}