force-app/main/default/objects/NAM__c/NAM__c.object-meta.xml
<CustomObject>
    <label>NAM</label>
    <nameField>
        <label>NAM Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NAMs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NAM__c/fields/BRLAmount__c.field-meta.xml
<CustomField>
    <fullName>BRLAmount__c</fullName>
    <label>BRL Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/MaterialMdBAmount__c.field-meta.xml
<CustomField>
    <fullName>MaterialMdBAmount__c</fullName>
    <label>Material MdB Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/MaterialMIIAmount__c.field-meta.xml
<CustomField>
    <fullName>MaterialMIIAmount__c</fullName>
    <label>Material MII Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/MaterialMINCAmount__c.field-meta.xml
<CustomField>
    <fullName>MaterialMINCAmount__c</fullName>
    <label>Material MINC Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/MdBAmount__c.field-meta.xml
<CustomField>
    <fullName>MdBAmount__c</fullName>
    <inlineHelpText>Imported from 1nd WO</inlineHelpText>
    <label>MdB Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/MIIAmount__c.field-meta.xml
<CustomField>
    <fullName>MIIAmount__c</fullName>
    <inlineHelpText>Imported from 2nd WO</inlineHelpText>
    <label>MII Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/MINCAmount__c.field-meta.xml
<CustomField>
    <fullName>MINCAmount__c</fullName>
    <inlineHelpText>Imported from 3nd WO</inlineHelpText>
    <label>MINC Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/NAMRevision__c.field-meta.xml
<CustomField>
    <fullName>NAMRevision__c</fullName>
    <formula>IF(TEXT(ClosedOutStatus__c) &lt;&gt; &apos;&apos;, TEXT(Revision__c) + &apos;-&apos; +  Text(RevisionCO__c), text(Revision__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>NAM Revision</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/ServiceMdBAmount__c.field-meta.xml
<CustomField>
    <fullName>ServiceMdBAmount__c</fullName>
    <label>Service MdB Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/ServiceMIIAmount__c.field-meta.xml
<CustomField>
    <fullName>ServiceMIIAmount__c</fullName>
    <label>Service MII Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/ServiceMINCAmount__c.field-meta.xml
<CustomField>
    <fullName>ServiceMINCAmount__c</fullName>
    <label>Service MINC Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/Vessel__c.field-meta.xml
<CustomField>
    <fullName>Vessel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vessel</label>
    <referenceTo>Vessel__c</referenceTo>
    <relationshipLabel>NAMs</relationshipLabel>
    <relationshipName>NAMs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NAM__c/fields/WorkOrderPrimaryNumber__c.field-meta.xml
<CustomField>
    <fullName>WorkOrderPrimaryNumber__c</fullName>
    <label>Work Order Primary Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vessel__c/Vessel__c.object-meta.xml
<CustomObject>
    <label>Vessel</label>
    <nameField>
        <label>Vessel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vessels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vessel__c/fields/WOAttention__c.field-meta.xml
<CustomField>
    <fullName>WOAttention__c</fullName>
    <label>WO Attention</label>
    <length>31072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Vessel__c/fields/WOAttentionMINC__c.field-meta.xml
<CustomField>
    <fullName>WOAttentionMINC__c</fullName>
    <label>WO Attention MINC</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/ByPassRenameWO__c.field-meta.xml
<CustomField>
    <fullName>ByPassRenameWO__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ByPass Rename WO</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/ClonedWO__c.field-meta.xml
<CustomField>
    <fullName>ClonedWO__c</fullName>
    <label>Cloned WO</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Material__c.field-meta.xml
<CustomField>
    <fullName>Material__c</fullName>
    <label>Material</label>
    <summarizedField>WorkOrderLineItem.Price__c</summarizedField>
    <summaryFilterItems>
        <field>WorkOrderLineItem.MS__c</field>
        <operation>equals</operation>
        <value>Material</value>
    </summaryFilterItems>
    <summaryForeignKey>WorkOrderLineItem.WorkOrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/NAM__c.field-meta.xml
<CustomField>
    <fullName>NAM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NAM</label>
    <referenceTo>NAM__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>WorkOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/NAMRevision__c.field-meta.xml
<CustomField>
    <fullName>NAMRevision__c</fullName>
    <formula>TEXT(NAM__r.Revision__c)</formula>
    <label>NAM Revision</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Responsible__c.field-meta.xml
<CustomField>
    <fullName>Responsible__c</fullName>
    <formula>Contractor__r.ShortName__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Responsible</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/ScopeWork__c.field-meta.xml
<CustomField>
    <fullName>ScopeWork__c</fullName>
    <label>Scope of Work</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <summarizedField>WorkOrderLineItem.Price__c</summarizedField>
    <summaryFilterItems>
        <field>WorkOrderLineItem.MS__c</field>
        <operation>equals</operation>
        <value>Service</value>
    </summaryFilterItems>
    <summaryForeignKey>WorkOrderLineItem.WorkOrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <formula>PortionAmount__c +  MarkUpAmount__c +  TaxISS2__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/TotalBRL__c.field-meta.xml
<CustomField>
    <fullName>TotalBRL__c</fullName>
    <formula>PortionBRL__c +  TaxISS2BRL__c +  MarkupAmountBRL__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total BRL</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/VesselClientId__c.field-meta.xml
<CustomField>
    <fullName>VesselClientId__c</fullName>
    <formula>NAM__r.Vessel__r.SPC__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vessel Client Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/WOAttention__c.field-meta.xml
<CustomField>
    <fullName>WOAttention__c</fullName>
    <label>WO Attention</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>WorkOrder__c</fullName>
    <externalId>true</externalId>
    <label>Work Order</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/WorkOrderPrimaryNumber__c.field-meta.xml
<CustomField>
    <fullName>WorkOrderPrimaryNumber__c</fullName>
    <label>WorkOrder Primary Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/NAM__c.field-meta.xml
<CustomField>
    <fullName>NAM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NAM</label>
    <referenceTo>NAM__c</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>WorkOrderLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Responsible__c.field-meta.xml
<CustomField>
    <fullName>Responsible__c</fullName>
    <label>Responsible</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MII</fullName>
            </value>
            <value>
                <fullName>MdB</fullName>
            </value>
            <value>
                <fullName>MINC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/ResponsibleCountry__c.field-meta.xml
<CustomField>
    <fullName>ResponsibleCountry__c</fullName>
    <label>Responsible</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Outside of Brazil</fullName>
            </value>
            <value>
                <fullName>MODEC, Inc</fullName>
                <isActive>false</isActive>
                <label>MODEC, Inc</label>
            </value>
            <value>
                <fullName>MdB</fullName>
                <isActive>false</isActive>
                <label>MdB</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>WorkOrder__c</fullName>
    <formula>HYPERLINK(WorkOrder.Id, WorkOrder.WorkOrder__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>WorkOrder</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WorkOrderBO.cls
public class WorkOrderBO {
    private static final WorkOrderBO instance = new WorkOrderBO();

	public static WorkOrderBO getInstance() {
		return instance;
	}
    public void cloneWO(List<WorkOrder> lstWO){
        Map<Id, Id> mapCloneWO = new Map<Id, Id>();
        for(WorkOrder woItem : lstWO){
            if(woItem.ClonedWO__c != null) mapCloneWO.put(woItem.ClonedWO__c, woItem.Id);
        }
        if(mapCloneWO.size() > 0){
            List<WorkOrder> lstCloned = WorkOrderDAO.getByWOItem(mapCloneWO.keySet());
            List<WorkOrderLineItem> lstWOLine = new  List<WorkOrderLineItem>();
            WorkOrderLineItem woLineItem;
            for(WorkOrder wo : lstCloned){
                for(WorkOrderLineItem woLine : wo.WorkOrderLineItems){
                    woLineItem = woLine.clone(false, false, false, false);
                    woLineItem.WorkOrderId = mapCloneWO.get(wo.Id);
                    woLineItem.ResponsibleCountry__c = woLine.ResponsibleCountry__c;
                    lstWOLine.add(woLineItem);
                }
            }
            insert lstWOLine;
        }
    }
    public void summarizingNAMValues(List<WorkOrder> lstWO){
        Set<String> setIds = new Set<String>();
        for(WorkOrder woItem : lstWO){
            setIds.add(woItem.NAM__c);
        }

        List<NAM__c> lstNAM = NamDAO.getById(setIds);
        Map<String, Decimal> mapNamWO = new Map<String, Decimal>();

        for(NAM__c namItem : lstNAM){

            namItem.MdbAmount__c = 0;
            namItem.MIIAmount__c = 0;
            namItem.MINCAmount__c = 0;
            namItem.ServiceMdbAmount__c = 0;
            namItem.MaterialMdbAmount__c = 0;
            namItem.ServiceMIIAmount__c = 0;
            namItem.MaterialMIIAmount__c = 0;                    
            namItem.ServiceMINCAmount__c = 0;
            namItem.MaterialMINCAmount__c = 0;
            
            namItem.BRLAmount__c = 0;              

            for(WorkOrder woItem : namItem.WorkOrders__r){
                if(woItem.Responsible__c == 'MdB'){ 
                    namItem.MdbAmount__c += woItem.TotalAmount__c;
                    namItem.ServiceMdbAmount__c += woItem.Service__c;
                    namItem.MaterialMdbAmount__c += woItem.Material__c;
                    namItem.BRLAmount__c += woItem.TotalBRL__c;
                }
                else if(woItem.Responsible__c == 'MII'){ 
                    namItem.MIIAmount__c += woItem.TotalAmount__c;
                    namItem.ServiceMIIAmount__c += woItem.Service__c;
                    namItem.MaterialMIIAmount__c += woItem.Material__c;                    
                }
                else if(woItem.Responsible__c == 'MINC'){ 
                    namItem.MINCAmount__c += woItem.TotalAmount__c;
                    namItem.ServiceMINCAmount__c += woItem.Service__c;
                    namItem.MaterialMINCAmount__c += woItem.Material__c;                    
                }                          
            }
        }
        update lstNAM;
    }

    public void fillWOPrimaryNumberInNAM(List<WorkOrder> lstWO){
        Set<String> setIds = new Set<String>();
        for(WorkOrder wo : lstWO){
            setIds.add(wo.NAM__c);
        }

        List<NAM__c> lstNAM = NamDAO.getById(setIds);
        if (!lstNAM.isEmpty()) {
            List<NAM__c> lstNAMUpdate = new List<NAM__c>();
            for(WorkOrder wo : lstWO){
                for(NAM__c nam : lstNAM){
                    if(!String.isBlank(wo.WorkOrderPrimaryNumber__c) && String.isBlank(nam.WorkOrderPrimaryNumber__c)){
                        nam.WorkOrderPrimaryNumber__c = wo.WorkOrderPrimaryNumber__c;
                        lstNAMUpdate.add(nam);
                    }
                }
            }
            if(!lstNAMUpdate.isEmpty())
                update lstNAMUpdate;
        }
    }

    public void beforeInsertWO(List<WorkOrder> lstWO){
        String modecInc = System.Label.MINC;
        String scopeOfWorkMINC = '<p>The scope defined here is covering the scope of overall NAM.</p> <p>The actual scope of the Contractor is demarcated as &quot;Brazil&quot; under &quot;Responsible&quot; in the table under section PRICE/RATES AND TERMS OF PAYMENT.</p> <br/>'; 
        Set<String> setIDs = new Set<String>();

        for(WorkOrder item : lstWO){
            item.CurrencyIsoCode = 'USD';
            setIDs.add(item.NAM__c);    
        }

        Map<Id, NAM__c> mapNAM = new Map<Id, NAM__c>(NamDAO.getById(setIDs));
        for(WorkOrder woItem : lstWO){
             
            if(mapNAM.containsKey(woItem.NAM__c)){
                NAM__c nam = mapNAM.get(woItem.NAM__c);
                woItem.WOAttention__c = woItem.AccountId == modecInc ? nam.Vessel__r.WOAttention__c : nam.Vessel__r.WOAttentionMINC__c;
                if(woItem.AccountId != modecInc && woItem.VesselClientId__c != null) woItem.AccountId = woItem.VesselClientId__c;
                woItem.ScopeWork__c = woItem.AccountId != modecInc ? woItem.ScopeWork__c : scopeOfWorkMINC + woItem.ScopeWork__c;
                
                if(!woItem.ByPassRenameWO__c){
                    Integer index = nam.Name.indexOf('_r');
                    String nameWO = nam.Name.replace('NAM', 'WO');
                    if(index != -1) nameWO = nameWO.subString(0, index -1);
                    woItem.WorkOrderPrimaryNumber__c = nameWO;
                    woItem.WorkOrder__c = nameWO + '-' + String.valueOf(nam.WorkOrders__r.size() + 1)+'_r'+woItem.NAMRevision__c; //WO-MV27-00-006-2_r0
                }
            }
        }
    }
    public void generateNewPdf(List<WorkOrder> lstWO, Map<Id, WorkOrder> mapOld){
        Map<String, String> mapIdVsName = new Map<String, String>();
        for(WorkOrder wo : lstWO){
            if(wo.WorkOrder__c != mapOld.get(wo.Id).WorkOrder__c){ 
                mapIdVsName.put(wo.Id, mapOld.get(wo.Id).WorkOrder__c);
            }
        }
        GeneratePdfController.savePdfFuture(JSON.serialize(mapIdVsName), 'WorkOrder'); 
    }
}