force-app/main/default/objects/NAM__c/NAM__c.object-meta.xml
<CustomObject>
    <label>NAM</label>
    <nameField>
        <label>NAM Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NAMs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NAM__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/NAM__c.field-meta.xml
<CustomField>
    <fullName>NAM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NAM</label>
    <referenceTo>NAM__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>WorkOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/WorkOrder__c.field-meta.xml
<CustomField>
    <fullName>WorkOrder__c</fullName>
    <externalId>true</externalId>
    <label>Work Order</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GeneratePdfController.cls
public class GeneratePdfController {

    @AuraEnabled
	public static void savePdf(String recordId, String sObjectName) {
		System.debug('### sObjectName => ' + sObjectName);
		switch on sObjectName {
			when 'NAM__c' {
				NAM__c nam = NamDAO.getById(recordId);
				Util.generatePdf(recordId, nam.Name + ' - ' + nam.Subject__c, 'NAMReportPdf');
			}
			when 'WorkOrder' {
				WorkOrder wo = WorkOrderDAO.getById(recordId);
				Util.generatePdf(recordId, wo.WorkOrder__c, 'WorkOrderPdf');
			}
		}
			
	}
	@future(callout=true)
	public static void savePdfFuture(String mapSerialized, String sObjectName) {
		Map<String, String> mapIdVsName = (Map<String, String>) JSON.deserialize(mapSerialized, Map<String, String>.class);
		System.debug('### sObjectName => ' + sObjectName);
		switch on sObjectName {
			when 'NAM__c' {
				// NAM__c nam = NamDAO.getById(mapIdName.keySet());
				Util.generatePdf(mapIdVsName, 'NAMReportPdf');
			}
			when 'WorkOrder' {
				// WorkOrder wo = WorkOrderDAO.getByWOItem(setIds);
				Util.generatePdf(mapIdVsName, 'WorkOrderPdf');
			}
		}
			
	}
}