force-app/main/default/objects/ContractDailyRateHistory__c/ContractDailyRateHistory__c.object-meta.xml
<CustomObject>
    <label>Contract Daily Rate History</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>History Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Daily Rate Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ContractDailyRateHistory__c/fields/DailyRate__c.field-meta.xml
<CustomField>
    <fullName>DailyRate__c</fullName>
    <label>Daily Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ContractDailyRateHistory__c/fields/VesselContract__c.field-meta.xml
<CustomField>
    <fullName>VesselContract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vessel Contract</label>
    <referenceTo>VesselContract__c</referenceTo>
    <relationshipLabel>Contract Daily Rate Histories</relationshipLabel>
    <relationshipName>Contract_Daily_Rate_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VesselContract__c/VesselContract__c.object-meta.xml
<CustomObject>
    <label>Vessel Contract</label>
    <nameField>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vessel Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VesselContract__c/fields/ActualDailyRateBRL__c.field-meta.xml
<CustomField>
    <fullName>ActualDailyRateBRL__c</fullName>
    <label>Actual Daily Rate (BRL)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VesselContract__c/fields/ActualDailyRateUSD__c.field-meta.xml
<CustomField>
    <fullName>ActualDailyRateUSD__c</fullName>
    <label>Actual Daily Rate (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VesselContract__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Charter</fullName>
            </value>
            <value>
                <fullName>Cost Plus</fullName>
            </value>
            <value>
                <fullName>O&amp;M Support</fullName>
            </value>
            <value>
                <fullName>Pre-Ops</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VesselContractBO.cls
public with sharing class VesselContractBO {
    
    private static final VesselContractBO instance = new VesselContractBO();

	public static VesselContractBO getInstance() {
		return instance;
    }

    public void populateDailyRateHistory(List<VesselContract__c> triggerNew, Map<Id, VesselContract__c> oldMap){

        List<ContractDailyRateHistory__c> historyToInsert = new List<ContractDailyRateHistory__c>();      

        for(VesselContract__c lst : triggerNew){

            if(oldMap == null){

                if(lst.ActualDailyRateUSD__c != null && lst.ActualDailyRateUSD__c > 0 && lst.Type__c == 'Charter'){
                    ContractDailyRateHistory__c dailyRateHistory = new ContractDailyRateHistory__c();
                    dailyRateHistory.VesselContract__c = lst.Id;
                    dailyRateHistory.DailyRate__c =  lst.ActualDailyRateUSD__c;
                    dailyRateHistory.StartDate__c = System.today();
                    
                    historyToInsert.add(dailyRateHistory);
                }
    
                if(lst.ActualDailyRateBRL__c != null && lst.ActualDailyRateBRL__c > 0 && lst.Type__c == 'Services'){
                    ContractDailyRateHistory__c dailyRateHistoryBRL = new ContractDailyRateHistory__c();
                    dailyRateHistoryBRL.VesselContract__c = lst.Id;
                    dailyRateHistoryBRL.DailyRate__c = lst.ActualDailyRateBRL__c;
                    dailyRateHistoryBRL.StartDate__c = System.today();
                    
                    historyToInsert.add(dailyRateHistoryBRL);
                }
            } else{

                Decimal rateUSDOldMap = oldMap.get(lst.Id).ActualDailyRateUSD__c;
                Decimal rateBRLOldMap = oldMap.get(lst.Id).ActualDailyRateBRL__c;

                if(lst.ActualDailyRateUSD__c != rateUSDOldMap && lst.ActualDailyRateUSD__c != null && lst.ActualDailyRateUSD__c > 0 && lst.Type__c == 'Charter'){
                    ContractDailyRateHistory__c dailyRateHistory = new ContractDailyRateHistory__c();
                    dailyRateHistory.VesselContract__c = lst.Id;
                    dailyRateHistory.DailyRate__c =  lst.ActualDailyRateUSD__c;
                    dailyRateHistory.StartDate__c = System.today();
                    
                    historyToInsert.add(dailyRateHistory);
                }

                if(lst.ActualDailyRateBRL__c != rateBRLOldMap && lst.ActualDailyRateBRL__c != null && lst.ActualDailyRateBRL__c > 0 && lst.Type__c == 'Services'){
                    ContractDailyRateHistory__c dailyRateHistoryBRL = new ContractDailyRateHistory__c();
                    dailyRateHistoryBRL.VesselContract__c = lst.Id;
                    dailyRateHistoryBRL.DailyRate__c = lst.ActualDailyRateBRL__c;
                    dailyRateHistoryBRL.StartDate__c = System.today();
                    
                    historyToInsert.add(dailyRateHistoryBRL);
                }
            }
        }

        insert historyToInsert;
    }
}