force-app/main/default/objects/ContractDailyRateHistory__c/ContractDailyRateHistory__c.object-meta.xml
<CustomObject>
    <label>Contract Daily Rate History</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>History Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Daily Rate Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ContractDailyRateHistory__c/fields/DailyRate__c.field-meta.xml
<CustomField>
    <fullName>DailyRate__c</fullName>
    <label>Daily Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ContractDailyRateHistory__c/fields/EscalationIndex__c.field-meta.xml
<CustomField>
    <fullName>EscalationIndex__c</fullName>
    <label>Escalation Index</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ContractDailyRateHistory__c/fields/Index1__c.field-meta.xml
<CustomField>
    <fullName>Index1__c</fullName>
    <label>Index¹</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ContractDailyRateHistory__c/fields/Index2__c.field-meta.xml
<CustomField>
    <fullName>Index2__c</fullName>
    <label>Index²</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ContractDailyRateHistory__c/fields/Index3__c.field-meta.xml
<CustomField>
    <fullName>Index3__c</fullName>
    <label>Index³</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ContractDailyRateHistory__c/fields/VesselContract__c.field-meta.xml
<CustomField>
    <fullName>VesselContract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vessel Contract</label>
    <referenceTo>VesselContract__c</referenceTo>
    <relationshipLabel>Contract Daily Rate Histories</relationshipLabel>
    <relationshipName>Contract_Daily_Rate_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vessel__c/Vessel__c.object-meta.xml
<CustomObject>
    <label>Vessel</label>
    <nameField>
        <label>Vessel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vessels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vessel__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New build</fullName>
            </value>
            <value>
                <fullName>Conversion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VesselContract__c/VesselContract__c.object-meta.xml
<CustomObject>
    <label>Vessel Contract</label>
    <nameField>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vessel Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VesselContract__c/fields/BOMEndDate__c.field-meta.xml
<CustomField>
    <fullName>BOMEndDate__c</fullName>
    <formula>ADDMONTHS(BOMStartDate__c ,1) - 1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BOM End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VesselContract__c/fields/BOMStartDate__c.field-meta.xml
<CustomField>
    <fullName>BOMStartDate__c</fullName>
    <label>BOM Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VesselContract__c/fields/Index1__c.field-meta.xml
<CustomField>
    <fullName>Index1__c</fullName>
    <label>Index¹</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VesselContract__c/fields/Index2__c.field-meta.xml
<CustomField>
    <fullName>Index2__c</fullName>
    <label>Index²</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VesselContract__c/fields/Index3__c.field-meta.xml
<CustomField>
    <fullName>Index3__c</fullName>
    <label>Index³</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VesselContract__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Charter</fullName>
            </value>
            <value>
                <fullName>Cost Plus</fullName>
            </value>
            <value>
                <fullName>O&amp;M Support</fullName>
            </value>
            <value>
                <fullName>Pre-Ops</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VesselContract__c/fields/Vessel__c.field-meta.xml
<CustomField>
    <fullName>Vessel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vessel</label>
    <referenceTo>Vessel__c</referenceTo>
    <relationshipLabel>Vessel Contracts</relationshipLabel>
    <relationshipName>VesselContracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ContractDailyRateHistoryDAO.cls
public with sharing class ContractDailyRateHistoryDAO {
    
    public static List<ContractDailyRateHistory__c> getContractDailyRateHistoryByContractAndBOMDate(Id idContract, Date endDate) {
        return [SELECT 
                    Id,
                    Comments__c,
                    DailyRate__c,
                    EndDate__c,
                    EscalationIndex__c,
                    Name,
                    Index2__c,
                    Index3__c,
                    Index1__c,
                    StartDate__c,
                    VesselContract__c
                    FROM
                    ContractDailyRateHistory__c
                    WHERE
                    VesselContract__c =: idContract
                    AND
                    StartDate__c <=: endDate
                    AND 
                    EndDate__c >=: endDate];
    }

    public static List<ContractDailyRateHistory__c> getInfosByContractDailyRateHistory(Set<Id> setIds){
        return [SELECT 
                    Id,
                    Comments__c,
                    DailyRate__c,
                    EndDate__c,
                    EscalationIndex__c,
                    Name,
                    Index2__c,
                    Index3__c,
                    Index1__c,
                    StartDate__c,
                    VesselContract__c,
                    VesselContract__r.Name,
                    VesselContract__r.Type__c,
                    VesselContract__r.BOMStartDate__c,
                    VesselContract__r.BOMEndDate__c,
                    VesselContract__r.VesselShortName__c,
                    VesselContract__r.Vessel__c
                    FROM
                    ContractDailyRateHistory__c
                    WHERE
                    Id IN: setIds];
    }
}