force-app/main/default/objects/TOBJ_Participants__c/TOBJ_Participants__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>PN-{YYYY}{MM}-{0000}</displayFormat>
        <label>Nome do Participante</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TOBJ_Participants__c/fields/TCF_Supplier__c.field-meta.xml
<CustomField>
    <fullName>TCF_Supplier__c</fullName>
    <label>Fornecedor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>TRN_ParticipantsAccount</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TOBJ_Participants__c/fields/Warning__c.field-meta.xml
<CustomField>
    <fullName>Warning__c</fullName>
    <label>Warning</label>
    <referenceTo>TOBJ_Warning__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>TRN_ParticipantsWarning</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TOBJ_Warning__c/TOBJ_Warning__c.object-meta.xml
<CustomObject>
    <label>Warning</label>
    <nameField>
        <displayFormat>WARN-{00000000}</displayFormat>
        <label>Nome do Aviso</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Warning</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/TOBJ_Warning__c/fields/PublicationDate__c.field-meta.xml
<CustomField>
    <fullName>PublicationDate__c</fullName>
    <label>Data de publicação</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TOBJ_Warning__c/fields/PublicationDateView__c.field-meta.xml
<CustomField>
    <fullName>PublicationDateView__c</fullName>
    <formula>TEXT(MONTH(PublicationDate__c))+&apos;/&apos;+TEXT(DAY(PublicationDate__c))+&apos;/&apos;+TEXT(YEAR(PublicationDate__c))</formula>
    <label>Visualização da data de publicação</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TOBJ_Warning__c/fields/TCF_DueDate__c.field-meta.xml
<CustomField>
    <fullName>TCF_DueDate__c</fullName>
    <label>Data de vencimento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TOBJ_Warning__c/fields/TCF_Notice__c.field-meta.xml
<CustomField>
    <fullName>TCF_Notice__c</fullName>
    <label>Notícia</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/TOBJ_Warning__c/fields/TCF_Subject__c.field-meta.xml
<CustomField>
    <fullName>TCF_Subject__c</fullName>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WarningSettings__c/WarningSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Warning Settings</label>
</CustomObject>

force-app/main/default/objects/WarningSettings__c/fields/CardsByScreenLarge__c.field-meta.xml
<CustomField>
    <fullName>CardsByScreenLarge__c</fullName>
    <description>Warning News Tab</description>
    <inlineHelpText>How many cards will be displayed at once on a large screen? Ex: Desktops. The recommendation is 9.</inlineHelpText>
    <label>Cards By Screen (Large)</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WarningSettings__c/fields/CardsByScreenMedium__c.field-meta.xml
<CustomField>
    <fullName>CardsByScreenMedium__c</fullName>
    <description>Warning News Tab</description>
    <inlineHelpText>How many cards will be displayed at once on a medium screen? Ex: Tablets. The recommendation is 6.</inlineHelpText>
    <label>Cards By Screen (Medium)</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WarningSettings__c/fields/CardsByScreenSmall__c.field-meta.xml
<CustomField>
    <fullName>CardsByScreenSmall__c</fullName>
    <description>Warning News Tab</description>
    <inlineHelpText>How many cards will be displayed at once on a small screen? Ex: Smartphones. The recommendation is 3.</inlineHelpText>
    <label>Cards By Screen (Small)</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WarningSettings__c/fields/WarningsByRowLarge__c.field-meta.xml
<CustomField>
    <fullName>WarningsByRowLarge__c</fullName>
    <description>Warning News Tab</description>
    <inlineHelpText>How many cards will be displayed for each row on a large screen? Ex: Desktops. The recommendation is 3.</inlineHelpText>
    <label>Warnings By Row (Large)</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WarningSettings__c/fields/WarningsByRowMedium__c.field-meta.xml
<CustomField>
    <fullName>WarningsByRowMedium__c</fullName>
    <description>Warning News Tab</description>
    <inlineHelpText>How many cards will be displayed for each row on a medium screen? Ex: Tablets. The recommendation is 2.</inlineHelpText>
    <label>Warnings By Row (Medium)</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WarningSettings__c/fields/WarningsByRowSmall__c.field-meta.xml
<CustomField>
    <fullName>WarningsByRowSmall__c</fullName>
    <description>Warning News Tab</description>
    <inlineHelpText>How many cards will be displayed for each row on a medium screen? Ex: Smartphones. The recommendation is 1.</inlineHelpText>
    <label>Warnings By Row (Small)</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WarningSettings__c/fields/WarningsLoadMoreLarge__c.field-meta.xml
<CustomField>
    <fullName>WarningsLoadMoreLarge__c</fullName>
    <description>Warning News Tab</description>
    <inlineHelpText>How many cards will be loaded when the user clicks on the button &quot;Load More Warnings&quot; on a large screen? Ex: Desktops. The recommendation is 9.</inlineHelpText>
    <label>Warnings to Load More (Large)</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WarningSettings__c/fields/WarningsLoadMoreMedium__c.field-meta.xml
<CustomField>
    <fullName>WarningsLoadMoreMedium__c</fullName>
    <description>Warning News Tab</description>
    <inlineHelpText>How many cards will be loaded when the user clicks on the button &quot;Load More Warnings&quot; on a medium screen? Ex: Tablets. The recommendation is 6.</inlineHelpText>
    <label>Warnings to Load More (Medium)</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WarningSettings__c/fields/WarningsLoadMoreSmall__c.field-meta.xml
<CustomField>
    <fullName>WarningsLoadMoreSmall__c</fullName>
    <description>Warning News Tab</description>
    <inlineHelpText>How many cards will be loaded when the user clicks on the button &quot;Load More Warnings&quot; on a small screen? Ex: Smartphones. The recommendation is 3.</inlineHelpText>
    <label>Warnings to Load More (Small)</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/T_WarningViewScreenController.cls
public without sharing class T_WarningViewScreenController {

    private static Integer limiteQuery = 100;
    
    @AuraEnabled
    public static WarningSettings__c getWarningsSettings(){
        WarningSettings__c warningSetting;
        
        IF(!Test.isRunningTest()){
            warningSetting = WarningSettings__c.getInstance();
        } else {
            warningSetting = new WarningSettings__c();
            warningSetting.CardsByScreenLarge__c = 9;
            warningSetting.CardsByScreenMedium__c = 6;
            warningSetting.CardsByScreenSmall__c = 3;
            warningSetting.WarningsByRowLarge__c = 3;
            warningSetting.WarningsByRowMedium__c = 2;
            warningSetting.WarningsByRowSmall__c = 1;
            warningSetting.WarningsLoadMoreLarge__c = 9;
            warningSetting.WarningsLoadMoreMedium__c = 6;
            warningSetting.WarningsLoadMoreSmall__c = 3;
        }
        return warningSetting;
    }
    
    @AuraEnabled
    public static List<SObject> getWarning(String DateToOrdenate, String Order){
        Date hoje = Date.today();
        List<TOBJ_Warning__c> retorno = new List<TOBJ_Warning__c>();
        User usuario = null;
        try{
            usuario = [select id, Contact.AccountId 
                       From User 
                       where id =: UserInfo.getUserId() and Contact.AccountId != null 
                       limit 1];
        } catch(Exception e){
            usuario = null;
        }
        String soql = 'select ';
        
        if(usuario != null){
            soql += 'Warning__c, Warning__r.TCF_Subject__c, Warning__r.TCF_Notice__c, Warning__r.PublicationDateView__c ';
            soql += 'from TOBJ_Participants__c ';
            soql += 'where TCF_Supplier__c = \''+usuario.Contact.AccountId+'\' and Warning__r.PublicationDate__c <=: hoje ';
            soql += 'and Warning__r.TCF_DueDate__c >=: hoje ';
            
            soql += 'order by Warning__r.'+DateToOrdenate+' '+Order+' ';
            soql += 'limit :limiteQuery ';
            
            List<TOBJ_Participants__c> participantes = Database.query(soql);
            
            for(TOBJ_Participants__c participante: participantes){
                TOBJ_Warning__c warning = (TOBJ_Warning__c) participante.getSObject('Warning__r');
                retorno.add(warning);
            }
        } else {
            soql += 'id, TCF_Subject__c, TCF_Notice__c, PublicationDateView__c, PublicationDate__c ';
            soql += 'from TOBJ_Warning__c ';
            soql += 'where PublicationDate__c <=: hoje and TCF_DueDate__c >=: hoje ';
            soql += 'order by '+DateToOrdenate+' '+Order+' ';
            soql += 'limit :limiteQuery ';
            retorno = Database.query(soql);
        }
        
        return retorno;
    }
}