force-app/main/default/objects/ConfiguracoesGerais__c/ConfiguracoesGerais__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ConfiguraçõesGerais</label>
</CustomObject>

force-app/main/default/objects/ConfiguracoesGerais__c/fields/LimiteDownloadArquivos__c.field-meta.xml
<CustomField>
    <fullName>LimiteDownloadArquivos__c</fullName>
    <inlineHelpText>Limite de arquivos que a funcionalidade de download do Documentaion vai fazer ao mesmo tempo</inlineHelpText>
    <label>Limite Download Arquivos</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConfiguracoesGerais__c/fields/URLPortalFornecedor__c.field-meta.xml
<CustomField>
    <fullName>URLPortalFornecedor__c</fullName>
    <label>URL do portal do fornecedor</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/T_DownloadFilesComponentController.cls
public class T_DownloadFilesComponentController {

    @AuraEnabled
    public static List<ContentDocument> getContentDocumentLinks(String recordId){
        List<ContentDocument> retorno = new List<ContentDocument>();
        ConfiguracoesGerais__c cg = ConfiguracoesGerais__c.getInstance();
        
        Try{
            List<ContentDocumentLink> temp = T_ContentDocumentLinkREP.getContentDocumentLinksByLinkedEntityId(recordId, cg.LimiteDownloadArquivos__c != null ? Integer.valueOf(cg.LimiteDownloadArquivos__c) : 10);
            For(ContentDocumentLink cdl: temp){
                retorno.add((ContentDocument) cdl.getSObject('ContentDocument'));
            }
        } catch(Exception e) {
            retorno = null;
        }
        return retorno;
    }
    
    @AuraEnabled
    public static String getOrgURL(){
        User oUser = T_UserRep.getLoggedUser();
        if(oUser.Profile.UserLicense.Name == 'External Apps') {
            return ConfiguracoesGerais__c.getInstance().URLPortalFornecedor__c;
        } else {
            return URL.getSalesforceBaseUrl().toExternalForm()+'/';
        }
        
    }
}