force-app/main/default/objects/TW1_Inspection_Item__c/TW1_Inspection_Item__c.object-meta.xml
<CustomObject>
    <label>Inspection Item</label>
    <nameField>
        <displayFormat>Item-{000000}</displayFormat>
        <label>Inspection Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspection Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Inspection_Item__c/fields/TW1_Heat_Number__c.field-meta.xml
<CustomField>
    <fullName>TW1_Heat_Number__c</fullName>
    <label>Heat Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Inspection_Item__c/fields/TW1_Inspection_Appraisal__c.field-meta.xml
<CustomField>
    <fullName>TW1_Inspection_Appraisal__c</fullName>
    <label>Inspection Appraisal</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TW1_Inspection_Item__c/fields/TW1_Item_Description__c.field-meta.xml
<CustomField>
    <fullName>TW1_Item_Description__c</fullName>
    <label>Item Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Inspection_Item__c/fields/TW1_Quantity__c.field-meta.xml
<CustomField>
    <fullName>TW1_Quantity__c</fullName>
    <label>Quantity</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TW1_Inspection_Item__c/fields/TW1_Rejection_Reason__c.field-meta.xml
<CustomField>
    <fullName>TW1_Rejection_Reason__c</fullName>
    <label>Rejection Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>TW1_Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Documentation</fullName>
            </value>
            <value>
                <fullName>Manufacturing Defect</fullName>
            </value>
            <value>
                <fullName>Out of Specification</fullName>
            </value>
            <value>
                <fullName>PO Divergence</fullName>
            </value>
            <value>
                <fullName>Non-presentation of the Item</fullName>
            </value>
            <value>
                <fullName>Notification less than 24 hours</fullName>
            </value>
            <value>
                <fullName>IRF Canceled</fullName>
                <label>IRF Canceled/Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Inspection_Item__c/fields/TW1_Request__c.field-meta.xml
<CustomField>
    <fullName>TW1_Request__c</fullName>
    <label>Request</label>
    <referenceTo>TW1_Request__c</referenceTo>
    <relationshipLabel>Inspection Items</relationshipLabel>
    <relationshipName>Inspection_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TW1_Inspection_Item__c/fields/TW1_Status__c.field-meta.xml
<CustomField>
    <fullName>TW1_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Previously Inspected</fullName>
            </value>
            <value>
                <fullName>Approved with Restriction</fullName>
            </value>
            <value>
                <fullName>Approved by OM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Inspection_Item__c/fields/TW1_Tag_or_Certificate_Number__c.field-meta.xml
<CustomField>
    <fullName>TW1_Tag_or_Certificate_Number__c</fullName>
    <inlineHelpText>In case of Inspection in parts/spools, the tag must be inserted in this field</inlineHelpText>
    <label>Tag or Certificate Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/TW1_Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>REQ{000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Rejection_Reason__c.field-meta.xml
<CustomField>
    <fullName>TW1_Rejection_Reason__c</fullName>
    <label>Rejection Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rejection_Reason</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Status__c.field-meta.xml
<CustomField>
    <fullName>TW1_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Rejection_Reason.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CNPJ da NF divergente da PO</fullName>
    </customValue>
    <customValue>
        <fullName>NF fora do período de competência</fullName>
    </customValue>
    <customValue>
        <fullName>Pendente PDF da NF</fullName>
    </customValue>
    <customValue>
        <fullName>Outros</fullName>
    </customValue>
    <customValue>
        <fullName>Valor de folha (SES) divergente da NF</fullName>
    </customValue>
    <customValue>
        <fullName>Valor de folha (SES) divergente da NF e CNPJ da NF divergente da PO</fullName>
    </customValue>
    <customValue>
        <fullName>Boleto vencido</fullName>
    </customValue>
    <customValue>
        <fullName>CNPJ Fornecedor divergente da PO</fullName>
    </customValue>
    <masterLabel>Rejection Reason</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/T_MODEC_InspecItem_REP.cls
/**
 * @File Name          : T_MODEC_InspecItem_REP.cls
 * @Description        :
 * @Author             : Rafael Hadama
 * @Group              :
 * @Last Modified By   : Rafael Hadama
 * @Last Modified On   : 29/06/2020 22:09:24
 * @Modification Log   :
 * Ver       Date            Author              Modification
 * 1.0    29/06/2020   Rafael Hadama     Initial Version
 **/
public class T_MODEC_InspecItem_REP {
    public list<TW1_Inspection_Item__c> getInspectionItensbyRequestId(string RequestId)
    {
        list<TW1_Inspection_Item__c> listInspectionItens = [SELECT Id, Name, TW1_Inspection_Appraisal__c, TW1_Quantity__c, TW1_Tag_or_Certificate_Number__c, TW1_Heat_Number__c, TW1_Item_Description__c, TW1_Rejection_Reason__c, TW1_Status__c, TW1_Request__c FROM TW1_Inspection_Item__c where TW1_Request__c =:RequestId ORDER by CreatedDate];

        return listInspectionItens;
    }
}