force-app/main/default/objects/TW1_Inspection_Item__c/TW1_Inspection_Item__c.object-meta.xml
<CustomObject>
    <label>Inspection Item</label>
    <nameField>
        <displayFormat>Item-{000000}</displayFormat>
        <label>Inspection Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspection Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Inspection_Item__c/fields/TW1_All_Appraisal__c.field-meta.xml
<CustomField>
    <fullName>TW1_All_Appraisal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>All Appraisal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TW1_Inspection_Item__c/fields/TW1_Inspection_Appraisal__c.field-meta.xml
<CustomField>
    <fullName>TW1_Inspection_Appraisal__c</fullName>
    <label>Inspection Appraisal</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TW1_Inspection_Item__c/fields/TW1_Item_Description__c.field-meta.xml
<CustomField>
    <fullName>TW1_Item_Description__c</fullName>
    <label>Item Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TW1_Inspection_Item__c/fields/TW1_Rejection_Reason__c.field-meta.xml
<CustomField>
    <fullName>TW1_Rejection_Reason__c</fullName>
    <label>Rejection Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>TW1_Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Documentation</fullName>
            </value>
            <value>
                <fullName>Manufacturing Defect</fullName>
            </value>
            <value>
                <fullName>Out of Specification</fullName>
            </value>
            <value>
                <fullName>PO Divergence</fullName>
            </value>
            <value>
                <fullName>Non-presentation of the Item</fullName>
            </value>
            <value>
                <fullName>Notification less than 24 hours</fullName>
            </value>
            <value>
                <fullName>IRF Canceled</fullName>
                <label>IRF Canceled/Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Inspection_Item__c/fields/TW1_Request__c.field-meta.xml
<CustomField>
    <fullName>TW1_Request__c</fullName>
    <label>Request</label>
    <referenceTo>TW1_Request__c</referenceTo>
    <relationshipLabel>Inspection Items</relationshipLabel>
    <relationshipName>Inspection_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TW1_Inspection_Item__c/fields/TW1_Status__c.field-meta.xml
<CustomField>
    <fullName>TW1_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Previously Inspected</fullName>
            </value>
            <value>
                <fullName>Approved with Restriction</fullName>
            </value>
            <value>
                <fullName>Approved by OM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Request__c/TW1_Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>REQ{000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Request__c/fields/TW1_All_Appraisal__c.field-meta.xml
<CustomField>
    <fullName>TW1_All_Appraisal__c</fullName>
    <label>All Appraisal</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_All_Inspection_Items_Status__c.field-meta.xml
<CustomField>
    <fullName>TW1_All_Inspection_Items_Status__c</fullName>
    <label>All Inspection Items Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved with Restriction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_All_Inspection_Items_Status_Filled__c.field-meta.xml
<CustomField>
    <fullName>TW1_All_Inspection_Items_Status_Filled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>All Inspection Items Status Filled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Rejection_Reason__c.field-meta.xml
<CustomField>
    <fullName>TW1_Rejection_Reason__c</fullName>
    <label>Rejection Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rejection_Reason</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Status__c.field-meta.xml
<CustomField>
    <fullName>TW1_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Request__c/recordTypes/Inspection.recordType-meta.xml
<RecordType>
    <fullName>Inspection</fullName>
    <active>true</active>
    <label>Inspection</label>
</RecordType>

force-app/main/default/globalValueSets/Rejection_Reason.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CNPJ da NF divergente da PO</fullName>
    </customValue>
    <customValue>
        <fullName>NF fora do período de competência</fullName>
    </customValue>
    <customValue>
        <fullName>Pendente PDF da NF</fullName>
    </customValue>
    <customValue>
        <fullName>Outros</fullName>
    </customValue>
    <customValue>
        <fullName>Valor de folha (SES) divergente da NF</fullName>
    </customValue>
    <customValue>
        <fullName>Valor de folha (SES) divergente da NF e CNPJ da NF divergente da PO</fullName>
    </customValue>
    <customValue>
        <fullName>Boleto vencido</fullName>
    </customValue>
    <customValue>
        <fullName>CNPJ Fornecedor divergente da PO</fullName>
    </customValue>
    <masterLabel>Rejection Reason</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/T_MODEC_InspectionItem_App.cls
/**
 * @File Name          : T_MODEC_InspectionItem_App.cls
 * @Description        :
 * @Author             : Rafael Hadama
 * @Group              :
 * @Last Modified By   : Rafael Hadama
 * @Last Modified On   : 07-13-2020
 * @Modification Log   :
 * Ver       Date            Author              Modification
 * 1.0    29/06/2020   Rafael Hadama     Initial Version
 **/
public class T_MODEC_InspectionItem_App {
    /**
     * @description Method that validate changes in the Inspection Item Status, and update the related Request if all itens have Status != from null.
     * @author Rafael Hadama | 16/06/2020
     * @param OldInspecItem
     * @param NewInspecItem
     * @return void
     **/
    public static void CheckAllInspectionItens(TW1_Inspection_Item__c OldInspecItem, TW1_Inspection_Item__c NewInspecItem)
    {
        T_MODEC_InspecItem_REP InspectionItemREP = new T_MODEC_InspecItem_REP();
        T_MODEC_Request_Rep    RequestREP        = new T_MODEC_Request_Rep();

        if ((OldInspecItem.TW1_Status__c != NewInspecItem.TW1_Status__c) || (OldInspecItem.TW1_Inspection_Appraisal__c != NewInspecItem.TW1_Inspection_Appraisal__c) || (OldInspecItem.TW1_Rejection_Reason__c != NewInspecItem.TW1_Rejection_Reason__c) || (OldInspecItem.TW1_Item_Description__c != NewInspecItem.TW1_Item_Description__c))
        {
            system.debug('Status or Inspection Appraisal or Rejection Reason was modified in Inspection Item.');
            //Querying all inspection itens related to the request
            list<TW1_Inspection_Item__c> listInspecItens = InspectionItemREP.getInspectionItensbyRequestId(NewInspecItem.TW1_Request__c);
            system.debug('List of Inspection Itens:' + listInspecItens);

            //Validating if all Itens status were analized.
            //If not the boolean below is false.
            boolean AllItensStatusAnalyzed = true;

            //referente TW1_All_Inspection_Items_Status__c
            String AllInpectionItemStatus = '';


            //Validating if all Itens status are Approved or Previously Approved.
            //If not the boolean below is false.
            //boolean AllItensStatusApproved = true;

            string AllAppraisals = '';
            for (TW1_Inspection_Item__c InspecItem : listInspecItens)
            {
                if (InspecItem.TW1_Status__c == null)
                {
                    AllItensStatusAnalyzed = false;
                }


                //Preenchend campo para envio no email
                AllAppraisals += 'Inspection Item: ' + InspecItem.TW1_Item_Description__c + '\n';
                if (InspecItem.TW1_Status__c == 'Rejected')
                {
                    AllAppraisals += 'Status: ' + InspecItem.TW1_Status__c + '\n';
                    AllAppraisals += 'Rejection Reason: ' + InspecItem.TW1_Rejection_Reason__c + '\n';
                }
                else
                {
                    AllAppraisals += 'Status: ' + InspecItem.TW1_Status__c + '\n';
                }
                AllAppraisals += 'Inspection Appraisal: ' + InspecItem.TW1_Inspection_Appraisal__c + '\n \n';


                String AllInpectionItemStatusAux = '';
                //Validando status para atualizar TW1_All_Inspection_Items_Status__c field in request.
                if ((InspecItem.TW1_Status__c == 'Approved') || (InspecItem.TW1_Status__c == 'Previously Approved'))
                {
                    AllInpectionItemStatusAux = 'Approved';
                }
                if (InspecItem.TW1_Status__c == 'Approved with Restriction')
                {
                    AllInpectionItemStatusAux = 'Approved with Restriction';
                }
                if (InspecItem.TW1_Status__c == 'Rejected')
                {
                    AllInpectionItemStatusAux = 'Rejected';
                }

                //Verificando que caso existe 1 item - rejected - resultado status request : Rejected
                //Ou se existe nenhuma reject, e pelo menos uma Approved with Restriction : resultado status request :Approved with Restriction

                if (AllInpectionItemStatusAux == 'Rejected')
                {
                    AllInpectionItemStatus = 'Rejected';
                }
                else if (AllInpectionItemStatusAux == 'Approved with Restriction')
                {
                    if (AllInpectionItemStatus != 'Rejected')
                    {
                        AllInpectionItemStatus = 'Approved with Restriction';
                    }
                }
                else if (AllInpectionItemStatusAux == 'Approved')
                {
                    if ((AllInpectionItemStatus != 'Rejected') && (AllInpectionItemStatus != 'Approved with Restriction'))
                    {
                        AllInpectionItemStatus = 'Approved';
                    }
                }
            }

            system.debug('AllItensStatusAnalyzed >' + AllItensStatusAnalyzed);
            system.debug('AllAppraisals >' + AllAppraisals);


            //Querying related Request -- atualizar buscando agora o - TW1_All_Inspection_Items_Status__c
            TW1_Request__c InspectionRequest = RequestREP.getRequestById(NewInspecItem.TW1_Request__c);
            if (AllItensStatusAnalyzed == true)
            {
                InspectionRequest.TW1_All_Inspection_Items_Status_Filled__c = true;
            }
            else
            {
                InspectionRequest.TW1_All_Inspection_Items_Status_Filled__c = false;
            }

            system.debug('Atribuindo o status da inspection na request>' + AllInpectionItemStatus);
            InspectionRequest.TW1_All_Inspection_Items_Status__c = AllInpectionItemStatus;
            InspectionRequest.TW1_All_Appraisal__c = AllAppraisals;

            system.debug('Req TW1_All_Inspection_Items_Status_Filled>' + InspectionRequest.TW1_All_Inspection_Items_Status_Filled__c);
            system.debug('Req TW1_All_Appraisal__c>' + InspectionRequest.TW1_All_Appraisal__c);
            //Adding stopRequestTrigger = false, so the Request trigger does not run
            TriggerFactory.stopRequestTrigger = false;

            update InspectionRequest;
        }
    }
}