force-app/main/default/objects/BOM__c/BOM__c.object-meta.xml
<CustomObject>
    <label>BOM</label>
    <nameField>
        <displayFormat>BOM-{00000}</displayFormat>
        <label>BOM Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BOMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BOM__c/fields/Vessel__c.field-meta.xml
<CustomField>
    <fullName>Vessel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vessel</label>
    <referenceTo>Vessel__c</referenceTo>
    <relationshipLabel>BOMs</relationshipLabel>
    <relationshipName>BOMs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/VesselShortName__c.field-meta.xml
<CustomField>
    <fullName>VesselShortName__c</fullName>
    <formula>Vessel__r.ShortName__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vessel Short Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RDO__c/RDO__c.object-meta.xml
<CustomObject>
    <label>RDO</label>
    <nameField>
        <label>Num RDO</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RDOs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RDO__c/fields/BOM__c.field-meta.xml
<CustomField>
    <fullName>BOM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BOM</label>
    <referenceTo>BOM__c</referenceTo>
    <relationshipLabel>RDOs</relationshipLabel>
    <relationshipName>BOMs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RDO__c/fields/BurningGasContrVolume__c.field-meta.xml
<CustomField>
    <fullName>BurningGasContrVolume__c</fullName>
    <label>Contractor’s Responsibility</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RDO__c/fields/BurningGasPetrVolume__c.field-meta.xml
<CustomField>
    <fullName>BurningGasPetrVolume__c</fullName>
    <label>Client’s Responsibility</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RDO__c/fields/CharterContract__c.field-meta.xml
<CustomField>
    <fullName>CharterContract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Charter Contract</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>VesselContract__c.Vessel__c</field>
            <operation>equals</operation>
            <valueField>$Source.Vessel__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>VesselContract__c</referenceTo>
    <relationshipLabel>RDOs</relationshipLabel>
    <relationshipName>RDOs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RDO__c/fields/DailyRateServices__c.field-meta.xml
<CustomField>
    <fullName>DailyRateServices__c</fullName>
    <label>Daily Rate (Services)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RDO__c/fields/DieselConsumCtrlContrConsumed__c.field-meta.xml
<CustomField>
    <fullName>DieselConsumCtrlContrConsumed__c</fullName>
    <label>Consumed.</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RDO__c/fields/LimitDate__c.field-meta.xml
<CustomField>
    <fullName>LimitDate__c</fullName>
    <formula>IF(WaterInjectionUninjectedVolume__c &gt; 0, ADDMONTHS(Date__c,3) - 1, null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Limit Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RDO__c/fields/LocalContentPetr__c.field-meta.xml
<CustomField>
    <fullName>LocalContentPetr__c</fullName>
    <label>Client</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RDO__c/fields/LocalContentPetrCont__c.field-meta.xml
<CustomField>
    <fullName>LocalContentPetrCont__c</fullName>
    <label>Diving Team</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RDO__c/fields/NaturalGasExported__c.field-meta.xml
<CustomField>
    <fullName>NaturalGasExported__c</fullName>
    <label>Exported/Imported Gas</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RDO__c/fields/NaturalGasHPFlareBurn__c.field-meta.xml
<CustomField>
    <fullName>NaturalGasHPFlareBurn__c</fullName>
    <label>HP Flare</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RDO__c/fields/NaturalGasLPFlareBurn__c.field-meta.xml
<CustomField>
    <fullName>NaturalGasLPFlareBurn__c</fullName>
    <label>LP Flare</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RDO__c/fields/NaturalGasProduced__c.field-meta.xml
<CustomField>
    <fullName>NaturalGasProduced__c</fullName>
    <label>Produced Gas</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RDO__c/fields/Prioritization__c.field-meta.xml
<CustomField>
    <fullName>Prioritization__c</fullName>
    <label>Prioritization</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RDO__c/fields/RateDeltaDaily__c.field-meta.xml
<CustomField>
    <fullName>RateDeltaDaily__c</fullName>
    <label>Daily Rate (Charter)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RDO__c/fields/ServicesContract__c.field-meta.xml
<CustomField>
    <fullName>ServicesContract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Services Contract</label>
    <referenceTo>VesselContract__c</referenceTo>
    <relationshipLabel>RDOs (Services Contract)</relationshipLabel>
    <relationshipName>RDOs1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RDO__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Adjusted</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RDO__c/fields/Vessel__c.field-meta.xml
<CustomField>
    <fullName>Vessel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vessel</label>
    <referenceTo>Vessel__c</referenceTo>
    <relationshipLabel>RDOs</relationshipLabel>
    <relationshipName>RDOs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RDO__c/fields/WaterInjectionTimeParcialStop__c.field-meta.xml
<CustomField>
    <fullName>WaterInjectionTimeParcialStop__c</fullName>
    <label>Time of Partial Stop</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/RDO__c/fields/WaterInjectionTimeTotalStop__c.field-meta.xml
<CustomField>
    <fullName>WaterInjectionTimeTotalStop__c</fullName>
    <label>Time of Total Stop</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/RDO__c/fields/WIAmountReceived__c.field-meta.xml
<CustomField>
    <fullName>WIAmountReceived__c</fullName>
    <label>Volume Received</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RDO__c/fields/WIAmountSent__c.field-meta.xml
<CustomField>
    <fullName>WIAmountSent__c</fullName>
    <label>Volume Sent</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RDO__c/fields/WITotal__c.field-meta.xml
<CustomField>
    <fullName>WITotal__c</fullName>
    <formula>WaterInjectionInjectedVolume__c +  WIAmountReceived__c -  WIAmountSent__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Actual Injection</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vessel__c/Vessel__c.object-meta.xml
<CustomObject>
    <label>Vessel</label>
    <nameField>
        <label>Vessel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vessels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vessel__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Decommissioned</fullName>
            </value>
            <value>
                <fullName>EPCI</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>In Operation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RDODAO.cls
public with sharing class RDODAO {
    
    public static List<RDO__c> getRDOById(String idRDO){
        return [SELECT 
                  id,   
                  CharterContract__c,
                  Date__c,
                  Name,
                  RateDeltaDaily__c,
                  ServicesContract__c,
                  Status__c,
                  Vessel__c,
                  BOM__c,
                  LocalContentPetrCont__c,
                  LocalContentPetr__c,
                  NaturalGasHPFlareBurn__c,
                  NaturalGasLPFlareBurn__c,
                  NaturalGasProduced__c,
                  NaturalGasExported__c,
                  BurningGasPetrVolume__c,
                  Prioritization__c,
                  WIAmountReceived__c,
                  WIAmountSent__c,
                  WITotal__c,
                  LimitDate__c,
                  WaterInjectionTimeTotalStop__c,
                  WaterInjectionTimeParcialStop__c,
                  DieselConsumCtrlContrConsumed__c
                  FROM
                  RDO__c
                  WHERE
                  id =: idRDO];
    }

    public static List<RDO__c> getRDOsByIdBOM(String idBOM, String inactive){
        return [SELECT 
                  id,   
                  CharterContract__c,
                  Date__c,
                  Name,
                  RateDeltaDaily__c,
                  DailyRateServices__c,
                  DieselConsumCtrlContrConsumed__c,
                  ServicesContract__c,
                  LocalContentPetrCont__c,
                  LocalContentPetr__c,
                  Status__c,
                  Vessel__c,
                  BOM__c,
                  NaturalGasHPFlareBurn__c,
                  NaturalGasLPFlareBurn__c,
                  NaturalGasProduced__c,
                  NaturalGasExported__c,
                  BurningGasPetrVolume__c,
                  BurningGasContrVolume__c,
                  Prioritization__c,
                  WIAmountReceived__c,
                  WIAmountSent__c,
                  WITotal__c,
                  LimitDate__c
                  FROM
                  RDO__c
                  WHERE
                  BOM__c =: idBOM
                  AND
                  Status__c !=: inactive];
    }

    public static List<RDO__c> getRDOByName(String nameRDO){
        return [SELECT 
                  id,   
                  CharterContract__c,
                  Date__c,
                  Name,
                  RateDeltaDaily__c,
                  ServicesContract__c,
                  Status__c,
                  Vessel__c,
                  BOM__c
                  FROM
                  RDO__c
                  WHERE
                  Name =: nameRDO];
    }


    public static List<RDO__c> getRDOByNameAndShortName(String nameRDO, String vessel){
        return [SELECT 
                  id,   
                  CharterContract__c,
                  Date__c,
                  Name,
                  RateDeltaDaily__c,
                  ServicesContract__c,
                  Status__c,
                  Vessel__c,
                  BOM__c
                  FROM
                  RDO__c
                  WHERE
                  Name =: nameRDO
                  AND
                  VesselShortName__c =: vessel];
    }

    public static List<RDO__c> getRDOsByIdBOMList(Set<Id> setIdBOM, String inactive){
        return [SELECT 
                  id,   
                  CharterContract__c,
                  Date__c,
                  Name,
                  RateDeltaDaily__c,
                  DieselConsumCtrlContrConsumed__c,
                  ServicesContract__c,
                  LocalContentPetrCont__c,
                  LocalContentPetr__c,
                  Status__c,
                  Vessel__c,
                  BOM__c,
                  NaturalGasHPFlareBurn__c,
                  NaturalGasLPFlareBurn__c,
                  NaturalGasProduced__c,
                  NaturalGasExported__c,
                  BurningGasPetrVolume__c,
                  Prioritization__c,
                  WIAmountReceived__c,
                  WIAmountSent__c,
                  WITotal__c,
                  LimitDate__c
                  FROM
                  RDO__c
                  WHERE
                  BOM__c IN: setIdBOM
                  AND
                  Status__c !=: inactive];
    }
}