force-app/main/default/objects/BOM__c/BOM__c.object-meta.xml
<CustomObject>
    <label>BOM</label>
    <nameField>
        <displayFormat>BOM-{00000}</displayFormat>
        <label>BOM Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BOMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BOM__c/fields/DailyRateBRL__c.field-meta.xml
<CustomField>
    <fullName>DailyRateBRL__c</fullName>
    <label>Daily Rate (BRL)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/DailyRateLosses__c.field-meta.xml
<CustomField>
    <fullName>DailyRateLosses__c</fullName>
    <formula>TotalPossibleDaysPeriod__c - RDOsDailyRateSum__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total daily rate losses (Charter)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/DailyRateUSD__c.field-meta.xml
<CustomField>
    <fullName>DailyRateUSD__c</fullName>
    <label>Daily Rate (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/N__c.field-meta.xml
<CustomField>
    <fullName>N__c</fullName>
    <label>N</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/Observations__c.field-meta.xml
<CustomField>
    <fullName>Observations__c</fullName>
    <label>Observations</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/RDOsDailyRateSum__c.field-meta.xml
<CustomField>
    <fullName>RDOsDailyRateSum__c</fullName>
    <label>RDOs Daily Rate Sum (Charter)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/ReferenceMonth__c.field-meta.xml
<CustomField>
    <fullName>ReferenceMonth__c</fullName>
    <label>Reference Month</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/RevenueCharter__c.field-meta.xml
<CustomField>
    <fullName>RevenueCharter__c</fullName>
    <label>Charter Revenue (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/RevenueServices__c.field-meta.xml
<CustomField>
    <fullName>RevenueServices__c</fullName>
    <label>Services Revenue (BRL)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/RMCharterAmountUSD__c.field-meta.xml
<CustomField>
    <fullName>RMCharterAmountUSD__c</fullName>
    <label>RM Charter Amount (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/RMCharterNumber__c.field-meta.xml
<CustomField>
    <fullName>RMCharterNumber__c</fullName>
    <label>RM Charter Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/RMServicesAmountBRL__c.field-meta.xml
<CustomField>
    <fullName>RMServicesAmountBRL__c</fullName>
    <label>RM Services Amount (BRL)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/RMServicesNumber__c.field-meta.xml
<CustomField>
    <fullName>RMServicesNumber__c</fullName>
    <label>RM Services Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/SumDailyRates__c.field-meta.xml
<CustomField>
    <fullName>SumDailyRates__c</fullName>
    <label>Sum of daily rates</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/SumDieselConsumed__c.field-meta.xml
<CustomField>
    <fullName>SumDieselConsumed__c</fullName>
    <label>Sum of diesel consumed</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/TotalDailyRateLossesServices__c.field-meta.xml
<CustomField>
    <fullName>TotalDailyRateLossesServices__c</fullName>
    <formula>TotalPossibleDaysPeriod__c - RDOsDailyRateSumServices__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total daily rate losses (Services)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/TotalLossesBRLAuto__c.field-meta.xml
<CustomField>
    <fullName>TotalLossesBRLAuto__c</fullName>
    <label>Total losses (BRL)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/TotalLossesUSDAuto__c.field-meta.xml
<CustomField>
    <fullName>TotalLossesUSDAuto__c</fullName>
    <label>Total losses (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/TotalReductionIUGAAuto__c.field-meta.xml
<CustomField>
    <fullName>TotalReductionIUGAAuto__c</fullName>
    <label>Total reduction by IUGA</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/TotalReductionOffloadingdDelayAuto__c.field-meta.xml
<CustomField>
    <fullName>TotalReductionOffloadingdDelayAuto__c</fullName>
    <label>Total reduction by Offloading delay</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/TotalReductionPartialShutdownAuto__c.field-meta.xml
<CustomField>
    <fullName>TotalReductionPartialShutdownAuto__c</fullName>
    <label>Total reduction by Partial Shutdown</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/TotalReductionShutdownAuto__c.field-meta.xml
<CustomField>
    <fullName>TotalReductionShutdownAuto__c</fullName>
    <label>Total reduction by Shutdown</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/TotalReductionTotalWIStopAuto__c.field-meta.xml
<CustomField>
    <fullName>TotalReductionTotalWIStopAuto__c</fullName>
    <label>Total reduction by Total WI Stop</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/TotalReductionWIPartialStopAuto__c.field-meta.xml
<CustomField>
    <fullName>TotalReductionWIPartialStopAuto__c</fullName>
    <label>Total reduction by WI Partial Stop</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/Vessel__c.field-meta.xml
<CustomField>
    <fullName>Vessel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vessel</label>
    <referenceTo>Vessel__c</referenceTo>
    <relationshipLabel>BOMs</relationshipLabel>
    <relationshipName>BOMs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/VesselShortName__c.field-meta.xml
<CustomField>
    <fullName>VesselShortName__c</fullName>
    <formula>Vessel__r.ShortName__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vessel Short Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vessel__c/Vessel__c.object-meta.xml
<CustomObject>
    <label>Vessel</label>
    <nameField>
        <label>Vessel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vessels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BOMDAO.cls
public with sharing class BOMDAO {
    
    public static List<BOM__c> getBOMByVesselAndDate(Id idVessel, Date startDate, Date endDate) {
        return [SELECT 
                    Id,
                    EndDate__c,
                    Observations__c,
                    RDOsDailyRateSum__c,
                    ReferenceMonth__c,
                    RevenueCharter__c,
                    RevenueServices__c,
                    RMCharterAmountUSD__c,
                    RMCharterNumber__c,
                    RMServicesAmountBRL__c,
                    RMServicesNumber__c,
                    StartDate__c,
                    Vessel__c,
                    VesselShortName__c,
                    SumDailyRates__c,
                    SumDieselConsumed__c,
                    TotalLossesBRLAuto__c,
                    TotalLossesUSDAuto__c,
                    DailyRateLosses__c
                    FROM
                    BOM__c
                    WHERE
                    Vessel__c =: idVessel
                    AND
                    StartDate__c =: startDate
                    AND 
                    EndDate__c =: endDate];
    }

    public static List<BOM__c> getBOMByVesselAndPastDate(Id idVessel, Date pastDate) {
        return [SELECT 
                    Id,
                    EndDate__c,
                    Observations__c,
                    RDOsDailyRateSum__c,
                    ReferenceMonth__c,
                    RevenueCharter__c,
                    RevenueServices__c,
                    RMCharterAmountUSD__c,
                    RMCharterNumber__c,
                    RMServicesAmountBRL__c,
                    RMServicesNumber__c,
                    StartDate__c,
                    Vessel__c,
                    VesselShortName__c,
                    TotalLossesBRLAuto__c,
                    TotalLossesUSDAuto__c
                    FROM
                    BOM__c
                    WHERE
                    Vessel__c =: idVessel
                    AND
                    StartDate__c <=: pastDate
                    AND 
                    EndDate__c >=: pastDate];
    }

    public static List<BOM__c> getBOMById(String idBOM) {
        return [SELECT 
                    Id,
                    EndDate__c,
                    DailyRateBRL__c,
                    DailyRateUSD__c,
                    Observations__c,
                    RDOsDailyRateSum__c,
                    ReferenceMonth__c,
                    RevenueCharter__c,
                    RevenueServices__c,
                    RMCharterAmountUSD__c,
                    RMCharterNumber__c,
                    RMServicesAmountBRL__c,
                    RMServicesNumber__c,
                    StartDate__c,
                    Vessel__c,
                    VesselShortName__c,
                    SumDailyRates__c,
                    SumDieselConsumed__c,
                    TotalLossesBRLAuto__c,
                    TotalLossesUSDAuto__c,
                    TotalReductionIUGAAuto__c,
                    TotalReductionOffloadingdDelayAuto__c,
                    TotalReductionPartialShutdownAuto__c,
                    TotalReductionShutdownAuto__c,
                    DailyRateLosses__c,
                    TotalReductionTotalWIStopAuto__c,
                    TotalReductionWIPartialStopAuto__c,
                    N__c,
                    TotalDailyRateLossesServices__c
                    FROM
                    BOM__c
                    WHERE
                    Id =: idBOM];
    }
}