force-app/main/default/objects/BOM__c/BOM__c.object-meta.xml
<CustomObject>
    <label>BOM</label>
    <nameField>
        <displayFormat>BOM-{00000}</displayFormat>
        <label>BOM Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BOMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BOM__c/fields/DailyRateBRL__c.field-meta.xml
<CustomField>
    <fullName>DailyRateBRL__c</fullName>
    <label>Daily Rate (BRL)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/DailyRateUSD__c.field-meta.xml
<CustomField>
    <fullName>DailyRateUSD__c</fullName>
    <label>Daily Rate (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/Vessel__c.field-meta.xml
<CustomField>
    <fullName>Vessel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vessel</label>
    <referenceTo>Vessel__c</referenceTo>
    <relationshipLabel>BOMs</relationshipLabel>
    <relationshipName>BOMs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContractDailyRateHistory__c/ContractDailyRateHistory__c.object-meta.xml
<CustomObject>
    <label>Contract Daily Rate History</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>History Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Daily Rate Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ContractDailyRateHistory__c/fields/DailyRate__c.field-meta.xml
<CustomField>
    <fullName>DailyRate__c</fullName>
    <label>Daily Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ContractDailyRateHistory__c/fields/VesselContract__c.field-meta.xml
<CustomField>
    <fullName>VesselContract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vessel Contract</label>
    <referenceTo>VesselContract__c</referenceTo>
    <relationshipLabel>Contract Daily Rate Histories</relationshipLabel>
    <relationshipName>Contract_Daily_Rate_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RDO__c/RDO__c.object-meta.xml
<CustomObject>
    <label>RDO</label>
    <nameField>
        <label>Num RDO</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RDOs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RDO__c/fields/BOM__c.field-meta.xml
<CustomField>
    <fullName>BOM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BOM</label>
    <referenceTo>BOM__c</referenceTo>
    <relationshipLabel>RDOs</relationshipLabel>
    <relationshipName>BOMs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RDO__c/fields/Vessel__c.field-meta.xml
<CustomField>
    <fullName>Vessel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vessel</label>
    <referenceTo>Vessel__c</referenceTo>
    <relationshipLabel>RDOs</relationshipLabel>
    <relationshipName>RDOs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vessel__c/Vessel__c.object-meta.xml
<CustomObject>
    <label>Vessel</label>
    <nameField>
        <label>Vessel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vessels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vessel__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New build</fullName>
            </value>
            <value>
                <fullName>Conversion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VesselContract__c/VesselContract__c.object-meta.xml
<CustomObject>
    <label>Vessel Contract</label>
    <nameField>
        <label>Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vessel Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VesselContract__c/fields/BOMEndDate__c.field-meta.xml
<CustomField>
    <fullName>BOMEndDate__c</fullName>
    <formula>ADDMONTHS(BOMStartDate__c ,1) - 1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BOM End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VesselContract__c/fields/BOMStartDate__c.field-meta.xml
<CustomField>
    <fullName>BOMStartDate__c</fullName>
    <label>BOM Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VesselContract__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Charter</fullName>
            </value>
            <value>
                <fullName>Cost Plus</fullName>
            </value>
            <value>
                <fullName>O&amp;M Support</fullName>
            </value>
            <value>
                <fullName>Pre-Ops</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VesselContract__c/fields/Vessel__c.field-meta.xml
<CustomField>
    <fullName>Vessel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vessel</label>
    <referenceTo>Vessel__c</referenceTo>
    <relationshipLabel>Vessel Contracts</relationshipLabel>
    <relationshipName>VesselContracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ContractDailyRateHistBO.cls
public with sharing class ContractDailyRateHistBO {

    private static final ContractDailyRateHistBO instance = new ContractDailyRateHistBO();

	public static ContractDailyRateHistBO getInstance() {
		return instance;
    }

    public void atualizarTaxasBOM(List<ContractDailyRateHistory__c> lstDailyRateHistory)
    {
        List<ContractDailyRateHistory__c> lstVesselContractDetails = new List<ContractDailyRateHistory__c>();
        List<BOM__c> lstBOM = new List<BOM__c>();
        List<BOM__c> lstBOMUpdate = new List<BOM__c>();
        Set<Id> setIds = new Set<Id>();
        Date bomStartDate;
        Date bomEndDate;
        Id vesselId;
        String contractType;
        String rdo;


        for(ContractDailyRateHistory__c rateHistory : lstDailyRateHistory){
            setIds.add(rateHistory.Id);
        }

        lstVesselContractDetails = ContractDailyRateHistoryDAO.getInfosByContractDailyRateHistory(setIds);

        for(ContractDailyRateHistory__c contractRate : lstVesselContractDetails){
            bomStartDate = contractRate.VesselContract__r.BOMStartDate__c;
            bomEndDate = contractRate.VesselContract__r.BOMEndDate__c;
            vesselId = contractRate.VesselContract__r.Vessel__c;
            contractType = contractRate.VesselContract__r.Type__c;
        }

        lstBOM = BOMDAO.getBOMByVesselAndDate(vesselId, bomStartDate, bomEndDate);

        for(BOM__c bom : lstBOM){
            if(contractType == 'Services'){
                BOM__c newBOM = new BOM__c(
                    Id = bom.Id,
                    DailyRateBRL__c = lstVesselContractDetails[0].DailyRate__c);

                    lstBOMUpdate.add(newBOM);
            }

            if(contractType == 'Charter'){
                BOM__c newBOM = new BOM__c(
                    Id = bom.Id,
                    DailyRateUSD__c = lstVesselContractDetails[0].DailyRate__c);

                    lstBOMUpdate.add(newBOM);
            }
        }

        if(!lstBOMUpdate.isEmpty()){
            update lstBOMUpdate;
        }

        if(!lstBOMUpdate.isEmpty()){
            List<RDO__c> rdoRegister = RDODAO.getRDOsByIdBOM(lstBOMUpdate[0].Id, 'Inactive');
            
            if(rdoRegister != null && !rdoRegister.isEmpty()){
                rdo = rdoRegister[0].Id;
            }

            RDOBO.getInstance().createOrUpdateBOM(rdo);
        }
    }
}