force-app/main/default/objects/DailyRates__c/DailyRates__c.object-meta.xml
<CustomObject>
    <label>Daily Rates</label>
    <nameField>
        <displayFormat>DR-{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DailyRates__c/fields/PercentReduction__c.field-meta.xml
<CustomField>
    <fullName>PercentReduction__c</fullName>
    <label>% Reduction</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DailyRates__c/fields/RDO__c.field-meta.xml
<CustomField>
    <fullName>RDO__c</fullName>
    <label>RDO</label>
    <referenceTo>RDO__c</referenceTo>
    <relationshipLabel>Daily Rates</relationshipLabel>
    <relationshipName>Daily_Rates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RDO__c/RDO__c.object-meta.xml
<CustomObject>
    <label>RDO</label>
    <nameField>
        <label>Num RDO</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RDOs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TriggerHandlerDailyRatesTest.cls
@isTest
public with sharing class TriggerHandlerDailyRatesTest {

    @isTest
    public static void handlerTest()
    {
        RDO__c rdo = TestUtil.createRDO();
        DailyRates__c dailyRate = new DailyRates__c(RDO__c = rdo.Id,
                                                    Description__c = 'Test',
                                                    PercentReduction__c = '0.05%');
        Test.startTest();

        insert dailyRate;
        update dailyRate;
        
        Test.stopTest();
    }
}