force-app/main/default/objects/DailyRates__c/DailyRates__c.object-meta.xml
<CustomObject>
    <label>Daily Rates</label>
    <nameField>
        <displayFormat>DR-{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DailyRates__c/fields/ExtraTime__c.field-meta.xml
<CustomField>
    <fullName>ExtraTime__c</fullName>
    <label>Extra Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/DailyRates__c/fields/ExtraTimeFrm__c.field-meta.xml
<CustomField>
    <fullName>ExtraTimeFrm__c</fullName>
    <label>Extra Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DailyRates__c/fields/TimeOccurrence__c.field-meta.xml
<CustomField>
    <fullName>TimeOccurrence__c</fullName>
    <label>Time of Occurrence</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/DailyRates__c/fields/TimeOcurrenceFrm__c.field-meta.xml
<CustomField>
    <fullName>TimeOcurrenceFrm__c</fullName>
    <label>Time of Occurrence</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DailyRatesBOTest.cls
@isTest
public with sharing class DailyRatesBOTest {
    
    @isTest
    public static void FillNReportTest()
    {
        Test.startTest();
        DailyRates__c dailyRate = TestUtil.createDailyRate();
        update dailyRate;
        List<DailyRates__c> lstDailyRate = new List<DailyRates__c>();

        lstDailyRate.add(dailyRate);

        DailyRatesBO.getInstance().FillNReport(lstDailyRate);

        Test.stopTest();
    }

    @isTest
    public static void formatTimeFields()
    {
        Test.startTest();

        DailyRates__c dailyRate = TestUtil.createDailyRate();
        update dailyRate;

        List<DailyRates__c> lstDailyRate = new List<DailyRates__c>();

        dailyRate.ExtraTime__c = Time.newInstance(11, 1, 0, 0);
        dailyRate.TimeOccurrence__c = Time.newInstance(11, 1, 0, 0);

        lstDailyRate.add(dailyRate);
        DailyRatesBO.getInstance().formatTimeFields(lstDailyRate);
        lstDailyRate.clear();

        dailyRate.ExtraTime__c = Time.newInstance(11, 1, 0, 0);
        dailyRate.TimeOccurrence__c = Time.newInstance(11, 1, 0, 0);
        
        lstDailyRate.add(dailyRate);
        DailyRatesBO.getInstance().formatTimeFields(lstDailyRate);
        lstDailyRate.clear();

        dailyRate.ExtraTime__c = Time.newInstance(11, 11, 0, 0);
        dailyRate.TimeOccurrence__c = Time.newInstance(11, 11, 0, 0);
        
        lstDailyRate.add(dailyRate);
        DailyRatesBO.getInstance().formatTimeFields(lstDailyRate);
        lstDailyRate.clear();

        dailyRate.ExtraTime__c = null;
        dailyRate.ExtraTimeFrm__c = '11:01:00';
        dailyRate.TimeOccurrence__c = null;
        dailyRate.TimeOcurrenceFrm__c = '11:01:00';

        lstDailyRate.add(dailyRate);
        DailyRatesBO.getInstance().formatTimeFields(lstDailyRate);

        Test.stopTest();
    }
}