force-app/main/default/objects/DailyRates__c/DailyRates__c.object-meta.xml
<CustomObject>
    <label>Daily Rates</label>
    <nameField>
        <displayFormat>DR-{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DailyRates__c/fields/PercentReduction__c.field-meta.xml
<CustomField>
    <fullName>PercentReduction__c</fullName>
    <label>% Reduction</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DailyRates__c/fields/RDO__c.field-meta.xml
<CustomField>
    <fullName>RDO__c</fullName>
    <label>RDO</label>
    <referenceTo>RDO__c</referenceTo>
    <relationshipLabel>Daily Rates</relationshipLabel>
    <relationshipName>Daily_Rates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RDO__c/RDO__c.object-meta.xml
<CustomObject>
    <label>RDO</label>
    <nameField>
        <label>Num RDO</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RDOs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DailyRatesDAO.cls
public with sharing class DailyRatesDAO {
    
    public static List<DailyRates__c> getDailyRatesByRDO(set<ID> idRDO){
       return [SELECT ID,
                      RDO__c,
                      Description__c, 
                      PercentReduction__c 
                      FROM 
                      DailyRates__c 
                      WHERE 
                      RDO__c =: idRDO];
    }

    public static List<DailyRates__c> getDailyRatesBySetRDO(set<ID> idRDO){
        return [SELECT ID,
                       RDO__c,
                       Description__c, 
                       PercentReduction__c 
                       FROM 
                       DailyRates__c 
                       WHERE 
                       RDO__c IN: idRDO];
     }

}