force-app/main/default/objects/TW1_Documentation__c/TW1_Documentation__c.object-meta.xml
<CustomObject>
    <label>Documentation</label>
    <nameField>
        <displayFormat>DOC{000000}</displayFormat>
        <label>Documentation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documentations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Documentation__c/fields/TW1_DocumentationAux__c.field-meta.xml
<CustomField>
    <fullName>TW1_DocumentationAux__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Booleano para controle dos documentation que foram efetivamente criados. 
para facilitar schedule de delete posterior.</description>
    <label>DocumentationAux</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/T_MODEC_DeleteDocumentation_App.cls
/**
 * @File Name          : T_MODEC_DeleteDocumentation_App.cls
 * @Description        : Classe Application onde está a regra para Apagar Documentation
 * @Author             : Rafael Hadama
 * @Group              :
 * @Last Modified By   : Rafael Hadama
 * @Last Modified On   : 24/04/2020 18:26:00
 * @Modification Log   :
 * Ver       Date            Author              Modification
 * 1.0    17/12/2019   Rafael Hadama     Initial Version
 **/
public class T_MODEC_DeleteDocumentation_App {
   public static void deleteDocs()
   {
      try{
         Datetime NowMinus20minutes = datetime.now().addMinutes(-20);
         system.debug('NowMinus20minutes >' + NowMinus20minutes);
         list<TW1_Documentation__c> listDocDelete = [SELECT Id, CreatedDate, TW1_DocumentationAux__c FROM TW1_Documentation__c where TW1_DocumentationAux__c = true AND CreatedDate <: NowMinus20minutes limit 9980];

         Database.DeleteResult[] deleteResultList = Database.delete(listDocDelete, false);
      }
      catch (Exception e)
      {
         // Exception handling goes here....
         T_SDK_DebugLog.EscreverLog('Erro deletar Documentations mocks' + e.getMessage());
         T_SDK_DebugLog.EscreverLog('Erro ao deletar Documentation- stacktrace: ' + e.getStackTraceString());
      }
      finally{
         //Reschedular job.
         T_SDK_ScheaduleUtils.scheadule('T_MODEC_SCH_DeleteDocumentations', 10);
      }
   }
}