force-app/main/default/objects/TW1_Documentation__c/TW1_Documentation__c.object-meta.xml
<CustomObject>
    <label>Documentation</label>
    <nameField>
        <displayFormat>DOC{000000}</displayFormat>
        <label>Documentation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documentations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Documentation__c/fields/TW1_Interaction__c.field-meta.xml
<CustomField>
    <fullName>TW1_Interaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interaction</label>
    <referenceTo>TW1_Interaction__c</referenceTo>
    <relationshipLabel>Documentations</relationshipLabel>
    <relationshipName>Documentations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Documentation__c/fields/TW1_Request__c.field-meta.xml
<CustomField>
    <fullName>TW1_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request</label>
    <referenceTo>TW1_Request__c</referenceTo>
    <relationshipLabel>Documentations</relationshipLabel>
    <relationshipName>Documentations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Documentation__c/recordTypes/HSE_Audit.recordType-meta.xml
<RecordType>
    <fullName>HSE_Audit</fullName>
    <active>true</active>
    <label>HSE Audit</label>
</RecordType>

force-app/main/default/objects/TW1_Documentation__c/recordTypes/ReportIncidensInvestigation.recordType-meta.xml
<RecordType>
    <fullName>ReportIncidensInvestigation</fullName>
    <active>true</active>
    <description>Relatório de investigação de incidentes</description>
    <label>Report of Incidens Investigation</label>
</RecordType>

force-app/main/default/objects/TW1_Interaction__c/TW1_Interaction__c.object-meta.xml
<CustomObject>
    <label>Interaction</label>
    <nameField>
        <displayFormat>I-{000000}</displayFormat>
        <label>Interaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Interaction__c/fields/TW1_Status__c.field-meta.xml
<CustomField>
    <fullName>TW1_Status__c</fullName>
    <defaultValue>&quot;Open&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>In Validation By the Legal</fullName>
            </value>
            <value>
                <fullName>Validated Notification</fullName>
            </value>
            <value>
                <fullName>Awaiting Return</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>New Proposed Date</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved under restriction</fullName>
            </value>
            <value>
                <fullName>New incident treatment</fullName>
            </value>
            <value>
                <fullName>Sent incident to supplier</fullName>
            </value>
            <value>
                <fullName>Incident responded</fullName>
            </value>
            <value>
                <fullName>Awaiting evidence of treatment</fullName>
            </value>
            <value>
                <fullName>Evidence sent</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Incident treatment rejected</fullName>
            </value>
            <value>
                <fullName>Incident treatment approved</fullName>
            </value>
            <value>
                <fullName>Clarification Required</fullName>
            </value>
            <value>
                <fullName>Analyzing Audit Info</fullName>
            </value>
            <value>
                <fullName>Audit Scheduled</fullName>
            </value>
            <value>
                <fullName>Awaiting Action Plan</fullName>
            </value>
            <value>
                <fullName>Action Plan Evaluation</fullName>
            </value>
            <value>
                <fullName>Action Plan Validation</fullName>
            </value>
            <value>
                <fullName>Awaiting Evidences</fullName>
            </value>
            <value>
                <fullName>Evidences Sent</fullName>
            </value>
            <value>
                <fullName>Evidences Analyzed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Reproved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Interaction__c/recordTypes/TW1_Incidents.recordType-meta.xml
<RecordType>
    <fullName>TW1_Incidents</fullName>
    <active>true</active>
    <label>Incidents</label>
</RecordType>

force-app/main/default/objects/TW1_Request__c/TW1_Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>REQ{000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Status__c.field-meta.xml
<CustomField>
    <fullName>TW1_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Request__c/recordTypes/Inspection.recordType-meta.xml
<RecordType>
    <fullName>Inspection</fullName>
    <active>true</active>
    <label>Inspection</label>
</RecordType>

force-app/main/default/classes/T_MODEC_BAT_UpdateFilesVisibility.cls
/**
 * @description       : Batch job - to grant access to files for Community User - Only in Inspection(wave2)
 * @author            : Felipe Cardozo
 * @group             :
 * @last modified on  : 08-05-2020
 * @last modified by  : Felipe Cardozo
 * Modifications Log
 * Ver   Date         Author          Modification
 * 1.0   07-16-2020   Rafael Hadama   Initial Version
 **/
public class T_MODEC_BAT_UpdateFilesVisibility implements Database.Batchable<sObject> {
    //variable to hold the recordtypeId for use in query.
    public string InspectionRequestRecordtypeId;
    public string DocumentationRecordtypeId;
    public string InteractionRecordtypeId;
    public string DocumentationHSEAuditRTId;
    public T_MODEC_BAT_UpdateFilesVisibility()
    {
        this.InspectionRequestRecordtypeId = Schema.SObjectType.TW1_Request__c.getRecordTypeInfosByDeveloperName().get('Inspection').getRecordTypeId();
        this.DocumentationRecordtypeId = Schema.SObjectType.TW1_Documentation__c.getRecordTypeInfosByDeveloperName().get('ReportIncidensInvestigation').getRecordTypeId();
        this.InteractionRecordtypeId = Schema.SObjectType.TW1_Interaction__c.getRecordTypeInfosByDeveloperName().get('TW1_Incidents').getRecordTypeId();
        this.DocumentationHSEAuditRTId = Schema.SObjectType.TW1_Documentation__c.getRecordTypeInfosByDeveloperName().get('HSE_Audit').getRecordTypeId();
    }

    //Querying all documentation related to a request of recordtype Inspection and its open.
    public Database.QueryLocator start(Database.BatchableContext BC)
    {
        return Database.getQueryLocator([Select Id, Name, RecordTypeId, TW1_Request__c, TW1_Request__r.RecordtypeId, TW1_Request__r.TW1_Status__c from TW1_Documentation__c where (RecordtypeId =: DocumentationHSEAuditRTId) OR (TW1_Request__r.RecordtypeId = : InspectionRequestRecordtypeId AND TW1_Request__r.TW1_Status__c = 'Open') OR (TW1_Interaction__r.RecordtypeId =:InteractionRecordtypeId AND RecordTypeId=:DocumentationRecordtypeId AND TW1_Interaction__r.TW1_Status__c !='Incident treatment rejected' AND TW1_Interaction__r.TW1_Status__c !='Incident treatment approved')]);
    }

    public void execute(Database.BatchableContext  BC,
                        List<TW1_Documentation__c> scope)
    {
        system.debug('List of documentations queried >' + scope);
        //Creating list variable and assign ids, for use in the query of ContentDocumentLink
        List<String> DocIds = new List<string>();
        for (TW1_Documentation__c doc : scope)
        {
            DocIds.add(doc.Id);
        }

        //Query ContentDocumentLink related to documentations queried before
        List<ContentDocumentLink> listDocLinks = [SELECT Id, LinkedEntityId, ContentDocumentId, IsDeleted, SystemModstamp, ShareType, Visibility FROM ContentDocumentLink where LinkedEntityId IN :DocIds];
        system.debug('listDocLinks >>' + listDocLinks);
        system.debug('listDocLinks.size() >>' + listDocLinks.size());

        List<ContentDocumentLink> listDocLinksUpdate = new list<ContentDocumentLink>();
        //Granting visibility access to all users with documents related to documentation queried.
        for (ContentDocumentLink DocLink:listDocLinks) {
            
            if (DocLink.Visibility != 'AllUsers') {
                DocLink.Visibility = 'AllUsers';
                listDocLinksUpdate.add(DocLink);
            }
        }
        system.debug('listDocLinksUpdate >>' + listDocLinksUpdate);
        system.debug('listDocLinksUpdate.size() >>' + listDocLinksUpdate.size());
        update listDocLinksUpdate;
    }

    public void finish(Database.BatchableContext BC)
    {
        
      /*if (!Test.isRunningTest())
      {
        // Reagendar o processo para execução em 10 minutos
        T_SDK_DebugLog.EscreverLog('Reagendando schedule de update files visibility');
        T_SDK_ScheaduleUtils.scheadule('T_MODEC_SCH_UpdateFilesVisibility', 3);
      }*/
    }
}