force-app/main/default/objects/TW1_Documentation__c/TW1_Documentation__c.object-meta.xml
<CustomObject>
    <label>Documentation</label>
    <nameField>
        <displayFormat>DOC{000000}</displayFormat>
        <label>Documentation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documentations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Documentation__c/fields/TW1_Interaction__c.field-meta.xml
<CustomField>
    <fullName>TW1_Interaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interaction</label>
    <referenceTo>TW1_Interaction__c</referenceTo>
    <relationshipLabel>Documentations</relationshipLabel>
    <relationshipName>Documentations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Documentation__c/fields/TW1_Request__c.field-meta.xml
<CustomField>
    <fullName>TW1_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request</label>
    <referenceTo>TW1_Request__c</referenceTo>
    <relationshipLabel>Documentations</relationshipLabel>
    <relationshipName>Documentations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Interaction__c/TW1_Interaction__c.object-meta.xml
<CustomObject>
    <label>Interaction</label>
    <nameField>
        <displayFormat>I-{000000}</displayFormat>
        <label>Interaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Interaction__c/fields/TW3_From_Portal__c.field-meta.xml
<CustomField>
    <fullName>TW3_From_Portal__c</fullName>
    <label>From Portal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Senegal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Request__c/TW1_Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>REQ{000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Request__c/recordTypes/Inspection.recordType-meta.xml
<RecordType>
    <fullName>Inspection</fullName>
    <active>true</active>
    <label>Inspection</label>
</RecordType>

force-app/main/default/objects/TW1_Step__c/TW1_Step__c.object-meta.xml
<CustomObject>
    <label>Step</label>
    <nameField>
        <displayFormat>S{000000}</displayFormat>
        <label>Steps Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Step__c/fields/TW1_Interaction__c.field-meta.xml
<CustomField>
    <fullName>TW1_Interaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interaction</label>
    <referenceTo>TW1_Interaction__c</referenceTo>
    <relationshipLabel>Steps</relationshipLabel>
    <relationshipName>Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Step__c/fields/TW1_Request__c.field-meta.xml
<CustomField>
    <fullName>TW1_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request</label>
    <referenceTo>TW1_Request__c</referenceTo>
    <relationshipLabel>Steps</relationshipLabel>
    <relationshipName>Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/T_MODEC_UpdateFromPortal.cls
/**
 * @description       :
 * @author            : Rafael Hadama
 * @group             :
 * @last modified on  : 10-29-2020
 * @last modified by  : Rafael Hadama
 * Modifications Log
 * Ver   Date         Author          Modification
 * 1.0   10-29-2020   Rafael Hadama   Initial Version
 **/
global class T_MODEC_UpdateFromPortal implements Database.Batchable<sObject> {
    //variable to hold the recordtypeId for use in query.
    global string ObjectType;
    global T_MODEC_UpdateFromPortal(String objectToUpdate)
    {
        system.debug('sobject for batch >' + objectToUpdate);
        this.ObjectType = objectToUpdate;
    }

    //Querying all documentation related to a request of recordtype Inspection and its open.
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        string query = 'SELECT Id, RecordTypeId, TW3_From_Portal__c FROM ' + ObjectType + '  where TW3_From_Portal__c = null';

        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC,
                        List<Sobject>             scope)
    {
        system.debug('List of objects queried >' + scope);
        system.debug('sobject for batch >' + ObjectType);

        TriggerFactory.stopRequestTrigger = false;
        TriggerFactory.stopStepTrigger    = false;
        //update ctrlTriggers;
        if (ObjectType == 'TW1_Request__c')
        {
            list<TW1_Request__c> listreq = (list<TW1_Request__c>)scope;
            for (TW1_Request__c req:listreq)
            {
                req.TW3_From_Portal__c = 'Brazil';
            }
            system.debug('listreq >' + listreq);
            update listreq;
        }
        else if (ObjectType == 'TW1_Step__c')
        {
            system.debug('Step batch >');
            list<TW1_Step__c> liststep = (list<TW1_Step__c>)scope;
            for (TW1_Step__c req:liststep)
            {
                req.TW3_From_Portal__c = 'Brazil';
            }
            system.debug('liststep >' + liststep);
            update liststep;
        }
        else if (ObjectType == 'TW1_Documentation__c')
        {
            list<TW1_Documentation__c> listdoc = (list<TW1_Documentation__c>)scope;
            for (TW1_Documentation__c req:listdoc)
            {
                req.TW3_From_Portal__c = 'Brazil';
            }
            system.debug('listdoc >' + listdoc);
            update listdoc;
        }
        else if (ObjectType == 'TW1_Interaction__c')
        {
            list<TW1_Interaction__c> listint = (list<TW1_Interaction__c>)scope;
            for (TW1_Interaction__c req:listint)
            {
                req.TW3_From_Portal__c = 'Brazil';
            }
            system.debug('listint >' + listint);
            update listint;
        }
    }

    global void finish(Database.BatchableContext BC)
    {
        system.debug('Final do batch');
    }
}