force-app/main/default/objects/TW1_Documentation__c/TW1_Documentation__c.object-meta.xml
<CustomObject>
    <label>Documentation</label>
    <nameField>
        <displayFormat>DOC{000000}</displayFormat>
        <label>Documentation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documentations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Documentation__c/fields/TW1_Request__c.field-meta.xml
<CustomField>
    <fullName>TW1_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request</label>
    <referenceTo>TW1_Request__c</referenceTo>
    <relationshipLabel>Documentations</relationshipLabel>
    <relationshipName>Documentations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Documentation__c/recordTypes/TW1_Inspection_Documentation.recordType-meta.xml
<RecordType>
    <fullName>TW1_Inspection_Documentation</fullName>
    <active>true</active>
    <label>Inspection Documentation</label>
</RecordType>

force-app/main/default/objects/TW1_Request__c/TW1_Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>REQ{000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Inspection_Status__c.field-meta.xml
<CustomField>
    <fullName>TW1_Inspection_Status__c</fullName>
    <label>Inspection Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TW1_Inspection_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/TW1_Inspection_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Inspection Rescheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Reproved</fullName>
    </customValue>
    <customValue>
        <fullName>Awaiting Date Confirmation</fullName>
    </customValue>
    <customValue>
        <fullName>Verifying Date Availability</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>Inspection Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Rescheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <customValue>
        <fullName>Emergency Inspection</fullName>
    </customValue>
    <customValue>
        <fullName>Not Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Approved with Restriction</fullName>
    </customValue>
    <masterLabel>Inspection Status</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/T_DocumentationREP.cls
/**
* @description       :
* @author            : Hugo Brito
* @group             :
* @last modified on  : 05-10-2021
* @last modified by  : Hugo Brito
* Modifications Log
* Ver   Date         Author       Modification
* 1.0   05-10-2021   Hugo Brito   Criação da classe
**/
public class T_DocumentationREP {
    
    public static List<TW1_Documentation__c> getInspectionDocumentation(Set<String> ids) {     
                
        return [select id from TW1_Documentation__c 
                where id in: ids and 
                RecordType.DeveloperName = 'TW1_Inspection_Documentation' and 
                (TW1_Request__r.TW1_Inspection_Status__c = 'Approved' or 
                TW1_Request__r.TW1_Inspection_Status__c = 'Approved with Restriction' or
                TW1_Request__r.TW1_Inspection_Status__c = 'Canceled' or
                TW1_Request__r.TW1_Inspection_Status__c = 'Rejected' or
                TW1_Request__r.TW1_Inspection_Status__c = 'Reproved')
               ];
        
    }
    
    public static Map<id, TW1_Documentation__c> getInspectionDocumentationMap(Set<String> ids) {        
        return new Map<id, TW1_Documentation__c>([select id from TW1_Documentation__c 
                where id in: ids and 
                RecordType.DeveloperName = 'TW1_Inspection_Documentation' and 
                (TW1_Request__r.TW1_Inspection_Status__c = 'Approved' or 
                TW1_Request__r.TW1_Inspection_Status__c = 'Approved with Restriction' or
                TW1_Request__r.TW1_Inspection_Status__c = 'Canceled' or
                TW1_Request__r.TW1_Inspection_Status__c = 'Rejected' or
                TW1_Request__r.TW1_Inspection_Status__c = 'Reproved')
               ]); 
    }
}