force-app/main/default/objects/TW1_Documentation__c/TW1_Documentation__c.object-meta.xml
<CustomObject>
    <label>Documentation</label>
    <nameField>
        <displayFormat>DOC{000000}</displayFormat>
        <label>Documentation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documentations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Documentation__c/fields/TW1_Request__c.field-meta.xml
<CustomField>
    <fullName>TW1_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request</label>
    <referenceTo>TW1_Request__c</referenceTo>
    <relationshipLabel>Documentations</relationshipLabel>
    <relationshipName>Documentations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TW1_Documentation__c/recordTypes/TW1_Inspection_Documentation.recordType-meta.xml
<RecordType>
    <fullName>TW1_Inspection_Documentation</fullName>
    <active>true</active>
    <label>Inspection Documentation</label>
</RecordType>

force-app/main/default/objects/TW1_Request__c/TW1_Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>REQ{000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Request__c/fields/TW1_Inspection_Status__c.field-meta.xml
<CustomField>
    <fullName>TW1_Inspection_Status__c</fullName>
    <label>Inspection Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TW1_Inspection_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TW1_Request__c/recordTypes/Inspection.recordType-meta.xml
<RecordType>
    <fullName>Inspection</fullName>
    <active>true</active>
    <label>Inspection</label>
</RecordType>

force-app/main/default/globalValueSets/TW1_Inspection_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Inspection Rescheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Reproved</fullName>
    </customValue>
    <customValue>
        <fullName>Awaiting Date Confirmation</fullName>
    </customValue>
    <customValue>
        <fullName>Verifying Date Availability</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>Inspection Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Rescheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <customValue>
        <fullName>Emergency Inspection</fullName>
    </customValue>
    <customValue>
        <fullName>Not Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Approved with Restriction</fullName>
    </customValue>
    <masterLabel>Inspection Status</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/T_MODEC_ContentDocumentApp.cls
/**
* @description       :
* @author            : Rafael Hadama
* @group             :
* @last modified on  : 10-08-2020
* @last modified by  : Saulo Silva
* Modifications Log
* Ver   Date         Author          Modification
* 1.0   09-21-2020   Rafael Hadama   Initial Version
**/
public class T_MODEC_ContentDocumentApp {
    /**
* @description Method that validates if the file is related to a documentation related to an inspection request.
* @author Rafael Hadama | 09-21-2020
**/
    public static void ValidateDeletedDocument(Map<Id, ContentDocument> mapaContentDocuments) {
        //Validar se o usuario é guest. senão return
        
        //Buscar pelo ContentDocument id, com quais objetos ele está relacionado.
        //Caso esteja relacionado a uma documentation, validar se está relacionado a uma request do tipo inspection
        //caso sim - impedir com aviso de sem permissão.
        
        User oUser = T_UserRep.getLoggedUser();       
        
        Set<String> ContentDocumentsIds = T_Utils.getSetIds(mapaContentDocuments.values(), 'Id');
        Id rt = Schema.SObjectType.TW1_Documentation__c.getRecordTypeInfosByDeveloperName().get('TW1_Inspection_Documentation').getRecordTypeId();
        List<ContentDocumentLink> cdl = [SELECT Id, LinkedEntityId, ShareType, ContentDocumentId FROM ContentDocumentLink where ContentDocumentId in: ContentDocumentsIds];
        
        if(oUser.Profile.UserLicense.Name == 'External Apps') {
            IF(cdl.size() > 0) {
                Set<String> vIdsLinkedEntityId = T_Utils.getSetIds(cdl, 'LinkedEntityId');
                Set<String> documentationIds = new Set<String>();
                
                for(String recordId: vIdsLinkedEntityId){
                    Id sId = recordId;
                    String sobjectType = sId.getSObjectType().getDescribe().getName();
                    
                    IF(sobjectType == 'TW1_Documentation__c'){
                        documentationIds.add(recordId);
                    }
                }
                
                IF(documentationIds.size() > 0){
                    List<TW1_Documentation__c> oDocumentacao = new List<TW1_Documentation__c>();
                    oDocumentacao = [SELECT ID, RecordTypeId, TW1_Request__r.TW1_Inspection_Status__c FROM TW1_Documentation__c WHERE RecordTypeId =: rt and ID IN: documentationIds];
                    
                    if (oDocumentacao.size() > 0) {
                        for(ContentDocumentLink recordLink: cdl){
                            IF(documentationIds.contains(recordLink.LinkedEntityId) && mapaContentDocuments.containsKey(recordLink.ContentDocumentId)){
                                SObject obj = mapaContentDocuments.get(recordLink.ContentDocumentId);
                                obj.addError('Não é possível deletar o arquivo da inspeção. Por favor, entre em contato com a Modec.');
                            }
                        }
                    }
                }
            }
        }
    }
}