force-app/main/default/objects/LetterGroup__c/LetterGroup__c.object-meta.xml
<CustomObject>
    <label>Letter Group</label>
    <nameField>
        <displayFormat>LG-{00000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Letter Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LetterGroup__c/fields/Vessel__c.field-meta.xml
<CustomField>
    <fullName>Vessel__c</fullName>
    <label>Vessel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LetterGroup__c/recordTypes/Vessel.recordType-meta.xml
<RecordType>
    <fullName>Vessel</fullName>
    <active>true</active>
    <label>Vessel</label>
</RecordType>

force-app/main/default/objects/LetterGroupVesselAssociation__c/LetterGroupVesselAssociation__c.object-meta.xml
<CustomObject>
    <label>Letter Group Vessel Association</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Letter Group Vessel Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LetterGroupVesselAssociation__c/fields/LetterGroup__c.field-meta.xml
<CustomField>
    <fullName>LetterGroup__c</fullName>
    <label>Letter Group</label>
    <referenceTo>LetterGroup__c</referenceTo>
    <relationshipLabel>Letter Group Vessel Associations</relationshipLabel>
    <relationshipName>LetterGroupVesselAssociationsLetterGroup</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LetterGroupVesselAssociation__c/fields/Vessel__c.field-meta.xml
<CustomField>
    <fullName>Vessel__c</fullName>
    <label>Vessel</label>
    <referenceTo>Vessel__c</referenceTo>
    <relationshipLabel>Letter Group Vessel Associations</relationshipLabel>
    <relationshipName>LetterGroupVesselAssociationsVessel</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Vessel__c/Vessel__c.object-meta.xml
<CustomObject>
    <label>Vessel</label>
    <nameField>
        <label>Vessel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vessels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TriggerHandlerLGVAssociationTest.cls
@isTest
public class TriggerHandlerLGVAssociationTest {
    
    @isTest
    public static void handlerTest()
    {
        LetterGroup__c letterGroup = TestUtil.createLetterGroup();
        Vessel__c vessel = TestUtil.createVessel2();

        LetterGroupVesselAssociation__c letterGroupAssoc = new LetterGroupVesselAssociation__c();
        letterGroupAssoc.LetterGroup__c = letterGroup.Id;
        letterGroupAssoc.Vessel__c = vessel.Id;

        Test.startTest();

        insert letterGroupAssoc;
        update letterGroupAssoc;
               
        Test.stopTest();
    }

    @isTest
    public static void handlerDelete()
    {

        LetterGroup__c letterGroup = TestUtil.createLetterGroup();
        Vessel__c vessel = TestUtil.createVessel2();

        LetterGroupVesselAssociation__c letterGroupAssoc = new LetterGroupVesselAssociation__c();
        letterGroupAssoc.LetterGroup__c = letterGroup.Id;
        letterGroupAssoc.Vessel__c = vessel.Id;
        insert letterGroupAssoc;

        Test.startTest();

        List<LetterGroupVesselAssociation__c> lstAssoc = [SELECT Id, Vessel__c FROM LetterGroupVesselAssociation__c WHERE Id =: letterGroupAssoc.Id];

        delete lstAssoc;
        
        Test.stopTest();
    }

    @isTest
    public static void boDelete()
    {
        LetterGroup__c letterGroup = TestUtil.createLetterGroup();
        Vessel__c vessel = TestUtil.createVessel2();
        List<LetterGroupVesselAssociation__c> lstAssoc = new List<LetterGroupVesselAssociation__c>();
        Map<Id, LetterGroupVesselAssociation__c> mapAssoc = new Map<Id, LetterGroupVesselAssociation__c>();

        LetterGroupVesselAssociation__c letterGroupAssoc = new LetterGroupVesselAssociation__c();
        letterGroupAssoc.LetterGroup__c = letterGroup.Id;
        letterGroupAssoc.Vessel__c = vessel.Id;
        insert letterGroupAssoc;

        lstAssoc.add(letterGroupAssoc);
        mapAssoc.put(letterGroupAssoc.Id, letterGroupAssoc);

        Test.startTest();
        
        LGVAssociationBO.getInstance().FillVesselName(lstAssoc, mapAssoc);
        
        Test.stopTest();
    }
}