force-app/main/default/objects/LetterGroup__c/LetterGroup__c.object-meta.xml
<CustomObject>
    <label>Letter Group</label>
    <nameField>
        <displayFormat>LG-{00000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Letter Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LetterGroup__c/fields/Vessel__c.field-meta.xml
<CustomField>
    <fullName>Vessel__c</fullName>
    <label>Vessel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LetterGroup__c/recordTypes/Vessel.recordType-meta.xml
<RecordType>
    <fullName>Vessel</fullName>
    <active>true</active>
    <label>Vessel</label>
</RecordType>

force-app/main/default/objects/LetterGroupVesselAssociation__c/LetterGroupVesselAssociation__c.object-meta.xml
<CustomObject>
    <label>Letter Group Vessel Association</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Letter Group Vessel Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LetterGroupVesselAssociation__c/fields/LetterGroup__c.field-meta.xml
<CustomField>
    <fullName>LetterGroup__c</fullName>
    <label>Letter Group</label>
    <referenceTo>LetterGroup__c</referenceTo>
    <relationshipLabel>Letter Group Vessel Associations</relationshipLabel>
    <relationshipName>LetterGroupVesselAssociationsLetterGroup</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LetterGroupVesselAssociation__c/fields/Vessel__c.field-meta.xml
<CustomField>
    <fullName>Vessel__c</fullName>
    <label>Vessel</label>
    <referenceTo>Vessel__c</referenceTo>
    <relationshipLabel>Letter Group Vessel Associations</relationshipLabel>
    <relationshipName>LetterGroupVesselAssociationsVessel</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Vessel__c/Vessel__c.object-meta.xml
<CustomObject>
    <label>Vessel</label>
    <nameField>
        <label>Vessel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vessels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/LGVAssociationBO.cls
public with sharing class LGVAssociationBO {
    

    private static final LGVAssociationBO instance = new LGVAssociationBO();


    public static LGVAssociationBO getInstance() {
		return instance;
    }

    public void FillVesselName(List<LetterGroupVesselAssociation__c> lstLGVAssociation, Map<Id, LetterGroupVesselAssociation__c> oldMap){

        List<LetterGroup__c> lstLetterGroup = new List<LetterGroup__c>();
        List<LetterGroupVesselAssociation__c> lstLetterGroupVessels = new List<LetterGroupVesselAssociation__c>();
        List<LetterGroup__c> lstUpdate = new List<LetterGroup__c>();
        set<Id> idLetterGroup = new set<Id>();
        String vessel = '';
        Integer contador = 0;
    
        if(oldMap == null){

            for(LetterGroupVesselAssociation__c lst : lstLGVAssociation){

                if(!lstLGVAssociation.isEmpty()){
                    idLetterGroup.add(lst.LetterGroup__c);
                }

            }

            lstLetterGroup = LetterGroupDAO.getLetterGroupBySetId(idLetterGroup);
            lstLetterGroupVessels = LetterGroupVesselAssociationDAO.getLetterGroupVesselById(idLetterGroup);
            system.debug( 'lstLetterGroup: '+ lstLetterGroup );

            for(LetterGroupVesselAssociation__c lstLGV : lstLetterGroupVessels){

                for(LetterGroup__c lstLG : lstLetterGroup){
            
                    if(contador == 0){
                    lstLG.Vessel__c = '';
                    }
                    lstLG.Vessel__c = lstLG.Vessel__c + ' ' + lstLGV.VesselShortName__c;
                    //lstUpdate.add(lstLG); 
                    vessel = lstLG.Vessel__c;
                    contador ++;
                    
                }
            }

            system.System.debug('LIST UPDATE ' + lstUpdate);
            LetterGroup__c letterGroup = new LetterGroup__c();
            letterGroup = lstLetterGroup[0];
            letterGroup.Vessel__c = vessel;
            update letterGroup;
    } else 
    {
        String letterGroup = oldMap.values().LetterGroup__c;
        idLetterGroup.add(letterGroup);

        lstLetterGroup = LetterGroupDAO.getLetterGroupBySetId(idLetterGroup);
        lstLetterGroupVessels = LetterGroupVesselAssociationDAO.getLetterGroupVesselById(idLetterGroup);
        system.debug( 'lstLetterGroup: '+ lstLetterGroup );

        for(LetterGroupVesselAssociation__c lstLGV : lstLetterGroupVessels){

            for(LetterGroup__c lstLG : lstLetterGroup){
            
                if(contador == 0){
                    lstLG.Vessel__c = '';
                }
                    lstLG.Vessel__c = lstLG.Vessel__c + ' ' + lstLGV.VesselShortName__c;
                    //lstUpdate.add(lstLG); 
                    vessel = lstLG.Vessel__c;
                    contador ++;
            }
        }

            system.System.debug('LIST UPDATE ' + lstUpdate);
            LetterGroup__c letterGroupDelete = new LetterGroup__c();
            letterGroupDelete = lstLetterGroup[0];
            letterGroupDelete.Vessel__c = vessel;
            update letterGroupDelete;
        } 
    }  
}