force-app/main/default/objects/LetterGroup__c/LetterGroup__c.object-meta.xml
<CustomObject>
    <label>Letter Group</label>
    <nameField>
        <displayFormat>LG-{00000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Letter Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LetterGroup__c/fields/Vessel__c.field-meta.xml
<CustomField>
    <fullName>Vessel__c</fullName>
    <label>Vessel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LetterGroupVesselAssociation__c/LetterGroupVesselAssociation__c.object-meta.xml
<CustomObject>
    <label>Letter Group Vessel Association</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Letter Group Vessel Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LetterGroupVesselAssociation__c/fields/LetterGroup__c.field-meta.xml
<CustomField>
    <fullName>LetterGroup__c</fullName>
    <label>Letter Group</label>
    <referenceTo>LetterGroup__c</referenceTo>
    <relationshipLabel>Letter Group Vessel Associations</relationshipLabel>
    <relationshipName>LetterGroupVesselAssociationsLetterGroup</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LetterGroupVesselAssociation__c/fields/Vessel__c.field-meta.xml
<CustomField>
    <fullName>Vessel__c</fullName>
    <label>Vessel</label>
    <referenceTo>Vessel__c</referenceTo>
    <relationshipLabel>Letter Group Vessel Associations</relationshipLabel>
    <relationshipName>LetterGroupVesselAssociationsVessel</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Vessel__c/Vessel__c.object-meta.xml
<CustomObject>
    <label>Vessel</label>
    <nameField>
        <label>Vessel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vessels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/LetterGroupVesselAssociationDAO.cls
public with sharing class LetterGroupVesselAssociationDAO {
    
    public static List<LetterGroupVesselAssociation__c> getLetterGroupVesselById(String idGroup) {
        return [SELECT 
                    Id,
                    Vessel__c
                    FROM
                    LetterGroupVesselAssociation__c
                    WHERE
                    LetterGroup__c =: idGroup];
    }

    public static List<LetterGroupVesselAssociation__c> getLetterGroupVesselById(set<Id> setIdGroup) {
        return [SELECT 
                    Id,
                    VesselShortName__c,
                    Vessel__c
                    FROM
                    LetterGroupVesselAssociation__c
                    WHERE
                    LetterGroup__c IN: setIdGroup];
    }
}