force-app/main/default/objects/Backcharge__c/Backcharge__c.object-meta.xml
<CustomObject>
    <label>Backcharge</label>
    <nameField>
        <displayFormat>B-{00000}</displayFormat>
        <label>Backcharge Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Backcharges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Backcharge__c/fields/ChargedAmountBRL__c.field-meta.xml
<CustomField>
    <fullName>ChargedAmountBRL__c</fullName>
    <label>Charged Amount (BRL)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Backcharge__c/fields/ChargedAmountSumUSD__c.field-meta.xml
<CustomField>
    <fullName>ChargedAmountSumUSD__c</fullName>
    <label>Charged Amount Sum (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Backcharge__c/fields/ChargedAmountUSD__c.field-meta.xml
<CustomField>
    <fullName>ChargedAmountUSD__c</fullName>
    <label>Charged Amount (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Backcharge__c/fields/TotalAmountBRL__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountBRL__c</fullName>
    <label>Total Amount (BRL)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Backcharge__c/fields/TotalAmountSumUSD__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountSumUSD__c</fullName>
    <label>Total Amount Sum (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BackchargeBO.cls
public with sharing class BackchargeBO {
    
    private static final BackchargeBO instance = new BackchargeBO();

	public static BackchargeBO getInstance() {
		return instance;
    }

    public void calculateDollar (List<Backcharge__c> lstBackcharge)
    {
        Double actualDollar = Double.valueOf(Label.ActualDollar);

        for(Backcharge__c backcharge : lstBackcharge)
        {
            if(backcharge.ChargedAmountBRL__c == null)
                backcharge.ChargedAmountBRL__c = 0;
            
            if(backcharge.ChargedAmountUSD__c == null)
                backcharge.ChargedAmountUSD__c = 0;

            if(backcharge.TotalAmountBRL__c == null)
                backcharge.TotalAmountBRL__c = 0;
            
            if(backcharge.TotalAmountUSD__c == null)
                backcharge.TotalAmountUSD__c = 0;            

            backcharge.ChargedAmountSumUSD__c = (backcharge.ChargedAmountBRL__c/actualDollar) + backcharge.ChargedAmountUSD__c;
            backcharge.TotalAmountSumUSD__c = (backcharge.TotalAmountBRL__c/actualDollar) + backcharge.TotalAmountUSD__c;
        }
    }
}