force-app/main/default/objects/BM_Item__c/BM_Item__c.object-meta.xml
<CustomObject>
    <label>BM Service Line</label>
    <nameField>
        <displayFormat>Item-{000000}</displayFormat>
        <label>BM Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BM Service Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BM_Item__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <label>Request</label>
    <referenceTo>TW1_Request__c</referenceTo>
    <relationshipName>BM_Itens</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/TW1_Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>REQ{000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Request__c/fields/TW1_BM_Reference_Number_in_SAP_MODEC__c.field-meta.xml
<CustomField>
    <fullName>TW1_BM_Reference_Number_in_SAP_MODEC__c</fullName>
    <inlineHelpText>This field is read-only. Do not try to fill it.</inlineHelpText>
    <label>BM Reference Number in SAP MODEC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/T_MODEC_BMItem_App.cls
/**
 * @File Name          : T_MODEC_BMItem_App.cls
 * @Description        : Application for the handler of the BM_Item__c object
 * @Author             : Rafael Hadama
 * @Group              :
 * @Last Modified By   : Rafael Hadama
 * @Last Modified On   : 30/03/2020 17:04:12
 * @Modification Log   :
 * Ver       Date            Author              Modification
 * 1.0    30/03/2020   Rafael Hadama     Initial Version
 **/
public class T_MODEC_BMItem_App {
   public static void AvoidDeleteOfBMItem(BM_Item__c deletedBMItem)
   {
      T_SDK_DebugLog.EscreverLog('Entrou no metodo "AvoidDeleteOfBMItem"');

      //realizar query no request(BM) relacionado, para validar se possui numero de folha criada.
      //SELECT Id, Name, Request__c FROM BM_Item__c
      TW1_Request__c RelatedBM = [SELECT Id, TW1_BM_Reference_Number_in_SAP_MODEC__c FROM TW1_Request__c where Id =:deletedBMItem.Request__c];

      if (RelatedBM.TW1_BM_Reference_Number_in_SAP_MODEC__c != null)
      {
         String currentuserId   = UserInfo.getUserId();
         User   currentUserInfo = [select LanguageLocaleKey from User where Id = :UserInfo.getUserId()];
         if (currentUserInfo.LanguageLocaleKey == 'pt_BR')
         {
            deletedBMItem.addError('Não é possivel deletar um linha de item relacionado a um BM já criado no MODEC-SAP');
         }
         else
         {
            deletedBMItem.addError('You cannot delete a BM Service Line related to a BM already created in MODEC-SAP');
         }
      }
      //Caso sim soltar erro.
   }
}