force-app/main/default/objects/BM_Item__c/BM_Item__c.object-meta.xml
<CustomObject>
    <label>BM Service Line</label>
    <nameField>
        <displayFormat>Item-{000000}</displayFormat>
        <label>BM Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BM Service Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BM_Item__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <label>Request</label>
    <referenceTo>TW1_Request__c</referenceTo>
    <relationshipName>BM_Itens</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BM_Item__c/fields/T_Quantity__c.field-meta.xml
<CustomField>
    <fullName>T_Quantity__c</fullName>
    <label>Quantity</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BM_Item__c/fields/TW1_Gross_Value__c.field-meta.xml
<CustomField>
    <fullName>TW1_Gross_Value__c</fullName>
    <label>Unit Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BM_Item__c/fields/TW1_Service_Line__c.field-meta.xml
<CustomField>
    <fullName>TW1_Service_Line__c</fullName>
    <label>Service Line Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BM_Item__c/fields/TW1_Total__c.field-meta.xml
<CustomField>
    <fullName>TW1_Total__c</fullName>
    <formula>TW1_Gross_Value__c *  T_Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/TW1_Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>REQ{000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TW1_Request__c/fields/T_Quantity__c.field-meta.xml
<CustomField>
    <fullName>T_Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TW1_Request__c/fields/TW1_BM_Reference_Number_in_SAP_MODEC__c.field-meta.xml
<CustomField>
    <fullName>TW1_BM_Reference_Number_in_SAP_MODEC__c</fullName>
    <inlineHelpText>This field is read-only. Do not try to fill it.</inlineHelpText>
    <label>BM Reference Number in SAP MODEC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/T_MODEC_BMItem_TST.cls
/**
 * @File Name          : T_MODEC_BMItem_TST.cls
 * @Description        :
 * @Author             : Rafael Hadama
 * @Group              :
 * @Last Modified By   : Rafael Hadama
 * @Last Modified On   : 30/03/2020 17:39:23
 * @Modification Log   :
 * Ver       Date            Author              Modification
 * 1.0    30/03/2020   Rafael Hadama     Initial Version
 **/
@isTest
public class T_MODEC_BMItem_TST {
   @isTest
   public static void deleteServiceLineTst()
   {
      T_MODEC_Request_App_TST.criarCustomSettings();

      TW1_Request__c requestTest1 = T_MODEC_Request_App_TST.criarRegistroMock();     //Trigger 1
      requestTest1.TW1_BM_Reference_Number_in_SAP_MODEC__c = '1234567898';
      update requestTest1;
      //SELECT Id, TW1_Service_Line__c, T_Quantity__c, TW1_Gross_Value__c, TW1_Total__c FROM BM_Item__c
      BM_Item__c BMItemMock = new BM_Item__c();
      BMItemMock.Request__c          = requestTest1.Id;
      BMItemMock.TW1_Service_Line__c = '10';
      BMItemMock.T_Quantity__c       = 1;
      BMItemMock.TW1_Gross_Value__c  = 1;
      insert BMItemMock;

      try{
         delete BMItemMock;
      }
      catch (Exception e)
      {
         string mensagem        = e.getMessage();
         String currentuserId   = UserInfo.getUserId();
         User   currentUserInfo = [select LanguageLocaleKey from User where Id = :UserInfo.getUserId()];
         if (currentUserInfo.LanguageLocaleKey == 'pt_BR')
         {
            system.assert (mensagem.contains('Não é possivel deletar um linha de item relacionado a um BM já criado no MODEC-SAP'));
         }
         else
         {
            system.assert (mensagem.contains('You cannot delete a BM Service Line related to a BM already created in MODEC-SAP'));
         }
      }
   }
}