force-app/main/default/objects/BM_Item__c/BM_Item__c.object-meta.xml
<CustomObject>
    <label>BM Service Line</label>
    <nameField>
        <displayFormat>Item-{000000}</displayFormat>
        <label>BM Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BM Service Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BM_Item__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <label>Request</label>
    <referenceTo>TW1_Request__c</referenceTo>
    <relationshipName>BM_Itens</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BM_Item__c/fields/T_Quantity__c.field-meta.xml
<CustomField>
    <fullName>T_Quantity__c</fullName>
    <label>Quantity</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BM_Item__c/fields/TW1_Gross_Value__c.field-meta.xml
<CustomField>
    <fullName>TW1_Gross_Value__c</fullName>
    <label>Unit Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BM_Item__c/fields/TW1_Service_Line__c.field-meta.xml
<CustomField>
    <fullName>TW1_Service_Line__c</fullName>
    <label>Service Line Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BM_Item__c/fields/TW1_Total__c.field-meta.xml
<CustomField>
    <fullName>TW1_Total__c</fullName>
    <formula>TW1_Gross_Value__c *  T_Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/T_MODEC_BMItem_REP.cls
/**
 * @File Name          : T_MODEC_BMItem_REP.cls
 * @Description        : Classe REP do objeto BM_Item__c
 * @Author             : Rafael Hadama
 * @Group              :
 * @Last Modified By   : Rafael Hadama
 * @Last Modified On   : 20/04/2020 20:15:29
 * @Modification Log   :
 * Ver       Date            Author              Modification
 * 1.0    20/04/2020   Rafael Hadama     Initial Version
 **/
public class T_MODEC_BMItem_REP {
   public list<BM_Item__c> getRequestBMStatus(string requestId)
   {
      list<BM_Item__c> listBmItens = [SELECT Id, Request__c, TW1_Gross_Value__c, TW1_Service_Line__c, TW1_Total__c, T_Quantity__c FROM BM_Item__c where Request__c =:requestid];

      return listBmItens;
   }
}