force-app/main/default/objects/TW1_End_Fiscal_Period__c/TW1_End_Fiscal_Period__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>End Fiscal Period</label>
</CustomObject>

force-app/main/default/objects/TW1_End_Fiscal_Period__c/fields/TW1_APR_END__c.field-meta.xml
<CustomField>
    <fullName>TW1_APR_END__c</fullName>
    <label>APR END</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TW1_End_Fiscal_Period__c/fields/TW1_APR_INI__c.field-meta.xml
<CustomField>
    <fullName>TW1_APR_INI__c</fullName>
    <label>APR INI</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TW1_End_Fiscal_Period__c/fields/TW1_AUG_END__c.field-meta.xml
<CustomField>
    <fullName>TW1_AUG_END__c</fullName>
    <label>AUG END</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TW1_End_Fiscal_Period__c/fields/TW1_AUG_INI__c.field-meta.xml
<CustomField>
    <fullName>TW1_AUG_INI__c</fullName>
    <label>AUG INI</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TW1_End_Fiscal_Period__c/fields/TW1_DEC_END__c.field-meta.xml
<CustomField>
    <fullName>TW1_DEC_END__c</fullName>
    <label>DEC END</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TW1_End_Fiscal_Period__c/fields/TW1_DEC_INI__c.field-meta.xml
<CustomField>
    <fullName>TW1_DEC_INI__c</fullName>
    <label>DEC INI</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TW1_End_Fiscal_Period__c/fields/TW1_FEB_END__c.field-meta.xml
<CustomField>
    <fullName>TW1_FEB_END__c</fullName>
    <label>FEB END</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TW1_End_Fiscal_Period__c/fields/TW1_FEB_INI__c.field-meta.xml
<CustomField>
    <fullName>TW1_FEB_INI__c</fullName>
    <label>FEB INI</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TW1_End_Fiscal_Period__c/fields/TW1_JAN_END__c.field-meta.xml
<CustomField>
    <fullName>TW1_JAN_END__c</fullName>
    <label>JAN END</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TW1_End_Fiscal_Period__c/fields/TW1_JAN_INI__c.field-meta.xml
<CustomField>
    <fullName>TW1_JAN_INI__c</fullName>
    <label>JAN INI</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TW1_End_Fiscal_Period__c/fields/TW1_JUL_END__c.field-meta.xml
<CustomField>
    <fullName>TW1_JUL_END__c</fullName>
    <label>JUL END</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TW1_End_Fiscal_Period__c/fields/TW1_JUL_INI__c.field-meta.xml
<CustomField>
    <fullName>TW1_JUL_INI__c</fullName>
    <label>JUL INI</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TW1_End_Fiscal_Period__c/fields/TW1_JUN_END__c.field-meta.xml
<CustomField>
    <fullName>TW1_JUN_END__c</fullName>
    <label>JUN END</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TW1_End_Fiscal_Period__c/fields/TW1_JUN_INI__c.field-meta.xml
<CustomField>
    <fullName>TW1_JUN_INI__c</fullName>
    <label>JUN_INI</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TW1_End_Fiscal_Period__c/fields/TW1_MAR_END__c.field-meta.xml
<CustomField>
    <fullName>TW1_MAR_END__c</fullName>
    <label>MAR END</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TW1_End_Fiscal_Period__c/fields/TW1_MAR_INI__c.field-meta.xml
<CustomField>
    <fullName>TW1_MAR_INI__c</fullName>
    <label>MAR_INI</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TW1_End_Fiscal_Period__c/fields/TW1_MAY_END__c.field-meta.xml
<CustomField>
    <fullName>TW1_MAY_END__c</fullName>
    <label>MAY END</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TW1_End_Fiscal_Period__c/fields/TW1_MAY_INI__c.field-meta.xml
<CustomField>
    <fullName>TW1_MAY_INI__c</fullName>
    <label>MAY_INI</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TW1_End_Fiscal_Period__c/fields/TW1_NOV_END__c.field-meta.xml
<CustomField>
    <fullName>TW1_NOV_END__c</fullName>
    <label>NOV END</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TW1_End_Fiscal_Period__c/fields/TW1_NOV_INI__c.field-meta.xml
<CustomField>
    <fullName>TW1_NOV_INI__c</fullName>
    <label>NOV_INI</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TW1_End_Fiscal_Period__c/fields/TW1_OCT_END__c.field-meta.xml
<CustomField>
    <fullName>TW1_OCT_END__c</fullName>
    <label>OCT END</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TW1_End_Fiscal_Period__c/fields/TW1_OCT_INI__c.field-meta.xml
<CustomField>
    <fullName>TW1_OCT_INI__c</fullName>
    <label>OCT_INI</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TW1_End_Fiscal_Period__c/fields/TW1_SEP_END__c.field-meta.xml
<CustomField>
    <fullName>TW1_SEP_END__c</fullName>
    <label>SEP END</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TW1_End_Fiscal_Period__c/fields/TW1_SEP_INI__c.field-meta.xml
<CustomField>
    <fullName>TW1_SEP_INI__c</fullName>
    <label>SEP_INI</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/T_MODEC_CustomSettingsRep.cls
/**
 * @File Name          : T_MODEC_CustomSettingsRep.cls
 * @Description        : 
 * @Author             : Rafael Hadama
 * @Group              : 
 * @Last Modified By   : Rafael Hadama
 * @Last Modified On   : 10/02/2020 13:13:45
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    28/01/2020   Rafael Hadama     Initial Version
**/
public class T_MODEC_CustomSettingsRep {

    public TW1_End_Fiscal_Period__c GetFiscalPeriodDates(){

        TW1_End_Fiscal_Period__c CustomFiscalPeriodDates = [SELECT Id, Name, TW1_JAN_INI__c, TW1_FEB_INI__c, TW1_MAR_INI__c, TW1_APR_INI__c, TW1_MAY_INI__c, TW1_JUN_INI__c, TW1_JUL_INI__c, TW1_AUG_INI__c, TW1_SEP_INI__c, TW1_OCT_INI__c, TW1_NOV_INI__c, TW1_DEC_INI__c, TW1_JAN_END__c, TW1_FEB_END__c, TW1_MAR_END__c, TW1_APR_END__c, TW1_MAY_END__c, TW1_JUN_END__c, TW1_JUL_END__c, TW1_AUG_END__c, TW1_SEP_END__c, TW1_OCT_END__c, TW1_NOV_END__c, TW1_DEC_END__c FROM TW1_End_Fiscal_Period__c];

        return CustomFiscalPeriodDates;

    }
    
}