force-app/main/default/objects/TOBJ_Warning__c/TOBJ_Warning__c.object-meta.xml
<CustomObject>
    <label>Warning</label>
    <nameField>
        <displayFormat>WARN-{00000000}</displayFormat>
        <label>Nome do Aviso</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Warning</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/TOBJ_Warning__c/fields/PublicationDate__c.field-meta.xml
<CustomField>
    <fullName>PublicationDate__c</fullName>
    <label>Data de publicação</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TOBJ_Warning__c/fields/TCF_DueDate__c.field-meta.xml
<CustomField>
    <fullName>TCF_DueDate__c</fullName>
    <label>Data de vencimento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/T_UpdateFilesVisibility.cls
/**
 * @description       : Job - to grant access to files for Community User
 * @author            : Gabriel Uchoa
 * @group             :
 * @last modified on  : 04-20-2021
 * @last modified by  : Gabriel Uchoa
 * Modifications Log
 * Ver   Date         Author          Modification
 * 1.0   04-20-2021   Gabriel Uchoa   Initial Version
 **/
public class T_UpdateFilesVisibility {
    
    public static void manageShareFilesVisibility(){
        ShareFileVisibility('select id from TOBJ_Warning__c where PublicationDate__c <=: hoje and TCF_DueDate__c >=: hoje');
    }
    
    @future
    private static void ShareFileVisibility(String soql){
        Date hoje = Date.today();
        List<SObject> registros = Database.query(soql + ' limit 40000');
        Set<String> ids = T_Utils.getSetIds(registros, 'Id');
		IF(ids != null && ids.size() > 0) {
			List<ContentDocumentLink> filesRelationships = [select id from ContentDocumentLink where visibility != 'AllUsers' and LinkedEntityId in: ids limit 10000];
			
			for(ContentDocumentLink fileRelationship: filesRelationships){
				 fileRelationship.Visibility = 'AllUsers';
			}
			
			update filesRelationships;
		}
    }
}